### ISSUE TITLE
Getting consuls geo-failover to work by using queries instead of services

### ISSUE THREAD

**Issue by avendretter** [containous/traefik#5178] opened 2019-08-06 15:16 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### Problem:

In Consul I have a query for a server A in place which handles failover within one datacenter.
So if service A.service.consul is not available in datacenter DC_A it will return the IP of DC_B.

Now I do not want to use Consul as a DNS-Server, so I connected traefik with it. 

I realized, that traefik just uses A.service.consul for getting the IP. 
This results in missing of datacenter failover handling.

If my service dies in DC_A, my frontend and backend disappear, instead of switching to the other datacenter DC_B.

### What did you expect to see?

I would like to see a way to activate consul queries to use them instead of the service itself

I hope I am right to post this here, because I think its not an issue with Consul but with traefik.

Best,
Aven

**Comment by dtomcej** [comment] 2019-08-06 15:25
Duplicate of #544

**Closed by dtomcej** 2019-08-06 15:25 UTC
Labels: status/0-needs-triage
