### ISSUE TITLE
Allow to configure TLS on the entrypoint in Traefik 2.0

### ISSUE THREAD

**Issue by apollo13** [containous/traefik#5183] opened 2019-08-08 09:07 UTC
As far as I can see there is no way in Traefik 2.0 to force an entrypoint to allow only https connections. One can redirect via a router, but this is rather late imo and puts the responsibility onto the router. Having a global option would make the individual router configuration via docker labels etc easier.

**Comment by apollo13** [comment] 2019-08-08 09:11
To extend on the description from above my usecase is the following: I am using traefik as an ingress and want to ensure that:
 * all http requests are redirected to https
 * no http traffic is returned from traefik aside from the https redirect from above
 * this should be doable without having to do this for every router/service

Basically as a system administrator I want to ensure that the system is secure without having to rely on the "users" to configure tls properly via labels etc…

**Comment by ldez** [comment] 2019-08-08 10:27
Duplicate of #4863

**Closed** 2019-08-08 15:35 UTC
Labels: status/0-needs-triage
