### ISSUE TITLE
Continue to serve traffic to Marathon applications during leader (re-)election phases while not serving to unready ones

### ISSUE THREAD

**Issue by timoreimann** [containous/traefik#1185] opened 2017-02-23 12:51 UTC
#653 introduced a change to the Marathon provider that made Traefik continue to serve traffic even in the absence of health check results. The motivation was that during phases where a Marathon (re-)election would take place, Marathon would not have health-checked all applications and thus not have provided health check results, causing Traefik to lose all backend servers. Technically, however, those applications would still be available (at least with a very high probability).

#1080 undid the change again since it would cause applications to be taken into load-balancing rotation prior to their health checks going green. This could lead to traffic being served while the application was still bootstrapping.

I think this issue should come up with the answers to two questions:

1. Should #1080 be reverted prior to releasing 1.2.0?
2. Can we come up with a way to resolve the two conflicting changes such that both goals can be achieved? 

/cc @gomes @jangie @emilevauge @vdemeester @errm

**Comment by jangie** [comment] 2017-02-23 12:59
My apologies, I did not realize this was the reason the zero health check status was marked as healthy. In our usage, new versions of applications are deployed on a much more frequent basis than marathon leader re-election occurs, and are not immediately able to serve traffic. 

A quick, but perhaps unpalatable fix may be to add in a configuration to choose this new behavior? Alternatively, any time a connection is made to a marathon leader, to set a configurable timeout before which zero health checks are marked as unhealthy?

**Comment by timoreimann** [comment] 2017-02-23 13:00
Here are my 2 cents to the questions:

1. I think #1080 should be reverted as Traefik went live with #563 in 1.1.0. To me, #1080 constitutes a breaking (behavioral) change, which should not be introduced without a new major release. Given that the current state isn't satisfactory either, to me there's less value in "breaking even further".
2. IMHO, the right way to deal with this is to follow Kubernetes' pattern and require Marathon applications to employ [readiness checks](https://mesosphere.github.io/marathon/docs/readiness-checks.html) which have been available in Marathon for a while. There's no support for readiness checks in Traefik yet though, so it'd need to be added.
A possible workaround to readiness checks is to enable retrying in Traefik so that failing requests to yet unready applications are re-routed to different backend servers. It's not ideal and still has a chance of failing (and for sure a delaying effect) but it should be fairly easy to implement AFAICS.

**Comment by jangie** [comment] 2017-02-23 13:44
[I am fine with 1080 being reverted for now and have issued a new PR above to do so]

**Comment by gomes** [comment] 2017-02-23 18:16
HealthChecks are not mandatory and a lot of users do not configure this. Since Traefik does not have his own checks, he needs to believe in Marathon behavior to put in or put out instances in his list. I don't know the size of your cluster, but in my case with more than 2000 apps in every cluster, it's normal to me that sometimes Marathon stops to run some healthchecks until a new deploy.

As a load balancer, we have to ensure that all available instances can be accessed ASAP, and trust that Marathon's configuration is defined for your single case.

**Comment by felipemouzerlemos** [comment] 2017-02-23 18:29
With this PR in a case of a Marathon (re-)election all application will be unavailable until a new leader get elected.

**Comment by jangie** [comment] 2017-02-23 18:55
@gomes for what it's worth, the code in #1080 was intended to only kick in when a health check is configured and when there were zero results for that defined health check, and I believe follows that intention. That said, I'm happy for it to be removed (via #1186) until we can come to a more satisfactory way to deal with a newly-deployed slow-to-serve-traffic-successfully task.

**Comment by timoreimann** [comment] 2017-02-23 20:54
@jangie thanks for the quick response.

A timeout would probably be very brittle and subject to a number of external factors. For instance, in our Marathon cluster, we have seen re-elections taking as long as a few seconds to several minutes. Personally I'd have a hard time picking a proper value.

I'd consider a configuration switch to choose between the two behaviors an intermediary solution at most: Ideally teams should be able to use a solution that fits both use cases. That said, I can see how you may want to give preference to avoid taking applications into load-balancing prematurely if the impact of a leader election is not a major concern to you. (Similar to @gomes, for us it is a major problem as it causes huge outages.)

FWIW, in our cluster we have been doing service discovery with [Bamboo](https://github.com/QubitProducts/bamboo)/HAProxy in front of Marathon/Mesos for quite some time and relied on HAProxy retries to deal with Marathon tasks becoming healthy too late (and dying too quickly, for that matter). If Traefik's retry mechanism is somewhat similar, it should also be helpful in mitigating the problem.

Again, I think the right solution to the problem are readiness checks. It's also more flexible since a healthy task does not guarantee a ready task per se. (Think of cache pre-warming or similar that applications may want to complete prior to serving traffic.)

Curious to hear what Traefik maintainers think would be the right approach to deal with this problem.

**Comment by timoreimann** [comment] 2017-02-23 21:04
@jangie:

>for what it's worth, the code in #1080 was intended to only kick in when a health check is configured and when there were zero results for that defined health check, and I believe follows that intention.

Unfortunately, that behavior matches the one you see when a new leader is (re-)elected, which is pretty similar to what you get when a brand new task gets scheduled.

I once tracked down the "evolution" of the health check results: It basically goes through several stages from `null` to fully available. See [my comment on the go-marathon issue tracker](https://github.com/gambol99/go-marathon/issues/118#issuecomment-234366225) if you're curious about the details.

**Comment by jangie** [comment] 2017-02-23 22:37
Oof, interesting. So if I understand the lifecycle of the health checks correctly, in steps 1 and 2 it would be identified as without health check configuration, steps 3 and 4 identified as with a health check configuration, and then only in step 5 would we have health check results to work with? That's frustrating.

**Comment by timoreimann** [comment] 2017-02-23 22:50
@jangie That's correct. At best, things may have improved since I tested it (which must have been somewhere around Marathon 1.1 to 1.3).

**Comment by timoreimann** [comment] 2017-02-27 21:03
@jangie thanks for the (now merged) revert.

If you think there's a viable approach that supports your use case without sacrificing on the availability of Marathon applications during leader election phases, I'd be happy to drive a PR.

**Comment by timoreimann** [comment] 2017-02-27 21:04
What I'll definitely work on for sure is support for Marathon readiness checks.

**Comment by jangie** [comment] 2017-02-27 21:15
👍 

do readiness checks persist in some kind of shared state during leadership reelections?

**Comment by timoreimann** [comment] 2017-02-28 23:34
@jangie according to tests I ran a while ago against Marathon, state sharing should not be needed: Readiness checks can only fail during deployments. (In fact, the readiness check result is a JSON key on the deployment endpoint.) As long as a deployment is ongoing, the readiness check will fail, which can be the case while Marathon is actively pinging the readiness check and receiving a negative result; or when Marathon hasn't been able to check at all during a leader election.

It's only at the end of the (successful) deployment that the readiness check will go green and the task will immediately transition into the `TASK_RUNNING` state. By definition, all running tasks have succeeded their readiness check, no matter whether a leader has been elected or not.

**Comment by timoreimann** [comment] 2017-03-04 10:08
I learned yesterday that the upcoming Traefik 1.2.0 will bring support for health check URLs that Traefik pings regularly in order to determine whether servers should be taking into rotation or not. At least, that's how I interpret [the documentation](http://docs.traefik.io/basics/#backends) and the code.

@jangie this sounds like it could solve your dilemma: Set the health check URL to a Marathon application health check URL and rely on Traefik to only take new deployments into rotation when they actually go green. 
What do you think?

**Comment by jangie** [comment] 2017-03-04 13:58
That sounds like it could solve much, if not all, of it! I'll be doing some testing once it hits to see if it resolves my use case. Thanks for pointing it out!

**Comment by timoreimann** [comment] 2017-03-04 14:46
@jangie awesome, looking forward to your feedback. :+1:

If you feel impatient, the 1.2.0 release candidate includes the feature and is published already.

**Closed** 2017-08-18 01:08 UTC
Labels: area/provider/marathon, kind/proposal
