### ISSUE TITLE
Wrong HTTPS redirect when also using AddPrefix

### ISSUE THREAD

**Issue by schoren** [containous/traefik#2024] opened 2017-08-29 15:28 UTC
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I'm using traefik as a kubernetes ingress controller. I have configured HTTPS redirect as follows in the TOML config file:

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    regex = "^http://(.*)"
    replacement = "https://$1"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
```

I have also configured an ingress like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: "AddPrefix"
spec:
  tls:
  - hosts:
    - demo.example.com
    secretName: tls
  rules:
  - host: demo.example.com
    http:
      paths:
      - path: /path
        backend:
          serviceName: myservice
          servicePort: 80
```

### What did you expect to see?

When accessing `http://demo.example.com`, I wanted it to redirect to `https://demo.example.com`.

### What did you see instead?

When accessing `http://demo.example.com`, I wanted it to redirect to `https://demo.example.com/path`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.7
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-25_08:56:06PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    regex = "^http://(.*)"
    replacement = "https://$1"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
[acme]
email = "certmaster@example.com"
storage = "/acme/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
acmelogging = true
caServer = "https://acme-v01.api.letsencrypt.org/directory"
acmeLogging = true
```

**Comment by dtomcej** [comment] 2017-08-29 17:50
Hello @schoren 

In your report, you have 2 conflicting statements:

```
What did you expect to see?

When accessing http://demo.example.com, I wanted it to redirect to https://demo.example.com.

What did you see instead?

When accessing http://demo.example.com, I wanted it to redirect to https://demo.example.com/path.
```

Can you please confirm which was the intended, and which was the actual?

**Comment by schoren** [comment] 2017-08-29 17:57
I'm really sorry, this is the right report:

### What did you expect to see?

When accessing http://demo.example.com, I wanted it to redirect to https://demo.example.com.

### What did you see instead?

When accessing http://demo.example.com, I got redirected to https://demo.example.com/path.

**Comment by ldez** [comment] 2017-08-29 18:13
May related to #1957

**Comment by schoren** [comment] 2017-08-29 18:15
Yes, I have already saw that. I have some experience in Go and would like to contribute to this project. Could you point me to a good starting point to investigate this?

**Comment by ldez** [comment] 2017-08-29 18:20
First read https://github.com/containous/traefik/blob/master/CONTRIBUTING.md

All the code of the K8s provider is here: https://github.com/containous/traefik/tree/master/provider/kubernetes

**Comment by kachkaev** [comment] 2017-09-04 15:31
Hi @schoren! Did you have a chance to investigate? What could be causing this behaviour? Totally agree with @ldez that this is likely to be related to https://github.com/containous/traefik/issues/1957.

**Comment by schoren** [comment] 2017-09-04 21:27
Hi @ldez, I have been looking at the code but so far couldn't find the problem. Will update here if I can make any progress

**Comment by schoren** [comment] 2017-09-04 21:36
BTW, what's the best way to test or debug the code? I thin using a minikube could work, but it would require to rebuild the image and reload the minikube for each change.

Do you guys have a method for this?

**Comment by ldez** [comment] 2017-09-04 22:11
@schoren you can simply rebuild the binary: `make binary`

perhaps @timoreimann have a better method.

**Comment by timoreimann** [comment] 2017-09-05 20:09
@schoren the fastest feedback cycles can be achieved if you can reproduce the problem on something simpler than Kubernetes, like the file provider.

If Kubernetes is needed, the second best thing you can do is to configure minikube to use your host Docker daemon. That way, you only need to rebuild the Docker image and kill your Traefik pods for changes to become effective.

What I have never tried myself but should be possible theoretically is to launch a development container into Kubernetes, `kubectl exec` into it, and develop / build from there. It seems more like a hack though.

Finally, there's Microsoft's Draft tool which promises to streamline the Kubernetes development process as well. I yet have to give it a whirl too, but what I have read and seen looks promising.

Hope this helps.

**Comment by schoren** [comment] 2017-09-05 20:11
@timoreimann thank you, I was thinking that exactly. I'll do some debuggin tonight to see if the same issue happens without kubernetes.

**Comment by schoren** [comment] 2017-09-06 20:58
Quick update. I have been able to reproduce the problem with a basic file provider. The bug seems to be that the Rewrite middleware is being applied after the AddPath middleware. 
I'm trying to switch the order and see if that works (and doesn't break anything).

Any ideas are welcome :)

**Comment by kachkaev** [comment] 2017-09-12 17:01
@schoren have you discovered anything else since your last comment? Just curious.

@fabiorauber @ArcticDolphin you mentioned that you also faced the same issue in https://github.com/containous/traefik/issues/1738 and https://github.com/containous/traefik/issues/1957. If you know Go at least a bit, could you please have a look at what could be causing this? I have no experience in this language and despite that I tried browsing through the sources, I could not dig out anything that could help solving this :disappointed: 

Permanent http to https redirects are pretty common these days and keeping different containers behind different paths becomes popular too. So looks like the bug might affect quite a few users.

**Comment by schoren** [comment] 2017-09-14 15:23
@kachkaev I have been doing some tests with the load order of mddlewares. The problem here is that the Route middlewares (such as addPrefix, stripPath, etc) are being executed before the entrypoint middlewares. I tried inverting the order in which they are loaded, but it seemed to have no effect.

The issues you mention are very likely to be related to this.

Still working, any help from someone more experienced with Negroni and Traefik would be great

**Comment by LSmith130** [comment] 2018-01-25 18:09
Any update on this? I'm still experiencing this issue on v1.5.0, and I can't figure out a good work around.

**Comment by kachkaev** [comment] 2018-01-25 18:24
@LSmith130 there is a discussion in https://github.com/containous/traefik/issues/1957 – these issues seem to be related. I'm also hoping that this is fixed soon.

**Comment by schoren** [comment] 2018-01-26 21:17
Yes, #1957 is totally related. The problem is in the execution order of the middlewares. However, it will require some thinking to fix this without introducing regressions and/or new bugs.

**Comment by dtomcej** [comment] 2018-07-16 22:40
Addprefix is designed to add to the backend request, not to build a custom redirect.

We now have full redirect capabilities, and modifier/matcher capabilities in 1.7.

We have rewritten the matchers and modifiers to allow this to work properly.

I will go ahead and close this, as it may confuse other issues moving forward.

**Comment by dtomcej** [comment] 2018-10-25 15:42
Closing this issue, as #3742 should have resolved any outstanding issues. Any further issues will need to be noted in a new ticket.

Thanks!

**Closed by dtomcej** 2018-10-25 15:42 UTC
Labels: area/provider/k8s, kind/bug/possible
