### ISSUE TITLE
ingress.kubernetes.io/pass-tls-cert not work

### ISSUE THREAD

**Issue by kuramal** [containous/traefik#3123] opened 2018-04-04 03:39 UTC
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
i set ingress.kubernetes.io/pass-tls-cert whit true , and i want pass the end-user Client certificates to my service, but it not work

### What did you expect to see?

traefik forward the end-user client certificates to the backend

### What did you see instead?

bad certificates

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```

**Comment by ldez** [comment] 2018-04-04 07:57
duplicate of #3052

**Closed by ldez** 2018-04-04 07:57 UTC
Labels: resolution/duplicate
