### ISSUE TITLE
Wrong wildcard certificate selected between generic one and specific subdomain one

### ISSUE THREAD

**Issue by icedream** [containous/traefik#7001] opened 2020-07-06 04:52 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am using some external certificate management to sign certificates for different subdomain wildcards to be used. They are all loaded in via [dynamic configuration](https://docs.traefik.io/https/tls/#user-defined) by [watching a folder of configuration files](https://docs.traefik.io/providers/file/#watch).

Assume one certificate is signed to cover `example.com` (CN) and `*.example.com` (SAN). This certificate is also configured to be the SNI default certificate [as described here](https://docs.traefik.io/https/tls/#default-certificate).

Another certificate covers `subdomain.example.com` (CN) and `*.subdomain.example.com` (SAN).

### What did you expect to see?

- When visiting `https://example.com` or `https://anything.example.com` that the certificate `CN=example.com` would be used.
- When visiting `https://subdomain.example.com` or `https://anything.subdomain.example.com` that the certificate `CN=subdomain.example.com` would be used.

### What did you see instead?

- The correct certificate is used for `https://example.com` and `https://anything.example.com`.
- The `CN=example.com` certificate is wrongly used for `https://subdomain.example.com` and `https://anything.subdomain.example.com` instead of the correct one.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Originally tested on this version:

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

Also tested on newer 2.2 version:

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

This is actually the `traefik:2.2` Docker image.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

- Provider: Docker (could replicate this on Swarm and non-Swarm equally)
- Platform: Linux amd64 (Swarm: CoreOS, non-Swarm: Arch Linux)
- [I have prepared an isolated test environment.](https://github.com/icedream/testcase-traefik-2-sni-wildcard) It contains an applicable example configuration as described above, which can be set up and run to replicate the behavior.

### Possibly related issues:

- #4081 though I don't know if it covers this specific case of two wildcard certificates covering different subdomain layers

**Comment by icedream** [comment] 2020-07-06 22:09
I have also tested this on v2.2.1, I just forgot to pull the newest image when I originally reported this.

**Comment by kevinpollet** [comment] 2020-07-21 13:03
Hello @icedream,

First, thanks for your test environment which was really helpful 😄

I've tried to reproduce your issue, and I've seen that you have a typo in your [dynamic configuration](https://github.com/icedream/testcase-traefik-2-sni-wildcard/blob/master/traefik.d/80-dyn-certificates.toml). As described in the [documentation](https://docs.traefik.io/https/tls/#certificates-stores) the property is named `tls.certificates`. After fixing the dynamic configuration everything was working as expected.

```
$ openssl s_client -connect localhost:443 -showcerts -servername whoami.traefik.localhost
---
Server certificate
subject=/CN=traefik.localhost
issuer=/CN=Test CA
---

$ openssl s_client -connect localhost:443 -showcerts -servername nginx.sub.traefik.localhost
---
Server certificate
subject=/CN=sub.traefik.localhost
issuer=/CN=Test CA
---
```

Can you check that your dynamic configuration is valid?

**Comment by icedream** [comment] 2020-07-23 07:59
Hello @kevinpollet!

I was actually able to indeed get the configuration working like that in the test setup. I derived the test case from a production setup, however the problem didn't seem to be fixed there with the same changes. I'll dive deeper into where the actual issue could be in the coming time, it could be the the certificates themselves, or something else that's super-specific to that setup.

Thanks for your help so far though!

**Comment by jbdoumenjou** [comment] 2020-07-23 12:34
I will close this issue as it seems to be solved.
Feel free to reopen it if needed.
Thanks.

**Closed by jbdoumenjou** 2020-07-23 12:34 UTC
Labels: area/tls, contributor/waiting-for-feedback, kind/bug/possible
