### ISSUE TITLE
Incorrect Dashboard page returned

### ISSUE THREAD

**Issue by rrichardson** [containous/traefik#831] opened 2016-11-11 22:49 UTC
I have Traefik set up in kubernetes as an ingress LB.  I also have traefik itself serving up the dashboard page.  Traefik is a LoadBalanced service, so  ELB round-robins over 3 instances of Traefik.  

A couple hours after I restart Traefik,  when I attempt to view the Dashboard page,  I get this instead: 

![traefik](https://cloud.githubusercontent.com/assets/124171/20232534/f548c670-a81d-11e6-9ff3-10de0550bbfd.png)

I haven't dug into this too much just yet. I wanted to see if this was a known issue before I dig in to the cause.

**Comment by SantoDE** [comment] 2016-11-11 22:51
Hey. This is a duplicate of #796 and therefore closed ;-)

**Closed by SantoDE** 2016-11-11 22:51 UTC
