### ISSUE TITLE
Traefik dies if it cannot reach the ACME server

### ISSUE THREAD

**Issue by Yajo** [containous/traefik#1631] opened 2017-05-19 10:33 UTC
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Started a Traefik instance just as always, but today, with the special situation that [Let's Encrypt is down](https://twitter.com/letsencrypt_ops/status/865479090748268544).

### What did you expect to see?

Traefik should `WARN` when there's no access to ACME provider, but still continue serving the sites, with these conditionals:

- Already existing certs should continue being served as usual.
- New sites without cert should get served with traefik's default cert, raising an error to the user but actually making the site usable.
- Traefik should retry ACME connections and continue normal operation when reconnected.

### What did you see instead?

Traefik dies with an `ERROR`, all sites behind it become completely unreachable, sysadmin goes crazy. 😢

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.2.3
Codename:     morbier
Go version:   go1.7.5
Built:        2017-04-13_07:21:10PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Arguments:

      - --ACME.ACMELogging
      - --ACME.Email=****
      - --ACME.EntryPoint=https
      - --ACME.OnDemand
      - --ACME.OnHostRule
      - --ACME.Storage=/etc/traefik/acme/acme.json
      - --DefaultEntryPoints=http,https
      - --Docker
      - --Docker.EndPoint=http://dockersocket:2375
      - --Docker.ExposedByDefault=false
      - --Docker.Watch
      - --EntryPoints=Name:http Address::80 Redirect.EntryPoint:https Compress:on
      - --EntryPoints=Name:https Address::443 TLS Compress:on
      - --LogLevel=DEBUG

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
INFO[2017-05-19T10:23:22Z] Loading ACME Account...                      
INFO[2017-05-19T10:23:22Z] Loaded ACME config from store /etc/traefik/acme/acme.json 
DEBU[2017-05-19T10:23:22Z] Building ACME client...                      
ERRO[2017-05-19T10:23:32Z] Error creating TLS config: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
FATA[2017-05-19T10:23:32Z] Error preparing server: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory:net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by Yajo** [comment] 2017-05-19 10:50
When booting it for the first time (empty `acme.json`) it dies also with:

```
INFO[2017-05-19T10:47:07Z] Generating ACME Account...                   
DEBU[2017-05-19T10:47:08Z] Building ACME client...                      
INFO[2017-05-19T10:47:09Z] Register...                                  
legolog: 2017/05/19 10:47:09 [INFO] acme: Registering account for support+interna@tecnativa.com
ERRO[2017-05-19T10:47:19Z] Error creating TLS config: Failed to post JWS message. -> Failed to HTTP POST to https://acme-staging.api.letsencrypt.org/acme/new-reg -> Post https://acme-staging.api.letsencrypt.org/acme/new-reg: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
FATA[2017-05-19T10:47:19Z] Error preparing server: Failed to post JWS message. -> Failed to HTTP POST to https://acme-staging.api.letsencrypt.org/acme/new-reg -> Post https://acme-staging.api.letsencrypt.org/acme/new-reg: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
```

This is really sad, 😞 I simply cannot use Traefik today!

**Comment by np** [comment] 2017-05-19 11:58
This happens to me as well.
We could expect traefik to survive and keep trying.
In particular I have all the certs I need for now but traefik won't serve without access to letsencrypt API.

**Comment by pedrobaeza** [comment] 2017-05-19 12:06
I have been hit by the same bug.

**Comment by emilevauge** [comment] 2017-05-19 12:22
Duplicate of #791

**Closed by emilevauge** 2017-05-19 12:22 UTC
