### ISSUE TITLE
Serving content from Google Cloud buckets on K8s

### ISSUE THREAD

**Issue by EdanBrooke** [containous/traefik#4852] opened 2019-05-07 10:16 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

We're trying to use Google Cloud Buckets as a backend cache and we are using Traefik on K8s as our ingress. However, Traefik doesn't support piping traffic through to Google Cloud buckets based on URL.

It would be good if you could configure Traefik to serve content from Google Cloud buckets.

**Comment by jbdoumenjou** [comment] 2019-05-07 15:15
Hi @EdanBrooke !

Thank you for your feedback.

I'm not sure about the proposal and think we need to discuss this further.
Could you be more precise on your use case ?

For now, I'm tagging the issue and will wait for others to react.

**Comment by EdanBrooke** [comment] 2019-05-08 08:01
Hi,

This is because we have our main website - in a Kubernetes deployment, but we are storing certain static content in Google's bucket storage (e.g. /sitemaps).

Therefore, in this case it would be useful to be able to have an option within Traefik to add an additional rule to pass all requests to `/sitemaps` to Google's bucket storage as a reverse proxy.

For instance, the user visits the site and their browser requests `/sitemaps`. Then Traefik recognises this and makes a request (HTTPS) to Google Cloud bucket, gets the relevant resource and sends it back to the user.

We should be able to get this working with an NGINX deployment as a reverse proxy but seems silly given Traefik is in itself a reverse proxy.

Hope this makes sense (sorry if not - it's early morning!)

Thank you,
Edan

**Comment by dtomcej** [comment] 2019-05-08 14:31
If the bucket is accessible through your cluster, you should be able to use the `ExternalName` service type (https://kubernetes.io/docs/concepts/services-networking/service/#externalname), and have Traefik proxy the request as intended.

Please let us know if that works for you.

Thanks!

**Comment by EdanBrooke** [comment] 2019-05-20 07:32
Thanks @dtomcej - this did work for our use case. 😄 

I was under the impression it wouldn't because of the URI that wouldn't be passed as part of a DNS lookup which is essentially what ExternalName does, but alas we managed to get it working.

Thanks again.

**Comment by traefiker** [comment] 2019-05-20 15:20
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

Thanks again for your interest in Traefik!

I'm glad to close the issue because I think that the question has been answered (Yes, I'm quite an advanced AI :smile:)

Join our [Slack workspace](https://slack.traefik.io/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Closed by traefiker** 2019-05-20 15:20 UTC
Labels: kind/proposal, kind/question
