### ISSUE TITLE
Its not possible to override basic auth from label if you are using basic auth on endpoint

### ISSUE THREAD

**Issue by lukasmrtvy** [containous/traefik#4165] opened 2018-11-06 10:42 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Its not possible to override Basic Auth from labels, when are You using another Basic Auth on entrypoint.

```
docker run -d -p 80:80 -p 443:443 \
--label "traefik.enable=true" \
--label "traefik.basic.frontend.rule=Host:traefik.example.com" \
--label "traefik.basic.port=8080" \
--label 'traefik.frontend.auth.basic=myName:$apr1$a7R637Ua$TvXp8/lgky5MDLGLacI1e1' \
-v /var/run/docker.sock:/var/run/docker.sock \
--name traefik \
--network my-bridge \
traefik:v1.7-alpine  \
--api \
--api.dashboard=true \
--api.entrypoint=traefik \
--api.statistics=true \
--docker \
--docker.domain=example.com \
--docker.endpoint=unix:///var/run/docker.sock \
--docker.exposedbydefault=false \
--docker.watch=true \
--defaultentrypoints="http,https" \
--entryPoints="Name:http Address::80 Redirect.EntryPoint:https"  \
--entryPoints='Name:https Address::443 TLS Auth.Basic.Users:user:$apr1$fCN/lR9E$9hLH9feJ.onymNsjtQRWn1 Auth.HeaderField:X-WebAuth-User'  \
--entryPoints='Name:traefik Address::8080 '
```

### What did you expect to see?
Authentication with myName:myPassword to https://traefik.example.com 
Authentication with user:user to other services

### What did you see instead?
Basic Authentication does not work for https://traefik.example.com.
Response: 401 Unauthorized

If I remove Auth.Basic.Users from https entrypoint it is working.

### Output of `traefik version`: (_What version of Traefik are you using?_)
traefik:v1.7-alpine  docker image

**Comment by ldez** [comment] 2018-11-06 10:53
duplicate of #3562

**Closed** 2018-11-06 15:31 UTC
Labels: status/0-needs-triage
