### ISSUE TITLE
Traefik Docker Swarm (WinServer 2019) - Bad Gateway

### ISSUE THREAD

**Issue by mgiangrandi** [containous/traefik#4485] opened 2019-02-11 15:54 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. I've downloaded the latest version of Traefik (v.1.7.9) from GitHub - traefik_windows-amd64.exe - on my Windows Server 2019 EC2 instance.

2. Created folder C:\traefik and I moved the .exe inside. 

3. Launched ```docker-swarm init --advertise-addr 127.0.0.1``` and created an overlay network (traefik-net).

4. I've opened a CMD and, after moving to C:\traefik, I've executed the following command:

```"traefik_windows-amd64.exe" --configFile=traefik.toml```

5. Created my docker service (replicated 5 times) with the following command:

```docker service create --name=tbbackend --replicas 5 --publish 10000:10000 -e TB_LogService=http://my.logger:5000 -e TB_LogOnFileSystem=true -e TB_LoggedMessageTypes=59 -e TB_VerboseProcesses=2 -e TB_ProvidersCallPolicy=0 -e TB_LogInEventViewer=0 -e TB__INSTANCE_KEY=M-99990 -e MiddlewareUrl=http://M-99990.service:6811 --label "traefik.enable=true" --label "traefik.port=10000" --label "traefik.backend=tbbackend" --label "traefik.frontend.rule=PathPrefix:/" --label "traefik.backend.loadbalancer.sticky=true" myrepo/tbbackend:1.0.0.2220-develop-win2019```

6. I've opened Chrome and navigated to http://localhost:8080 (Traefik Dashboard) - every service were correctly listed

7. Tryed to open "api" of my service through Traefik (http://localhost:85/myservice/api - yes, I've moved Traefik default port to 85).

### What did you expect to see?

I expected Traefik to redirect the endpoint correctly

### What did you see instead?

"Bad Gateway" error

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      windows/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel="DEBUG"
debug=true

[entryPoints]
  [entryPoints.http]
  address = ":85"

[web]
address=":8080"

[docker]
endpoint="npipe:////./pipe/docker_engine"
watch=true
swarmmode=true
```

OS: Windows Server 2019 Datacenter

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
DEBU[2019-02-11T16:52:07+01:00] '502 Bad Gateway' caused by: dial tcp 10.255.0.32:10000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
DEBU[2019-02-11T16:52:07+01:00] vulcand/oxy/forward/http: Round trip: http://10.255.0.32:10000, code: 502, Length: 11, duration: 21.001011s
DEBU[2019-02-11T16:52:08+01:00] vulcand/oxy/forward/http: completed ServeHttp on request  Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.255.0.32:10000\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"_TRAEFIK_BACKEND=http://10.255.0.16:10000\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"],\"X-Forwarded-Prefix\":[\"/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost:85\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:57532\",\"RequestURI\":\"/tb/document/getProcessId/\",\"TLS\":null}"
DEBU[2019-02-11T16:52:08+01:00] vulcand/oxy/forward: completed ServeHttp on request  Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.255.0.32:10000\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"_TRAEFIK_BACKEND=http://10.255.0.16:10000\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"],\"X-Forwarded-Prefix\":[\"/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost:85\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:57532\",\"RequestURI\":\"/tb/document/getProcessId/\",\"TLS\":null}"
DEBU[2019-02-11T16:52:08+01:00] vulcand/oxy/roundrobin/rr: completed ServeHttp on request  Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/tb/document/getProcessId/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"_TRAEFIK_BACKEND=http://10.255.0.16:10000\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"],\"X-Forwarded-Prefix\":[\"/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost:85\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:57532\",\"RequestURI\":\"/tb/document/getProcessId/\",\"TLS\":null}"
DEBU[2019-02-11T16:52:08+01:00] vulcand/oxy/roundrobin/rr: begin ServeHttp on request  Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"_TRAEFIK_BACKEND=http://10.255.0.32:10000\"],\"Referer\":[\"http://localhost:85/tb/document/getProcessId/\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"],\"X-Forwarded-Prefix\":[\"/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost:85\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:57532\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
DEBU[2019-02-11T16:52:08+01:00] vulcand/oxy/roundrobin/rr: Forwarding this request to URL  Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"_TRAEFIK_BACKEND=http://10.255.0.32:10000\"],\"Referer\":[\"http://localhost:85/tb/document/getProcessId/\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"],\"X-Forwarded-Prefix\":[\"/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost:85\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:57532\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}" ForwardURL="http://10.255.0.32:10000"
DEBU[2019-02-11T16:52:08+01:00] vulcand/oxy/forward: begin ServeHttp on request  Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.255.0.32:10000\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"_TRAEFIK_BACKEND=http://10.255.0.32:10000\"],\"Referer\":[\"http://localhost:85/tb/document/getProcessId/\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"],\"X-Forwarded-Prefix\":[\"/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost:85\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:57532\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
DEBU[2019-02-11T16:52:08+01:00] vulcand/oxy/forward/http: begin ServeHttp on request  Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.255.0.32:10000\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"_TRAEFIK_BACKEND=http://10.255.0.32:10000\"],\"Referer\":[\"http://localhost:85/tb/document/getProcessId/\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"],\"X-Forwarded-Prefix\":[\"/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost:85\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:57532\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
```

**Comment by mmatur** [comment] 2019-02-12 15:24
Hi @mgiangrandi 

Seems to be a duplicate of #4409. so I will close this issue.

**Closed by mmatur** 2019-02-12 15:24 UTC
Labels: status/0-needs-triage
