### ISSUE TITLE
Traefik cannot find kubernetes secrets

### ISSUE THREAD

**Issue by hectorhuertas** [containous/traefik#3128] opened 2018-04-04 14:00 UTC
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
Deployed traefik with kubernetes backend, aiming to use certificates stored in kubernetes secrets

### What did you expect to see?
Traefik using the certificate from kubernetes secret

### What did you see instead?
Traefik using it's own default certificate and logging that the kubernetes secret doesn't exist. I let it run overnight to allow plenty of time for the secrets sync, but without luck

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.0-rc3
Codename:     tetedemoine
Go version:   go1.10
Built:        2018-03-28_04:04:00PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
apiVersion: v1
kind: Service
metadata:
  name: external-ingress-proxy
  namespace: sys-ingress-pub
spec:
  selector:
    app: external-ingress-proxy
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 30180
  - name: https-proto
    port: 443
    nodePort: 30143
  selector:
    k8s-app: external-ingress-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-ingress-proxy
  namespace: sys-ingress-pub
  labels:
    k8s-app: external-ingress-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: external-ingress-proxy
  revisionHistoryLimit: 8
  template:
    metadata:
      labels:
        k8s-app: external-ingress-proxy
        name: external-ingress-proxy
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.6.0-rc3-alpine
        name: traefik
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080
        args:
        - --web
        - --web.metrics
        - --web.metrics.prometheus
        - --logLevel=INFO
        - --kubernetes
        - --kubernetes.labelselector=kubernetes.io/ingress.class=traefik-public
        - --entryPoints=Name:http-redirect Address::80 Redirect.EntryPoint:https-proto
        - --entryPoints=Name:https-proto Address::443 TLS
        - --defaultentrypoints=http-redirect,https-proto

```
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: sys-mon
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: traefik
  labels:
    kubernetes.io/ingress.class: traefik-public
spec:
  tls:
  - secretName: traefik-test-tls-cert
  rules:
  - host: myservice.io
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: sys-mon
  labels:
    name: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: web
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: sys-mon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      namespace: sys-mon
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: web
          containerPort: 80
```
RBAC clusterrolebinding:
```
Name:         traefik-test
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  cluster-admin
Subjects:
  Kind            Name     Namespace
  ----            ----     ---------
  ServiceAccount  default  sys-ingress-pub
```
The secret with the cert:
```
Name:         traefik-test-tls-cert
Namespace:    sys-mon
Labels:       <none>
Annotations:  <none>
Type:  kubernetes.io/tls
Data
====
tls.crt:  1034 bytes
tls.key:  1704 bytes
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
time="2018-04-04T08:57:49Z" level=warning msg="web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics"
time="2018-04-04T08:57:49Z" level=info msg="Traefik version v1.6.0-rc3 built on 2018-03-28_04:04:00PM"
time="2018-04-04T08:57:49Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2018-04-04T08:57:49Z" level=info msg="Preparing server https-proto &{Address::443 TLS:0xc420402280 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc420485b80} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-04-04T08:57:51Z" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc420485f40} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-04-04T08:57:51Z" level=info msg="Starting server on :443"
time="2018-04-04T08:57:51Z" level=info msg="Preparing server http-redirect &{Address::80 TLS:<nil> Redirect:0xc4203ca1c0 Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc420485a40} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-04-04T08:57:51Z" level=info msg="Starting server on :8080"
time="2018-04-04T08:57:51Z" level=info msg="Starting provider *kubernetes.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"kubernetes.io/ingress.class=traefik-public\",\"IngressClass\":\"\"}"
time="2018-04-04T08:57:51Z" level=info msg="Starting server on :80"
time="2018-04-04T08:57:51Z" level=info msg="Creating in-cluster Provider client"
time="2018-04-04T08:57:52Z" level=error msg="Error configuring TLS for ingress sys-mon/nginx: secret sys-mon/traefik-test-tls-cert does not exist"
time="2018-04-04T08:57:52Z" level=info msg="Server configuration reloaded on :80"
time="2018-04-04T08:57:52Z" level=info msg="Server configuration reloaded on :443"
time="2018-04-04T08:57:52Z" level=info msg="Server configuration reloaded on :8080"
time="2018-04-04T09:07:51Z" level=warning msg="Error checking new version: GET https://api.github.com/repos/containous/traefik/releases: 403 API rate limit exceeded for 52.18.166.166. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 20m5.628041774s"
time="2018-04-04T09:07:52Z" level=error msg="Error configuring TLS for ingress sys-mon/nginx: secret sys-mon/traefik-test-tls-cert does not exist"
time="2018-04-04T09:17:52Z" level=error msg="Error configuring TLS for ingress sys-mon/nginx: secret sys-mon/traefik-test-tls-cert does not exist" W0404 09:20:39.482673       1 reflector.go:341] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: watch of *v1.Endpoints ended with: too old resource version: 5095910 (5096509)
time="2018-04-04T09:27:52Z" level=error msg="Error configuring TLS for ingress sys-mon/nginx: secret sys-mon/traefik-test-tls-cert does not exist"
time="2018-04-04T09:37:52Z" level=error msg="Error configuring TLS for ingress sys-mon/nginx: secret sys-mon/traefik-test-tls-cert does not exist" W0404 09:45:27.582778       1 reflector.go:341] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: watch of *v1.Endpoints ended with: too old resource version: 5098162 (5098951)
time="2018-04-04T09:47:52Z" level=error msg="Error configuring TLS for ingress sys-mon/nginx: secret sys-mon/traefik-test-tls-cert does not exist"
time="2018-04-04T09:57:52Z" level=error msg="Error configuring TLS for ingress sys-mon/nginx: secret sys-mon/traefik-test-tls-cert does not exist"
time="2018-04-04T10:07:52Z" level=error msg="Error configuring TLS for ingress sys-mon/nginx: secret sys-mon/traefik-test-tls-cert does not exist"

```

**Comment by timoreimann** [comment] 2018-04-05 20:36
Ran some initial tests via minikube. I think we may be observing two issues here:

- The label selector seems to apply to all objects and not just Ingresses. This looks lika a regression from #2867 to me when we [applied the label selector filter to the single, per-namespace factory](https://github.com/containous/traefik/pull/2867/files#diff-d174c899711aea85d1257ab45384fb35R127) (and not excluded the non-Ingress objects) /cc @yue9944882 
- The secret is not picked up, even when I remove the label selector. The error message just keeps popping up.

**Comment by timoreimann** [comment] 2018-04-05 23:00
Submitted a PR to fix the label selector issue.

**Comment by timoreimann** [comment] 2018-04-06 00:01
@hectorhuertas when I remove the label selector and apply all of your manifests to a minikube-based cluster, I see the TLS error message disappearing rather quickly and HTTPS working:

```
$ curl -k -L -H 'Host: myservice.io' https://192.168.99.100:30143/
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

Do you have the possibility to check again without the label selector (or with the label selector and the Docker image `timoreimann/traefik:labelsel-fix` containing the fix from the PR)?

By the way: You have the selector defined twice in your Traefik service manifest -- once with the wrong label (`app`) and the other time with the correct one (`k8s-app`). Luckily, the correct one comes last and overrides the first one. You may want to fix that in your manifests.

**Comment by hectorhuertas** [comment] 2018-04-06 16:13
I have removed the wrong duplicated `app` selector and applied the configuration with the label selector, using your `timoreimann/traefik:labelsel-fix` image.

I get the same results as you: the TLS error message disappearing rather quickly and HTTPS working

Thanks for the super quick fix!

**Comment by ulrichSchreiner** [comment] 2018-04-07 19:51
hi,

i have the same problem. tried your `timoreimann/traefik:labelsel-fix` image but error still occurs:
~~~
traefik-ingress-lb time="2018-04-07T19:42:50Z" level=info msg="Traefik version 75856d006cf526203121b36f1c31cc40ad6cf4be built on 2018-04-05_11:52:33PM"
...
traefik-ingress-lb time="2018-04-07T19:42:50Z" level=error msg="Error configuring TLS for ingress default/httpbin: secret default/httpbin does not exist"
~~~
but
~~~
➜  ~ kubectl describe secret -n default httpbin
Name:         httpbin
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
tls.crt:  3826 bytes
tls.key:  1679 bytes
~~~

the secret is created by `cert-manager` but this shouldn't have any impact.

**Comment by timoreimann** [comment] 2018-04-07 20:51
@ulrichSchreiner did you wait long enough? It could theoretically take up to several minutes before the certificate is recognized.

If you did, please create a new issue along with all relevant manifests and DEBUG level logs. Thanks.

**Comment by ldez** [comment] 2018-04-09 07:10
@ulrichSchreiner the certificates problem is fixed by #3136

**Comment by nmengin** [comment] 2018-04-09 07:15
Hello @ulrichSchreiner ,

Many thanks for your feedback.

Actually, Træfik really adds TLS certificates **only on TLS EntryPoints**.
However, if the defined frontend has no defined EntryPoint (option `traefik.frontend.entryPoints`), Træfik tries to add the service and its certificates to the `defaultEntryPoints`.

If no `defaultEntryPoints` have been defined, Træfik will add the service to the `http` entryPoint but it will not add the certificates. It will just append the DEBUG message `Certificates not added to non-TLS entryPoint http.` in Træfik logs.

Create the `defaultEntryPoints` list or a `traefik.frontend.entryPoints` list with your TLS EntryPoint are the good way to add correctly your certificates to this EntryPoint.

**Comment by kordianbruck** [comment] 2018-04-10 02:48
Did someone already try this with multiple certificates? I have two different hostnames with separate certificates (Catch all certs). The first ingress works fine, for the second one I only get the `TRAEFIK DEFAULT CERT`. I'm also testing on the above image, so not sure where the problem is. I've also noticed fequent reloading of the configuration about every 5 seconds - is this normal? :thinking:

**Comment by nmengin** [comment] 2018-04-18 07:02
Hello @kordianbruck ,

Many thanks for your interest in the project.

If you think there is an bug in Træfik, can you open a new issue and provide all the information about your configuration?

Moreover, for more help, you can  join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by nmengin** [comment] 2018-04-18 07:32
I close the issue because is original bug is fixed.

If you have a similar problem, feel free to join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/) or open a new issue.

**Closed by nmengin** 2018-04-18 07:32 UTC
Labels: area/provider/k8s, area/tls, kind/bug/possible

**Comment by aaron-trout** [comment] 2018-06-26 11:33
Hmm, it sounds like this is fixed but I am hitting the same issue today with 1.6.4. I am not specifying any custom labels to match for the `Ingress` with `kubernetes.labelSelector` (I have installed via the helm chart).

My config file looks like this:

```
# traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      minVersion = "1.2"
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
[kubernetes]
[web]
address = ":8080"
```

**Comment by dNetGuru** [comment] 2018-11-25 09:45
I ran into the same issue on `1.7.4` installed by helm (with `ssl.enabled` set to true) and manually created and set the service account.
After a lot of trial and error I found that removing `http` from `defaultEntryPoints` from traefik's configmap seemed to fix the problem!

**Comment by anapsix** [comment] 2019-03-06 13:13
@dNetGuru if you do that, then ingresses will not bind to HTTP, and you'd have to explicitly add "http" entrypoint via [Annotations](https://docs.traefik.io/configuration/backends/kubernetes/#annotations)

And `ingress.kubernetes.io/ssl-redirect: "true"` will be meaningless, without explicit "http" entrypoint on ingress.

**Comment by Overbryd** [comment] 2019-03-06 21:51
I was running into the same issue, and the *only* relief was the *ORDERING* of the `defaultentrypoints=https,http`.

If I set `defaultentrypoints=http,https` it will not work. `https` has to go first. Nothing else helps, traefik chokes with this very misleading error message that it cannot find the certificates. *sigh

traefik version `1.7.9` hope this helps to anyone coming from Google.

**Comment by anapsix** [comment] 2019-03-07 13:23
@Overbryd, also using traefik 1.7.9
even though error is displayed at first, traefik does the right thing, after it takes a moment to find certificates

> @ulrichSchreiner did you wait long enough? It could theoretically take up to several minutes before the certificate is recognized.

**Comment by tannh** [comment] 2019-04-01 08:31
hum, you can check namespaces accross traefik and secret
