### ISSUE TITLE
ConsulCatalog provider filter services by node`s serfHealth state

### ISSUE THREAD

**Issue by huhr** [containous/traefik#3722] opened 2018-08-03 03:19 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

We are using traefik with consul catalog and have met a problem
One of our linux server has crash and consul agent gone away;
From this issue: https://github.com/hashicorp/consul/issues/1133 
The crash node's serfHealth status is 'critical' but the services on the node  are still keeping health status of 'passing'.
I find that consulCatalog provider doesn't  detect this. 

thank you.

**Comment by mmatur** [comment] 2018-08-09 09:03
Hi @huhr ,

Thanks for your interest in the project.

After some test, I can see that consulCatalog provider detect `serfHealth` change.

Which traefik version are you using?
Which consul version are you using?

Are you able to provide us a compose file that reproduce this issue please?

**Comment by huhr** [comment] 2018-08-13 11:06
Thanks for replay @mmatur ！

We are using  Consul v0.9.3 & traefik-1.4.2; 

When a consul agent was running as client mode and been sent SIGKILL，then the consul cluster health/state api return 
`[
  {
    "Node": "agent3",
    "CheckID": "serfHealth",
    "Name": "Serf Health Status",
    "Status": "critical",
    "Notes": "",
    "Output": "Agent not live or unreachable",
    "ServiceID": "",
    "ServiceName": "",
    "ServiceTags": [
    ],
    "CreateIndex": 1535,
    "ModifyIndex": 2041
  },  {
    "Node": "agent3",
    "CheckID": "service:172.18.0.3-6666",
    "Name": "Service 'demo' check",
    "Status": "passing",
    "Notes": "",
    "Output": "HTTP GET http://172.18.0.3:6666/health: 200 OK Output: ",
    "ServiceID": "172.18.0.3-6666",
    "ServiceName": "demo",
    "ServiceTags": [

    ],
    "CreateIndex": 1985,
    "ModifyIndex": 2023
  }
]
`
and backend-demo in the traefik dashboard still has the "demo--172-18-0-3--6666--5" server.

**Comment by huhr** [comment] 2018-09-06 09:08
any update ?

**Comment by mmatur** [comment] 2018-09-06 14:31
Hi @huhr,

Sorry for the delay. 

A lot of issue on Consul catalog provider has been fixed between Træfik version 1.4.2 and the [latest Træfik version](https://github.com/containous/traefik/releases/latest).

You issue should be fixed by https://github.com/containous/traefik/pull/3390 and it's available in the latest Træfik version.

Could you please try with latest Træfik version?

**Comment by traefiker** [comment] 2018-12-06 00:00
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Closed by traefiker** 2018-12-06 00:00 UTC
Labels: area/provider/consulcatalog, contributor/waiting-for-feedback, kind/enhancement, priority/P1
