### ISSUE TITLE
Panic in kubernetes ingress (traefik 1.1.0)

### ISSUE THREAD

**Issue by jezell** [containous/traefik#910] opened 2016-11-28 18:45 UTC
Getting this every few minutes:

time="2016-11-28T18:37:39Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://10.0.0.1:443/apis/extensions/v1beta1/ingresses\" : unexpected EOF, retrying in 567.501112ms" 
time="2016-11-28T18:38:40Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://10.0.0.1:443/apis/extensions/v1beta1/ingresses\" : unexpected EOF, retrying in 730.22723ms" 
time="2016-11-28T18:39:40Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://10.0.0.1:443/apis/extensions/v1beta1/ingresses\" : unexpected EOF, retrying in 499.83126ms" 
time="2016-11-28T18:40:31Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://10.0.0.1:443/api/v1/services\" : EOF, retrying in 593.014246ms" 
time="2016-11-28T18:41:31Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://10.0.0.1:443/apis/extensions/v1beta1/ingresses\" : unexpected EOF, retrying in 524.75291ms" 
panic: send on closed channel

goroutine 31857 [running]:
panic(0xd292c0, 0xc42034fe60)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/containous/traefik/provider/k8s.(*clientImpl).watch.func1.1(0xc420519560, 0xc420423020, 0xc420428ff0, 0x24, 0xc420422f60)
	/go/src/github.com/containous/traefik/provider/k8s/client.go:280 +0x33f
created by github.com/containous/traefik/provider/k8s.(*clientImpl).watch.func1
	/go/src/github.com/containous/traefik/provider/k8s/client.go:286 +0xbf

**Comment by dweidenfeld** [comment] 2016-11-29 06:17
+1

**Comment by dweidenfeld** [comment] 2016-11-29 06:19
The issue is gone if you downgrade to 1.0.2/1.0.3.

**Comment by jonaz** [comment] 2016-11-29 13:00
Duplicate of #877 which is fixed but not yet release. You can close this issue.

**Closed** 2016-11-30 22:48 UTC
