### ISSUE TITLE
Make it possible to choose a default TLS cert for clients with no SNI

### ISSUE THREAD

**Issue by kachkaev** [containous/traefik#1814] opened 2017-07-02 14:16 UTC
### Do you want to request a *feature* or report a *bug*?

feature; somewhat related to https://github.com/containous/traefik/issues/1003

### What did you do?

I plan to host multiple websites on a single server behind traefik and I'd like one of them to be working on the old browsers such as IE8 on Win XP. That browser does not support SNI, about which [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html) tool reminds promptly:
![screen shot 2017-07-02 at 15 08 29](https://user-images.githubusercontent.com/608862/27770548-58090c62-5f38-11e7-8bff-b30524822f33.png)

In my current nginx reverse-proxy setup I'm able to tell what ACME certificate should be used for clients with no SNI and the trick works great. In traefik, however, it seems impossible to say that this or that ACME cert is the default one and thus traefik always uses its self-signed expired cert when there is no SNI in the handshake.

Would be great to be able to define a default cert option in `traefik.toml`, possibly in a form of a domain name so that this worked with dynamic ACME certs. How feasible does this feature look?

**Comment by ldez** [comment] 2017-07-02 14:24
Seems a duplicate of #1605

**Comment by kachkaev** [comment] 2017-07-02 21:06
Just remembered one more use case for a default TLS certs, which is java maven servers (something similar to npm). If a company uses nexus or artifactory to host jars at `maven.company.com`, it's necessary to provide a cert for this domain to some non-CNI java clients. I was once able to configure maven behind [nginx-proxy](https://github.com/jwilder/nginx-proxy) + [letsencrypt campanion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion), but I don't know what I'd do if needed to switch from nginx to traefik.

**Closed** 2018-07-06 08:30 UTC
Labels: area/acme, kind/enhancement, priority/P3
