### ISSUE TITLE
Disable default HTTPS certificate

### ISSUE THREAD

**Issue by Tyilo** [containous/traefik#6886] opened 2020-06-04 14:38 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

According to https://docs.traefik.io/https/tls/#default-certificate you have two options to define the default certificate for HTTPS:
- Leave the `tls.stores.default.defaultCertificate` blank and Traefik will generate a self-signed certificate
- Define `certFile` and `keyFile` in `tls.stores.default.defaultCertificate` and Traefik will use that as the default certificate

I would like to disable having a default certificate altogether, such that Traefik will just drop the connection if it has no certificate matching the SNI sent by the client.

Maybe add a `tls.stores.default.defaultCertificate.disable` option which is false by default, but when set to true does what I want.

**Comment by mpl** [comment] 2020-06-05 15:22
https://github.com/containous/traefik/issues/6848#issuecomment-634137936

**Comment by mpl** [comment] 2020-06-05 15:23
duplicate of #6848

**Closed** 2020-06-16 15:43 UTC
Labels: resolution/duplicate
