### ISSUE TITLE
Traefik does not start if Let's Encrypt ACME API is down

### ISSUE THREAD

**Issue by fabiorauber** [containous/traefik#1636] opened 2017-05-19 18:26 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Tried to start Traefik with ACME Enabled while Let's Encrypt API was down.

### What did you expect to see?

Traefik running OK.

### What did you see instead?

Traefik dying almost immediately.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.0-rc1
Codename:     raclette
Go version:   go1.8.1
Built:        2017-05-05_02:03:01PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
 traefik:
    image: traefik:1.3.0-rc1-alpine
    volumes:
    - traefik_acme:/mnt
    ports:
    - 8000:8080/tcp
    - 80:80/tcp
    - 443:443/tcp
    command:
    - --web
    - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
    - --entryPoints=Name:https Address::443 TLS
    - --defaultentrypoints=http,https
    - --rancher
    - --rancher.domain=my.domain
    - --rancher.endpoint=https://rancher.my.domain/v1/projects/1a000
    - --rancher.accesskey=MY_ACCESS_KEY
    - --rancher.secretkey=MY_SECRET_KEY
    - --rancher.exposedbydefault=false
    - --acme
    - --acme.email=acme@my.domain
    - --acme.storage=/mnt/acme.json
    - --acme.entrypoint=https
    - --acme.ondemand=true
    - --logLevel=INFO

```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```

> 2017-5-19 15:09:06time="2017-05-19T18:09:06Z" level=info msg="Loaded ACME config from store /mnt/acme.json"
> 2017-5-19 15:09:07time="2017-05-19T18:09:07Z" level=warning msg="A new release has been found: 1.3.0-rc2. Please consider updating."
> 2017-5-19 15:09:16time="2017-05-19T18:09:16Z" level=error msg="Error creating TLS config: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
> 2017-5-19 15:09:16time="2017-05-19T18:09:16Z" level=fatal msg="Error preparing server: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
```

**Comment by ldez** [comment] 2017-05-19 18:28
Duplicate of #791 (and #1631 and #1632)

**Closed by ldez** 2017-05-19 18:28 UTC
Labels: area/acme, resolution/duplicate
