### ISSUE TITLE
Kubernetes example is using deprecated resources

### ISSUE THREAD

**Issue by dungahk** [containous/traefik#6411] opened 2020-02-29 21:13 UTC
### Do you want to request a *feature* or report a *bug*?
Feature?

Feature

### What did you expect to see?

An up to date Kubernetes file using not-deprecated resources at https://docs.traefik.io/routing/providers/kubernetes-crd/

At the moment `apiextensions.k8s.io/v1beta1` is deprecated in favor of `apiextensions.k8s.io/v1` and the `version` field should not be used anymore. See https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions

**Comment by ldez** [comment] 2020-02-29 21:37
duplicate of #5473

**Closed by ldez** 2020-02-29 21:37 UTC
Labels: resolution/duplicate

**Comment by dungahk** [comment] 2020-02-29 22:09
thanks, I'll try to spend more time looking for an existing issue next time, couldn't find that one.
