### ISSUE TITLE
Migrate k8s to kubernetes/client-go 

### ISSUE THREAD

**Issue by emilevauge** [containous/traefik#678] opened 2016-09-15 16:07 UTC
The official k8s go client has now its own repository and seems a lot more useful than the old one (https://github.com/kubernetes/kubernetes/issues/11606): https://github.com/kubernetes/client-go
It's time to migrate :)

**Comment by ekozan** [comment] 2016-09-26 16:32
the size of the client still ugly :/

**Comment by jsravn** [comment] 2017-02-21 16:10
It's large, but handles all known failure cases with the apiserver. I don't think traefik's client is correct. Also, it uses protobuf now which is much more efficient.

**Comment by jsravn** [comment] 2017-02-21 16:13
Ah I see this is a duplicate of an issue that covers many more of the problems, ignore me :)

**Comment by errm** [comment] 2017-02-21 23:29
This should have been closed when #836 was merged

**Closed by errm** 2017-02-21 23:29 UTC
Labels: provider/k8s
