### ISSUE TITLE
panic: Timeout while stopping traefik, killing instance ✝

### ISSUE THREAD

**Issue by ewirch** [containous/traefik#6935] opened 2020-06-18 07:59 UTC
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
Nothing in particular. Traefik is sometimes shut down by container redeploy.

### What did you expect to see?
Traefik shuts down gracefully.

### What did you see instead?
Shutdown times out and Traefik is killed.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
panic: Timeout while stopping traefik, killing instance ✝

goroutine 387 [running]:
github.com/containous/traefik/v2/pkg/server.(*Server).Close.func1(0x2cfd7e0, 0xc0033577a0)
	/go/src/github.com/containous/traefik/pkg/server/server.go:91 +0x10c
created by github.com/containous/traefik/v2/pkg/server.(*Server).Close
	/go/src/github.com/containous/traefik/pkg/server/server.go:86 +0x82
```

version: 2.2.1

**Comment by notsureifkevin** [comment] 2020-06-18 11:59
✝✝✝

Thanks for opening this issue @ewirch -- we'll need some more information from you to troubleshoot this, but a quick glance at the code tells me that the server will [force shut down after 10 seconds](https://github.com/containous/traefik/blob/v2.2/pkg/server/server.go#L84-L93) if certain [non-critical shutdown operations](https://github.com/containous/traefik/blob/v2.2/pkg/server/server.go#L95-L104) aren't completed. At this point in the shutdown though, [all entrypoints have been gracefully closed and decommissioned](https://github.com/containous/traefik/blob/v2.2/pkg/server/server.go#L73-L80), so Traefik isn't responding/handling requests.

We'd need to know more about your configuration, which middlewares do you have configured? Are you using any telemetry providers (metrics/tracing)? Can you provide the debug logs prior to the forced shutdown?

**Comment by aweris** [comment] 2020-07-01 14:25
@notsureifkevin  Sorry for the late reply. 

We're not using telemetry providers at the moment. Only using `basicAuth` and `redirectScheme` middleware. And unfortunately, we don't have debug logs prior to the problem.

However, we were using `cert-manager` to generate SSL certificates and hit the weekly limit for Lets Encrypt. As a result of this limitation, some of our `IngressRoute` definitions start to throw configuration errors. Do you think is it related to TLS config errors?

example error msg: 
```
 {
  ingress: "< retracted >"   
  level: "error"   
  msg: "Error configuring TLS: secret < retracted > not exist"   
  namespace: "< retracted >"   
  providerName: "kubernetescrd"   
 }
```

**Comment by notsureifkevin** [comment] 2020-07-01 15:25
@aweris no worries, thanks for checking in.

without steps to reproduce, debug logs, or a full trace, it's impossible to determine what is causing this issue. since we don't have enough information to troubleshoot, we will close the issue. however, if you come across this again and can provide us more details around the problem we'll definitely take a closer look. thanks again for your report.

**Closed** 2020-07-03 14:56 UTC
Labels: kind/bug/possible
