### ISSUE TITLE
While scaling Docker services we are getting 502 from traefik

### ISSUE THREAD

**Issue by avikatgithub** [containous/traefik#1855] opened 2017-07-11 15:15 UTC
Issue::
We are using docker swarm as backed.  When we are scaling up services during that we are hitting services (load test) we are getting 502 bad gateway during scaling up of the services. Whereas swarm says while scaling up it should be zero downtime and even if there is any it should show meaningful messages like 404 service not available. 

### What did you expect to see?
I shouldn't get any error or some meaning full message instead of 502.

### What did you see instead?
I see 502 bad gateway error.

### Output of `traefik version`: (_What version of Traefik are you using?_)
v1.3.3

Version:      v1.3.3
Codename:     raclette
Go version:   go1.8.3
Built:        2017-07-06_05:32:56PM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)

#graceTimeOut = "40s"
#MaxIdleConnsPerHost = 200
defaultEntryPoints = ["http", "https"]
logLevel = "DEBUG"
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  clientCAFiles = ["/etc/traefik/tls/file.crt"]
    [[entryPoints.https.tls.certificates]]
    certFile = "/etc/traefik/tls/file.cert"
    keyFile = "/etc/traefik/tls/file.key"

[web]
address = ":8080"


# IdleTimeout: maximum amount of time an idle (keep-alive) connection will remain idle before closing itself.
# This is set to enforce closing of stale client connections.
# Can be provided in a format supported by [time.ParseDuration](https://golang.org/pkg/time/#ParseDuration) or as raw
# values (digits). If no units are provided, the value is parsed assuming seconds.
#
# Optional
# Default: "180s"
#

IdleTimeout = "300s"



################################################################
# Docker Swarmmode configuration backend
################################################################

# Enable Docker configuration backend
#
# Optional
#
[docker]

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a services.
#
# Required
#
domain = "eib-dev.nt.lab.com"

watch = true

# Use Docker Swarm Mode as data provider
#
# Optional
#
swarmmode = true

<!--
Add more configuration information here.
-->

**Comment by timoreimann** [comment] 2017-07-11 15:45
I'm inclined to say this is a duplicate of #1480. See also https://github.com/containous/traefik/issues/1480#issuecomment-296501197 which references the open upstream issue moby/moby#30321 setting out to bring zero-downtime support.

**Comment by avikatgithub** [comment] 2017-07-11 18:25
@timoreimann Thanks a lot for your response. From the comments it seems there are two work around options.
1. increase the retry count which will add latency.
2. traefik.backend.loadbalancer.swarm=true label for more availability.

Could you please guide me which one to use or is there anything else I need to follow to achieve zero downtime.

**Comment by ldez** [comment] 2017-07-11 22:04
For the next please discuss this in the [Traefik community Slack channel](https://traefik.herokuapp.com)

**Closed by ldez** 2017-07-11 22:04 UTC
Labels: area/provider/docker/swarm, resolution/duplicate
