### ISSUE TITLE
[Kubernetes] When an IngressRoute references a TLSOptions item which isn't present, new traefik pods don't start

### ISSUE THREAD

**Issue by Daynnnnn** [containous/traefik#6465] opened 2020-03-11 14:02 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Created an IngressRoute which referenced a TLSOptions item which was not there

### What did you expect to see?

New traefik pods would load despite the misconfiguration.

### What did you see instead?

New pods would not load due to the misconfiguration, traefik loaded fine after removing the TLSOptions reference from the affected ingressroute

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
Version:      2.1.6
Codename:     cantal
Go version:   go1.13.8
Built:        2020-02-28T17:40:18Z
OS/Arch:      linux/amd64
```

```yml
          "--providers.kubernetesingress=true",
          "--providers.kubernetescrd=true",
          "--providers.kubernetesingress.ingressclass=traefik",
          "--entrypoints.http.address=:80",
          "--entrypoints.https.address=:443",
          "--entrypoints.traefik.address=:8080",
          "--entrypoints.http.proxyprotocol=true",
          "--entrypoints.https.proxyprotocol=true",
          "--entrypoints.http.proxyprotocol.trustedips=10.30.0.0/16",
          "--entrypoints.https.proxyprotocol.trustedips=10.30.0.0/16",
          "--entryPoints.traefik-metrics.address=:8082",
          "--ping.entrypoint=http",
          "--serverstransport.insecureskipverify=true",
          "--log=false",
          "--log.level=FATAL",
          "--accesslog.format=json",
          "--accesslog.fields.defaultmode=keep",
          "--accesslog.fields.headers.defaultmode=keep",
          "--accesslog=true",
          "--api=true",
          "--api.insecure",
          "--metrics.prometheus",
          "--metrics.prometheus.entryPoint=traefik-metrics",
          "--tracing=true",
          "--providers.file.filename=/etc/traefik/traefik-config.yaml"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
{"ClientAddr":"95.91.42.2:40781","ClientHost":"95.91.42.2","ClientPort":"40781","ClientUsername":"-","DownstreamContentSize":19,"DownstreamStatus":404,"Duration":114906,"OriginContentSize":19,"OriginDuration":14214,"OriginStatus":404,"Overhead":100692,"RequestAddr":"www.example.co.uk","RequestContentSize":0,"RequestCount":77,"RequestHost":"www.example.co.uk","RequestMethod":"GET","RequestPath":"/directory/search_tag/training%20in%20research%20delivery","RequestPort":"-","RequestProtocol":"HTTP/1.1","RetryAttempts":0,"StartLocal":"2020-03-11T12:32:22.689005625Z","StartUTC":"2020-03-11T12:32:22.689005625Z","downstream_Content-Type":"text/plain; charset=utf-8","downstream_X-Content-Type-Options":"nosniff","entryPointName":"http","level":"info","msg":"","origin_Content-Type":"text/plain; charset=utf-8","origin_X-Content-Type-Options":"nosniff","request_Accept":"text/html,text/plain,text/xml,text/*,application/xml,application/xhtml+xml,application/rss+xml,application/atom+xml,application/rdf+xml,application/php,application/x-php,application/x-httpd-php","request_Accept-Encoding":"br,gzip","request_Accept-Language":"en","request_User-Agent":"Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)","request_X-Forwarded-Host":"www.example.co.uk","request_X-Forwarded-Port":"80","request_X-Forwarded-Proto":"http","request_X-Forwarded-Server":"traefik-ingress-controller-84795cc76f-grznj","request_X-Real-Ip":"95.91.42.2","time":"2020-03-11T12:32:22Z"}
time="2020-03-11T12:32:22Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:37838->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
{"ClientAddr":"35.158.136.137:10234","ClientHost":"35.158.136.137","ClientPort":"10234","ClientUsername":"-","DownstreamContentSize":19,"DownstreamStatus":404,"Duration":126568,"OriginContentSize":19,"OriginDuration":10858,"OriginStatus":404,"Overhead":115710,"RequestAddr":"www.example.co.uk","RequestContentSize":0,"RequestCount":78,"RequestHost":"www.example.co.uk","RequestMethod":"GET","RequestPath":"/directory/search_tag/boost'r%20hybrid","RequestPort":"-","RequestProtocol":"HTTP/1.1","RetryAttempts":0,"StartLocal":"2020-03-11T12:32:23.001207426Z","StartUTC":"2020-03-11T12:32:23.001207426Z","downstream_Content-Type":"text/plain; charset=utf-8","downstream_X-Content-Type-Options":"nosniff","entryPointName":"http","level":"info","msg":"","origin_Content-Type":"text/plain; charset=utf-8","origin_X-Content-Type-Options":"nosniff","request_Accept-Encoding":"gzip","request_Cloudfront-Forwarded-Proto":"http","request_Connection":"Keep-Alive","request_User-Agent":"Amazon CloudFront","request_Via":"1.1 2d1e1e8dc0f3eb7773ec9d89a7d50ce2.cloudfront.net (CloudFront)","request_X-Amz-Cf-Id":"raJ8NK4qj1CcEYtvje2nczmohbpQOfL4CTQcPbAxubjPIWnUOwM3-g==","request_X-Forwarded-Host":"www.example.co.uk","request_X-Forwarded-Port":"80","request_X-Forwarded-Proto":"http","request_X-Forwarded-Server":"traefik-ingress-controller-84795cc76f-grznj","request_X-Real-Ip":"35.158.136.137","time":"2020-03-11T12:32:23Z"}
E0311 12:32:23.435469       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190718183610-8e956561bbf5/tools/cache/reflector.go:98: Failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha1.IngressRouteSpec.TLS: v1alpha1.TLS.Options: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|options":[{"name":"t|..., bigger context ...|master-openresty","port":80}]}],"tls":{"options":[{"name":"tlsoptions","namespace":"citipark-ecom-pr|...
{"ClientAddr":"156.67.242.12:29997","ClientHost":"156.67.242.12","ClientPort":"29997","ClientUsername":"-","DownstreamContentSize":19,"DownstreamStatus":404,"Duration":120844,"OriginContentSize":19,"OriginDuration":9981,"OriginStatus":404,"Overhead":110863,"RequestAddr":"central.exposecms.com","RequestContentSize":0,"RequestCount":79,"RequestHost":"www.example.co.uk","RequestMethod":"GET","RequestPath":"/times/employee/55","RequestPort":"-","RequestProtocol":"HTTP/1.1","RetryAttempts":0,"StartLocal":"2020-03-11T12:32:23.49085403Z","StartUTC":"2020-03-11T12:32:23.49085403Z","downstream_Content-Type":"text/plain; charset=utf-8","downstream_X-Content-Type-Options":"nosniff","entryPointName":"http","level":"info","msg":"","origin_Content-Type":"text/plain; charset=utf-8","origin_X-Content-Type-Options":"nosniff","request_Connection":"close","request_Cookie":"CakeCookie[employee_id]=55; PHPSESSID=db228477bf5d747a4a5389c1b8876483","request_X-Forwarded-Host":"central.exposecms.com","request_X-Forwarded-Port":"80","request_X-Forwarded-Proto":"http","request_X-Forwarded-Server":"traefik-ingress-controller-84795cc76f-grznj","request_X-Real-Ip":"156.67.242.12","time":"2020-03-11T12:32:23Z"}
E0311 12:32:24.809140       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190718183610-8e956561bbf5/tools/cache/reflector.go:98: Failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha1.IngressRouteSpec.TLS: v1alpha1.TLS.Options: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|options":[{"name":"t|..., bigger context ...|master-openresty","port":80}]}],"tls":{"options":[{"name":"tlsoptions","namespace":"citipark-ecom-pr|...
{"ClientAddr":"95.91.42.2:40781","ClientHost":"95.91.42.2","ClientPort":"40781","ClientUsername":"-","DownstreamContentSize":19,"DownstreamStatus":404,"Duration":109318,"OriginContentSize":19,"OriginDuration":11212,"OriginStatus":404,"Overhead":98106,"RequestAddr":"www.example.co.uk","RequestContentSize":0,"RequestCount":80,"RequestHost":"www.example.co.uk","RequestMethod":"GET","RequestPath":"/directory/search_tag/training%20institute","RequestPort":"-","RequestProtocol":"HTTP/1.1","RetryAttempts":0,"StartLocal":"2020-03-11T12:32:25.687732297Z","StartUTC":"2020-03-11T12:32:25.687732297Z","downstream_Content-Type":"text/plain; charset=utf-8","downstream_X-Content-Type-Options":"nosniff","entryPointName":"http","level":"info","msg":"","origin_Content-Type":"text/plain; charset=utf-8","origin_X-Content-Type-Options":"nosniff","request_Accept":"text/html,text/plain,text/xml,text/*,application/xml,application/xhtml+xml,application/rss+xml,application/atom+xml,application/rdf+xml,application/php,application/x-php,application/x-httpd-php","request_Accept-Encoding":"br,gzip","request_Accept-Language":"en","request_User-Agent":"Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)","request_X-Forwarded-Host":"www.example.co.uk","request_X-Forwarded-Port":"80","request_X-Forwarded-Proto":"http","request_X-Forwarded-Server":"traefik-ingress-controller-84795cc76f-grznj","request_X-Real-Ip":"95.91.42.2","time":"2020-03-11T12:32:25Z"}
time="2020-03-11T12:32:25Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:37838->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
```

This log output pretty much kept looping the same stuff after that, can supply if necessary.

**Comment by dtomcej** [comment] 2020-03-11 17:09
The error provided is that the ingressRoute was malformed.

Can you please provide the ingressRoute that caused this issue?

**Comment by Daynnnnn** [comment] 2020-03-11 17:26
IngerssRoute (With referenced middleware):
`apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: 'www.example.co.uk-https'
  namespace: 'example'
spec:
  entryPoints:
    - https
  routes:
  - match: Host(`www.example.co.uk`)
    kind: Rule
    services:
    - name: 'master-openresty'
      port: 80
    middlewares:
      - name: security-headers
        namespace: 'example'
  tls:
    secretName: 'a58ebb6197da843f22cf40cf5049362b-ssl'
    options:
    - name: tlsoptions
      namespace: 'example'
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: 'example'
spec:
  headers:
    frameDeny: "true"
    sslRedirect: "true"
    stsSeconds: 31536000
    stsPreload: "true"
    browserXssFilter: "true"
    sslForceHost: "true"
    contentTypeNosniff: "true"
    referrerPolicy: "same-origin"
    featurePolicy: "self"
    stsIncludeSubdomains: "true"
`

**Comment by dtomcej** [comment] 2020-03-11 17:39
Hello @Daynnnnn ,

From the reference documentation (https://docs.traefik.io/v2.1/reference/dynamic-configuration/kubernetes-crd/#resources),

tls options is not a list, can you try:

```
  tls:
    secretName: 'a58ebb6197da843f22cf40cf5049362b-ssl'
    options:
      name: tlsoptions
      namespace: 'example'
```

and see if that works the way you expect?

**Comment by ldez** [comment] 2020-03-11 17:42
Duplicate of #6370

**Comment by Daynnnnn** [comment] 2020-03-11 17:49
Hey @dtomcej,

Ahhh okay  I guess it's a different issue to what I thought, but my underlying point still stands. I don't think a miss-configured ingressroute should result in the whole reverse proxy failing to start - this could also mean an accidental space could take down all the http services on a cluster, which is very scary.

**Comment by dtomcej** [comment] 2020-03-11 17:54
@Daynnnnn, thanks for confirming that was the issue.

We are currently working on implementing validation via #6109 which should prevent this.

Feel free to follow that issue for more updates!

**Closed** 2020-03-11 18:00 UTC
Labels: area/provider/k8s/crd, resolution/duplicate
