### ISSUE TITLE
Traefik 1.5.* starts very slowly

### ISSUE THREAD

**Issue by yuriy-zhilovets2** [containous/traefik#3025] opened 2018-03-15 21:53 UTC
### Do you want to request a *feature* or report a *bug*?
a bug

### What did you do?

start traefik

### What did you expect to see?

Traefik is up and running in reasonable time

### What did you see instead?

```console
$ date
Птн Мар 16 00:26:12 MSK 2018

$ sudo ./traefik-1.5.3 --configFile=/etc/traefik/traefik.toml -d
WARN[0000] The ETCD API V2 is deprecated. Please use API V3 instead
```

_... 5 minutes later ..._

`WARN[0290] top-level traefikLogsFile has been deprecated -- please use traefiklog.filepath `

### Log file

```shell
time="2018-03-16T00:30:50+03:00" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml" 
time="2018-03-16T00:30:50+03:00" level=warning msg="web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics" 
time="2018-03-16T00:30:50+03:00" level=warning msg="top-level grace period configuration has been deprecated -- please use lifecycle grace period" 
time="2018-03-16T00:30:50+03:00" level=info msg="Traefik version v1.5.3 built on 2018-02-27_02:45:46PM" 
time="2018-03-16T00:30:50+03:00" level=info msg="
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://docs.traefik.io/basics/#collected-data
" 
time="2018-03-16T00:30:50+03:00" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc420356690 Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc420615ce0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
time="2018-03-16T00:30:50+03:00" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc4206e3180 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:true ProxyProtocol:<nil> ForwardedHeaders:0xc420615d00} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
time="2018-03-16T00:30:50+03:00" level=info msg="Starting server on :80" 
time="2018-03-16T00:30:51+03:00" level=info msg="Preparing server traefik &{Network: Address::1080 TLS:<nil> Redirect:<nil> Auth:0xc4204bf080 WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc420615d20} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
time="2018-03-16T00:30:51+03:00" level=info msg="Starting provider *file.Provider {"Watch":true,"Filename":"/etc/traefik/rules.toml","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Directory":""}" 
time="2018-03-16T00:30:51+03:00" level=info msg="Starting provider *etcd.Provider {"Watch":true,"Filename":"","Constraints":[],"Trace":true,"DebugLogGeneratedTemplate":true,"Endpoint":"127.0.0.1:2379","Prefix":"/traefik","TLS":null,"Username":"","Password":"","UseAPIV3":false}" 
time="2018-03-16T00:30:51+03:00" level=info msg="Starting server on :443" 
time="2018-03-16T00:30:51+03:00" level=info msg="Starting server on :1080" 
time="2018-03-16T00:30:51+03:00" level=warning msg="The ETCD API V2 is deprecated. Please use API V3 instead" 
time="2018-03-16T00:30:51+03:00" level=info msg="Node d888c6f9-16d0-4efd-9c0a-d6af1c9bddb5 elected worker ♝" 
time="2018-03-16T00:30:51+03:00" level=info msg="Server configuration reloaded on :1080" 
time="2018-03-16T00:30:51+03:00" level=info msg="Server configuration reloaded on :80" 
time="2018-03-16T00:30:51+03:00" level=info msg="Server configuration reloaded on :443" 
time="2018-03-16T00:30:51+03:00" level=info msg="Node d888c6f9-16d0-4efd-9c0a-d6af1c9bddb5 elected leader ♚" 
time="2018-03-16T00:31:41+03:00" level=info msg="Server configuration reloaded on :80" 
time="2018-03-16T00:31:41+03:00" level=info msg="Server configuration reloaded on :443" 
time="2018-03-16T00:31:41+03:00" level=info msg="Server configuration reloaded on :1080" 
time="2018-03-16T00:31:53+03:00" level=info msg="Skipping same configuration for provider etcd" 
time="2018-03-16T00:32:38+03:00" level=error msg="KV connection error: watchtree channel closed, retrying in 650.480148ms" 
time="2018-03-16T00:32:38+03:00" level=info msg="Server configuration reloaded on :443" 
time="2018-03-16T00:32:38+03:00" level=info msg="Server configuration reloaded on :1080" 
time="2018-03-16T00:32:38+03:00" level=info msg="Server configuration reloaded on :80" 
time="2018-03-16T00:34:55+03:00" level=info msg="Server configuration reloaded on :443" 
time="2018-03-16T00:34:55+03:00" level=info msg="Server configuration reloaded on :1080" 
time="2018-03-16T00:34:55+03:00" level=info msg="Server configuration reloaded on :80" 
```
And then, another 15 seconds later traefik starts to dispatch requests

### Additional info

The same happens with traefik v.1.5.2, v.1.5.1, v.1.5.0
traefik 1.4.4 starts 1-2 minutes, 1.3.0 even faster

Start under strace reveals nothing - no kernel requests at this 5 minutes:

```
...
lstat("nowhere", 0xc420344e08)          = -1 ENOENT (No such file or directory)
clock_gettime(CLOCK_MONOTONIC, {8793760, 577153287}) = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 577426917}) = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 577567321}) = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 577650840}) = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 580153968}) = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 580295613}) = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 580406368}) = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 580487370}) = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 580583513}) = 0
clock_gettime(CLOCK_REALTIME, {1521150596, 195023697}) = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 580739853}) = 0
epoll_wait(4, {}, 128, 0)               = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 580896426}) = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 580979498}) = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 581080100}) = 0
clock_gettime(CLOCK_MONOTONIC, {8793760, 581174564}) = 0
futex(0xc42002a538, FUTEX_WAKE, 1)      = 1
clock_gettime(CLOCK_MONOTONIC, {8793760, 581380210}) = 0
futex(0x3310ec0, FUTEX_WAIT, 0, {29, 999905536}WARN[0000] The ETCD API V2 is deprecated. Please use API V3 instead 
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.3
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-27_02:45:46PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
etcd 3.1.2

```json
{
 "LifeCycle": {
  "RequestAcceptGraceTimeout": "0s",
  "GraceTimeOut": "0s"
 },
 "GraceTimeOut": "0s",
 "Debug": false,
 "CheckNewVersion": false,
 "SendAnonymousUsage": false,
 "AccessLogsFile": "",
 "AccessLog": null,
 "TraefikLogsFile": "/var/log/traefik.log",
 "TraefikLog": null,
 "LogLevel": "INFO",
 "EntryPoints": {
  "http": {
   "Network": "",
   "Address": "xxxx",
   "TLS": null,
   "Redirect": {
    "entryPoint": "xxxx"
   },
   "Auth": null,
   "WhitelistSourceRange": null,
   "Compress": false,
   "ProxyProtocol": null,
   "ForwardedHeaders": null
  },
  "https": {
   "Network": "",
   "Address": "xxxx",
   "TLS": {
    "MinVersion": "VersionTLS10",
    "CipherSuites": null,
    "Certificates": [],
    "ClientCAFiles": null,
    "ClientCA": {
     "Files": null,
     "Optional": false
    }
   },
   "Redirect": null,
   "Auth": null,
   "WhitelistSourceRange": null,
   "Compress": false,
   "ProxyProtocol": null,
   "ForwardedHeaders": null
  }
 },
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [
  "http",
  "https"
 ],
 "ProvidersThrottleDuration": "2s",
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": "0s",
 "InsecureSkipVerify": false,
 "RootCAs": null,
 "Retry": null,
 "HealthCheck": {
  "Interval": "30s"
 },
 "RespondingTimeouts": null,
 "ForwardingTimeouts": null,
 "Web": {
  "Address": ":1080",
  "CertFile": "",
  "KeyFile": "",
  "ReadOnly": false,
  "Statistics": null,
  "Metrics": null,
  "Path": "",
  "Auth": {
   "Basic": {
    "Users": [],
    "UsersFile": ""
   },
   "Digest": null,
   "Forward": null,
   "HeaderField": ""
  },
  "Debug": false
 },
 "Docker": null,
 "File": null,
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": {
  "Watch": true,
  "Filename": "",
  "Constraints": [],
  "Trace": false,
  "DebugLogGeneratedTemplate": false,
  "Endpoint": "xxxx",
  "Prefix": "/traefik",
  "TLS": null,
  "Username": "",
  "Password": "",
  "UseAPIV3": false
 },
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ServiceFabric": null,
 "Rest": null,
 "API": null,
 "Metrics": null,
 "Ping": null,
 "ConfigFile": "/etc/traefik/traefik.toml"
}
```

**Comment by nmengin** [comment] 2018-04-05 12:03
Hello @yuriy-zhilovets2 .

Many thanks for your interest in the project.

I am sorry but I cannot reproduce your issue on my own machine.
I used successfully the [example](https://github.com/containous/traefik/tree/master/examples/cluster) with ETCD API V2 and V3.

Do you have still the problem?

I see you are using a ETCD 3.1.2, can you try to use ETCD V3 API?

**Comment by yuriy-zhilovets2** [comment] 2018-04-06 22:27
**Do you have still the problem?**
Yes, it is not transient. Every start hangs about 5 and even more minutes.

Some experiments:

I have deleted from the ETCD the whole tree _/traefik/backends_
Start time - 60 seconds

Then I have additionally deleted the tree _/traefik/frontends_
Start time - 9 seconds

I have restored both trees, start time is about 300 seconds again. I have ~ 30 backend+frontend pretty standard entries.

**can you try to use ETCD V3 API?**
Right now, no, the soft understands only etcd v2. But I might try some debugging version of the _traefik_.

**Comment by yuriy-zhilovets2** [comment] 2018-04-13 22:08
ETCD API v3 works well. Start lasts about 10-20 seconds.

**Comment by nmengin** [comment] 2018-04-18 07:06
Many thanks for your feedback @yuriy-zhilovets2 .

I'm happy to see that using ETCD V3  solved your problem.
ETCD V2 support is deprecated in Træfik and it's better to migrate to V3 if possible.

I close the issue because I guess it's solved, if necessary feel free to join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Closed by nmengin** 2018-04-18 07:06 UTC
Labels: contributor/waiting-for-feedback, kind/bug/possible, priority/P1
