### ISSUE TITLE
gRPC support

### ISSUE THREAD

**Issue by drewwells** [containous/traefik#1419] opened 2017-04-11 15:20 UTC
### What version of Traefik are you using (`traefik version`)?
1.2.1/HEAD

### What is your environment & configuration (arguments, toml...)?
OS X, linux

### What did you do?
Start up Golang gRPC examples: https://github.com/grpc/grpc-go/tree/master/examples

### What did you expect to see?
Successful connection between client and server

### What did you see instead?
Errors setting up transport by client

### If applicable, please paste the log output in debug mode (`--debug` switch)

Traefik supports http2 b/c this is enabled by default in net/http. However, gRPC requires special considerations when wiring together the transport between client <-> server. This may be a limitation of oxy.

**Comment by krancour** [comment] 2017-04-11 15:38
Related to #790

**Comment by drewwells** [comment] 2017-04-11 15:40
I think it's better to separate these. #790 is asking for configuration to support http2, there is nothing to configure for http2.

**Comment by krancour** [comment] 2017-04-11 15:57
Doesn't #790 propose, as you have, that the problem is in oxy? I think that makes these related, no?

**Comment by drewwells** [comment] 2017-04-11 15:59
That's when I thought there was an issue with http2 support. traefik can proxy http2 connections, but gRPC is not able to create transports through the proxy. Envoy supports this and explains a bit about some of the finer points https://lyft.github.io/envoy/docs/configuration/http_filters/grpc_http1_bridge_filter.html

**Comment by tcolgate** [comment] 2017-05-19 11:22
I've been experimenting with this. It can work but...

- Go's HTTP client will not do http2 if insecureSkipVerify.
- With a backend such as marathon, you have to make sure they are serving TLS with a cert that is valid.

**Comment by tcolgate** [comment] 2017-05-19 16:37
My suspicion is that oxy isn't copy trailers. I'll look into this.

**Comment by drewwells** [comment] 2017-05-19 17:30
The TLS cert on the server only needs to be valid for the client. So using compatible self-signed on both sides works, this is how we do it.

**Comment by tcolgate** [comment] 2017-05-19 18:38
Yes, same here. Do you have working gRPC calls? Mine are fine as long as
they are sending errors, but a full return seems to fail.

**Comment by drewwells** [comment] 2017-05-19 19:21
I haven't via a proxy or via oxy.

**Comment by tcolgate** [comment] 2017-05-20 11:53
I've located the cause of the problem, and have a preliminiary fix (found the problem in a comment in caddy's source in the end). https://github.com/mholt/caddy/blob/master/caddyhttp/proxy/reverseproxy.go
Oxy doesn't copy trailers, and there's an extra step needed becaue grpc.Serve() doesn't announce the trailers in advance.
  Oxy has actually moved over to using httputil.ReverseProxy for the forward support, unfortunately that is broken in the same way, and also means the PR isn't to oxy, but to a core Go package :(
I'll give it a go anyway

**Comment by tcolgate** [comment] 2017-05-20 11:55
since you have a fork of oxy, I can send you the fix for that.

**Comment by tcolgate** [comment] 2017-05-20 12:17
Preliminary PR https://github.com/containous/traefik/pull/1639

**Comment by tcolgate** [comment] 2017-05-23 19:40
By way of an "endorsemnt", my fix for httputil.ReverseProxy, along the same lines, got merged for go 1.9 I think. https://github.com/golang/go/issues/20437

**Comment by ldez** [comment] 2017-08-29 09:45
gRPC is fully supported noew.

**Closed by ldez** 2017-08-29 09:45 UTC
Labels: area/oxy, kind/enhancement, priority/P2

**Comment by saschagrunert** [comment] 2017-08-29 19:04
Really? I will give it a try

**Comment by arunkjn** [comment] 2017-09-07 09:41
Is it working in 1.3.7?

**Comment by SantoDE** [comment] 2017-09-07 09:43
@arunkjn you need to try the 1.4.0-rc1 :)

**Comment by arunkjn** [comment] 2017-09-07 09:48
@SantoDE  Cool. Also is SSL mandatory for it to work?

**Comment by ldez** [comment] 2017-09-07 09:52
@arunkjn yes

**Comment by arunkjn** [comment] 2017-09-07 12:50
I am having trouble setting up tls with self signed certificates in local environment. Could you please point me to some docs I can refer?

**Comment by beenokle** [comment] 2017-09-07 13:45
I got the same problem on 1.4.0-rc1
`level=warning msg="Error forwarding to https://127.0.0.1:4002, err: EOF"`

I use self-signed certificate
Direct TLS connection `GrpcClient -> GrpcServer` works well
`GrpcClient -> Traefik -> GrpcServer` does not (EOF error)

I set the same certificate for Traefik as on backend grpc server

My traefik configuration is:
```
InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"  
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/server.pem"
      KeyFile = "/ssl/server.key"  

[web]      
address = ":8080"

[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "https://127.0.0.1:4002"

[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.byhost]
    rule = "Host:testgrpc.dev"  
```

Does the problem relate to self-signed certificate?

**Comment by ldez** [comment] 2017-09-07 13:46
Thanks for your interest in Traefik 😃 

This issue is closed. Please discuss this in :
- the [Traefik community Slack channel](https://traefik.herokuapp.com)

**Comment by Juliens** [comment] 2017-09-07 13:53
@arunkjn The documentation is in WIP, I try to publish it soon

@beenokle
You can not use InsecureSkipVerifiy, because in this case, http2 is not working (and grpc neither).

You must use RootCAs in traefik in order to have a valid https backend (https://docs.traefik.io/configuration/commons/#main-section)

For more information come on the [Traefik community Slack channel](https://traefik.herokuapp.com)
