### ISSUE TITLE
[Feature] Add support for HTTPS/TLS encrypted backends (loadbalancing/routing)

### ISSUE THREAD

**Issue by janknieling** [containous/traefik#6913] opened 2020-06-11 10:43 UTC
**[Feature] Add support for HTTPS/TLS encrypted backends (loadbalancing/routing)**

Can you please add support for full HTTPS/TLS encryption, so that routing/loadbalancing to HTTPS/TLS (for HTTP router and TCP router) encrypted backends is possible?
Now if I have the following construction  HTTPS/TLS -> Traefik -> Backend service (encrypted via TLS oder HTTPS) I only can use a TCP router with TLS passthrough. 
In my opinion this isn't very optimal because I have to add the hostname/domainname of the loadbalancer to the SANs ot the backend certifiactes. 
Bacause of that I can't get them via ACME from LetsEncrypt or my internal CA (like smallstep ca).

This feature is very important for me because of some guidelines internal traffic between VMs, kubernetes pods (or services on bare metal servers) not running on the same host must be encrypted via HTTPS oder TLS (because of the risk of man in the middle attacks)

Other Loadbalancers like HAProxy have these feature if I remember correctly.

Thank you very much

**Comment by jbdoumenjou** [comment] 2020-06-12 15:16
duplicate of #4835

**Closed by jbdoumenjou** 2020-06-12 15:16 UTC
Labels: resolution/duplicate
