### ISSUE TITLE
DelayBeforeCheck option does not work

### ISSUE THREAD

**Issue by BaronMsk** [containous/traefik#2997] opened 2018-03-11 16:57 UTC
### Do you want to request a *feature* or report a *bug*?
`DelayBeforeCheck` option does not work

### What did you expect to see?
Delay 300 seconds before checking TXT recording

### What did you see instead?

Testing revealed that TXT recording is created for 3-4 seconds

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.3
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-27_02:47:04PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
k8s, consul kv
```
curl -XPUT --data "300" https://consul.local/kv/traefik/acme/dnschallenge/delaybeforecheck 
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

**Comment by liderman** [comment] 2018-03-11 17:06
+1

**Comment by nmengin** [comment] 2018-03-12 10:42
Hello @BaronMsk ,

Many thanks for your interest in the project.
We need more information to reproduce your problem.

Can you precise if : 
- You are using the `storeconfig` command to export the others options. If yes, are you sending the insertion request before to launch the `storeconfig` command?
- Is Træfik already started when you sent the insertion request? If yes, does the problem persits if you restart Træfik?

Morevover, can you provide us your Træfik configuration and logs?

Thank you in advance.

**Comment by BaronMsk** [comment] 2018-03-12 11:34
Hello @nmengin 

- At the first start, I used ```traefik storeconfig```, when the kv structure was created, an option was set via ```curl -XPUT --data "300" https://consul.local/kv/traefik/acme/dnschallenge/delaybeforecheck ```

- At the moment I had to start v1.5.0-rc4 because in this version the delay works correctly, the problem repeats after restarting traefik.

**Comment by nmengin** [comment] 2018-03-13 09:13
Hello @BaronMsk.

Many thanks for your feedback.
Unfortunately, I cannot reproduce your issue with Træfik V1.5.3.
Can you give me more information : 

- How many instances of Træfik are you using?
- Do you have a `traefik.toml` file in one of these paths : `/`, `/etc/traefik/`, `$HOME/.traefik/`, `${TRAEFIK_PATH`)?
- Can you send me the logs? At least the logs generated when Træfik starts.
- Can you provide me all your configuration?

**Comment by BaronMsk** [comment] 2018-03-13 09:49
- 5 instances

-  There are no files, I'm using kv consul

-  log files are not saved, now I'm using the RC version, if it's important, I can try running again 1.5.3

- traefik.toml    
```
logLevel = "INFO"
checkNewVersion = false
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]

[acme]
email = "devops@domain.ru"
storage = "traefik/acme/account"
dnsProvider = "pdns"
delayDontCheckDNS = 300
entryPoint = "https"
onDemand = false
OnHostRule = true
acmeLogging = true

[web]
ReadOnly = true

[kubernetes]
```

**Comment by nmengin** [comment] 2018-03-14 09:25
Hello @BaronMsk,

> 5 instances

Are you sure you are using the same Træfik as cluster leader when the error occurs?
Indeed, the `ACME Account` is loaded when Træfik starts, if the value was not modified when one of the instance starts, this instance will not takes the option in account.

> I can try running again 1.5.3

Released version is more stable than RC, it can be a good idea even if I do not think it will change the behavior.

>dnsProvider = "pdns"
delayDontCheckDNS = 300

These options are deprecated in 1.5. Moreover, using both `acme.delaydontcheckDNS` and `acme.dnschallenge.delaybeforecheck` can be a problem, if Træfik detects the both values, it will not use `acme.dnschallenge.delaybeforecheck`. 

Can you delete them and use : 
```
[acme]
email = "devops@domain.ru"
storage = "traefik/acme/account"
entryPoint = "https"
onDemand = false
OnHostRule = true
acmeLogging = true
  [dnsChallenge]
  provider = "pdns"
  delayBeforeCheck = 300
```

**Comment by BaronMsk** [comment] 2018-03-16 10:13
log

> legolog: 2018/03/16 09:45:01 [INFO][telegraminfobot.services.citik.ru] acme: Trying renewal with 718 hours remaining
legolog: 2018/03/16 09:45:01 [INFO][telegraminfobot.services.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/16 09:45:02 [INFO][telegraminfobot.services.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/Kb5FLfGJqShJ-XsrWPQGPEXpTbuT2mDZiIpjN5dLcNA
legolog: 2018/03/16 09:45:02 [INFO][telegraminfobot.services.citik.ru] acme: Could not find solver for: http-01
legolog: 2018/03/16 09:45:02 [INFO][telegraminfobot.services.citik.ru] acme: Trying to solve DNS-01
legolog: 2018/03/16 09:45:02 [INFO][telegraminfobot.services.citik.ru] Checking DNS record propagation using [10.1.28.10:53]
time="2018-03-16T09:45:04Z" level=error msg="Error renewing certificate from LE: acme: Error 400 - urn:acme:error:connection - DNS problem: NXDOMAIN looking up TXT for _acme-challenge.telegraminfobot.services.citik.ru
Error Detail:
"

**Comment by BaronMsk** [comment] 2018-03-19 09:00
log ver 1.5.4 
legolog: 2018/03/16 12:16:46 [INFO][docker.citik.ru] acme: Trying renewal with 691 hours remaining
legolog: 2018/03/16 12:16:46 [INFO][docker.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/16 12:16:47 [INFO][docker.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/i_bsxuQSAUd4XecP9BhoT4vveAE_yJ-OeH1Qdo1ve2M
legolog: 2018/03/16 12:16:47 [INFO][docker.citik.ru] acme: Could not find solver for: http-01
legolog: 2018/03/16 12:16:47 [INFO][docker.citik.ru] acme: Trying to solve DNS-01
legolog: 2018/03/16 12:16:47 [INFO][docker.citik.ru] Checking DNS record propagation using [10.1.28.10:53]
time="2018-03-16T12:16:49Z" level=error msg="Error renewing certificate from LE: acme: Error 403 - urn:acme:error:unauthorized - No TXT record found at _acme-challenge.docker.citik.ru
Error Detail:
" 
legolog: 2018/03/16 12:16:49 [INFO][product-view-daemon.services.citik.ru] acme: Trying renewal with 642 hours remaining
legolog: 2018/03/16 12:16:49 [INFO][product-view-daemon.services.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/16 12:16:49 [INFO][product-view-daemon.services.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/c0G67Dr60tUk6Qqc6Z_rZxAgR5vbHKhkNvG2SEs3l5I
legolog: 2018/03/16 12:16:49 [INFO][product-view-daemon.services.citik.ru] acme: Authorization already valid; skipping challenge
legolog: 2018/03/16 12:16:49 [INFO][product-view-daemon.services.citik.ru] acme: Validations succeeded; requesting certificates
time="2018-03-16T12:16:50Z" level=error msg="Error renewing certificate from LE: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: product-view-daemon.services.citik.ru: see https://letsencrypt.org/docs/rate-limits/" 
legolog: 2018/03/16 12:16:50 [INFO][telegraminfobot.services.citik.ru] acme: Trying renewal with 715 hours remaining
legolog: 2018/03/16 12:16:50 [INFO][telegraminfobot.services.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/16 12:16:51 [INFO][telegraminfobot.services.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/iuC_14gZDVEAxeUFIqYwOHRI3QlDtEwFLSJbW65FTF0
legolog: 2018/03/16 12:16:51 [INFO][telegraminfobot.services.citik.ru] acme: Trying to solve DNS-01
legolog: 2018/03/16 12:16:51 [INFO][telegraminfobot.services.citik.ru] Checking DNS record propagation using [10.1.28.10:53]
time="2018-03-16T12:16:53Z" level=error msg="Error renewing certificate from LE: acme: Error 400 - urn:acme:error:connection - DNS problem: NXDOMAIN looking up TXT for _acme-challenge.telegraminfobot.services.citik.ru
Error Detail:
" 
legolog: 2018/03/17 12:16:34 [INFO][ci.citik.ru] acme: Trying renewal with 715 hours remaining
legolog: 2018/03/17 12:16:34 [INFO][ci.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/17 12:16:38 [INFO][ci.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/cv9e74q-nAp4fQl3zfNafY3chC-cqkHxroe-Ea67dVg
legolog: 2018/03/17 12:16:38 [INFO][ci.citik.ru] acme: Trying to solve DNS-01
legolog: 2018/03/17 12:16:43 [INFO][ci.citik.ru] Checking DNS record propagation using [10.1.28.10:53]
time="2018-03-17T12:16:45Z" level=error msg="Error renewing certificate from LE: acme: Error 403 - urn:acme:error:unauthorized - No TXT record found at _acme-challenge.ci.citik.ru
Error Detail:
" 
legolog: 2018/03/17 12:16:45 [INFO][docker.citik.ru] acme: Trying renewal with 667 hours remaining
legolog: 2018/03/17 12:16:45 [INFO][docker.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/17 12:16:45 [INFO][docker.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/fjmsu-YC6j28ESZDfJYB4JiFd6n7pD73l4JtwzoW2xw
legolog: 2018/03/17 12:16:45 [INFO][docker.citik.ru] acme: Could not find solver for: http-01
legolog: 2018/03/17 12:16:45 [INFO][docker.citik.ru] acme: Trying to solve DNS-01
legolog: 2018/03/17 12:16:45 [INFO][docker.citik.ru] Checking DNS record propagation using [10.1.28.10:53]
time="2018-03-17T12:16:47Z" level=error msg="Error renewing certificate from LE: acme: Error 403 - urn:acme:error:unauthorized - No TXT record found at _acme-challenge.docker.citik.ru
Error Detail:
" 
legolog: 2018/03/17 12:16:47 [INFO][product-view-daemon.services.citik.ru] acme: Trying renewal with 618 hours remaining
legolog: 2018/03/17 12:16:47 [INFO][product-view-daemon.services.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/17 12:16:48 [INFO][product-view-daemon.services.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/c0G67Dr60tUk6Qqc6Z_rZxAgR5vbHKhkNvG2SEs3l5I
legolog: 2018/03/17 12:16:48 [INFO][product-view-daemon.services.citik.ru] acme: Authorization already valid; skipping challenge
legolog: 2018/03/17 12:16:48 [INFO][product-view-daemon.services.citik.ru] acme: Validations succeeded; requesting certificates
time="2018-03-17T12:16:48Z" level=error msg="Error renewing certificate from LE: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: product-view-daemon.services.citik.ru: see https://letsencrypt.org/docs/rate-limits/" 
legolog: 2018/03/17 12:16:48 [INFO][telegraminfobot.services.citik.ru] acme: Trying renewal with 691 hours remaining
legolog: 2018/03/17 12:16:48 [INFO][telegraminfobot.services.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/17 12:16:49 [INFO][telegraminfobot.services.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/TmVYSDClDq_ybbPtM5LETwhJDE3znQbNPahzyRWZb70
legolog: 2018/03/17 12:16:49 [INFO][telegraminfobot.services.citik.ru] acme: Could not find solver for: http-01
legolog: 2018/03/17 12:16:49 [INFO][telegraminfobot.services.citik.ru] acme: Trying to solve DNS-01
legolog: 2018/03/17 12:16:49 [INFO][telegraminfobot.services.citik.ru] Checking DNS record propagation using [10.1.28.10:53]
time="2018-03-17T12:16:51Z" level=error msg="Error renewing certificate from LE: acme: Error 400 - urn:acme:error:connection - DNS problem: NXDOMAIN looking up TXT for _acme-challenge.telegraminfobot.services.citik.ru
Error Detail:
" 
legolog: 2018/03/17 12:16:51 [INFO][www.docker.citik.ru] acme: Trying renewal with 715 hours remaining
legolog: 2018/03/17 12:16:51 [INFO][www.docker.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/17 12:16:53 [INFO][www.docker.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/YWti6EheJEwDI9GsIskLtaHh40pFKMrfxYz7vBfr4ac
legolog: 2018/03/17 12:16:53 [INFO][www.docker.citik.ru] acme: Could not find solver for: tls-sni-01
legolog: 2018/03/17 12:16:53 [INFO][www.docker.citik.ru] acme: Could not find solver for: http-01
legolog: 2018/03/17 12:16:53 [INFO][www.docker.citik.ru] acme: Trying to solve DNS-01
legolog: 2018/03/17 12:16:53 [INFO][www.docker.citik.ru] Checking DNS record propagation using [10.1.28.10:53]
time="2018-03-17T12:16:55Z" level=error msg="Error renewing certificate from LE: acme: Error 403 - urn:acme:error:unauthorized - No TXT record found at _acme-challenge.www.docker.citik.ru
Error Detail:
" 
legolog: 2018/03/18 12:16:34 [INFO][ci.citik.ru] acme: Trying renewal with 691 hours remaining
legolog: 2018/03/18 12:16:34 [INFO][ci.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/18 12:16:35 [INFO][ci.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/JtatsMQ-5hpS03QYv1-Xbxv8wJmww-kOUAsAtsYHBpM
legolog: 2018/03/18 12:16:35 [INFO][ci.citik.ru] acme: Could not find solver for: http-01
legolog: 2018/03/18 12:16:35 [INFO][ci.citik.ru] acme: Trying to solve DNS-01
legolog: 2018/03/18 12:16:40 [INFO][ci.citik.ru] Checking DNS record propagation using [10.1.28.10:53]
time="2018-03-18T12:16:41Z" level=error msg="Error renewing certificate from LE: acme: Error 403 - urn:acme:error:unauthorized - No TXT record found at _acme-challenge.ci.citik.ru
Error Detail:
" 
legolog: 2018/03/18 12:16:41 [INFO][docker.citik.ru] acme: Trying renewal with 643 hours remaining
legolog: 2018/03/18 12:16:41 [INFO][docker.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/18 12:16:42 [INFO][docker.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/qiZnEfJv3bt92gdi7Yp86VrRLFPq9mb9Dt7XsiBvppU
legolog: 2018/03/18 12:16:42 [INFO][docker.citik.ru] acme: Could not find solver for: http-01
legolog: 2018/03/18 12:16:42 [INFO][docker.citik.ru] acme: Could not find solver for: tls-sni-01
legolog: 2018/03/18 12:16:42 [INFO][docker.citik.ru] acme: Trying to solve DNS-01
legolog: 2018/03/18 12:16:42 [INFO][docker.citik.ru] Checking DNS record propagation using [10.1.28.10:53]
time="2018-03-18T12:16:44Z" level=error msg="Error renewing certificate from LE: acme: Error 403 - urn:acme:error:unauthorized - No TXT record found at _acme-challenge.docker.citik.ru
Error Detail:
" 
legolog: 2018/03/18 12:16:44 [INFO][product-view-daemon.services.citik.ru] acme: Trying renewal with 594 hours remaining
legolog: 2018/03/18 12:16:44 [INFO][product-view-daemon.services.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/18 12:16:45 [INFO][product-view-daemon.services.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/c0G67Dr60tUk6Qqc6Z_rZxAgR5vbHKhkNvG2SEs3l5I
legolog: 2018/03/18 12:16:45 [INFO][product-view-daemon.services.citik.ru] acme: Authorization already valid; skipping challenge
legolog: 2018/03/18 12:16:45 [INFO][product-view-daemon.services.citik.ru] acme: Validations succeeded; requesting certificates
time="2018-03-18T12:16:45Z" level=error msg="Error renewing certificate from LE: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: product-view-daemon.services.citik.ru: see https://letsencrypt.org/docs/rate-limits/" 
legolog: 2018/03/18 12:16:45 [INFO][telegraminfobot.services.citik.ru] acme: Trying renewal with 667 hours remaining
legolog: 2018/03/18 12:16:45 [INFO][telegraminfobot.services.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/18 12:16:46 [INFO][telegraminfobot.services.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/NftsE31PMAtb1P73wuNf4Gs3MbXfbap6czuOkiCFjzU
legolog: 2018/03/18 12:16:46 [INFO][telegraminfobot.services.citik.ru] acme: Trying to solve DNS-01
legolog: 2018/03/18 12:16:46 [INFO][telegraminfobot.services.citik.ru] Checking DNS record propagation using [10.1.28.10:53]
time="2018-03-18T12:16:48Z" level=error msg="Error renewing certificate from LE: acme: Error 400 - urn:acme:error:connection - DNS problem: NXDOMAIN looking up TXT for _acme-challenge.telegraminfobot.services.citik.ru
Error Detail:
" 
legolog: 2018/03/18 12:16:48 [INFO][www.docker.citik.ru] acme: Trying renewal with 691 hours remaining
legolog: 2018/03/18 12:16:48 [INFO][www.docker.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/18 12:16:49 [INFO][www.docker.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/HsHwEKkkYwKLkLrEjJxJiBRq5RM-SJmlPm062MBKrU4
legolog: 2018/03/18 12:16:49 [INFO][www.docker.citik.ru] acme: Could not find solver for: http-01
legolog: 2018/03/18 12:16:49 [INFO][www.docker.citik.ru] acme: Could not find solver for: tls-sni-01
legolog: 2018/03/18 12:16:49 [INFO][www.docker.citik.ru] acme: Trying to solve DNS-01
legolog: 2018/03/18 12:16:49 [INFO][www.docker.citik.ru] Checking DNS record propagation using [10.1.28.10:53]
time="2018-03-18T12:16:51Z" level=error msg="Error renewing certificate from LE: acme: Error 400 - urn:acme:error:connection - DNS problem: NXDOMAIN looking up TXT for _acme-challenge.www.docker.citik.ru
Error Detail:
"

**Comment by BaronMsk** [comment] 2018-03-23 14:47
@nmengin  hi, I hardcoded the  function sleep and now the program works as it should:

> legolog: 2018/03/23 14:28:56 [INFO][ci.citik.ru] acme: Trying renewal with 569 hours remaining
legolog: 2018/03/23 14:28:56 [INFO][ci.citik.ru] acme: Obtaining bundled SAN certificate
legolog: 2018/03/23 14:28:57 [INFO][ci.citik.ru] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/vKIGsbKHQJ7WWhMtJOn9Nos76dow-b2tc9SO1tB1C8k
legolog: 2018/03/23 14:28:57 [INFO][ci.citik.ru] acme: Trying to solve DNS-01
legolog: 2018/03/23 14:28:57 [INFO][ci.citik.ru] Checking DNS record propagation using [10.1.28.10:53]
legolog: 2018/03/23 14:33:59 [INFO][ci.citik.ru] The server validated our request
legolog: 2018/03/23 14:33:59 [INFO][ci.citik.ru] acme: Validations succeeded; requesting certificates
legolog: 2018/03/23 14:34:00 [INFO] acme: Requesting issuer cert from https://acme-v01.api.letsencrypt.org/acme/issuer-cert
legolog: 2018/03/23 14:34:00 [INFO][ci.citik.ru] Server responded with a certificate.
time="2018-03-23T14:34:00Z" level=error msg="Datastore sync error: Object lock value: expected 8f022e6c-df5e-48b1-8948-386d33832657, got b94b2c9e-282c-478d-bb90-975433e4b2af, retrying in 713.857052ms" 

[MyCommit](https://github.com/BaronMsk/traefik/commit/2bf9dbd735ec7259ffdeef7be84f4516481a1cb9)

**Comment by BaronMsk** [comment] 2018-03-25 20:09
If in time.Sleep transmit int64 then wait will be in nanoseconds!

**Comment by nmengin** [comment] 2018-03-26 15:29
Hello @BaronMsk,

As I said in your PR #3077 : 

> `acme.dnsChallenge.delayBeforeCheck` option type is `Duration`, it is stored in **nano seconds** in the KV store by the `storeconfig`  command.

That's why the values have to be put in nanoseconds.

I close the issue but feel free to join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Closed by nmengin** 2018-03-26 15:29 UTC
Labels: area/acme, kind/question
