### ISSUE TITLE
Allow multiple different backends to receive the same request at the same time

### ISSUE THREAD

**Issue by yangm97** [containous/traefik#3503] opened 2018-06-15 16:54 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Kind like pub/sub but for HTTP. While we could use nginx with this config:

```
upstream  multiple_upstream  {
    server   host1
    server   host2
    server   host3
}
server {
    location / {
        proxy_pass http://multiple_upstream;
}
```

There are several drawbacks, like the fact nginx does the dns resolving once and only on the startup, so if one of the upstream servers is down nginx will refuse to start. Even worse, if you update the docker container of one of the upstreams and they do change the ip, nginx won’t be able to redirect requests to this new container, nor can it handle multiple containers/machines like treaefik does.

**Comment by ldez** [comment] 2018-06-15 17:17
Related to  #3040

**Comment by mmatur** [comment] 2018-06-18 16:08
Duplicate of #2989

**Closed by mmatur** 2018-06-18 16:08 UTC
Labels: status/0-needs-triage
