### ISSUE TITLE
Traefik dashboard front-end and back-end are not listed correctly as a pair

### ISSUE THREAD

**Issue by sercanyaldiz** [containous/traefik#5092] opened 2019-07-13 11:35 UTC
# Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
I configured the dashboard according the documentation

### What did you expect to see?
I expect to see the right back-end match the front-end in the dashboard view

### What did you see instead?
The back-end is not matching its front-end in the dashboard view. See picture below
![Traefik-Dashboard](https://user-images.githubusercontent.com/19766523/61171099-142fa680-a573-11e9-8fb3-bf2db3d5c47c.jpg)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

``` Arguements
lb:
    image: traefik
    command:  --docker \
              --api \
              --docker.network=django-app_overlay \
              --logLevel="DEBUG" \
              --accesslog \
              --docker.swarmmode \
              --docker.domain=docker.local \
              --docker.watch \
              --docker.exposedbydefault="false"
    ports:
      - 80:80
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - overlay
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.backend=traefik"
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:traefik.local"
        - "traefik.frontend.entryPoints=http"
```

**Comment by yourchanges** [comment] 2019-07-15 06:07
same problem

**Comment by dduportal** [comment] 2019-07-15 09:54
Hin @sercanyaldiz , could you elaborate a bit more please? On the screenshot, I can see that each "frontend" object on the left column has a field "Backend". Both frontend sounds like to have this field populated by the right backend: the frontend with the rule `Host:traefik.xxx` is asscoiated to the backend named `backend-traefik`. Isn't this the expected behavior?

**Comment by dduportal** [comment] 2019-07-15 15:19
Hi @sercanyaldiz , it looks like that you are expecting the mapping frontend <-> backend to happen on the web UI.

Alas each section is an isolated list, so it's not an expected behavior.

For your information, as the Traefik 1.7.x branch is not accepting any feature change,
and as Traefik v2.à is upcoming with a new UI, we'll close this issue.

Thanks for your interest on the project, feel free to reopen it if there is any misunderstanding.

**Closed by dduportal** 2019-07-15 15:19 UTC
Labels: kind/question, status/0-needs-triage

**Comment by sercanyaldiz** [comment] 2019-07-15 17:40
@dduportal thank you for your feedback and I will use v2 then!
