### ISSUE TITLE
Error starting provider *kubernetes.Provider: endpoint missing for external cluster client

### ISSUE THREAD

**Issue by Starefossen** [containous/traefik#1989] opened 2017-08-22 10:14 UTC
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Deployed Træfik to Kubernetes as a DaemonSet.

### What did you expect to see?

I expected all instances (Pods) of Træfik to have the same configuration.

### What did you see instead?

One of the pods had the following console log error message and no other configuration:

```
Error starting provider *kubernetes.Provider: endpoint missing for external cluster client
``` 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.3.3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
checkNewVersion = false                                    
                                                           
logLevel = "WARN"                                          
                                                           
InsecureSkipVerify = true                                  
                                                           
defaultEntryPoints = ["http", "https"]                     
                                                           
[entryPoints]                                              
  [entryPoints.http]                                       
  address = ":80"                                          
                                                           
  [entryPoints.https]                                      
  address = ":443"                                         
    [entryPoints.https.tls]                                
      [[entryPoints.https.tls.certificates]]               
      CertFile = "**REDACTED**.pem"
      KeyFile = "**REDACTED**.key" 
                                                           
[web]                                                      
address = ":8181"                                          
                                                           
[web.metrics.prometheus]                                   
Buckets=[0.1,0.3,1.2,5.0]                                  
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

**Comment by timoreimann** [comment] 2017-08-22 19:41
Traefik only tries to create an out-of-cluster client connection if it does not find one of the `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` environment variables. Can you make sure they are available?

What version of Kubernetes are you running?

**Comment by Starefossen** [comment] 2017-08-22 21:37
Restarting solved the problem, but it was very scary that it remained running and did not exit when it hit this error. I'll try setting the variables you mentioned for my Træfik deployment.

Kubernetes version `1.6.7`

**Comment by timoreimann** [comment] 2017-08-23 00:59
The variables should be injected by Kubernetes. There should be no need to set them manually.

My best guess is that some control loop hadn't finished yet so the node wasn't quite ready.

Making a decision to exit can be tricky: there might be other providers running just fine, so we'd be stopping them as well. It's not a no-go but it's something to be considered carefully. A better approach is often to retry; unfortunately, environment variables are only injected during process startup.

If you have a chance to determine the root cause of your problem, we can further consider ways to mitigate / solve the issue.

**Comment by timoreimann** [comment] 2017-09-08 09:07
@Starefossen did you manage to determine the reason for your problem by now?

**Comment by Starefossen** [comment] 2017-10-22 06:01
I haven't been able to reproduce this error with any of the versions since v.1.3.3. Closing this. Thanks for all the help and making Træfik so awesome ❤️

**Comment by mvernimmen** [comment] 2018-02-21 09:01
@timoreimann I'm sorry to respond on a closed ticket, but I don't want to open a new one just yet (I'd be happy to do so if you prefer that). I just had the same problem with traefik version 1.4.6 on kubernetes 1.8.3.
This happened after restarting each of the nodes in the cluster for OS updates. Strangely, only 1 of the 3 daemonset ingress controllers was affected with this problem. I've seen the same happen before on older versions of traefik and kubernetes but back then it was only a 1 time thing, now it's becoming a pattern.

I don't mind if traefik breaks, but because the pod continued running and did not show an error to the outside world (only the entry in the log), this would be very hard to detect by our monitoring systems. Would it perhaps be possible for traefik to exit when it comes upon this error? I'm not sure what providers would be running in the same pod that would be considered ok, but in my mind if one component in a pod is not ok, the whole pod is not ok. Safety in numbers (more than 1 traefik instance) will make sure the cluster remains available while the pod terminates.

**Comment by timoreimann** [comment] 2018-02-25 20:55
@mvernimmen prior to thinking about any potential changes to Traefik, I'd still like to understand first why the problem occurs. As I [have explained before](https://github.com/containous/traefik/issues/1989#issuecomment-324191395), the error should only manifest in an in-cluster usage if certain environment variables provided by Kubernetes are not injected for whatever reason. My best guess continues to be that the node wasn't fully ready yet or something along those lines. (FWIW, we restart Traefik multiple times a day sometimes, and I haven't run into the issue myself.) Do you have a chance to investigate to hopefully figure out the root cause?

It should still be possible to detect the scenario described, at least if you're using Prometheus: We expose metrics on the latest configuration update, so you could alert if a configuration update has never happened or there's too much of a divergence between multiple Traefik instances.

I'll reopen for the time being.

**Comment by dtomcej** [comment] 2018-05-07 14:34
I am going to go ahead and close this issue, since it apparently hasn't occurred since.

@mvernimmen If you run into this issue in the future, please let us know, as with the latest release (1.6) we have implemented hundreds of new features, and may have fixed the issue you encountered.

Please open a new ticket if you re-encounter this issue.

Thanks!

**Closed by dtomcej** 2018-05-07 14:34 UTC
Labels: area/provider/k8s, contributor/waiting-for-feedback, kind/bug/possible

**Comment by recet** [comment] 2019-03-29 09:32
Hi,

We are experiencing the same issue with traefik 1.7.8 on gke 1.12.5. We are also running traefik as daemonset (30-65 nodes).

it seems to occur during rapid autoscaling usecases (Nodes with high pressure) - and not on all nodes. Any suggestions on how to mitigate this issue?
