### ISSUE TITLE
Traefik https only 443 not working

### ISSUE THREAD

**Issue by port22** [containous/traefik#5057] opened 2019-07-02 15:49 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you expect to see?

Traefik only binds to the ports it's configured to.

### What did you see instead?

Traefik is configured only with entrypoint https:

When I start traefik, it complains:
```
traefik443.2.buoxzbz26nwx@swarm1b    | time="2019-07-02T15:43:19Z" level=fatal msg="Error preparing server: error opening listener: listen tcp :80: bind: address already in use"
```

That's because there is another webserver running on port 80 on this machine, on purpose.
I only want traefik to listen to https:443 only.

It seems, traefik just assumes it should start-bind on port 80 in any case.
That should not be the case.

Traefik binds on port 80, although that's not configured.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = true
swarmMode = true
```

**Comment by ldez** [comment] 2019-07-02 15:53
hello, could you give you docker-compose file or the way how you launch Traefik?

**Comment by port22** [comment] 2019-07-03 08:30
sure!

```docker service create --name traefik \
  --mount type=bind,source=$PWD/traefik.toml,destination=/etc/traefik/traefik.toml \
  --mount type=bind,source=$PWD/acme.json,destination=/etc/traefik/acme/acme.json \
  --mount type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock \
  --network host \
traefik
```

**Comment by geraldcroes** [comment] 2019-07-03 15:58
Hi! we strongly believe that this is not a bug but probably a problem of your configuration not being taken into account. Could you please follow up on the community forum so we can help you us the best we can.

If you don't mind, I'll close the issue right now, we'll open it back if it ends up being a bug (even though we can't reproduce it yet).

**Closed by geraldcroes** 2019-07-03 15:58 UTC
Labels: contributor/waiting-for-feedback, kind/question
