### ISSUE TITLE
Prometheus metrics counts a client cancel as a 500

### ISSUE THREAD

**Issue by jonaz** [containous/traefik#2932] opened 2018-02-26 06:52 UTC
### Do you want to request a *feature* or report a *bug*?

Bug report

### What did you do?

Start traefik and proxy to a service ansering slowly. 

Example slow service: 
```go
package main
import (
	"net/http"
	"time"
	"github.com/gin-gonic/gin"
	"github.com/koding/multiconfig"
)
type config struct {
	Port  string `default:"8080"`
	Sleep int    `default:"11"`
}
func main() {
	config := config{}
	multiconfig.New().MustLoad(&config)
	r := gin.Default()
	r.GET("/goslow", response(config))
	r.POST("/goslow", response(config))
	r.PUT("/goslow", response(config))
	r.DELETE("/goslow", response(config))
	r.Run(":" + config.Port)
}
func response(c config) gin.HandlerFunc {
	return func(g *gin.Context) {
		time.Sleep(time.Second * time.Duration(c.Sleep))
		g.Status(http.StatusOK)
	}
}
```

Do request from a browser and before the service answers (before 11 sec) press escape or Stop in the browser

### What did you expect to see?

Traefik should not report this as 500 errors. 

### What did you see instead?

Traefik will increae the 500 code counters:
```
traefik_requests_total{code="500",method="GET",service="/goslow"} 1
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.6
Codename:     roquefort
Go version:   go1.9.2
Built:        2018-01-02_12:27:08PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Any configuration should work just fine.

**Comment by mmatur** [comment] 2018-02-26 09:54
Duplicate of #1926

**Closed by mmatur** 2018-02-26 09:54 UTC
Labels: area/middleware/metrics, status/0-needs-triage
