### ISSUE TITLE
Kubernetes traefik:v1.7.12-alpine Basic Auth Secret Not Found

### ISSUE THREAD

**Issue by jralph** [containous/traefik#5069] opened 2019-07-08 15:10 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Run Traefik in Kubernetes and attempted to add basic auth to an ingress.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/auth-type: basic
    traefik.ingress.kubernetes.io/auth-secret: traefik-admin
spec:
  rules:
  - host: traefik.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-web-ui
          servicePort: web
```

### What did you expect to see?

- No errors in the traefik logs.
- Basic auth to be requested on the ingress.

### What did you see instead?

- Errors in the traefik log.
- Ingress was fully unauthenticated.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Docker Image:      traefik:v1.7.12-alpine

Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 35%
      maxUnavailable: 35%
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v1.7.12-alpine
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8080
        args:
        - '--api'
        - '--kubernetes'
        - '--logLevel=INFO'
        - '--defaultentrypoints=http,https'
        - '--entrypoints=Name:https Address::443 TLS'
        - '--entrypoints=Name:http Address::80'
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /health
            port: admin
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 2
          failureThreshold: 3
```

**Traefik Docker Image `traefik:v1.7.11-alpine` works correctly.**

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2019-07-08T13:26:31Z" level=info msg="Traefik version v1.7.12 built on 2019-05-29_07:35:02PM"
time="2019-07-08T13:26:31Z" level=debug msg="Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceTimeOut\":0,\"Debug\":true,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false,\"AccessLogsFile\":\"\",\"AccessLog\":{\"format\":\"common\",\"filters\":{\"retryAttempts\":true}},\"TraefikLogsFile\":\"\",\"TraefikLog\":null,\"Tracing\":null,\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"https\":{\"Address\":\":443\",\"TLS\":{\"MinVersion\":\"\",\"CipherSuites\":null,\"Certificates\":[],\"ClientCAFiles\":null,\"ClientCA\":{\"Files\":null,\"Optional\":false},\"DefaultCertificate\":null,\"SniStrict\":false},\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\",\"https\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"IdleTimeout\":0,\"InsecureSkipVerify\":false,\"RootCAs\":null,\"Retry\":null,\"HealthCheck\":{\"Interval\":30000000000},\"RespondingTimeouts\":null,\"ForwardingTimeouts\":null,\"AllowMinWeightZero\":false,\"KeepTrailingSlash\":false,\"Web\":null,\"Docker\":null,\"File\":null,\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\",\"IngressEndpoint\":null},\"Mesos\":null,\"Eureka\":null,\"ECS\":null,\"Rancher\":null,\"DynamoDB\":null,\"ServiceFabric\":null,\"Rest\":null,\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Debug\":true,\"CurrentConfigurations\":null,\"Statistics\":null},\"Metrics\":{\"Prometheus\":{\"Buckets\":[0.1,0.3,1.2,5],\"EntryPoint\":\"traefik\"},\"Datadog\":null,\"StatsD\":null,\"InfluxDB\":null},\"Ping\":null,\"HostResolver\":null}"
time="2019-07-08T13:26:31Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-07-08T13:26:31Z" level=debug msg="Configured Prometheus metrics"
time="2019-07-08T13:26:32Z" level=info msg="Preparing server https &{Address::443 TLS:0xc0001b87e0 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000817a00} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-07-08T13:26:34Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000817aa0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-07-08T13:26:34Z" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000817ba0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-07-08T13:26:34Z" level=info msg="Starting server on :443"
time="2019-07-08T13:26:34Z" level=info msg="Starting server on :80"
time="2019-07-08T13:26:34Z" level=info msg="Starting server on :8080"
time="2019-07-08T13:26:34Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
time="2019-07-08T13:26:34Z" level=info msg="Starting provider *kubernetes.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\",\"IngressEndpoint\":null}"
time="2019-07-08T13:26:34Z" level=debug msg="Using Ingress label selector: \"\""
time="2019-07-08T13:26:34Z" level=info msg="ingress label selector is: \"\""
time="2019-07-08T13:26:34Z" level=info msg="Creating in-cluster Provider client"
time="2019-07-08T13:26:35Z" level=debug msg="Received Kubernetes event kind *v1.Service"
time="2019-07-08T13:26:35Z" level=error msg="Failed to retrieve auth configuration for ingress kube-system/traefik-web-ui: failed to load auth credentials: secret \"kube-system\"/\"traefik-admin\" not found"
time="2019-07-08T13:26:35Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:35Z" level=error msg="Failed to retrieve auth configuration for ingress kube-system/traefik-web-ui: failed to load auth credentials: secret \"kube-system\"/\"traefik-admin\" not found"
time="2019-07-08T13:26:35Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:35Z" level=debug msg="Received Kubernetes event kind *v1.Secret"
time="2019-07-08T13:26:35Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"traefik.example.com/\":{\"loadBalancer\":{\"method\":\"wrr\"}}}}"
time="2019-07-08T13:26:35Z" level=debug msg="Received Kubernetes event kind *v1.Secret"
time="2019-07-08T13:26:35Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret"
time="2019-07-08T13:26:35Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"traefik.example.com/\":{\"servers\":{\"traefik-ingress-controller-5f4f47ff4b-jdh5m\":{\"url\":\"http://100.108.0.2:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"traefik.example.com/\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"traefik.example.com/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"traefik.example.com\":{\"rule\":\"Host:traefik.example.com\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"auth\":{\"basic\":{},\"headerField\":\"X-WebAuth-User\"}}}}"
time="2019-07-08T13:26:35Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:35Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:36Z" level=info msg="Server configuration reloaded on :443"
time="2019-07-08T13:26:36Z" level=info msg="Server configuration reloaded on :80"
time="2019-07-08T13:26:36Z" level=info msg="Server configuration reloaded on :8080"
time="2019-07-08T13:26:36Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:36Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:37Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:37Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:37Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:37Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:38Z" level=debug msg="Wiring frontend traefik.example.com/ to entryPoint http"
time="2019-07-08T13:26:38Z" level=debug msg="Creating backend traefik.example.com/"
time="2019-07-08T13:26:38Z" level=debug msg="Adding TLSClientHeaders middleware for frontend traefik.example.com/"
time="2019-07-08T13:26:38Z" level=debug msg="Creating load-balancer wrr"
time="2019-07-08T13:26:38Z" level=debug msg="Creating server traefik-ingress-controller-5f4f47ff4b-jdh5m at http://100.108.0.2:8080 with weight 1"
time="2019-07-08T13:26:38Z" level=debug msg="Creating route / PathPrefix:/"
time="2019-07-08T13:26:38Z" level=debug msg="Creating route traefik.example.com Host:traefik.example.com"
time="2019-07-08T13:26:38Z" level=debug msg="Wiring frontend traefik.example.com/ to entryPoint https"
time="2019-07-08T13:26:38Z" level=debug msg="Creating backend traefik.example.com/"
time="2019-07-08T13:26:38Z" level=debug msg="Adding TLSClientHeaders middleware for frontend traefik.example.com/"
time="2019-07-08T13:26:38Z" level=debug msg="Creating load-balancer wrr"
time="2019-07-08T13:26:38Z" level=debug msg="Creating server traefik-ingress-controller-5f4f47ff4b-jdh5m at http://100.108.0.2:8080 with weight 1"
time="2019-07-08T13:26:38Z" level=debug msg="Creating route / PathPrefix:/"
time="2019-07-08T13:26:38Z" level=debug msg="Creating route traefik.example.com Host:traefik.example.com"
time="2019-07-08T13:26:38Z" level=info msg="Server configuration reloaded on :80"
time="2019-07-08T13:26:38Z" level=info msg="Server configuration reloaded on :8080"
time="2019-07-08T13:26:38Z" level=info msg="Server configuration reloaded on :443"
time="2019-07-08T13:26:38Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:38Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:39Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:39Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:39Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:39Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:39Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:39Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"traefik.example.com/\":{\"servers\":{\"traefik-ingress-controller-5f4f47ff4b-fcrlb\":{\"url\":\"http://100.122.0.4:8080\",\"weight\":1},\"traefik-ingress-controller-5f4f47ff4b-jdh5m\":{\"url\":\"http://100.108.0.2:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"traefik.example.com/\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"traefik.example.com/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"traefik.example.com\":{\"rule\":\"Host:traefik.example.com\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"auth\":{\"basic\":{},\"headerField\":\"X-WebAuth-User\"}}}}"
time="2019-07-08T13:26:39Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:39Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:39Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:39Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:39Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:39Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"traefik.example.com/\":{\"servers\":{\"traefik-ingress-controller-5f4f47ff4b-fcrlb\":{\"url\":\"http://100.122.0.4:8080\",\"weight\":1},\"traefik-ingress-controller-5f4f47ff4b-jdh5m\":{\"url\":\"http://100.108.0.2:8080\",\"weight\":1},\"traefik-ingress-controller-5f4f47ff4b-n5q5l\":{\"url\":\"http://100.116.0.4:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"traefik.example.com/\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"traefik.example.com/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"traefik.example.com\":{\"rule\":\"Host:traefik.example.com\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"auth\":{\"basic\":{},\"headerField\":\"X-WebAuth-User\"}}}}"
time="2019-07-08T13:26:39Z" level=debug msg="Wiring frontend traefik.example.com/ to entryPoint http"
time="2019-07-08T13:26:39Z" level=debug msg="Creating backend traefik.example.com/"
time="2019-07-08T13:26:39Z" level=debug msg="Adding TLSClientHeaders middleware for frontend traefik.example.com/"
time="2019-07-08T13:26:39Z" level=debug msg="Creating load-balancer wrr"
time="2019-07-08T13:26:39Z" level=debug msg="Creating server traefik-ingress-controller-5f4f47ff4b-fcrlb at http://100.122.0.4:8080 with weight 1"
time="2019-07-08T13:26:39Z" level=debug msg="Creating server traefik-ingress-controller-5f4f47ff4b-jdh5m at http://100.108.0.2:8080 with weight 1"
time="2019-07-08T13:26:39Z" level=debug msg="Creating route / PathPrefix:/"
time="2019-07-08T13:26:39Z" level=debug msg="Creating route traefik.example.com Host:traefik.example.com"
time="2019-07-08T13:26:39Z" level=debug msg="Wiring frontend traefik.example.com/ to entryPoint https"
time="2019-07-08T13:26:39Z" level=debug msg="Creating backend traefik.example.com/"
time="2019-07-08T13:26:39Z" level=debug msg="Adding TLSClientHeaders middleware for frontend traefik.example.com/"
time="2019-07-08T13:26:39Z" level=debug msg="Creating load-balancer wrr"
time="2019-07-08T13:26:39Z" level=debug msg="Creating server traefik-ingress-controller-5f4f47ff4b-fcrlb at http://100.122.0.4:8080 with weight 1"
time="2019-07-08T13:26:39Z" level=debug msg="Creating server traefik-ingress-controller-5f4f47ff4b-jdh5m at http://100.108.0.2:8080 with weight 1"
time="2019-07-08T13:26:39Z" level=debug msg="Creating route / PathPrefix:/"
time="2019-07-08T13:26:39Z" level=debug msg="Creating route traefik.example.com Host:traefik.example.com"
time="2019-07-08T13:26:39Z" level=info msg="Server configuration reloaded on :80"
time="2019-07-08T13:26:39Z" level=info msg="Server configuration reloaded on :8080"
time="2019-07-08T13:26:39Z" level=info msg="Server configuration reloaded on :443"
time="2019-07-08T13:26:40Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:40Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:41Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:41Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:41Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:41Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:42Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:42Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:43Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:43Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:43Z" level=debug msg="Wiring frontend traefik.example.com/ to entryPoint http"
time="2019-07-08T13:26:43Z" level=debug msg="Creating backend traefik.example.com/"
time="2019-07-08T13:26:43Z" level=debug msg="Adding TLSClientHeaders middleware for frontend traefik.example.com/"
time="2019-07-08T13:26:43Z" level=debug msg="Creating load-balancer wrr"
time="2019-07-08T13:26:43Z" level=debug msg="Creating server traefik-ingress-controller-5f4f47ff4b-fcrlb at http://100.122.0.4:8080 with weight 1"
time="2019-07-08T13:26:43Z" level=debug msg="Creating server traefik-ingress-controller-5f4f47ff4b-jdh5m at http://100.108.0.2:8080 with weight 1"
time="2019-07-08T13:26:43Z" level=debug msg="Creating server traefik-ingress-controller-5f4f47ff4b-n5q5l at http://100.116.0.4:8080 with weight 1"
time="2019-07-08T13:26:43Z" level=debug msg="Creating route traefik.example.com Host:traefik.example.com"
time="2019-07-08T13:26:43Z" level=debug msg="Creating route / PathPrefix:/"
time="2019-07-08T13:26:43Z" level=debug msg="Wiring frontend traefik.example.com/ to entryPoint https"
time="2019-07-08T13:26:43Z" level=debug msg="Creating backend traefik.example.com/"
time="2019-07-08T13:26:43Z" level=debug msg="Adding TLSClientHeaders middleware for frontend traefik.example.com/"
time="2019-07-08T13:26:43Z" level=debug msg="Creating load-balancer wrr"
time="2019-07-08T13:26:43Z" level=debug msg="Creating server traefik-ingress-controller-5f4f47ff4b-fcrlb at http://100.122.0.4:8080 with weight 1"
time="2019-07-08T13:26:43Z" level=debug msg="Creating server traefik-ingress-controller-5f4f47ff4b-jdh5m at http://100.108.0.2:8080 with weight 1"
time="2019-07-08T13:26:43Z" level=debug msg="Creating server traefik-ingress-controller-5f4f47ff4b-n5q5l at http://100.116.0.4:8080 with weight 1"
time="2019-07-08T13:26:43Z" level=debug msg="Creating route traefik.example.com Host:traefik.example.com"
time="2019-07-08T13:26:43Z" level=debug msg="Creating route / PathPrefix:/"
time="2019-07-08T13:26:43Z" level=info msg="Server configuration reloaded on :443"
time="2019-07-08T13:26:43Z" level=info msg="Server configuration reloaded on :80"
time="2019-07-08T13:26:43Z" level=info msg="Server configuration reloaded on :8080"
time="2019-07-08T13:26:43Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:43Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:44Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:44Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
time="2019-07-08T13:26:45Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
```

**Comment by dtomcej** [comment] 2019-07-08 15:22
@jralph Could you please see if you can enable the debug logs, and provide the debug logs for this?

The reason is that ingresses can be loaded before the secrets are loaded, which can lead to an error in the logs, without necessarily meaning the secrets can't be found ( See #3667).

We are interested to see the events loading (which are shown in debug) before the server is reloaded with the new config.

As for the 1.7.11-1.7.12 change, there were no changes made to the kubernetes provider, which would have affected secret loading, so I am unsure if the change in version is related.

Let us know if you can get those debug logs!

**Comment by jralph** [comment] 2019-07-08 15:29
@dtomcej Sure, I've updated the Issue with the debug output now.

**Comment by jralph** [comment] 2019-07-08 15:39
I've just checked out #3667, I think it might be the case. If I try a browser that hasn't previously loaded the page (or curl), v1.7.12 works after everything has loaded and requests the basic auth.

**Comment by traefiker** [comment] 2019-10-07 00:00
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).

**Comment by dduportal** [comment] 2019-10-07 09:07
Re-opening as the bots closed based on the labels that were not up to date.

**Comment by dduportal** [comment] 2019-10-07 15:46
Closing as duplicate of #3667

**Closed by dduportal** 2019-10-07 15:46 UTC
Labels: area/provider/k8s/ingress, resolution/duplicate
