### ISSUE TITLE
[Kubernetes] ingress path priority in relation with length of path

### ISSUE THREAD

**Issue by aranair** [containous/traefik#4594] opened 2019-03-14 13:10 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Created a kubernetes ingress, single-hostname, multi-paths (nested tho), with a priority at the ingress level via `traefik.ingress.kubernetes.io/priority: "300"` - 

```
...
metadata:
  annotations:
     traefik.ingress.kubernetes.io/priority: "300"
...
spec:
  rules:
  - host: xxx
    http:
      paths:
      - backend:
          serviceName: models-5184edfb3
          servicePort: 8081
        path: /api/v2/ws/models
      - backend:
          serviceName: apigateway-5184edfb3
          servicePort: 80
        path: /api/v2/
```

### What did you expect to see?
Traffic should route based on the paths. 

E.g. traffic at `xxx/api/v2/ws/models`, the more specified path should go to the first service and `xxx/api/v2/` should go to the 2nd service

### What did you see instead?
The more specified path `/api/v2/ws/models` is getting matched to the more general path. If I remove the other path from this ingress, or create another ingress with a higher priority (e.g. 400), everything routes correctly. 

I also did not see this consistently. There were other similar ingresses behaving in the correct way.

The path length was previously used to calculate the priority, but that's no longer the case. So the priority of both the paths above are the same (e.g. the ingress priority) and depending on the init sequence, could different frontends be served?

Path length priority was [added here previously](https://github.com/containous/traefik/pull/588/files)  but the "priority" in that initialization is [now replaced by the ingress-level priority](https://github.com/containous/traefik/blob/v1.7/provider/kubernetes/kubernetes.go#L228)? 

Given that the priority of the route is basically taken as the [frontend's priority if it exists](https://github.com/containous/traefik/blob/v1.7/server/server_configuration.go#L294-L298), Should the priority for each path be calculated based on (ingress-level priority + path length), instead of just the priority value of the ingress itself? 

E.g. either modified at the provider level, or `serverRoute.Route.Priority(frontend.Priority + priority)` at the serverRoute level.

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.7.7
(installed with stable helm chart 1.60.0)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
kubernetes  /  ingress

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

No debug info but from the UI it seems like the appropriate backend/frontends are generated:

`300-xxx/api/v2/`
`300-xxx/api/v2/ws/models`

I'm not sure how/if that is sorted further downstream though.

**Comment by aranair** [comment] 2019-03-14 15:28
Reading up further, perhaps it may have been intended? Although, I think it's not immediately intuitive, to have rules in multi-path-ingresses to all end up having the same priority, since that would render routing for nested paths e.g. `/foo` and `/foo/bar` kind of arbitrary.

**Comment by dtomcej** [comment] 2019-04-15 14:56
@aranair, you are correct.

By default, Traefik builds internal priorities based on the length of the path that you specify.

However, there are cases where you want to override the priority to ensure that some routes always get matched first (such as the case with `PathPrefix: /` rules, which are greedy).

When you specify a priority in an ingress object via the annotations, they are applied to _all_ paths in that ingress object, since there is no way for us to tell if and/or which paths they should apply to.

The issue that you are encountering is expected behavior, even though it is not ideal. The advice would be to separate the overlapping paths into 2 separate ingress objects so that you can override the priority for both.

Since this is intended behavior, I will be closing this issue. Feel free to visit us on slack if you have any further questions or concerns: traefik.slack.com

Thanks!

**Closed by dtomcej** 2019-04-15 14:56 UTC
Labels: area/provider/k8s/ingress, kind/bug/possible, priority/P2

**Comment by millisami** [comment] 2019-08-06 05:34
According to the doc https://docs.traefik.io/user-guide/kubernetes/, specifying 
`traefik.frontend.priority: "1"` did the trick for my wildcard and specific sub-domain issue.
