### ISSUE TITLE
Add wrong Content-Type

### ISSUE THREAD

**Issue by thanhnl** [containous/traefik#2826] opened 2018-02-08 08:01 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I installed traefik in kubernetes. 

### What did you expect to see?

Correct `Content-Type` in response.

### What did you see instead?

Traefik added wrong `Content-Type: application/x-gzip` with `Accept-Encoding: gzip, deflate`. That made browser save content as `file.gz`

With `traefik`, empty "Accept-Encoding": 

```console
$ curl -vvv -s "http://example.com" -H "Accept-Encoding:"
*   Trying 1.2.3.4 ...
* TCP_NODELAY set                       
* Connected to example.com (1.2.3.4) port 80 (#0)
> GET / HTTP/1.1  
> Host: example.com
> User-Agent: curl/7.56.0                                                                                       
> Accept: */*                                                                           
>                                                                                                              
< HTTP/1.1 200 OK                                                                                               
< Cache-Control: max-age=0, private, must-revalidate
< Date: Thu, 08 Feb 2018 07:23:40 GMT
< Etag: W/"86fae97bd4622ab0d54e82923d63976a"
< Server: nginx/1.10.3 + Phusion Passenger 5.1.4        
< Set-Cookie: _st_session=RjMv; path=/; expires=Thu, 08 Mar 2018 07:23:40 -0000; HttpOnly
< Status: 200 OK
< Vary: Accept-Encoding
< X-Powered-By: Phusion Passenger 5.1.4
< X-Request-Id: ca09ab61-6f5f-417e-8a31-3f64473b929b
< X-Runtime: 0.025792
< Content-Length: 311
< Content-Type: text/html; charset=utf-8
<* Connection #0 to host example.com left intact
<script type='text/javascript' charset='utf-8'>top.location.href =....</script>
```

With `traefik`, `Accept-Encoding: gzip, deflate`:

```console
$ curl -vvv -s "http://example.com/" -H "Accept-Encoding: gzip, deflate" --compressed                                                                                                           
*   Trying 1.2.3.4...
* TCP_NODELAY set                                                                                               
* Connected to example.com (1.2.3.4) port 80 (#0)                                                        
> GET / HTTP/1.1                                                                  
> Host: example.com                                                                                            
> User-Agent: curl/7.56.0                                                                                       
> Accept: */*                                                                                                   
> Accept-Encoding: gzip, deflate                                                                                
>                                                                                                               
< HTTP/1.1 200 OK                                                                                               
< Cache-Control: max-age=0, private, must-revalidate                                                            
< Content-Encoding: gzip                                                                                        
< Date: Thu, 08 Feb 2018 07:22:16 GMT                                                                           
< Etag: W/"c5cdfad1a54c7c05b5f2aff5cd07a1cf"                                                                    
< Server: nginx/1.10.3 + Phusion Passenger 5.1.4
< Set-Cookie: _st_session=SGh... ; path=/; expires=Thu, 08 Mar 2018 07:22:16 -0000; HttpOnly
< Status: 200 OK
< Vary: Accept-Encoding
< X-Powered-By: Phusion Passenger 5.1.4
< X-Request-Id: 6f6ada1f-65cc-4803-a18c-543f20a178bd
< X-Runtime: 0.026733
< Content-Length: 258
< Content-Type: application/x-gzip
<
* Connection #0 to host example.com left intact
<script type='text/javascript' charset='utf-8'>top.location.href = .... </script>
```

Without `traefik`, empty `Accept-Encoding`

```console
$ curl -vvv -Ss "http://example.com/" -H "Accept-Encoding:"
*   Trying 1.2.3.4...
* TCP_NODELAY set
* Connected to example.com (1.2.3.4) port 80 (#0)
> GET / HTTP/1.1
> Host: example.com
> User-Agent: curl/7.56.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 311
< Connection: keep-alive
< Status: 200 OK
< Cache-Control: max-age=0, private, must-revalidate
< Vary: Accept-Encoding
< X-Request-Id: 6525c4a6-e604-48ff-8e93-44ce26e115a7
< ETag: W/"f77fd0837de44bd985eb6fdc91d61683"
< X-Runtime: 0.041206
< Date: Thu, 08 Feb 2018 07:37:58 GMT
< Set-Cookie: _st_session=Wnk0...; path=/; expires=Thu, 08 Mar 2018 07:37:58 -0000; HttpOnly
< X-Powered-By: Phusion Passenger 5.1.4
< Server: nginx/1.10.3 + Phusion Passenger 5.1.4
<
* Connection #0 to host example.com left intact
<script type='text/javascript' charset='utf-8'>top.location.href = .... </script>
```

Without `traefik`, with `Accept-Encoding: gzip, deflate`

```console
$ curl -vvv -Ss "http://example.com/" -H "Accept-Encoding: gzip, deflate" --compressed
*   Trying 1.2.3.4...
* TCP_NODELAY set
* Connected to example.com (1.2.3.4) port 80 (#0)
> GET / HTTP/1.1
> Host: example.com
> User-Agent: curl/7.56.0
> Accept: */*
> Accept-Encoding: gzip, deflate
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Connection: keep-alive
< Status: 200 OK
< Cache-Control: max-age=0, private, must-revalidate
< Vary: Accept-Encoding
< Content-Encoding: gzip
< X-Request-Id: 725a2814-63b7-4fe2-86a1-952752005c99
< ETag: W/"a75f3fea5014cd834eec348db59ed841"
< X-Runtime: 0.027118
< Date: Thu, 08 Feb 2018 07:41:47 GMT
< Set-Cookie: _st_session=U3h...; path=/; expires=Thu, 08 Mar 2018 07:41:47 -0000; HttpOnly
< X-Powered-By: Phusion Passenger 5.1.4
< Server: nginx/1.10.3 + Phusion Passenger 5.1.4
<
* Connection #0 to host example.com left intact
<script type='text/javascript' charset='utf-8'>top.location.href = .... </script>
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
    Container ID:  docker://109c0c9023d54f1648538ed613e42a799ddd987fab6b6c052bf25274f0f6826c
    Image:         traefik:1.5.1
    Image ID:      docker-pullable://traefik@sha256:a60f36880bbe8049cffb05f2f5d00d3068a327dfaebf85dab025c1d23b91
f5bb
```

```
Version:      v1.5.1
Codename:     cancoillotte
Go version:   go1.9.3
Built:        2018-01-29_02:14:02PM
OS/Arch:      linux/amd64
```

**Comment by Juliens** [comment] 2018-02-08 09:49
Duplicate of #518

**Closed by Juliens** 2018-02-08 09:49 UTC
Labels: status/0-needs-triage
