### ISSUE TITLE
Generic TCP proxying support?

### ISSUE THREAD

**Issue by christophetd** [containous/traefik#2595] opened 2017-12-20 09:25 UTC
Already tracked by several issues (#10, #608, #1409, #1376), but all of them have been closed / locked and I didn't see any answer from the maintainers.

Are there any plans to support generic TCP proxying in Traefik? I believe it would be super useful to get insights and statistics on connections to services such as MySQL, Kafka, RabbitMQ, etc.

**Comment by ldez** [comment] 2017-12-20 09:28
Duplicate of #10

**Closed by ldez** 2017-12-20 09:28 UTC

**Comment by christophetd** [comment] 2017-12-20 09:33
That's indeed a duplicate of #10. I wanted to write there, but the conversation is locked and restricted to project maintainers. 

The goal of this issue was to discuss whether a generic TCP proxying feature was planned for the future - which other issues do not have information about.

Thanks.

**Comment by ldez** [comment] 2017-12-20 10:05
Yes it's planned for the future.
