### ISSUE TITLE
Docker Compose TLS Configuration

### ISSUE THREAD

**Issue by kdankert** [containous/traefik#6100] opened 2019-12-28 11:29 UTC
### Do you want to request a *feature* or report a *bug*?

feature

### What feature would you like to see?

Are there any plans to define certificates outside of the file provider for example in the docker compose file as labels for the traefik instance. Why is this not possible so far? Are there any security concerns? Why shouldn't somebody be able to set the default certificate used as fallback from traefik or add own certificates instead of using letsencrypt.

I would really like to see the feature of being able to configure tls certificates inside the docker-compose.yml file and i think this would be a feature helpful for a lot of people using traefik.

**Comment by ldez** [comment] 2019-12-28 13:56
duplicate of #5507

**Closed by ldez** 2019-12-28 13:56 UTC
Labels: resolution/duplicate
