### ISSUE TITLE
Output Lets encrypt certificate in PEM format

### ISSUE THREAD

**Issue by pre-martin** [containous/traefik#4916] opened 2019-05-29 07:09 UTC
### Do you want to request a *feature* or report a *bug*?

Feature: Output Lets Encrypt certificate in PEM format (or update documentation how the certificate and key can be converted into PEM format).

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

I configured the acme provider in order to obtain Lets Encrypt certificates. The provider stores the private key and certificate in an unknown/not documented format in the JSON file.

As Traefik is running in front of a mail server, I have to extract the certificate and install it into the mail server itself, so that also IMAPS is using this certificate. The mail server does not understand the certificate format of Traefik, but only PEM encoded certificates.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

**Comment by ldez** [comment] 2019-05-29 07:48
Duplicate of #2418

Use https://github.com/ldez/traefik-certs-dumper/

**Comment by pre-martin** [comment] 2019-05-29 08:00
Thank you, this tool looks good. Should it be mentioned in https://docs.traefik.io/configuration/acme/ ?

**Closed** 2019-05-29 16:10 UTC
Labels: resolution/duplicate
