### ISSUE TITLE
Ability to define a route for both HTTP and HTTPS in a single IngressRoute CRD object

### ISSUE THREAD

**Issue by dbsanfte** [containous/traefik#6404] opened 2020-02-28 13:35 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Referencing this issue raised in the community forums:

https://community.containo.us/t/two-routes-for-http-and-https-in-one-ingressroute/4264/4

Having to define two IngressRoute objects like this is silly and repeating oneself. It should be enough to define a single IngressRoute object, open to both `web` and `websecure` entrypoints, and  Traefik should just 'figure it out'.

Secondly, it should not be obligatory to set a TLS secret on the IngressRoute. If some certificates are defined in the Traefik defaults, say via the `tls.certificates` field in `traefik.yaml`, Traefik should automatically select the correct certificate to service incoming requests based on the user's requesting `Host`.

This is all desirable because it would keep us from having to define multiple TLS secrets in multiple namespaces for Traefik, and run a single Traefik instance with its certs defined in one place.

Perhaps this is already doable somehow, but the documentation for Kubernetes CRD is so scattered and incomplete at the moment that I can't tell whether or not this use case, which to my mind seems desirable, is currently possible.

**Comment by ldez** [comment] 2020-02-28 13:39
Duplicate of #4863
Duplicate of #5468
Duplicate of #5630

**Closed by ldez** 2020-02-28 13:39 UTC
Labels: status/0-needs-triage
