### ISSUE TITLE
Traefik camel cases response headers

### ISSUE THREAD

**Issue by davidgenn** [containous/traefik#1969] opened 2017-08-18 07:31 UTC
### Do you want to request a *feature* or report a *bug*?

Bug
### What did you do?
Traefik in consul-catalogue mode.

### What did you expect to see?
Traefik returns backend response headers un-altered.

### What did you see instead?
Headers are camel cased eg:

X-MY-APPLICATION-HEADER: 12345

is returned as:

X-My-Application-Header: 12345

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.3.5

### TOML
```toml
[consulCatalog]

endpoint = "127.0.0.1:8500"
domain = "service.consul"

frontEndRule = "Host:{{ServiceName}}.{{Domain}},PathPrefixStrip:/{{ServiceName}}"
prefix = "traefik"
```

**Comment by ldez** [comment] 2017-08-18 08:48
RFC 7230 (and also 7540) states:
> "Each header field consists of a case-insensitive field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace."

Golang http server rewrites all headers in a canonical way and your backends shouldn't rely on case sensitivity golang/go#5022.

Duplicate of #1756 #466

**Closed by ldez** 2017-08-18 08:48 UTC
Labels: kind/question
