### ISSUE TITLE
Support custom Headers in Ipwhitelist

### ISSUE THREAD

**Issue by dragon2611** [containous/traefik#7211] opened 2020-08-24 22:30 UTC
Please consider supporting custom headers in the IPwhitelisting component e.g CF-Connecting-IP.

Also I'd like to make the headers optional, (I.e if the header is not present fallback to checking the originating IP of the Request)

**Comment by SantoDE** [comment] 2020-08-25 14:58
Duplicate of #5713

**Closed by SantoDE** 2020-08-25 14:58 UTC
Labels: status/0-needs-triage
