### ISSUE TITLE
Private and conflictless routers and middlewares

### ISSUE THREAD

**Issue by athoune** [containous/traefik#5847] opened 2019-11-15 21:07 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

#### Unique name

For now, you have to name most of your labels, without messing with another services.

Something like :

```
traefik.http.routers.my-container.rule=Host(`mydomain.com`)
```
If there is no coordination nor courtesy, with lots of services behind one træfik, conflict will happened.

Sharing stuff is good, but explicitly.

A simple answer can be a magic replacement character, like `$`. The label should be 
```
traefik.http.router.$.rule=Host(`mydomain.com`)
```

The provider implementation, juste after reading the label replaces `$` with the service name, which is already asserted as unique.

If you need multiple setups, like middlewares, you can use `$` as a prefix :
```
traefik.http.middlewares.$-auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0
```
The magic `$` must be handled in middlewares list too.

#### Private name

A label named with a magic `$` should be private. If my service name is `foo` and I named a middleware `$-auth`, others services can't name a service `foo-auth`. It must raise an error.

**Comment by traefiker** [comment] 2019-11-15 23:07
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by athoune** [comment] 2019-11-20 11:13
bunny saved.

**Comment by dduportal** [comment] 2019-11-20 16:20
Closing as duplicate of #5134.

Can you add your proposal with the `$` as a comment in #5134 please, so the discussion can happen with everyone?

Thanks!

**Closed by dduportal** 2019-11-20 16:20 UTC
Labels: contributor/need-more-information, status/0-needs-triage
