### ISSUE TITLE
Infinite redirect when access to dashboard

### ISSUE THREAD

**Issue by tonychee7000** [containous/traefik#6082] opened 2019-12-23 09:29 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

When I access to `https://traefik.example.com` 

### What did you expect to see?

it should redirect to `/dashboard`

### What did you see instead?

it should redirect to `/dashboard/`, and redirected again and again.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```yaml
# In short, I am using v2.1.1
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2019-12-19T12:19:19Z"
  generation: 7
  labels:
    app: traefik
    chart: traefik-1.77.1
    heritage: Tiller
    release: traefik
  name: traefik
  namespace: kube-system
  resourceVersion: "222592"
  selfLink: /apis/apps/v1/namespaces/kube-system/deployments/traefik
  uid: ddf330e6-2529-4246-ba44-09e60b75d900
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: traefik
      release: traefik
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 5072e2b9911158c04b7b76568f0c4f477d59793d52d6a44d35a4910b5e15527c
      creationTimestamp: null
      labels:
        app: traefik
        chart: traefik-1.77.1
        heritage: Tiller
        release: traefik
    spec:
      containers:
        - args:
            - --configfile=/config/traefik.toml
          env:
            - name: CLOUDFLARE_EMAIL
              valueFrom:
                secretKeyRef:
                  key: CLOUDFLARE_EMAIL
                  name: traefik-dnsprovider-config
            - name: CLOUDFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: CLOUDFLARE_API_KEY
                  name: traefik-dnsprovider-config
          image: traefik:2.1.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          name: traefik
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 8880
              name: httpn
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 8080
              name: dash
              protocol: TCP
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /ping
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /acme
              name: acme
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: traefik
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      volumes:
        - configMap:
            defaultMode: 420
            name: traefik
          name: config
        - hostPath:
            path: /app/tls
            type: Directory
          name: acme
```

There is a bad redirect rule, `https://traefik.example.com/` and `https://traefik.example.com/dashboard/` have same suffix with `/`

![image](https://user-images.githubusercontent.com/2174238/71349228-7a503900-25a9-11ea-8571-b123d8ef3626.png)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
Not important 
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
Not important
```

**Comment by ldez** [comment] 2019-12-23 09:40
Duplicate of #6073, #6041

**Closed by ldez** 2019-12-23 09:40 UTC
Labels: status/0-needs-triage
