### ISSUE TITLE
Redirecting from http -> https causes the HTTP verb to change to GET

### ISSUE THREAD

**Issue by davidwneary** [containous/traefik#1819] opened 2017-07-03 18:42 UTC
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

I implemented a redirect from `http` to `https`.
Then I tried POSTing to an endpoint in a flask app that sits behind traefik using both `http` and `https` prefixes. The POST to `https` was successful but the POST to `http` return `Method Not Allowed` because by the time it reached my flask container, the request had become a GET request

### What did you expect to see?

When I POST to `https://api.mysite.com` it is successful.
When I POST to `http://api.mysite.com` it redirects to `https` and is successful, returning the same result as the `https` call.

### What did you see instead?
When I POST to `https://api.mysite.com` it is successful.
When I POST to `http://api.mysite.com` the request received by the flask app is a GET request.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.2
Codename:     raclette
Go version:   go1.8.3
Built:        2017-06-29_04:52:35PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    regex = "^http://(.*)"
    replacement = "https://$1"
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/ssl/traefik.crt"
      keyFile = "/etc/traefik/ssl/traefik.key"
```

I build traefik using a docker compose file:
```
version: '3.2'
services:
  traefik:
    image: my-traefik-image:latest
    command: --configFile=/etc/traefik/traefik.toml --docker  --docker.swarmmode  --docker.domain=mysite.com  --docker.watch  --web
    volumes:
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
    networks:
      - traefik-net
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    logging:
      driver: json-file
    deploy:
      placement:
        constraints: [node.role == manager]
      
networks:
  traefik-net:
    external: true
```

and a Dockerfile:

```
FROM traefik
COPY . /etc/traefik 
```

And I have a flask app container started with the following labels:
```
labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:api.mysite.com"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)
Debug output from request is:
```
traefik_traefik.1.x4avy78pi5q1@swarm-manager000000    | time="2017-07-03T18:01:42Z" level=debug msg="Round trip: http://10.0.0.6:80, code: 405, duration: 3.04713ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:api.mysite.com"
```

Also, debug output contains this, repeated every 15 secs or so:
```
traefik_traefik.1.x4avy78pi5q1@swarm-manager000000    | time="2017-07-03T18:01:50Z" level=debug msg="Filtering container without port and no traefik.port label bbe_celery.1"
traefik_traefik.1.x4avy78pi5q1@swarm-manager000000    | time="2017-07-03T18:01:50Z" level=debug msg="Filtering container without port and no traefik.port label traefik_traefik.1"
traefik_traefik.1.x4avy78pi5q1@swarm-manager000000    | time="2017-07-03T18:01:50Z" level=debug msg="Validation of load balancer method for backend backend-bbe-web failed: invalid load-balancing method ''. Using default method wrr."
traefik_traefik.1.x4avy78pi5q1@swarm-manager000000    | time="2017-07-03T18:01:50Z" level=debug msg="Configuration received from provider docker: {"backends":{"backend-bbe-web":{"servers":{"server-bbe_web-1":{"url":"http://10.0.0.6:80","weight":0}},"loadBalancer":{"method":"wrr"}}},"frontends":{"frontend-Host-api-mysite-com":{"entryPoints":["http","https"],"backend":"backend-bbe-web","routes":{"route-frontend-Host-api-mysite-com":{"rule":"Host:api.mysite.com"}},"passHostHeader":true,"priority":0,"basicAuth":[]}}}"
traefik_traefik.1.x4avy78pi5q1@swarm-manager000000    | time="2017-07-03T18:01:50Z" level=info msg="Skipping same configuration for provider docker"
```

I'm new to traefik so my apologies if this is due to my implementation.

Cheers
Dave

**Comment by dtomcej** [comment] 2017-07-04 18:45
Hey @davidwneary when you do a `curl -v -L -X POST http://api.mysite.com` does it work properly?

**Comment by davidwneary** [comment] 2017-07-04 20:31
Hi @dtomcej,

That is better. The request is a 'POST' when it reaches my flask app with that command. I get a 'Bad Request' response but I get the same when pointing at the `https` endpoint so this is probably due to my poor curl skills.

What's the cause of the issue then?

Thanks

**Comment by dtomcej** [comment] 2017-07-04 20:46
When you have a redirect (http -> https), the response is returned to the client as a 301/302. What your client does with that is up to it.

`curl -L` follows these links, and retries the same command to the new location.

**Comment by davidwneary** [comment] 2017-07-05 11:28
Ah I see, I get it now. The issue seems to be that the response gives a `302` and there is a [discrepancy between how different clients respond to this](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.3). (I'm using Postman which has [an issue on github related to this](https://github.com/postmanlabs/postman-app-support/issues/2604).

It seems a better response code would be 301?

Which it appears there is already an issue for: #671 .

You said above that the response could be either 301 or 302, what determines this at the moment?

**Comment by emilevauge** [comment] 2017-07-05 19:16
Closing this one then, duplicate of #671

**Closed by emilevauge** 2017-07-05 19:16 UTC
Labels: area/rules, kind/bug/possible

**Comment by pciavald** [comment] 2019-07-31 11:06
Hi there, i'm commenting on this closed issue as i'm not actually sure it was resolved by the answer provided. I've had the same problem, here's the context:

- nodejs express server uses package `request` and `request-promise-native` WITH parameter `followAllRedirects: true`
- the express app sends a `HTTP POST` request to our gitlab's URL
- traefik handles the request and redirects `HTTP POST` to `HTTPS GET`

In this example, i think the express server and request package follow the redirect correctly, but instead of POSTing my request (which is a commit to gitlab), gitlab sees the request as GET and returns a list of commits.

I've changed my logic to use HTTPS instead of HTTP but that's not consistent with the rest of my logic because all other URLS are HTTP, made to be redirected to HTTPS only of they go through traefik, as we also sometimes send direct requests between local containers using HTTP.

**Comment by dduportal** [comment] 2019-07-31 15:24
Hi @pciavald , would you mind switching to our [Community Forum](http://community.containo.us) for continuing the discussion, as closed issues are not the best location for that?

BtW, Traefik only answers with 301 and the header `Location`, so the behavior you meet depends on the HTTP client, not on Traefik. Reference: <https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.2>.
