### ISSUE TITLE
forwardAuth: add service name to headers in auth service

### ISSUE THREAD

**Issue by sspilleman** [containous/traefik#6679] opened 2020-04-14 20:39 UTC
Hi,

Im using traefik behind a internet router with port forwarding (80/443). All my endpoints are only publicly accessible, so request from the internal network are also via external. I'm using docker-compose, so no k8s. I've implemented forwardAuth. It's "all" working honky-dory...... except:

I'm trying to implement conditional access based on router/service. So user A has access, but only to service "B". Hence the auth container need to know to which router/service the request is for.
All request (inside auth container) have the following header:

'x-forwarded-for': 'a.b.c.d'

Which (obviously) is my public IP address in case request are coming from the internal network as all my services are exposed publicly, eg. blog.spilleman.nl

The only way I can make it work is to create a custom header in my docker compose labels (for each application), explicitly setting it so I can access it in my auth container (the one called by the forwardAuth logic). I now do it via a custom header, per service like 'x-application-url': 'https://blog.spilleman.nl'

So by default, the request contains NO information that the user actually requested "blog.spilleman.nl"

How can I change this so the auth container DOES indeed know which service the user is trying to access (without custom headers)..... or am I doning something wrong?

Solution I can think of is that traefik (always) sets the service name in a header so I don't have to do it manually. What are your ideas?

Thanks!

Sander Spilleman

**Comment by ldez** [comment] 2020-04-14 22:06
duplicate of #3919

Note: please follow the issue template.

**Closed by ldez** 2020-04-14 22:06 UTC
Labels: resolution/duplicate
