### ISSUE TITLE
Fallback to another backend

### ISSUE THREAD

**Issue by 0xbaadf00d** [containous/traefik#2136] opened 2017-09-18 16:06 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Update a docker swarm service (with scale >= 2) via the command `docker service update --image=xxx yyy`

### What did you expect to see?

Traefik have to detect a lost backend or to switch to another available backend if the current don't respond within 5 seconds (by exampel) or if Traefik can't open connection on it.

### What did you see instead?

Nothing, browser (or curl) stay stuck on "waiting response" and Traefik never try to use another available backend, even when the `docker service update` command is finished...

Currently, with a scale = 2: 1 request / 2 stay stuck cause Traefik can't join available backends, traefik continue to trying to connect to a dead backend

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik 1.4RC1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
###############################################################################
## Entry points
# ~~~~~
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [[entryPoints.https.tls.certificates]]
    CertFile = "/etc/ssl/xxxx.io.crt"
    KeyFile = "/etc/ssl/xxxx.io.key"
  [[entryPoints.https.tls.certificates]]
    CertFile = "/etc/ssl/yyyy.ski.crt"
    KeyFile = "/etc/ssl/yyyy.ski.key"



###############################################################################
## Web administration port
# ~~~~~
[web]

# Web administration port
address = ":8080"

# Set REST API to read-only mode
ReadOnly = true

# Authentication
# https://websistent.com/tools/htdigest-generator-tool/
[web.auth.digest]
users = [
  "xxxx:traefik:xxxxx"
]




###############################################################################
## Docker configuration backend
# ~~~~~
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
endpoint = "unix:///var/run/docker.sock"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
domain = "xxxx.io"

# Enable watch docker changes
watch = true

# Expose containers by default in traefik
# If set to false, containers that don't have `traefik.enable=true` will be ignored
exposedbydefault = false

# Use Swarm Mode services as data provider
swarmmode = true




###############################################################################
## Custom health check options
# ~~~~~
[healthcheck]

# Set the default health check interval. Will only be effective if health check
# paths are defined. Given provider-specific support, the value may be
# overridden on a per-backend basis.
# Can be provided in a format supported by [time.ParseDuration](https://golang.org/pkg/time/#ParseDuration) or as raw
# values (digits). If no units are provided, the value is parsed assuming
# seconds
interval = "15s"




###############################################################################
## Access log
# ~~~~~
[accessLog]
```

**Comment by bitsofinfo** [comment] 2017-12-05 21:57
experiencing this as well, after `docker service [servicename] scale=N` swarm is spinning up new containers, traefik appears to start sending traffic to those new containers in the service, despite them not being fully up an able to actually respond.

**Comment by nmengin** [comment] 2017-12-06 08:07
Hello @0xbaadf00d, your problem seems to be related to #2459.

Apparently there were problems when Træfik had to detect containers states.

This problem was fixed by #2478 and will be available in Træfik v1.5.0-rc2.

Can you test with this new version when it will be available and give us a feedback?

**Comment by bitsofinfo** [comment] 2017-12-06 14:47
Will do, for anyone else experiencing this, enabling `--retry` on traefik seems to mitigate this issue

**Comment by mmatur** [comment] 2017-12-08 07:02
@bitsofinfo new Træfik v1.4.5 is available. Could you please test with this version?

**Comment by marco-jantke** [comment] 2018-01-27 16:32
Any news?

**Comment by u007** [comment] 2018-02-21 11:25
tested with health check and turn out, due to stickiness, it will attempt to always goes to the same backend even if the highest priority backend is up. i guess this is working as intended. ive even tried to down the backup instance, and turn out it shows bad gateway even thou the primary backend is up.
after several refresh, finally it switches back to the primary backend.

but this means there shall be a need to add additional option called "backup" and will only works when all other backend fails. and it needs to auto switch back to last sticky backend if available online, or otherwise to any other backend if available.

does this make sense? :)

**Comment by traefiker** [comment] 2018-05-23 00:00
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Closed by traefiker** 2018-05-23 00:00 UTC
Labels: area/healthcheck, area/provider/docker/swarm, contributor/waiting-for-feedback, kind/bug/possible

**Comment by yangm97** [comment] 2018-08-14 00:51
Ping?
