### ISSUE TITLE
Send traefik access log to fluentd

### ISSUE THREAD

**Issue by frenchviking** [containous/traefik#3021] opened 2018-03-15 12:04 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?
Configured Traefik to display access log, json format. Since I want my logs to end up in Elasticsearch, I had to configure the access log file to /dev/stdout.

### What did you expect to see?

No impact on performance.

### What did you see instead?

My websites TTFB went up to +300%.

![worldping-endpoint-web](https://user-images.githubusercontent.com/28394877/37462037-d27eff1a-2850-11e8-8c10-579e8d4cd465.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.5.3
```

Would it be possible to send access logs to fluentd ?

**Comment by Juliens** [comment] 2018-03-16 10:15
Thanks for your interest in Træfik.

I will close this issue because I think this a duplicate of #2151.

Feel free to reopen if needed.

**Closed by Juliens** 2018-03-16 10:15 UTC
Labels: area/logs, status/0-needs-triage
