### ISSUE TITLE
Content rewrite middleware

### ISSUE THREAD

**Issue by asida** [containous/traefik#6420] opened 2020-03-04 03:51 UTC
Feature

### What did you expect to see?
middleware with 4 parameters:
ContentType - value for content-type header that must match to trigger this middleware (text/html default)
ReplaceRule - array with pair of string values [regexMatch, regexReplace]
Repeat - bool, determines whether search for first match only or continue till the end of content
PreserveLastMod - bool, when last-modified header is present in response it will either retain original header value or replace it with current timestamp

How ot works:
When request returns content, middleware will look for content-type header, if match, it will apply rewrite to content and sent modified content as response, instead of original content.
There can be more than one [regexMatch, regexReplace] pair in configuration as it may replace various html content (eg. Page title, absolute urls,...) in one step
Regex match can be optimized to url string, as it will replace absolute url's with entrypoint url mainly.

**Comment by ldez** [comment] 2020-03-04 17:20
Duplicate of #30

**Closed by ldez** 2020-03-04 17:20 UTC
Labels: resolution/duplicate

**Comment by asida** [comment] 2020-03-07 12:46
readed #30 and I don understand what is duplicate about my feature request there ??
I don't agree w/ #30 duplicate mark

Every "true" reverse proxy must support content rewrite, at least to be able rewrite WSI service addresses in oldschool backend WSDL manifests (still very common with corporates) and also replace URLs in badly coded blackboxed html apps. This is lifebuoy feature in legacy environments !!

NGINX has nice content rewrite, ORCL ESB has this feature, so why traefix not ??
