### ISSUE TITLE
Log output is not consistent

### ISSUE THREAD

**Issue by 0xbaadf00d** [containous/traefik#2096] opened 2017-09-09 14:49 UTC
### Do you want to request a *feature* or report a *bug*?

Report a bug

### What did you do?

Enabling stdout requests log

### What did you expect to see?

Expect all string format flags interpreted, or in case of nil value, "-" (dash character)

### What did you see instead?

Get `%!d(<nil>)` rather than "-" or the right decimal value.

```
75.110.84.141  - - [08/Sep/2017:13:07:48 +0000] "HEAD /phpmyadmin2018/ HTTP/1.1" %!d(<nil>) %!d(<nil>) - "Mozilla/5.0 Jorgee" 1520 - - 0ms
60.191.38.77   - - [07/Sep/2017:21:52:32 +0000] "GET / HTTP/1.1" %!d(<nil>) %!d(<nil>) - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0" 1187 - - 0ms
118.193.31.222 - - [07/Sep/2017:19:47:53 +0000] "GET /version HTTP/1.1" %!d(<nil>) %!d(<nil>) - - 1185 - - 0ms
90.126.188.181 - - [08/Sep/2017:13:34:24 +0000] "GET /favicon.ico HTTP/2.0" 200 649 "https://whoami.domain.io/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.71 Safari/537.36 OPR/48.0.2685.16 (Edition beta)" 1542 "Host-whoami-domain-io" "http://10.0.0.7:80" 1ms
90.126.188.181 - - [08/Sep/2017:13:47:55 +0000] "GET / HTTP/2.0" 200 658 - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.71 Safari/537.36 OPR/48.0.2685.16 (Edition beta)" 1568 "Host-whoami-domain-io" "http://10.0.0.5:80" 1ms
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.4.0-rc1
```

**Comment by ldez** [comment] 2017-09-09 15:08
Duplicate of #2055

**Closed by ldez** 2017-09-09 15:08 UTC
