### ISSUE TITLE
Traefik bad perf for routing big data files

### ISSUE THREAD

**Issue by WTFKr0** [containous/traefik#1064] opened 2017-01-24 17:14 UTC
### What version of Traefik are you using (`traefik version`)?
Version: v1.1.2
Codename: camembert
Go version: go1.7.4
Built: 2016-12-15_10:21:15AM
OS/Arch: linux/amd64

### What is your environment & configuration (arguments, toml...)?
```
/traefik --web --retry --retry.attempts=10 --docker --docker.watch --docker.domain=my.domain.org --logLevel=DEBUG --entryPoints=Name:http Address::80 --defaultEntryPoints=http --web.address=:8081
```

### What did you do?
I start an nginx container, with some static files in web root
I export the port, and test :
- Download a 1.3GB file on the expose port (without traefik)
- Download same file by traefik on configured frontend

### What did you expect to see?
Almost same downlaod time

### What did you see instead?
I download directly in 2 sec and i got 6 sec through traefik
The traefik process use 50/60% CPU for 3 sec
At the end, the traefik process take 4.626g Virtual RAM (top) instead of classical ~100M
That RAM is released few minutes later (garbage collect ?)

I can't use traefik to route those requests, i have some big files, like 20/30 GB
How traefik works for that ?
Why it have to store those data in RAM ?

Thanx for reading

**Comment by WTFKr0** [comment] 2017-03-09 15:54
Tested in v1.2.0-rc2, problem still the same : 
```
Version:      v1.2.0-rc2
Codename:     morbier
Go version:   go1.7.5
Built:        2017-03-01_01:03:26PM
OS/Arch:      linux/amd64
```

**Comment by timoreimann** [comment] 2017-03-09 15:55
We should consider doing some profiling to see where the CPU cycles and memory is spent.

**Comment by emilevauge** [comment] 2017-03-09 16:42
To my mind, it comes from https://github.com/containous/oxy. I would bet on a buffering issue.

**Comment by WTFKr0** [comment] 2017-03-10 09:41
OK I got it !
After some tests, It's the retry option !
It seems logic that traefik need to store data somewhere in case of retry.
Maybe an annotation in doc will be useful for that ?

**Comment by timoreimann** [comment] 2017-03-10 13:16
Sounds like the retrying logic is reading all data into memory whereas it should stream it to the client (i.e., the "buffering issue" that @emilevauge mentioned).

To me, this looks like a bug that should be fixed.

**Comment by emilevauge** [comment] 2017-03-10 14:08
Well done @WTFKr0, great job !
@timoreimann not sure that's even possible to not cache the response in the retry middleware... If your connection fails in the middle of your streaming, how would you manage the retry ?

**Comment by timoreimann** [comment] 2017-03-10 15:13
@emilevauge my understanding is that if the connection fails midway and you retry, you just start all over again. If you want to pick up where you left off, that sounds more like resuming. Which might be better solved with things like chunked transfer encoding.

**Comment by Cedric-Venet** [comment] 2017-03-10 17:00
@timoreimann I think you assume that the endpoint will always return the exact same response, which is not the case in general. Appending (part of) the result of the second response to the first part of the first response does not make much sense.

**Comment by timoreimann** [comment] 2017-03-10 17:58
Actually, Traefik only retries on 502s and 504s (which may even be too liberal; see also #1104). We should probably follow HAProxy's and Nginx's examples and not try to be too smart: If data is already flowing and a failure occurs, don't retry but leave it up to the client to deal with the situation.

This would also obviate any need to think about buffering and the complexities it brings.

WDYT?

**Comment by samart** [comment] 2017-10-14 06:49
latest traefik crashes with fronting a docker registry.  obviously, we will not use traefik in this path now, but concerning nontheless, its not just docker registry that might have large files...

large memory spike on even just 1 image download can be seen in my prometheus memory view..

**Comment by timoreimann** [comment] 2017-10-14 09:07
@samart what's your request pattern for the spikes to appear? Does it take a single image download only or multiple? If the latter, how many roughly?

Anything that helps creating a reproducible case would be great.

**Comment by samart** [comment] 2017-10-15 02:54
docker engine --> f5 --> Traefik --> ( Nginx --> Artifactory)  (horrible number of hops, i know, we're changing this)

But - all you need to do is 1 docker pull (with docker engine client at defaults = 3 layers at a time) with some decently sized image 500mb to 1G and Basic container metrics mem, will spike.   Pull N more containers at the same time will usually crash traefik.

we run traefik in docker with 2G ram for the container.

**Comment by marco-jantke** [comment] 2018-01-23 11:14
@WTFKr0 and @samart I just pushed a PR that should fix the high RAM and therefore also some of the CPU usage in the retry middleware. https://github.com/containous/traefik/pull/2740 

Can you check whether it also fixes the problem in your setups? Let me know when you need assistance building a docker image from that version, I am also on the Slack channel in case.

**Comment by venediktov** [comment] 2018-06-24 06:09
@WTFKr0 , I read your earlier comment about retry logic , I am totally new to traefik , I needed something to keep my connections alive with backend , the files I am pushing about 1K . Benchmarked it with  ab my bidder load balanced with traefik  runs 3 times slower in docker swarm mode  then single instance of my bidder in docker container without any load balancing .
Where do you think is the issue ? I don't see in my config retry settings .

[example](https://github.com/venediktov/vanilla-rtb/tree/master/docker_swarm)

**Comment by traefiker** [comment] 2018-09-23 00:00
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Closed by traefiker** 2018-09-23 00:00 UTC
Labels: contributor/waiting-for-feedback, kind/bug/confirmed, priority/P1
