### ISSUE TITLE
http: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by raviada** [containous/traefik#1686] opened 2017-05-31 10:15 UTC
I just installed Traefik thru Helm on our newly created Kubernetes cluster on Azure.
Output from ```kubectl get --namespace=kube-system --export all``` gives me this.
```
NAME                                               READY     STATUS    RESTARTS   AGE
po/heapster-v1.2.0-1448994189-mzvg1                2/2       Running   0          23h
po/kube-addon-manager-k8s-master-b80ca162-0        1/1       Running   0          8h
po/kube-apiserver-k8s-master-b80ca162-0            1/1       Running   0          8h
po/kube-controller-manager-k8s-master-b80ca162-0   1/1       Running   0          8h
po/kube-dns-v19-7lkjb                              3/3       Running   0          23h
po/kube-dns-v19-d4z62                              3/3       Running   0          23h
po/kube-proxy-29df1                                1/1       Running   0          23h
po/kube-proxy-43zmh                                1/1       Running   0          23h
po/kube-proxy-b089t                                1/1       Running   0          23h
po/kube-proxy-sm0bd                                1/1       Running   0          23h
po/kube-scheduler-k8s-master-b80ca162-0            1/1       Running   0          8h
po/kubernetes-dashboard-696481038-9jbd7            1/1       Running   0          23h
po/tiller-deploy-3354596499-x5s2v                  1/1       Running   0          8h
po/traefik001-traefik-3907310088-z51kj             1/1       Running   0          8h

NAME              DESIRED   CURRENT   READY     AGE
rc/kube-dns-v19   2         2         2         23h

NAME                               CLUSTER-IP     EXTERNAL-IP    PORT(S)                      AGE
svc/heapster                       10.0.111.25    <none>         80/TCP                       23h
svc/kube-dns                       10.0.0.10      <none>         53/UDP,53/TCP                23h
svc/kubernetes-dashboard           10.0.106.144   <nodes>        80:30177/TCP                 23h
svc/tiller-deploy                  10.0.117.8     <none>         44134/TCP                    19h
svc/traefik001-traefik             10.0.114.211   40.71.95.213   80:32255/TCP,443:31271/TCP   19h
svc/traefik001-traefik-dashboard   10.0.193.213   <none>         80/TCP                       19h

NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/heapster-v1.2.0        1         1         1            1           23h
deploy/kubernetes-dashboard   1         1         1            1           23h
deploy/tiller-deploy          1         1         1            1           19h
deploy/traefik001-traefik     1         1         1            1           19h

NAME                                DESIRED   CURRENT   READY     AGE
rs/heapster-v1.2.0-1448994189       1         1         1         23h
rs/kubernetes-dashboard-696481038   1         1         1         23h
rs/tiller-deploy-3354596499         1         1         1         19h
rs/traefik001-traefik-3907310088    1         1         1         19h

```

My ingress for the APIs look like this
```
Name:			coreapi-ingress
Namespace:		default
Address:		
Default backend:	default-http-backend:80 (<none>)
Rules:
  Host			Path	Backends
  ----			----	--------
  coreapi.medl.io	
    			/datasetsapi 		datasets:http (<none>)
    			/imageapi 		image:http (<none>)

```
I have my DNS entry for ```coreapi.medl.io``` pointing to traefik which is ```40.71.95.213```

```
2017-05-31T09:19:31.632273392Z time="2017-05-31T09:19:31Z" level=warning msg="Error copying upstream response Body: write tcp 10.244.2.7:80->10.240.0.4:61200: write: connection timed out" 
2017-05-31T09:19:31.632304392Z 2017/05/31 09:19:31 server.go:2317: http: multiple response.WriteHeader calls
2017-05-31T09:39:39.439504878Z time="2017-05-31T09:39:39Z" level=warning msg="Error copying upstream response Body: write tcp 10.244.2.7:80->10.240.0.4:61602: write: connection timed out" 
2017-05-31T09:39:39.439733180Z 2017/05/31 09:39:39 server.go:2317: http: multiple response.WriteHeader calls
2017-05-31T09:53:12.495480508Z time="2017-05-31T09:53:12Z" level=warning msg="Error copying upstream response Body: write tcp 10.244.2.7:80->10.240.0.6:61909: write: connection timed out" 
2017-05-31T09:53:12.495510908Z 2017/05/31 09:53:12 server.go:2317: http: multiple response.WriteHeader calls
2017-05-31T10:02:47.983512804Z time="2017-05-31T10:02:47Z" level=warning msg="Error copying upstream response Body: write tcp 10.244.2.7:80->10.240.0.6:62215: write: connection timed out" 
2017-05-31T10:02:47.983551005Z 2017/05/31 10:02:47 server.go:2317: http: multiple response.WriteHeader calls
```

I am getting the output from backend sometimes and the same API call second or third time just sits there waiting and eventually timesout.

Any help would would be appreciated.

**Comment by raviada** [comment] 2017-05-31 16:44
I understand there are 9000 plus events generated for health check, but what I dont understand is why the response time is going up every time. Literally there is no traffic, I just kept them idle for a few hours, that is all. Is this normal or my setup is wrong?

<img width="1207" alt="2017-05-31_1138" src="https://cloud.githubusercontent.com/assets/819292/26643124/df1c71e6-45f5-11e7-882a-127bd4ec8260.png">

**Comment by timoreimann** [comment] 2017-05-31 20:10
This looks similar to #1184, which will presumably get fixed by containous/oxy#15.

Any chance you could try a custom Traefik build I'd provide that contains the presumed fix?

By the way, what version of Traefik are you running?

**Comment by raviada** [comment] 2017-05-31 20:16
Thanks for the quick response. I am using the latest image v1.2.3 with helm chart 1.3.0. I really like this ingress controller, it is unusable at this time because every other request is timing out. It has a fanout of 12 apis, I just installed it with higher resources than defaults to see if its starving for resources.

Yes, I would like to try the fix, but please let me know how to build it and install the custom chart.

Thanks
Ravi Ada

**Comment by timoreimann** [comment] 2017-05-31 20:22
@raviada I can build the image for you (it's not that trivial to do it since we need an in-flight PR of the containous/oxy dependency). However, I have zero experience with Helm. Do you know if it's possible to reuse an existing Helm chart with just a different image version/tag?

**Comment by raviada** [comment] 2017-05-31 20:26
I just reviewed [#1184](https://github.com/containous/traefik/issues/1184), I am not doing any media streaming though, mine is plain and simple REST calls. Do you think it is the same issue and can be addressed by this fix?
I am new to Helm as well, I can try to install it with new image.

**Comment by raviada** [comment] 2017-05-31 20:33
when I installed this again a few mins ago, I see this message in Traefik pod logs.
```2017-05-31T19:56:14.059843890Z time="2017-05-31T19:56:14Z" level=warning msg="A new release has been found: 1.3.0. Please consider updating." ```

I was using ```v1.2.3``` image.

Does this have the fix for [#1184](https://github.com/containous/traefik/issues/1184)?

**Comment by timoreimann** [comment] 2017-05-31 20:36
@raviada looking at#1184 and containous/oxy#15 again, I'm starting to doubt it's related to your problem.

I'm not sure if the just-released 1.3.0 contains a fix. Could you give it a try?

**Comment by raviada** [comment] 2017-05-31 20:39
I did, I am getting this error now.
```2017-05-31T20:35:40.961800774Z time="2017-05-31T20:35:40Z" level=error msg="Error creating route for frontend coreapi.medl.io/datasetsapi: Error parsing rule: Error parsing rule: 'pathprefixstrip:/datasetsapi'. Unknown function: 'pathprefixstrip'" ```

Has this changed in the new image? if yes how can I correct the rule to strip out the prefix?

**Comment by timoreimann** [comment] 2017-05-31 20:50
@raviada This might be a regression. Please try `PathPrefixStrip` (watch the case).

**Comment by raviada** [comment] 2017-06-01 01:14
After I upgraded to v1.3.0, I am seeing these errors.
```2017-06-01T01:05:22.276025841Z ERROR: logging before flag.Parse: E0601 01:05:22.275858       1 reflector.go:359] github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache/reflector.go:94: expected type *v1.Endpoints, but watch event object had type *v1.Secret```

**Comment by timoreimann** [comment] 2017-06-01 11:06
@raviada that error has been reported in #1596 as well. I'm not entirely sure, but I think it's not critical.

How's Traefik 1.3 doing for you w.rt. to the reported performance issues?

**Comment by raviada** [comment] 2017-06-01 12:55
@timoreimann I am having the same issue, I don't understand where the problem is. Each API is running fine individually when I exposed them thru LB, but when I use ingress I am having trouble, after some idle time, when I hit the same API call, I get the results in milliseconds, and takes forever and sometimes the request gets timed-out when I access the same API again.

Has anyone faced similar issue before? is it something specific to cloud provider, in this case it is Azure.

Any specific places to look for a possible problem?

**Comment by raviada** [comment] 2017-06-01 12:59
it works fine when we access the APIs continuously but timing out after some idle time. Let me switch to nginx controller and see it it makes any difference. If there is something wrong in my setup, I would like to know and correct it immediately. I am under the gun to setup our environment quickly.  Any help would greatly be appreciated.

**Comment by timoreimann** [comment] 2017-06-01 16:23
@raviada https://github.com/containous/oxy/pull/15#issuecomment-305389632 makes me think we should reconsider you trying out a custom Traefik build with that fixing PR included. If you still think that's feasible for you, let me know and I'll get things ready.

**Comment by timoreimann** [comment] 2017-07-14 00:28
I'll close this for now due to inactivity. @raviada, let me know if you'd like to continue on the issue and I'll reopen.

**Closed by timoreimann** 2017-07-14 00:28 UTC
Labels: area/oxy, area/provider/k8s, kind/bug/possible

**Comment by venth** [comment] 2017-10-27 18:21
I've similar situation. I have setup [kube-ops-view](https://github.com/hjacobs/kube-ops-view) on k8s. In traefik logs I entries as follows:

> 2017/10/27 17:50:57 server.go:2848: http: multiple response.WriteHeader calls
time="2017-10-27T17:51:03Z" level=warning msg="Error copying upstream response body: context canceled" 

In firebug I see:

> http://<fqdn>/kube-ops-view/events

with MIME-TYPE: text/event-stream and information that the resource failed to load.

It seems that traefik cannot route an event stream properly (forth and back)
