### ISSUE TITLE
Allow multiple accounts per provider

### ISSUE THREAD

**Issue by kopax** [containous/traefik#5991] opened 2019-12-10 20:17 UTC
# Feature

Allow multiple accounts per provider. For example, I have multiple OVH accounts, I want to be able to provide API key for all of them.

I am using version 2.1 and this is not possible yet.

# Purposed solution

Offer to override global values (if any) using `certificateResolvers.main.acme.environments`

**Comment by ldez** [comment] 2019-12-10 20:19
Duplicate of #5472

**Closed by ldez** 2019-12-10 20:19 UTC
Labels: status/0-needs-triage

**Comment by kopax** [comment] 2019-12-10 20:25
Sorry I didn't saw it. Thanks for linking!
