### ISSUE TITLE
Dropping Consul catalog change events

### ISSUE THREAD

**Issue by lmickh** [containous/traefik#1135] opened 2017-02-07 16:16 UTC
### What version of Traefik are you using (`traefik version`)?
The traefik:v1.1.2-alpine container from Docker Hub.

### What is your environment & configuration (arguments, toml...)?
```toml
defaultEntryPoints = ["https"]
logLevel = "DEBUG"

[web]
  address = ":8080"

[consul]
  endpoint = "127.0.0.1:8500"
  watch = true
  prefix = "app/traefik/am23-lb"
  [consul.tls]
    ca = "/etc/traefik/ssl/consul-ca.crt"
    cert = "/etc/traefik/ssl/consul.crt"
    key = "/etc/traefik/ssl/consul.key"
    insecureskipverify = true

[consulCatalog]
  endpoint = "127.0.0.1:8501"
  watch = true
  domain = "dev.example.com"
  #prefix = "traefik"
  constraints = ["tag==external"]


[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint= "https"
  [entryPoints.https]
  address = ":443"
    [[entryPoints.https.tls.certificates]]
    certFile = "/etc/traefik/ssl/star-bundle.crt"
    keyFile = "/etc/traefik/ssl/star.key"
```

Applications are running in Kubernetes pods.  They register themselves with Consul via [ContainerPilot](https://github.com/joyent/containerpilot).  Everything works as expected when Traefik is started.  It pulls the current state from the Consul catalog and creates all of the frontends and backends.

### What did you do?
Redeploy a pod which triggers a deregister followed by a register event in the Consul catalog.  

### What did you expect to see?
The latest state of the Consul catalog, which includes the re-register, to be acted upon and loaded into the Traefik configuration.  Even if it is understandably throttled, the latest state should be polled and/or resync'ed after a brief period.

### What did you see instead?
The deregister is acted on while the register is not.  Scrubbed debug level logs below.  The new registration is never applied unless another event happens in the catalog or Traefik is restarted.

```shell
time="2017-02-07T16:06:05Z" level=debug msg="Configuration received from provider consul_catalog: {\"backends\":{\"backend-insight-client\":{\"servers\":{\"insight-client--10-244-2-100--80--traefik-backend-loadbalancer-drr--traefik-frontend-entrypoints-https--traefik-frontend-rule-Host-insight-dev-example-com--traefik-protocol-http--traefik-tags-external--0\":{\"url\":\"http://10.244.2.100:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"drr\"}},\"backend-io\":{\"servers\":{\"io--10-244-2-99--80--traefik-backend-loadbalancer-drr--traefik-frontend-entrypoints-https--traefik-frontend-rule-Host-io-dev-example-com--traefik-protocol-http--traefik-tags-external--1\":{\"url\":\"http://10.244.2.99:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"drr\"}},\"backend-vault\":{\"servers\":{\"vault--am23-vault-0-dev-example-com--8200--dev--traefik-frontend-entrypoints-https--traefik-protocol-http--traefik-tags-external--active--2\":{\"url\":\"http://am23-vault-0.dev.example.com:8200\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-insight-client\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-insight-client\",\"routes\":{\"route-host-insight-client\":{\"rule\":\"Host:insight.dev.example.com\"}},\"passHostHeader\":true,\"priority\":0},\"frontend-io\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-io\",\"routes\":{\"route-host-io\":{\"rule\":\"Host:io.dev.example.com\"}},\"passHostHeader\":true,\"priority\":0},\"frontend-vault\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-vault\",\"routes\":{\"route-host-vault\":{\"rule\":\"Host:vault.dev.example.com\"}},\"passHostHeader\":true,\"priority\":0}}}"
time="2017-02-07T16:06:05Z" level=debug msg="Last consul_catalog config received more than 2s, OK"
time="2017-02-07T16:06:05Z" level=debug msg="Creating frontend frontend-insight-client"
time="2017-02-07T16:06:05Z" level=debug msg="Wiring frontend frontend-insight-client to entryPoint https"
time="2017-02-07T16:06:05Z" level=debug msg="Creating route route-host-insight-client Host:insight.dev.example.com"
time="2017-02-07T16:06:05Z" level=debug msg="Creating backend backend-insight-client"
time="2017-02-07T16:06:05Z" level=debug msg="Creating load-balancer drr"
time="2017-02-07T16:06:05Z" level=debug msg="Creating server insight-client--10-244-2-100--80--traefik-backend-loadbalancer-drr--traefik-frontend-entrypoints-https--traefik-frontend-rule-Host-insight-dev-example-com--traefik-protocol-http--traefik-tags-external--0 at http://10.244.2.100:80 with weight 0"
time="2017-02-07T16:06:05Z" level=debug msg="Creating frontend frontend-io"
time="2017-02-07T16:06:05Z" level=debug msg="Wiring frontend frontend-io to entryPoint https"
time="2017-02-07T16:06:05Z" level=debug msg="Creating route route-host-io Host:io.dev.example.com"
time="2017-02-07T16:06:05Z" level=debug msg="Creating backend backend-io"
time="2017-02-07T16:06:05Z" level=debug msg="Creating load-balancer drr"
time="2017-02-07T16:06:05Z" level=debug msg="Creating server io--10-244-2-99--80--traefik-backend-loadbalancer-drr--traefik-frontend-entrypoints-https--traefik-frontend-rule-Host-io-dev-campuslabs-io--traefik-protocol-http--traefik-tags-external--1 at http://10.244.2.99:80 with weight 0"
time="2017-02-07T16:06:05Z" level=debug msg="Creating frontend frontend-vault"
time="2017-02-07T16:06:05Z" level=debug msg="Wiring frontend frontend-vault to entryPoint https"
time="2017-02-07T16:06:05Z" level=debug msg="Creating route route-host-vault Host:vault.dev.example.com"
time="2017-02-07T16:06:05Z" level=debug msg="Creating backend backend-vault"
time="2017-02-07T16:06:05Z" level=debug msg="Creating load-balancer wrr"
time="2017-02-07T16:06:05Z" level=debug msg="Creating server vault--am23-vault-0-dev-example-com--8200--dev--traefik-frontend-entrypoints-https--traefik-protocol-http--traefik-tags-external--active--2 at http://am23-vault-0.dev.example.com:8200 with weight 0"
time="2017-02-07T16:06:05Z" level=info msg="Server configuration reloaded on :80"
time="2017-02-07T16:06:05Z" level=info msg="Server configuration reloaded on :443"
time="2017-02-07T16:06:05Z" level=debug msg="List of services changed"
time="2017-02-07T16:06:05Z" level=debug msg="Fetching service" service=consul
time="2017-02-07T16:06:05Z" level=debug msg="Service consul pruned by 'tag==external' constraint"
time="2017-02-07T16:06:05Z" level=debug msg="Service consul pruned by 'tag==external' constraint"
time="2017-02-07T16:06:05Z" level=debug msg="Service consul pruned by 'tag==external' constraint"
time="2017-02-07T16:06:05Z" level=debug msg="Fetching service" service=insight-client
time="2017-02-07T16:06:05Z" level=debug msg="Fetching service" service=io
time="2017-02-07T16:06:05Z" level=debug msg="Fetching service" service=vault
time="2017-02-07T16:06:05Z" level=debug msg="Load balancer method '<nil>' for backend backend-vault: Invalid method, using default. Using default wrr."
time="2017-02-07T16:06:05Z" level=debug msg="Configuration received from provider consul_catalog: {\"backends\":{\"backend-insight-client\":{\"servers\":{\"insight-client--10-244-2-100--80--traefik-backend-loadbalancer-drr--traefik-frontend-entrypoints-https--traefik-frontend-rule-Host-insight-dev-example-com--traefik-protocol-http--traefik-tags-external--0\":{\"url\":\"http://10.244.2.100:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"drr\"}},\"backend-io\":{\"servers\":{\"io--10-244-2-99--80--traefik-backend-loadbalancer-drr--traefik-frontend-entrypoints-https--traefik-frontend-rule-Host-io-dev-example-com--traefik-protocol-http--traefik-tags-external--1\":{\"url\":\"http://10.244.2.99:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"drr\"}},\"backend-vault\":{\"servers\":{\"vault--am23-vault-0-dev-example-com--8200--dev--traefik-frontend-entrypoints-https--traefik-protocol-http--traefik-tags-external--active--2\":{\"url\":\"http://am23-vault-0.dev.example.com:8200\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-insight-client\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-insight-client\",\"route\":{\"route-host-insight-client\":{\"rule\":\"Host:insight.dev.example.com\"}},\"passHostHeader\":true,\"priority\":0},\"frontend-io\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-io\",\"routes\":{\"route-host-io\":{\"rule\":\"Host:io.dev.example.com\"}},\"passHostHeader\":true,\"priority\":0},\"frontend-vault\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-vault\",\"routes\":{\"route-host-vault\":{\"rule\":\"Host:vault.dev.example.com\"}},\"passHostHeader\":true,\"priority\":0}}}"
time="2017-02-07T16:06:05Z" level=info msg="Skipping same configuration for provider consul_catalog"
time="2017-02-07T16:06:05Z" level=debug msg="List of services changed"
time="2017-02-07T16:06:05Z" level=debug msg="Fetching service" service=io
time="2017-02-07T16:06:05Z" level=debug msg="Fetching service" service=vault
time="2017-02-07T16:06:05Z" level=debug msg="Fetching service" service=consul
time="2017-02-07T16:06:05Z" level=debug msg="Service consul pruned by 'tag==external' constraint"
time="2017-02-07T16:06:05Z" level=debug msg="Service consul pruned by 'tag==external' constraint"
time="2017-02-07T16:06:05Z" level=debug msg="Service consul pruned by 'tag==external' constraint"
time="2017-02-07T16:06:05Z" level=debug msg="Fetching service" service=insight-client
time="2017-02-07T16:06:05Z" level=debug msg="Load balancer method '<nil>' for backend backend-vault: Invalid method, using default. Using default wrr."
time="2017-02-07T16:06:05Z" level=debug msg="Configuration received from provider consul_catalog: {\"backends\":{\"backend-io\":{\"servers\":{\"io--10-244-2-99--80--traefik-backend-loadbalancer-drr--traefik-frontend-entrypoints-https--traefik-frontend-rule-Host-io-dev-example-com--traefik-protocol-http--traefik-tags-external--0\":{\"url\":\"http://10.244.2.99:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"drr\"}},\"backend-vault\":{\"servers\":{\"vault--am23-vault-0-dev-example-com--8200--dev--traefik-frontend-entrypoints-https--traefik-protocol-http--traefik-tags-external--active--1\":{\"url\":\"http://am23-vault-0.dev.example.com:8200\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-io\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-io\",\"routes\":{\"route-host-io\":{\"rule\":\"Host:io.dev.example.com\"}},\"passHostHeader\":true,\"priority\":0},\"frontend-vault\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-vault\",\"routes\":{\"route-host-vault\":{\"rule\":\"Host:vault.dev.example.com\"}},\"passHostHeader\":true,\"priority\":0}}}"
time="2017-02-07T16:06:05Z" level=debug msg="Last consul_catalog config received less than 2s, waiting..."
time="2017-02-07T16:06:05Z" level=debug msg="List of services changed"
time="2017-02-07T16:06:05Z" level=debug msg="Fetching service" service=consul
time="2017-02-07T16:06:05Z" level=debug msg="Service consul pruned by 'tag==external' constraint"
time="2017-02-07T16:06:05Z" level=debug msg="Service consul pruned by 'tag==external' constraint"
time="2017-02-07T16:06:05Z" level=debug msg="Service consul pruned by 'tag==external' constraint"
time="2017-02-07T16:06:05Z" level=debug msg="Fetching service" service=insight-client
time="2017-02-07T16:06:05Z" level=debug msg="Fetching service" service=io
time="2017-02-07T16:06:05Z" level=debug msg="Fetching service" service=vault
time="2017-02-07T16:06:05Z" level=debug msg="Load balancer method '<nil>' for backend backend-vault: Invalid method, using default. Using default wrr."
time="2017-02-07T16:06:05Z" level=debug msg="Configuration received from provider consul_catalog: {\"backends\":{\"backend-insight-client\":{\"servers\":{\"insight-client--10-244-2-100--80--traefik-backend-loadbalancer-drr--traefik-frontend-entrypoints-https--traefik-frontend-rule-Host-insight-dev-example-com--traefik-protocol-http--traefik-tags-external--0\":{\"url\":\"http://10.244.2.100:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"drr\"}},\"backend-io\":{\"servers\":{\"io--10-244-2-99--80--traefik-backend-loadbalancer-drr--traefik-frontend-entrypoints-https--traefik-frontend-rule-Host-io-dev-example-com--traefik-protocol-http--traefik-tags-external--1\":{\"url\":\"http://10.244.2.99:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"drr\"}},\"backend-vault\":{\"servers\":{\"vault--am23-vault-0-dev-example-com--8200--dev--traefik-frontend-entrypoints-https--traefik-protocol-http--traefik-tags-external--active--2\":{\"url\":\"http://am23-vault-0.dev.example.com:8200\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-insight-client\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-insight-client\",\"routes\":{\"route-host-insight-client\":{\"rule\":\"Host:insight.dev.example.com\"}},\"passHostHeader\":true,\"priority\":0},\"frontend-io\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-io\",\"routes\":{\"route-host-io\":{\"rule\":\"Host:io.dev.example.com\"}},\"passHostHeader\":true,\"priority\":0},\"frontend-vault\":{\"entryPoints\":[\"https\"],\"backend\":\"backend-vault\",\"routes\":{\"route-host-vault\":{\"rule\":\"Host:vault.dev.example.com\"}},\"passHostHeader\":true,\"priority\":0}}}"
time="2017-02-07T16:06:05Z" level=info msg="Skipping same configuration for provider consul_catalog"
time="2017-02-07T16:06:07Z" level=debug msg="Waited for consul_catalog config, OK"
time="2017-02-07T16:06:07Z" level=debug msg="Creating frontend frontend-io"
time="2017-02-07T16:06:07Z" level=debug msg="Wiring frontend frontend-io to entryPoint https"
time="2017-02-07T16:06:07Z" level=debug msg="Creating route route-host-io Host:io.dev.example.com"
time="2017-02-07T16:06:07Z" level=debug msg="Creating backend backend-io"
time="2017-02-07T16:06:07Z" level=debug msg="Creating load-balancer drr"
time="2017-02-07T16:06:07Z" level=debug msg="Creating server io--10-244-2-99--80--traefik-backend-loadbalancer-drr--traefik-frontend-entrypoints-https--traefik-frontend-rule-Host-io-dev-campuslabs-io--traefik-protocol-http--traefik-tags-external--0 at http://10.244.2.99:80 with weight 0"
time="2017-02-07T16:06:07Z" level=debug msg="Creating frontend frontend-vault"
time="2017-02-07T16:06:07Z" level=debug msg="Wiring frontend frontend-vault to entryPoint https"
time="2017-02-07T16:06:07Z" level=debug msg="Creating route route-host-vault Host:vault.dev.example.com"
time="2017-02-07T16:06:07Z" level=debug msg="Creating backend backend-vault"
time="2017-02-07T16:06:07Z" level=debug msg="Creating load-balancer wrr"
time="2017-02-07T16:06:07Z" level=debug msg="Creating server vault--am23-vault-0-dev-example-com--8200--dev--traefik-frontend-entrypoints-https--traefik-protocol-http--traefik-tags-external--active--1 at http://am23-vault-0.dev.example.com:8200 with weight 0"
time="2017-02-07T16:06:07Z" level=info msg="Server configuration reloaded on :80"
time="2017-02-07T16:06:07Z" level=info msg="Server configuration reloaded on :443"
```

**Comment by ummecasino** [comment] 2017-02-09 13:19
Which version of Consul are you running? I just had the same issue using Consul v0.7.4 with Traefik 1.0.3 up to 1.1.2 and nomad deployments. Switching Consul back to v0.7.3 solved the problem for me, services are getting auto re-registered after redeployment.

**Comment by ummecasino** [comment] 2017-02-09 15:13
Which Consul version are you using? Ran into the same issue with Traefik (all versions from 1.0.2 up to 1.1.2) and Consul v0.7.4. After switching back Consul to 0.7.2 everything went back to normal. Seems like some changes were made there.

**Comment by lmickh** [comment] 2017-02-09 15:33
I'm running 0.7.2.

**Comment by danielbenzvi** [comment] 2017-02-15 12:50
Happening here as well with Consul 0.7.3 and traefik v1.1.2

**Comment by errm** [comment] 2017-02-21 23:32
why do you need Consul when your applications are running in Kubernetes? is there something that the Kubernetes integration does not provide?

**Comment by errm** [comment] 2017-02-21 23:38
Also looks to be a possible dupe of #1107 so might be fixed by #1130

**Comment by lmickh** [comment] 2017-02-22 00:34
@errm The reason for not using the Kubernetes integration has nothing to do with the capabilities of it.  We use Consul for a number of things that are well beyond the scope of the Kubernetes service discovery features.  Kubernetes is only a small subset of our current infrastructure.  It is largely a matter of trying to avoid having multiple "sources of truth".

It didn't seem to be a dupe since health checks are not defined for two of the services.  Happy to be wrong though.

**Comment by ldez** [comment] 2017-06-09 12:42
Do you still have the same problem with the latest version? [releases](https://github.com/containous/traefik/releases)

**Comment by traefiker** [comment] 2018-02-06 00:00
I'll close the issue due to inactivity but feel free to re-open if needed.

**Closed by traefiker** 2018-02-06 00:00 UTC
Labels: area/provider/consulcatalog, area/provider/k8s, contributor/waiting-for-feedback, status/0-needs-triage
