### ISSUE TITLE
Dashboard with secured API don't work with another port than 8080

### ISSUE THREAD

**Issue by deweller** [containous/traefik#5382] opened 2019-09-13 16:54 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?
Launched taefik with the following config:

```
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

# Default:
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.traefik]
    address = ":8000"

[http.routers.my-api]
    entryPoints = ["traefik"]
    rule="PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
    service="api@internal"
    middlewares=["auth"]

[http.middlewares.auth.basicAuth]
    users = [
        "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/", 
      ]

[api]
  dashboard = true
[ping]
[providers.docker]
```

### What did you expect to see?
dashboard at http://localhost:8000

### What did you see instead?
404 page

### Output of traefik version: (What version of Traefik are you using?)
```Version:      2.0.0-rc3
Codename:     montdor
Go version:   go1.13
Built:        2019-09-10T17:10:04Z
OS/Arch:      linux/amd64
```

### Other notes

Note that this does work when `api.insecure=true` is set in the toml file.  But the auth middleware is ignored when api.insecure is true.

This is related to #5363. Since that ticket was closed, I opened a new one.

**Comment by ldez** [comment] 2019-09-13 17:02
The dashboard need the API, and the API need to be secure.
Duplicate of #5363

https://github.com/containous/traefik/issues/5363#issuecomment-530729082

Maybe your problem is more related to the `PathPrefix`, you can follow  #5374 

Duplicate of #5374

**Comment by deweller** [comment] 2019-09-13 17:36
I tried removing the `rule` entirely and this still does not work for me.

**Comment by ldez** [comment] 2019-09-13 17:38
Try to add a `Host` rule.

Come in our support forum https://community.containo.us/, I will help you.

**Comment by ldez** [comment] 2019-09-13 21:15
I reopen because I reproduce the bug.

**Comment by ldez** [comment] 2019-09-13 21:23
I made a mistake in my local configuration.

It works, so I close.

**Closed by ldez** 2019-09-13 21:23 UTC
Labels: area/api, area/webui, kind/bug/confirmed, priority/P1

**Comment by tanwarsatya** [comment] 2019-09-15 15:18
@ldez could you please let me know what was the mistake in your local configuration and what did you change.

**Comment by deweller** [comment] 2019-09-16 13:57
@tanwarsatya - I believe the mistake was that the dynamic configuration was not in a separate file.

Separating the dynamic configuration into another file fixed this for me.

**Comment by ldez** [comment] 2019-09-16 14:00
My mistake was just a typo in a port.
