### ISSUE TITLE
Datadog metrics support

### ISSUE THREAD

**Issue by Regner** [containous/traefik#1213] opened 2017-03-01 21:45 UTC
I know I and a few others would love Traefik to support the sending of metrics to Datadog. I am open to making the changes, probably take me a while to figure it out but whatever. Before seriously digging into it though I figured a bit of discussion first would be in order.

From what I can see there are three ways of getting metrics into Datadog:
1. Send them directly with the Datadog HTTP API
    * http://docs.datadoghq.com/api/
    * https://github.com/zorkian/go-datadog-api
2. Require the usage of DogStatsD
    * http://docs.datadoghq.com/guides/dogstatsd/
    * https://github.com/DataDog/datadog-go
3. Write a Datadog agent integration that queries the API and forwards the metrics
    * http://docs.datadoghq.com/guides/agent_checks/

I would personally lean towards the first option, sending the stats directly to the DD API. However I am unsure what rate limits there are on that and if that would cause a problem.

Aside from the how something like this would work there is also the question of if it fits being in Traefik or not.

**Comment by Regner** [comment] 2017-03-01 22:01
Seems there may be a way to get into the official DD agent: https://github.com/DataDog/integrations-core

**Comment by aantono** [comment] 2017-05-16 16:35
Probably a duplicate of #834

**Comment by timoreimann** [comment] 2017-05-16 18:43
@Regner okay for you to continue tracking Datadog/StatsD support in #834 (and possibly coordinate with @aantono [who mentioned that he's got a PR prepared](https://github.com/containous/traefik/issues/834#issuecomment-301370498) already)?

**Closed** 2017-06-02 08:14 UTC
Labels: area/middleware/metrics, kind/question, resolution/duplicate
