### ISSUE TITLE
Support for default route for k8s backend

### ISSUE THREAD

**Issue by sheerun** [containous/traefik#1051] opened 2017-01-21 12:25 UTC
Traefik current doesn't recognize default backend of kubernetes ingress, showing 404 instead:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: deis
  name: deis
spec:
  backend:
    serviceName: deis-router
    servicePort: 80
```

Is it reasonable to configure catch-all in traefik if following ingress is present? I'd say so.

**Comment by christianhuening** [comment] 2017-01-21 13:03
probably related to https://github.com/containous/traefik/issues/374 ?

**Comment by sheerun** [comment] 2017-01-21 13:24
Might be, but not directly, as I don't use paths for services.

**Comment by mtpereira** [comment] 2017-02-23 10:21
I'm working on this issue with @errm 's guidance. :+1:

**Comment by timoreimann** [comment] 2017-03-06 16:57
AFAICS, the Kubernetes provider simply ignores Ingress resources that don't come with a path. #374 may affect it eventually, but it's not the root cause.

**Comment by ldez** [comment] 2017-05-24 08:52
Closed by #1638, in the version 1.3.0-rc3.

**Comment by kjvalencik** [comment] 2017-06-15 16:27
I'm using `1.3` and this doesn't appear to be working. Have others had success?

**Comment by kjvalencik** [comment] 2017-06-15 16:42
This issue doesn't appear to be completely resolved. Traefik still does not support a top level default backend.

https://kubernetes.io/docs/concepts/services-networking/ingress/#single-service-ingress

However, the fix does give a possible work around. You can create a rule with no `host` that will match all routes.

**Comment by mingfang** [comment] 2018-05-24 00:08
Default backend ingress still does not work in Traefik v1.62

**Comment by dtomcej** [comment] 2018-05-24 00:55
This seems like an exception case, where the ingress object does not provide any host or paths to match against.

However it is documented in the kubernetes documentation (https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource):

```
 One can specify a global default backend in the absence of which requests that don’t match a path in the spec are sent to the default backend of the Ingress controller.
```
I am reopening this, as I think this is a totally doable task.

**Closed** 2018-07-03 16:58 UTC
Labels: area/provider/k8s, kind/bug/confirmed, priority/P2
