### ISSUE TITLE
Support for a DNS provider per ACME domain

### ISSUE THREAD

**Issue by MaikelH** [containous/traefik#2773] opened 2018-01-27 13:26 UTC
### Do you want to request a *feature* or report a *bug*?
feature

### What did you do?
Tried to set different a DNS provider for a domain in`acme.domains`

### What did you expect to see?

Currently it is only possible to set a global `dnsProvider` for `acme`. Since we have domains on different registries we would like to use a different `dnsProvider` for some domains. For an example how this could work see the example configuration below.

It would be nice if you could still set a default dnsProvider and then have the ability to override it in the `acme.domains` section.

```toml
    [acme]
    email = "test@test.com"
    storage = "acme.json"
    entryPoint = "https"
    onDemand = false
    dnsProvider = "route53"
    acmeLogging = true

    [[acme.domains]]
       main = "abc.com"
       sans = []

    [[acme.domains]]
      main = "1234.com"
      dnsProvider =  "namecheap"
      sans = []
```

In the example above `abc.com` will default to `route53` and `1234.com` will use the override (`namecheap`)

**Comment by ldez** [comment] 2018-01-27 14:32
Duplicate of #2710

**Comment by MaikelH** [comment] 2018-01-27 16:09
#2710 is not a duplicate of this issue. #2710 describes different `dnsProviders` per entrypoint, not per domain. 

In the config we use have only one `https` endpoint which serves multiple domains. The feature as described in #2710 will not solve the issue since we are still forced to use the same `dnsProvider` for all domains under that entrypoint.

**Comment by tehKapa** [comment] 2019-05-12 08:37
I’ve the same need. use the dns challenge with different providers

**Comment by ldez** [comment] 2019-05-14 08:08
Close in favor of #4872 - Feel free to subscribe there for updates.

**Closed by ldez** 2019-05-14 08:08 UTC
Labels: area/acme, kind/enhancement, priority/P3
