### ISSUE TITLE
ingressclass option fails when quoted

### ISSUE THREAD

**Issue by rabidsloth** [containous/traefik#5822] opened 2019-11-13 03:28 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

In the [docs](https://docs.traefik.io/providers/kubernetes-crd/#ingressclass) for the ingressclass option when running traefik, the example is to quote the value `--providers.kubernetescrd.ingressclass="traefik-internal"`, like it would be in the annotation. This doesn't seem to work if this value is quoted, only when I removed the quotes did traefik start picking up ingressRoutes with this annotation. 

Not sure if this is just a doc bug, or if it should work quoted.

### What did you expect to see?

Setting `--providers.kubernetescrd.ingressclass="some-custom-value"`
should pick up an IngressRoute with the annotation `kubernetes.io/ingress.class: "some-custom-value"`

### What did you see instead?

Traefik did not pick up the route until the quotes were removed from the Traefik configuration like this:
`--providers.kubernetescrd.ingressclass=some-custom-value`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.0.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
K8s deployment arg in question:
          args:
            - --providers.kubernetescrd.ingressclass=traefik-external

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by ldez** [comment] 2019-11-13 03:35
Duplicate of  #5797

If you are using the binary (not the Docker image) you can use the double quotes.
The double quotes are optional.

**Closed** 2019-11-13 16:12 UTC
Labels: resolution/duplicate
