### ISSUE TITLE
X-Forwarded-Proto is overwritten in traefik ≥ 1.6.x

### ISSUE THREAD

**Issue by Gabology** [containous/traefik#3886] opened 2018-09-14 04:11 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I noticed this issue when upgrading from traefik 1.5.4 to 1.6.x. Because many of our services started showing erratic behavior, with redirect loops or attemping to load resources from HTTP instead of HTTPS. 

We are running traefik inside of a docker cluster and we have an edge loadbalancer in Google Clodu that handles SSL termination. 

The cause of this seems to be that the `X-Forwarded-Proto` header is being rewritten by traefik in ≥ 1.6.x. 

This was easy to confirm when running the whoami service, this is the output when running it in our environment with traefik 1.5.4:

```
Hostname: ...
IP: ...
GET / HTTP/1.1
Host: ...
User-Agent: curl/7.54.0
Accept: */*
Accept-Encoding: gzip
Via: 1.1 google
X-Cloud-Trace-Context: ...
X-Forwarded-For: [MY_REMOTE_IP], 35.241.29.202, 130.211.1.223
X-Forwarded-Host: ...
X-Forwarded-Port: 80
X-Forwarded-Proto: https
X-Forwarded-Server: ...
X-Real-Ip: 130.211.1.223
```

And this is the same request running traefik 1.6.6

```
IP: ...
GET / HTTP/1.1
Host: ...
User-Agent: curl/7.54.0
Accept: */*
Accept-Encoding: gzip
Via: 1.1 google
X-Cloud-Trace-Context: ...
X-Forwarded-For: 130.211.1.224, 10.0.0.37
X-Forwarded-Host: ...
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: ...
X-Real-Ip: 130.211.1.224
```

Both the `X-Forwarded-For` and `X-Forwarded-Proto` are overwritten by traefik in 1.6.6 which leads to the issue. 

I am using the same entrypoint configuration for both versions, attached a snippet below:

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["130.211.0.0/22", "35.191.0.0/16"]
```

**Comment by jbdoumenjou** [comment] 2018-09-21 15:48
Hi @Gabology, I did not succeed in reproducing your issue.
I chained 2 Træfik in front of a whoami and tried some configurations (trustedIPs) and versions of Træfik (1.5.X, 1.6.X, 1.7.X).
 
<pre>
   +--------+ https +---------+ http +----------+ http +---------+
   | Client |+-----&gt;| Rproxy1 |+----&gt;| Rproxy2  |+----&gt;| Whoami  |
   +--------+       +---------+      +----------+      +---------+
    </pre>

* If Rproxy2 trusts the Rproxy1 ip, we will have `https`
 as X-Forwarded-proto
* If it doesn't trust the Rproxy1 ip, we will have `http` because we have an http connexion between Rproxy1 and Rproxy2

Could you check your trusted ips ?

**Comment by Gabology** [comment] 2018-09-24 03:54
Thanks for the quick reply @jbdoumenjou 

I played around a bit more with this and it seems to me that the behavior for determining client IP has changed in traefik 1.6.x from traefik 1.5.x.

FYI this is the configuration I tried with both 1.5.4 and 1.6.6.

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["130.211.0.0/22", "35.191.0.0/16"]
```

In 1.6.6. like I mentioned, that configuration will not trust the `X-Forwarded-*` headers. However adding the actual client IP that connected through the edge load balancer will work in 1.6.6. And on the contrary in 1.5.4 the above configuration where the trusted IP is the IP of the edge load balancer itself will work, but only trusting the actual client IP that connected through the edge load balancer will NOT work.

Is it possible that the default strategy for determining client IP has changed between 1.5.x and 1.6.x?

**Comment by jbdoumenjou** [comment] 2018-09-24 08:02
Could you try for the v1.6.6 :
```
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.whitelist]
      sourceRange = ["130.211.0.0/22", "35.191.0.0/16"]
      useXForwardedFor = true
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
```
This configuration seems to be different between the v1.5 and the v1.6 (https://github.com/containous/traefik/compare/v1.5...v1.6#diff-ec0634b59fe8a2e061034f6643634d74)

**Comment by Gabology** [comment] 2018-10-01 10:03
Hi @jbdoumenjou 

Yes, I can confirm that this works, but only if I set `useXForwardedFor` to false. Which seems to be also confirm my suspicion that traefik now uses another strategy for resolving the client IP.

Also it doesn't seem to be documented anywhere that this behavior has changed, so perhaps you should add that somewhere?

For me personally I don't see why whitelist has anything to do with the XFF headers however. That to me should just be about restricting access on the endpoint to certain CIDR ranges.

**Comment by jbdoumenjou** [comment] 2018-10-02 15:51
@Gabology, XFF is a way to keep the Client Ip though the proxies/load balancers.
So, it could be the source of the IP to check with the whitelist.
The ability to use it was added on the v1.6.0 https://github.com/containous/traefik/pull/3070

Indeed, it is a good idea to improve the documentation on this subject.

**Comment by aranair** [comment] 2019-06-11 20:50
@jbdoumenjou ..  so if I want traefik to forward headers only for a specific CIDR, I need to set it up inside `http.whitelist`, and not `http.forwardedHeaders > trustedIps`? Hmm, what if one needs to allow traffic from 2 CIDR ranges but only want headers forwarded for 1 of them, how would that work out?

**Comment by aranair** [comment] 2019-06-11 21:26
Also, is that setting congruent to that of `traefik.ingress.kubernetes.io/whitelist-source-range: "1.2.3.0/24, fe80::/16"` and `ingress.kubernetes.io/whitelist-x-forwarded-for: "true"` on the ingress level (for kubernetes setup)?

**Comment by jbdoumenjou** [comment] 2019-10-29 10:07
The [whitelist](https://docs.traefik.io/v2.0/middlewares/ipwhitelist/) mechanism and its documentation have been improved in v2.0, I close this issue accordingly.

**Closed by jbdoumenjou** 2019-10-29 10:07 UTC
Labels: area/documentation, kind/enhancement, priority/P3
