### ISSUE TITLE
Middleware 'lua script' for Traefik v2

### ISSUE THREAD

**Issue by Negasus** [containous/traefik#4702] opened 2019-03-31 16:41 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Proposal for create middleware for run lua scripts.

This can be used as a replacement for custom middlewares.
We will need to create several modules providing API. For example: http, log, cache, etc.
To show an example, I have already written the initial version with some API.

LUA script is here [gist](https://gist.github.com/Negasus/1e62649b1477a1fc1c8d4ed532be0de8)
Traefik config is here [gist](https://gist.github.com/Negasus/d61aeb53ce64fa2f7b26a5973d47b823)

Short video with an example of middleware 'LuaScript' is here ([YouTube](https://youtu.be/C2umw-3SplM))

If there is interest, we can discuss implementation details and API.

**Comment by ldez** [comment] 2019-03-31 18:54
Duplicate of #1336

**Comment by geraldcroes** [comment] 2019-04-01 14:18
As said before, I'll close the issue in favor of #1336

**Closed by geraldcroes** 2019-04-01 14:18 UTC
Labels: status/0-needs-triage
