### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by tipruzs** [containous/traefik#2673] opened 2018-01-08 10:16 UTC
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

When using traefik in front of dynamic web applications (e.g. nextcloud, speedtest) i see very high cpu usage up to 100%, when data is transferred (e.g. large downloads or speedtests).

Note: traefik and web apps run both in docker swarm

**Update 1:** disable compression on entrypoint. cpu usage still at 50-60% -  is this expected?

### What did you expect to see?

no cpu spikes (e.g. like general load balancers / reverse proxies)

### What did you see instead?

cpu rises up to 100% cpu load

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.5
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-12-06_10:16:48AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
services:
  traefik:
    image: ${IMAGE}:${RELEASE}
    environment:
      ACME_EMAIL: ${ACME_EMAIL}
      ACME_DEFAULT_HOST: ${ACME_DEFAULT_HOST}
    command:
      - --configfile=/run/secrets/traefik_admin
      - --loglevel=WARN
      - --checknewversion=false
      - --insecureskipverify=true
      - --defaultentrypoints=http,https
      - "--entrypoints=Name:http Address::80 Compress:true Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS Compress:true"
      - --acme
      - --acme.email=${ACME_EMAIL}
      - --acme.domains=${ACME_DEFAULT_HOST}
      - --acme.onhostrule
      - --acme.entrypoint=https
      - --acme.storage=/data/acme.json
      - --docker
      - --docker.watch
      - --docker.exposedbydefault=false
      - --docker.swarmmode
      # - --debug
    networks:
     - traefik
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik:/data
    healthcheck:
      test: ["CMD-SHELL", "traefik healthcheck --web"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 30s
    deploy:
      restart_policy:
        condition: any
        delay: 2s
      update_config:
        monitor: 120s
        failure_action: continue
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=org_traefik"
        - "traefik.port=8080"
        - "traefik.protocol=http"
        - "traefik.frontend.rule=Host:${ACME_DEFAULT_HOST};PathPrefixStrip:/traefik"
    secrets:
      - traefik_admin
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

**Comment by timoreimann** [comment] 2018-01-08 10:36
Duplicate of #1064?

**Comment by Juliens** [comment] 2018-01-10 14:10
Can you try with the 1.5.0-rc4 ?

**Comment by Juliens** [comment] 2018-01-11 13:44
After some investigation, I isolated the piece of code that uses the CPU (by rewriting a simple reverse-proxy). And the culprit is `io.Copy` and more precisely the `syscall.Write` and `syscall.Read`. 

![perf](https://user-images.githubusercontent.com/195661/34828362-a2eabeb4-f6dd-11e7-9890-c0bddd4c1e22.png)

After some research it seems that this is a [known problem](http://golang-dev.narkive.com/1j39wawh/how-to-use-syscall-splice-call-instead-of-io-copy-during-copy-data-from-http-request-connection-for-
) and the solution coulb be to use `syscall.Splice`, but I don't think it is possible easily ( @mvertes )

**Comment by tipruzs** [comment] 2018-01-24 13:23
I retested with 1.5.0 and got similar cpu metrics.

**Comment by javydekoning** [comment] 2018-03-02 17:09
After migrating from `jwilder/nginx-proxy:latest` to Traefik v1.5.3 I run into the same issue. The CPU utilization spikes as soon as I open Grafana or similar through Traefik

**Comment by mo** [comment] 2018-03-12 08:30
I benchmarked haproxy vs traefik 1.5.3 this weekend and concluded that traefik takes quite a bit more CPU.

I believe haproxy avoids copying the data to user space (via IO splicing so that the kernel moves data directly from the read buffer to the write buffer). Can someone confirm that Traefik simply does not have this feature yet? Or could there by some general general "high CPU usage" bug in traefik that is worth chasing down?

**Comment by timoreimann** [comment] 2018-03-12 08:42
@Juliens any further thoughts on how to proceed here?

When in doubt, we should ask users to collect CPU profiles via pprof and analyze the data. My very own experience with benchmarking Traefik taught me that the performance behavior is very dependent on the existing configuration, i.e., which options are set and providers used.

**Comment by mo** [comment] 2018-03-12 11:46
If someone posts some instructions I'd be happy to do some profiling.

**Comment by Juliens** [comment] 2018-03-14 13:36
In fact, it could be the `syscall.Read / Write` problem, or it could be another problem with your configuration (as @timoreimann said).
We must analyze to be sure of the high CPU reason.


Here is how to get profiling data:

1. Start you traefik with `--debug` in command line or `debug=true` in toml file
2. Generate profile files (during Træfik is under load)
```bash
curl -o profile.pprof <traefik_ip>:8080/debug/pprof/profile    # CPU (takes 30 seconds to return)
curl -o heap.pprof <traefik_ip>:8080/debug/pprof/heap    
curl -o block.pprof <traefik_ip>:8080/debug/pprof/block    
curl -o mutex.pprof <traefik_ip>:8080/debug/pprof/mutex
curl -o goroutine.pprof <traefik_ip>:8080/debug/pprof/goroutine
curl -o trace.pprof <traefik_ip>:8080/debug/pprof/trace?seconds=5    # the seconds parameter is needed
```
3. Send us all the files you have generated

Thank you for your interest in Træfik.

**Comment by GaruGaru** [comment] 2018-03-14 17:10
Done the profiling on a test machine (cloud scaleway VC1S instance 2 core Intel Atom C2750 @ 2.40GHz) with traefik 1.5.3 running on docker  

[profiling.zip](https://github.com/containous/traefik/files/1812174/profiling.zip)

**Comment by mo** [comment] 2018-03-14 18:49
I collected a profile as well. Mine is from the smallest droplet on Digital Ocean (1 cpu, 1 GB RAM). While profiling I ran "wrk -c 6 -t 6 -d 999 ..." on it, causing constant 30% CPU usage in traefik v1.5.3 and 30% in my node webapp.

[pprof-mo-20180314.zip](https://github.com/containous/traefik/files/1812567/pprof-mo-20180314.zip)

**Comment by amq** [comment] 2018-03-18 17:42
Similar here. Traefik consumes more CPU than the backend PHP app and almost the same as MySQL.

I have observed this behavior since I started using Traefik at 1.3.x, it seems to be even a bit worse at 1.5.4

**Comment by Juliens** [comment] 2018-03-19 16:24
@GaruGaru @mo Thank you for this profiles, but can you add your traefik configuration?

**Comment by GaruGaru** [comment] 2018-03-19 16:57
@Juliens Edited my previous post with my configuration

**Comment by mo** [comment] 2018-03-19 17:24
@Juliens I have updated my comment above as well

**Comment by timoreimann** [comment] 2018-03-19 21:17
Looking at @GaruGaru's profile, it seems like most CPU cycles (43.25% sample time) are spent inside Go's `math` package for the purpose of TLS communication/handshaking:

```
(pprof) top
Showing nodes accounting for 16.46s, 72.86% of 22.59s total
Dropped 576 nodes (cum <= 0.11s)
Showing top 10 nodes out of 153
      flat  flat%   sum%        cum   cum%
     9.77s 43.25% 43.25%      9.77s 43.25%  math/big.addMulVVW
     1.94s  8.59% 51.84%     12.43s 55.02%  math/big.nat.montgomery
     1.67s  7.39% 59.23%      1.74s  7.70%  syscall.Syscall
     1.03s  4.56% 63.79%      1.03s  4.56%  runtime.memmove
     0.58s  2.57% 66.36%      0.58s  2.57%  math/big.mulAddVWW
     0.41s  1.81% 68.17%      1.90s  8.41%  math/big.nat.divLarge
     0.34s  1.51% 69.68%      0.34s  1.51%  runtime.usleep
     0.27s  1.20% 70.87%      0.27s  1.20%  crypto/sha256.block
     0.26s  1.15% 72.02%      0.26s  1.15%  math/big.subVV
     0.19s  0.84% 72.86%      0.19s  0.84%  math/big.shlVU
```

As a graph:

<img width="347" alt="garugaru-profile" src="https://user-images.githubusercontent.com/694826/37622261-8563c192-2bc1-11e8-8bf0-5935c53c037e.png">

It's hard for me to tell if those 44% CPU consumption that @GaruGaru reported are reasonable or not. (By the way, is that 44% per core or per entire machine?) It also depends on the request rate that those 50 concurrent users produced.

Is there a chance for you to disable TLS to see if it makes a difference?

**Comment by timoreimann** [comment] 2018-03-19 21:57
@mo's profile may be hard to interpret due to DEBUG level logging (as set automatically through `--debug`) dominating CPU time.

I submitted #3050 to fix that problem.

**Comment by timoreimann** [comment] 2018-03-19 21:59
@amq we need pprof profiles to make an assessment. Please see @Juliens' description [here](https://github.com/containous/traefik/issues/2673#issuecomment-373022820) on how to retrieve them.

**Comment by mo** [comment] 2018-03-20 19:45
@timoreimann I built 1.5.4 with your logging fix cherry picked, changed the logLevel to INFO in the config, and re-profiled. I got 40% CPU in node and 30% in traefik (and nothing in systemd this time because the log spam is gone).

[pprof-mo-20180320-traefik-1.5.4-without-debug-logging.zip](https://github.com/containous/traefik/files/1830940/pprof-mo-20180320-traefik-1.5.4-without-debug-logging.zip)

**Comment by ulope** [comment] 2018-04-05 21:01
Just to add an observation I recently made by accident:

I've been load-testing a certain backend application (doesn't matter which one for this) and also noticed very high traefik CPU load. However, switching the API client I've been using to use HTTP keep-alive dropped the CPU load to almost nothing. So it appears that establishing new connections is related to the high load.

**Comment by GaruGaru** [comment] 2018-04-06 10:24
Nice find @ulope i repeated the same test with and without keepalive and i've got the following results:

With keepalive
```
siege -r 100  -c 50  -R <(echo connection = keep-alive) "<service>"

Transactions:		        5000 hits
Availability:		      100.00 %
Elapsed time:		        3.23 secs
Data transferred:	        0.09 MB
Response time:		        0.03 secs
Transaction rate:	     1547.99 trans/sec
Throughput:		        0.03 MB/sec
Concurrency:		       48.73
Successful transactions:           0
Failed transactions:	           0
Longest transaction:	        0.44
Shortest transaction:	        0.00
```

Without keepalive

```
siege -r 100  -c 50  "<service>"

Transactions:		        5000 hits
Availability:		      100.00 %
Elapsed time:		       64.36 secs
Data transferred:	        0.09 MB
Response time:		        0.07 secs
Transaction rate:	       77.69 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		        5.08
Successful transactions:           0
Failed transactions:	           0
Longest transaction:	        0.56
Shortest transaction:	        0.00
```

**Comment by amq** [comment] 2018-06-03 11:42
Things have gotten worse in 1.6, I wish you would give more love towards performance soon, because it is not that far away till your space is overtaken by Envoy or some Nginx cloud-native advancements.

**Comment by cregev** [comment] 2018-06-24 19:02
We have recently upgraded to Traefik version 1.6.4 and the CPU usage increased dramatically.
<img width="774" alt="screen shot 2018-06-24 at 21 53 04" src="https://user-images.githubusercontent.com/7669819/41822552-391367f4-77fa-11e8-8774-5632f631842f.png">

**Comment by ldez** [comment] 2018-06-24 20:31
@cregev We must have more information to analyze the high CPU reason.

Could you give your configuration and do some profiling.

Here is how to get profiling data:

1. Start you traefik with `--debug` in command line or `debug=true` in toml file
2. Generate profile files (during Træfik is under load)
```bash
curl -o profile.pprof <traefik_ip>:8080/debug/pprof/profile    # CPU (takes 30 seconds to return)
curl -o heap.pprof <traefik_ip>:8080/debug/pprof/heap    
curl -o block.pprof <traefik_ip>:8080/debug/pprof/block    
curl -o mutex.pprof <traefik_ip>:8080/debug/pprof/mutex
curl -o goroutine.pprof <traefik_ip>:8080/debug/pprof/goroutine
curl -o trace.pprof <traefik_ip>:8080/debug/pprof/trace?seconds=5    # the seconds parameter is needed
```
3. Send us all the files you have generated

Thank you for your interest in Træfik.

**Comment by cregev** [comment] 2018-06-25 12:19
[traefik_cpu_issue.zip](https://github.com/containous/traefik/files/2133021/traefik_cpu_issue.zip)
Attached the pprof files

**Comment by emilevauge** [comment] 2018-07-03 09:12
@cregev Any chance to test with 1.6.3? We suspect a potential cause in 1.6.4. Thanks for your help :)

**Comment by Falx** [comment] 2018-09-19 14:14
Is there any update on this topic, we also suffer greatly from this. We use traefik as k8s ingress and after a few days, cpu io-wait spikes up to 90% in our monitoring tools and cripples the whole microservice platform.

**Comment by Falx** [comment] 2018-09-19 15:00
> @Falx Do you have a memory limit set in your pod? The issue could be related to this. I once noticed high CPU usage after certain requests and it simply turned out that there was a lot of pod’s swap IO due to memory limits set my default in the helm chart.
> 
> problem: [#1908 (comment)](https://github.com/containous/traefik/issues/1908#issuecomment-328343800)
> 
> solution: [#1908 (comment)](https://github.com/containous/traefik/issues/1908#issuecomment-328892261)

Thank you very much for this information. We've updated our memoryLimit in the helm chart to 100Mi and will see in the coming days!

**Comment by kachkaev** [comment] 2018-09-19 15:33
This memory limit in the helm chart is a pretty painful default – your team is not the first one that has been hurt by it. I tried to lobby [a change in the chart values](https://github.com/helm/charts/issues/2098) a while ago, but no luck to this date.

Now, given that the official helm chart is maintained by traefik team directly, feel free to propose a change in the defaults if you agree with me that this is reasonable. IMO the compound time spent on upgrading from chart v1 to v2 is far less than the effort needed to tackle this IO nightmare people randomly enter. It took me a while to figure out why traefik started killing my CPU, I felt desperate during the investigation 😞

**Comment by kachkaev** [comment] 2018-09-19 21:38
The issue is not specific to compression, it’s about resource usage in general. When you have compression, https, high load or any other resource-consuming factor, traefik goes over the default 20MiB ram limit and starts endlessly writing and reading from swap.

IMO the problem is that chart defaults are not picked correctly and this causes CPU madness in pretty standard conditions. I was in favor of changing the defaults and thus upgrading the chart to v2, but this proposal has not been accepted.

The result is that new traefik chart users fall into the same trap as me a year ago.

**Comment by Falx** [comment] 2018-09-19 21:46
Ok I see, so right now we increased the limit to 100Mi, but we will have to monitor if this is enough for our application. I am happy though that at least now we have a logical explanation for this weird behavior we've been seeing.

**Comment by clausndk** [comment] 2019-01-22 13:03
[profile.zip](https://github.com/containous/traefik/files/2782837/profile.zip)
I created a profile.

Our issue is migrating from a self implemented gateway, to Traefik.
FYI: We are using Service Fabric as our hosting environment.

Our own implementation did not use as much CPU in general, but after the upgrade, we have VM average CPU usage around 50%, where we came from 10-20% Avg. 

Can you help us analyse, since we wanted to move to Traefik for a standard product, but right now our own code is faster (Which I really doubt!).

Thanks for any pointers!

**Comment by Kindratte** [comment] 2019-03-13 09:38
> Looking at @GaruGaru's profile, it seems like most CPU cycles (43.25% sample time) are spent inside Go's `math` package for the purpose of TLS communication/handshaking:
> 
> ```
> (pprof) top
> Showing nodes accounting for 16.46s, 72.86% of 22.59s total
> Dropped 576 nodes (cum <= 0.11s)
> Showing top 10 nodes out of 153
>       flat  flat%   sum%        cum   cum%
>      9.77s 43.25% 43.25%      9.77s 43.25%  math/big.addMulVVW
>      1.94s  8.59% 51.84%     12.43s 55.02%  math/big.nat.montgomery
>      1.67s  7.39% 59.23%      1.74s  7.70%  syscall.Syscall
>      1.03s  4.56% 63.79%      1.03s  4.56%  runtime.memmove
>      0.58s  2.57% 66.36%      0.58s  2.57%  math/big.mulAddVWW
>      0.41s  1.81% 68.17%      1.90s  8.41%  math/big.nat.divLarge
>      0.34s  1.51% 69.68%      0.34s  1.51%  runtime.usleep
>      0.27s  1.20% 70.87%      0.27s  1.20%  crypto/sha256.block
>      0.26s  1.15% 72.02%      0.26s  1.15%  math/big.subVV
>      0.19s  0.84% 72.86%      0.19s  0.84%  math/big.shlVU
> ```
> As a graph:
> 
> <img alt="garugaru-profile" width="347" src="https://user-images.githubusercontent.com/694826/37622261-8563c192-2bc1-11e8-8bf0-5935c53c037e.png">
> 
> It's hard for me to tell if those 44% CPU consumption that @GaruGaru reported are reasonable or not. (By the way, is that 44% per core or per entire machine?) It also depends on the request rate that those 50 concurrent users produced.
> 
> Is there a chance for you to disable TLS to see if it makes a difference?

You're right, high cpu usage due to slow handshakes with default RSA4096 cert in traefik, check golang issue https://github.com/golang/go/issues/20058 . I change keytype to ECDSA  "--acme.keytype=EC256" and cpu usage back to normal.

**Comment by tboerger** [comment] 2019-09-30 11:11
Does this issue still apply to Traefik 2.0?

**Comment by dduportal** [comment] 2019-09-30 15:40
Hi @tboerger , the Traefik 2.0 GA version don't have this behaviour as far as we know (reference: #5294 was closed during the RC phase).

As this issue is old and hijacked by a lot of different users, we are closing it for triage cleanup.

Please feel free to open new issues with reproduction case if you are still having this behavior with latest Traefik v2.0. Thanks!

**Closed by dduportal** 2019-09-30 15:40 UTC
Labels: kind/bug/possible, priority/P2
