### ISSUE TITLE
SSL is not getting loaded with Ingress

### ISSUE THREAD

**Issue by getvivekv** [containous/traefik#6868] opened 2020-06-01 03:59 UTC
I tested with Traefik and Nginx ingress. Nginx works as expected with kubernetes ingress definition but traefik is not. 

```
kubectl create ns traefik-external
helm upgrade  --install  traefik-external traefik/traefik --namespace traefik-external -f external.yaml
```

_external.yaml_

```
additionalArguments:
  - "--providers.kubernetesingress.labelSelector=expose=external"
  - "--serversTransport.insecureSkipVerify=true"
```

I have a graylog installation. This was done using the [helm graylog chart](https://github.com/helm/charts/tree/master/stable/graylog). It creates an Ingress as follows

```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: graylog-web
  namespace: graylog-nonprod
  selfLink: /apis/extensions/v1beta1/namespaces/graylog-nonprod/ingresses/graylog-web
  uid: 21900903-1ca7-4576-b8cb-6df0375f1d47
  resourceVersion: '17046'
  generation: 1
  creationTimestamp: '2020-06-01T01:18:34Z'
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: graylog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: graylog
    app.kubernetes.io/version: '3.1'
    expose: external
    helm.sh/chart: graylog-1.6.6
  annotations:
    meta.helm.sh/release-name: graylog
    meta.helm.sh/release-namespace: graylog-nonprod
spec:
  tls:
    - hosts:
        - graylog-nonprod.mywebsite.com
      secretName: tdebusiness-ssl
  rules:
    - host: graylog-nonprod.mywebsite.com
      http:
        paths:
          - backend:
              serviceName: graylog-web
              servicePort: graylog
status:
  loadBalancer:
    ingress:
      - ip: 40.71.232.134
```

When I open my website it works for HTTP and not for HTTPS with traefik. However, it works correctly with Nginx ingress controller

**Comment by JonathanSerafini** [comment] 2020-06-01 15:46
I've noticed the same since upgrading to the latest version.
The Ingress resource creates a router for the HTTP route but not HTTPS. I've had to create a dedicated IngressRoute object to reinstate HTTPS.

**Comment by SantoDE** [comment] 2020-06-02 09:19
Hello @getvivekv,

thanks for your interest in the project.

Currently, that is  expected behavior.

We'll try to find a place to better document it.

In the mean time, I'll close this as a duplicate of #6764, as there is a solution included.

**Closed by SantoDE** 2020-06-02 09:19 UTC
Labels: status/0-needs-triage
