### ISSUE TITLE
Add support for the upcoming wildcard letsencrypt certificates

### ISSUE THREAD

**Issue by dimrozakis** [containous/traefik#2698] opened 2018-01-12 00:52 UTC
### Do you want to request a *feature* or report a *bug*?

feature

### Description

In my company, we use traefik with docker labels and letsencrypt for deployed production and internal apps. It works perfectly (with the exception of the recent issue with letsencrypt blocking tls-sni) for a relatively stable set of applications.

Apart from those production deployments, we often deploy temporary/test/demo/review apps. Basically any git branch of any app we're developing can be deployed at any time. We use this to run integration tests, manual testing by collaborators and to demo new versions or products to clients etc. In those scenarios, apps get started and deleted more often, causing us to hit rate limits by letsencrypt. These temporary apps are served under common a domain name (*.demo.example.com) using a wildcard DNS rule. On February, letsencrypt will add support for wildcard certificates. I was wondering if it's at all possible to leverage this wildcard letsencrypt certificate support in traefik.

What I had in mind is that **in addition** to the current letsencrypt support, one can define some wildcard letsencrypt certificates to be created (i think that only DNS challenge could be used for those), without being bound to any frontend. When a frontend defines a host rule, a new certificate should only be created (using the current letsencrypt mechanism) only if the hostname doesn't match that of a wildcard certificate.

Does that make sense? Is that something you think is feasible and be interested in supporting in traefik?

**Comment by ldez** [comment] 2018-01-12 01:41
Duplicate of #2674

**Closed by ldez** 2018-01-12 01:41 UTC
