### ISSUE TITLE
Logfile rotation for Windows.

### ISSUE THREAD

**Issue by avendretter** [containous/traefik#5390] opened 2019-09-16 11:29 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Since windows is not able to handle Kill command and/or sending SIGUSR1, I need to figure out how to rotate the logs. I tried with a python script but it keeps failing because traefik locks the logfile - as expected. 

So for Linux this script solution works but not for windows. Any recommendations/solutions for rotating the logfiles on windows besides adding the logrotate feature are welcome!

Best regards!

**Comment by dduportal** [comment] 2019-09-16 14:27
Hello, thanks for your feedback. We are closing this issue as duplicate of #3489.

**Closed by dduportal** 2019-09-16 14:27 UTC
Labels: status/0-needs-triage

**Comment by avendretter** [comment] 2019-09-18 07:42
@dduportal Thanks for the reply. Well this not really a duplicate but more an extension. In #3489 the possibility of third-party log handling is discussed. But what I need is a possibility for log rotations in Windows not a third-party tool.

**Comment by dduportal** [comment] 2019-09-18 09:58
Hi @avendretter I apologize as my previous comment was written a bit too fast.

The aforementioned issue (#3489) is about supporting log rotation at binary level. The use case described is different than yours, but the root problem is the same and could be formulated like this: "If you cannot send an USR1 signal to the Traefik binary, how can one trigger a log rotation?".

Would you mind adding a comment in #3489 explaining the use case you wrote here please?

The reasons for the "closed as duplicate + weight on the other issue" is simple: it ease tracking such feature requests for the contributing team.

Thanks a lot for your understanding!

**Comment by avendretter** [comment] 2019-09-23 08:32
> Would you mind adding a comment in #3489 explaining the use case you wrote here please?
sure no problem! Thanks for coming back to me and my issue ;)

**Comment by dduportal** [comment] 2019-09-23 09:17
@avendretter no problem, it's the least we could do :) 👍
