### ISSUE TITLE
Automatic DNS records with API

### ISSUE THREAD

**Issue by vc7ee** [containous/traefik#4942] opened 2019-06-10 11:53 UTC
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?

Below a huge list of records I noticed an API feature in CloudFlare. **What if Traefik would automatically create DNS records it needs?**
(lists them periodically, if it sees a new (sub)domain, then it adds it), both A and AAAA records, including the www.domain.

If it sees an unused domain in the machine's ip, it deletes it in x time when unused.

By only deleting records created by the same Traefik, it ensures it doesn't delete records created by other machine or human. Alternatively a txt record may solve the issue.

**Comment by ldez** [comment] 2019-06-10 12:03
Duplicate of #1287

**Closed** 2019-06-10 12:04 UTC
Labels: status/0-needs-triage
