### ISSUE TITLE
Ingress gets treated as a router

### ISSUE THREAD

**Issue by Furragen** [containous/traefik#5866] opened 2019-11-19 08:44 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I have a kubernetes cluster on which we are testing the upgrade to Traefik 2.0.
We upgraded the config of Traefik to 2.0, switched the image and the containers start normally.

### What did you expect to see?
1. Upgrade the config
2. Ingresses work just like before
3. Profit

### What did you see instead?
Somehow in the logs I can see that internally Traefik tries to convert ingress-objects to routers, middlewares and services?

Logentries like this come up:
```
level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [metrics ping web websecure]" routerName=someingress@kubernetes
Creating middleware" routerName=someingress@kubernetes serviceName=someingresssvc-http middlewareName=pipelining middlewareType=Pipelining entryPointName=websecure
```

The logs look like ingresses actually are received by Traefik but than handled as routers, which does not work at all, because Traefik does not know which endpoints it should connect the ingresses to.

The question is, why does this happen?
I expected the application traffic to just get routed to the containers like before when using ingress.
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version 2.0.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
log:
  level: DEBUG
providers:
  kubernetesIngress: {}
entryPoints:
  ping:
    address: ":9090"
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":7070"
ping:
  entryPoint: "ping"
metrics:
  prometheus:
    entryPoint: metrics
api:
  dashboard: true
tls:
  stores:
    default:
      defaultCertificate: (this setting gets ignored by the way)
        certFile: /tls.crt
        keyFile: /tls.key
http:
  routers:
    api:
      rule: Host(`some.host.com`)
      entrypoints:
        - websecure
      service: api@internal
      middlewares:
        - auth
      tls: {}
  middlewares:
    auth:
      basicAuth:
        users:
          - 'foo:bar'
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```

```

**Comment by dduportal** [comment] 2019-11-19 09:51
Hi @Furragen , can you check the migration guide at https://docs.traefik.io/v2.0/migration/v1-to-v2/ and switch to the community forum at https://community.containo.us/ where the discussion can take place please?

This issue is not considered as a bug, since Traefik v2.0 supports for Kubernetes Ingress is minimalistic as explained in the documentation: you have to switch to the new CRD `IngressRoute` instead.

By the way, the "router", "entrypoints" and "service" concepts are Traefik objects, so any "Ingress" or "IngressRoute" Kubernetes Objects is mapped by Traefik to its internal concepts: it is the same as any other Ingress controllers (Nginx converts "Ingress" to "vhosts" and "server" for instance).

**Comment by Furragen** [comment] 2019-11-19 11:19
Hi @dduportal ,
I checked that guide and while reading the rest of the docs got the impression that ingress is still very much supported and I could just switch over to 2.0 if I updated the config.

And since Traefik is an _ingress-controller_ I very much think that this is a bug if ingress is not really supported anymore. I mean this basically prevents anyone using your ingress-controller from using any 3rd-party helm-chart.

Also, how should I use ingress now if I can't really tell traefik which endpoint should be used for an ingress? Because at the moment it just randomly assigns endpoints to ingress.

**Comment by ldez** [comment] 2019-11-19 11:22
Duplicate of #5624

**Comment by Furragen** [comment] 2019-11-19 11:22
This is not a duplicate.
I just added in my last sentence a point that was made in another issue.

**Closed by ldez** 2019-11-19 11:22 UTC
Labels: kind/question

**Comment by ldez** [comment] 2019-11-19 11:27
> This issue is not considered as a bug, since Traefik v2.0 supports for Kubernetes Ingress is minimalist as explained in the documentation: you have to switch to the new CRD IngressRoute instead.

Traefik v2 support Ingress, but v2 doesn't support any annotations on Ingress.

**Comment by Furragen** [comment] 2019-11-19 11:32
But only one Ingress works.
And judging by the logs it works only because Traefik randomly decided to give map it to the right entrypoint.
Which leads me to think that ingress is actually not really supported anymore since you do not have control about where the traffic is routed.

**Comment by dduportal** [comment] 2019-11-19 16:24
Hi @Furragen can you switch the discussion to the community forum to get the most of the community answers and help please? Don't hesitate to mention me in the forum :)
