### ISSUE TITLE
[feature request] entrypoint provide tcp mode beside of http and https?

### ISSUE THREAD

**Issue by rmrf** [containous/traefik#2450] opened 2017-11-22 10:35 UTC
I really like traefik which I have already using it for our https related project. 

I'm looking forward entryPoint can provide tcp mode beside of http and https, then I can use it inside our Container Cluster for LB.  currently we are using haproxy and nghttp for this kind of job. 

does tcp mode on the roadmap ?

**Comment by Juliens** [comment] 2017-11-22 11:43
Duplicate of #10

**Closed by Juliens** 2017-11-22 11:43 UTC
