### ISSUE TITLE
traefik fails to initialize second TLS endpoint

### ISSUE THREAD

**Issue by jaychris** [containous/traefik#2294] opened 2017-10-20 16:49 UTC
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
I asked this on slack, but I feel like this is more likely a bug.  In looking for a workaround to [#2288](https://github.com/containous/traefik/issues/2288), I attempted to setup a second TLS enabled endpoint, running on a different port.

However, this didn't work, returning a TLS error:  

```(35) gnutls_handshake() failed: An unexpected TLS packet was received.```

When I enabled debug and examined the Traefik output, I found that it appears that Traefik is not enabling TLS on the second endpoint.

### What did you expect to see?
I expected to see a new TLS endpoint setup, using the certificates provided

### What did you see instead?
The endpoint did not have TLS enabled.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.4.0-rc4
Codename:     roquefort
Go version:   go1.9
Built:        2017-10-02_02:19:32PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "Debug"
defaultEntryPoints = ["https", "gemini"]
[entryPoints]
  [entryPoints.https]
  address = ":443"
  clientCAFiles = ["certs/platform-ca.crt"]
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    certFile = "certs/server.crt"
    keyFile = "certs/server.key"
  [entrypoints.gemini]
  address = ":8443"
  [entryPoints.gemini.tls]
    [[entryPoints.gemini.tls.certificates]]
    certFile = "certs/gemini.crt"
    keyFile = "certs/gemini.key"

[web]
address = ":8080"

[consulCatalog]
endpoint = "172.17.0.1:8500"
exposedByDefault = false
prefix = "traefik"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
INFO[2017-10-20T16:19:13Z] Preparing server gemini &{Network: Address::8443 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:false} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s
INFO[2017-10-20T16:19:13Z] Preparing server https &{Network: Address::443 TLS:0xc420648c60 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:false} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s
INFO[2017-10-20T16:19:13Z] Starting server on :8443
INFO[2017-10-20T16:19:13Z] Starting server on :443
INFO[2017-10-20T16:19:13Z] Server configuration reloaded on :8443
INFO[2017-10-20T16:19:13Z] Server configuration reloaded on :443
```

Note the "TLS: nil" entry for the server setup on port 8443.

**Comment by ldez** [comment] 2017-10-20 17:16
Thanks for reporting 👍 

Could you try with latest release (1.4.0)?

**Comment by jaychris** [comment] 2017-10-20 17:40
looks like the same issue still:

```
Version:      v1.4.0
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-16_04:52:07PM
OS/Arch:      linux/amd64
```

```
INFO[2017-10-20T17:38:38Z] Preparing server gemini &{Network: Address::8443 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4201d2220} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s
INFO[2017-10-20T17:38:38Z] Preparing server https &{Network: Address::443 TLS:0xc4204f84e0 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4201d22c0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s
INFO[2017-10-20T17:38:38Z] Starting server on :8443
INFO[2017-10-20T17:38:38Z] Starting server on :443
INFO[2017-10-20T17:38:38Z] Server configuration reloaded on :8443
INFO[2017-10-20T17:38:38Z] Server configuration reloaded on :443
```

**Comment by nmengin** [comment] 2017-10-23 07:50
@jaychris 

I tried to reproduce the problem with both `master` and `v1.4` branches and finally I did it!
I think it's due to a *typo* in your configuration file. 

Indeed, you defined the `HTTPS entrypoint` as `[entryPoints.https]` and `gemini entrypoint` as `[entrypoints.gemini]`. Apparently the problem comes from the downcase `p` in gemini entry**P**oint.

Can you try to use `[entryPoints.gemini]` tag? TOML is not key sensitive but if a tag is defined with uppercase all others sub tags or others  tags from a list have to respect the uppercases.

Moreover, your `clientCAFiles = ["certs/platform-ca.crt"]` parameter has to be set in the `[entryPoints.https.tls]` section to work correctly.

You can try the configuration described below : 

```toml
logLevel = "Debug"
defaultEntryPoints = ["https", "gemini"]
[entryPoints]
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    clientCAFiles = ["certs/platform-ca.crt"]
    [[entryPoints.https.tls.certificates]]
    certFile = "certs/server.crt"
    keyFile = "certs/server.key"
  [entryPoints.gemini]
  address = ":8443"
  [entryPoints.gemini.tls]
    [[entryPoints.gemini.tls.certificates]]
    certFile = "certs/gemini.crt"
    keyFile = "certs/gemini.key"

[web]
address = ":8080"

[consulCatalog]
endpoint = "172.17.0.1:8500"
exposedByDefault = false
prefix = "traefik"
```

I let you give us a feddback and close the issue if the solution is ok for you.

**Comment by jaychris** [comment] 2017-10-23 17:05
argh, yes, so sorry about that.  It works fine once the typo is fixed.  

FWIW, the clientCAFiles line seems to work correctly under [entryPoint.https] or [entryPoint.https.tls] in the same manner.  At least, I get a challenge for a client certificate either way.

**Comment by ldez** [comment] 2017-10-23 17:42
I'll close this issue, because I think the question is answered.

**Closed by ldez** 2017-10-23 17:42 UTC
Labels: area/provider/consulcatalog, area/tls, contributor/waiting-for-feedback, status/0-needs-triage

**Comment by nmengin** [comment] 2017-10-24 06:08
OK @jaychris .

Indeed, `clientCAFiles` can be to differents places.
Thanks for the feedback. I close the issue.
