### ISSUE TITLE
Disable or filter TLS from error logs

### ISSUE THREAD

**Issue by MichaelErmer** [containous/traefik#2319] opened 2017-10-25 09:19 UTC
### Do you want to request a *feature* or report a *bug*?

*feature*

### What did you do?

Run traefik with logLevel ERROR

### What did you expect to see?

logs about severe errors

### What did you see instead?

100-300x per second `server.go:2848: http: TLS handshake error`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.4.0 / roquefort
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
docker swarm
```

**Comment by mmatur** [comment] 2017-10-25 09:34
Duplicate of #1827

**Closed** 2017-10-25 09:35 UTC
Labels: area/tls, status/0-needs-triage

**Comment by MichaelErmer** [comment] 2017-10-25 09:40
Oh yes, the line number changed...
