### ISSUE TITLE
Show TLS certificate status on Dashboard

### ISSUE THREAD

**Issue by JulesTriomphe** [containous/traefik#7161] opened 2020-08-11 16:46 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I think the dashboard can be improved by adding some information on TLS:
- It would be nice to know whether Traefik has received the certificate from LE, whether it's using its own default certificate or whether it's using user defined certificates for each service.
- It would also be nice to have the certificate expiry date.
- Finally, it would be nice to have the main and sans information.

**Comment by ldez** [comment] 2020-08-11 16:50
Duplicate of #6156

**Closed by ldez** 2020-08-11 16:50 UTC
Labels: resolution/duplicate
