### ISSUE TITLE
Buffering middleware breaks `chunked` encoded requests

### ISSUE THREAD

**Issue by vojtad** [containous/traefik#7930] opened 2021-02-24 22:18 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We have deployed server from [discourse/prometheus_exporter](https://github.com/discourse/prometheus_exporter) behind Traefik.
Its client uses `Transfer-Encoding: chunked` to stream data to server. Each chunk is a valid JSON object.
Server reads these chunks, decodes JSON objects and process them.

### What did you expect to see?

We expected server to correctly parse JSON objects from each chunk sent by a client.

### What did you see instead?

Client requests are somehow buffered by Traefik and chunks are merged together in bigger chunks. This results in an invalid JSON since multiple JSON objects are simply concatenated as strings.
Server is not able to parse requests sent by a client when it is behind Traefik.

I believe this is could be due to Buffering middleware. Is there any way to alter this behaviour and pass chunks as they were originally sent to Traefik?

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.5
Codename:     livarot
Go version:   go1.15.8
Built:        2021-02-18T17:21:25Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

We run Traefik using docker-compose with docker provider set to discover services.

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[certificatesResolvers.lets-encrypt.acme]
  email = "admin@example.com"
  storage = "/acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[providers.docker]
  watch = true
  exposedByDefault = false
  network = "traefik"

[providers.file]
  filename = "/traefik_dynamic.toml"
```

**Comment by vojtad** [comment] 2021-02-24 22:25
Changed the bug report, originally I said `Transfer-Encoding: chunked` HTTP header was removed. That's not true, but chunks are concatenated together. Sorry about that, my bad.

**Comment by vojtad** [comment] 2021-02-26 21:57
I've found a workaround for this issue. I didn't think of it before.

I've used a TCP router instead of a HTTP router for this service and it is working just fine now.

**Comment by fredsig** [comment] 2021-11-12 16:35
Setting maxRequestBodyBytes also breaks chunked responses from the server. In my case, the origin server is streaming a csv file (as it's being generated) and we have observed Traefik caching the file locally before sending it back to the client (client connection times out because of the IdleTimeout setting of the ALB that sits in front of Traefik).

**Comment by cdemi** [comment] 2023-10-17 06:27
Does anyone know if this issue is still present in 2.10.5? I suspect I am hitting this same issue. 

If buffering middleware is present, Traefik waits for all the chunks before sending them to the client

**Comment by nmengin** [comment] 2023-10-19 12:30
Hey @cdemi,

Thanks for reaching out.

Could you provide a minimal reproducible case (for instance, full Kubernetes manifest to reproduce the issue)?
In the meantime, if any community member can help us find verified steps to reproduce, we would love the help.

**Comment by KimiJL** [comment] 2024-05-31 20:50
Facing the same issue.

running traefik 2.8.4 and fastapi+gunicorn

The streaming chunked response coming from the StreamingResponse interface breaks when buffering middleware is present. Once removed the stream is working as expected.

'Transfer-Encoding': 'chunked' is missing from the response header when buffering middleware was enabled with maxRequestBodyBytes

**Comment by nmengin** [comment] 2024-06-03 12:48
Hey @KimiJL,

Could you give it a try with Traefik v2.11?

**Comment by daymien** [comment] 2024-06-26 08:26
Hi @nmengin 

Issue remains for Traefik v2.11 + gunicorn + fastapi.
I use some similar setup then @KimiJL 

Settings for docker gunicorn + fastapi container
`
labels:
      traefik.enable: true
      traefik.http.routers.ai-api.rule: Host(`*****`)
      traefik.http.routers.ai-api.tls: true
      traefik.http.routers.ai-api.tls.certresolver: lb
      traefik.http.services.ai-api.loadbalancer.server.port: 5000
`

curl output of StreamingResponse interface via traefik 2.11 (same for 2.9)
`
< HTTP/2 200
< content-type: text/plain; charset=utf-8
< date: Wed, 26 Jun 2024 08:05:57 GMT
< server: uvicorn
<
some fake video bytes
some fake video bytes
`

curl output of StreamingResponse interface _without_ traefik 2.11
`
< HTTP/1.1 200 OK
< date: Wed, 26 Jun 2024 08:23:27 GMT
< server: uvicorn
< content-type: text/plain; charset=utf-8
< transfer-encoding: chunked
<
some fake video bytes
some fake video bytes
some fake video bytes
`

**Comment by nmengin** [comment] 2024-06-26 08:59
Hey @daymien,

Thanks for the additional information.
If any community member can help us to move forward on it, we would love the help.

**Comment by daymien** [comment] 2024-06-26 11:10
Hi @nmengin,

looks like at least my issue is not related to traefik but rather on my insufficient understanding on how fastapi handles async yielding functions.

If I turn `async def srt_stream(segments):` into `def srt_stream(segments):` synchronous function, it works just fine with traefik 1.7 and 2, 9, 2.11.

response header stay the same as in previous comment, but everything works as expected. Sorry for bothering. 

```
def srt_stream(segments_iter):
    for segment in segments_iter:
        return segment

@router.post("/")
async def create_transcription(
   ...
   return StreamingResponse(
        srt_stream(segments),
        media_type="text/plain"
    )
```

**Comment by KimiJL** [comment] 2024-06-28 14:18
@nmengin Hey, just saw, @daymien great catch, will definitely give it a try thank you

**Comment by nmengin** [comment] 2024-07-01 08:30
Hello @KimiJL,

Thank you for your answer.
If your issue is solved following @daymien input, please close the issue after your tests.

**Closed as completed** 2024-08-31 00:00 UTC
Labels: kind/bug/possible, area/middleware, contributor/waiting-for-feedback, status/5-frozen-due-to-age, contributor/wanted
