### ISSUE TITLE
Default custom 404 pages

### ISSUE THREAD

**Issue by LM1LC3N7** [containous/traefik#4633] opened 2019-03-19 16:20 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

On the last version this is possible to create custom error pages (404, 502, etc.) **per frontend**.
But there is no way to customize the default 404 page (for example).

Scenario example:
1. I am deploying a new website with a subdomain
2. I create a new DNS entry and try to reach the server (traefik)
3. I get a 404 page, this page that I would like to customize

Something like that would be great:

```bash
 [entryPoint]
  [entryPoints.http]
    address = ":80"
   [errors]
     status = "[500-600]"
     backend = "error"
     query = "/{status}.html"

  [entryPoints.https]
    address = ":443"
   [errors]
     status = "[500-600]"
     backend = "error"
     query = "/{status}.html"
```

Or at root level:

```bash
debug = false
checkNewVersion = true
logLevel = "INFO"
defaultEntryPoints = ["https","http"]
defaultErrorsStatus = "404, [500-600]"
defaultErrorsBackend = "error"
defaultErrorsQuery = "/{status}.html"
```

**Comment by ldez** [comment] 2019-03-19 20:46
Seems like a duplicate of #4218

**Comment by LM1LC3N7** [comment] 2019-03-19 21:16
Yes indeed. But I can see that there is no new official elements about it.

**Comment by guillaumebriday** [comment] 2019-03-20 08:40
If there are no new official elements about it, I think it's because they are working on more important features. Labels on #4218 are "enhancements" and "priority/p3".

It might come later, we just need to be patient. 👍 

I created a workaround explained on my issue if you really need it now 👌

**Comment by LM1LC3N7** [comment] 2019-03-20 09:00
> If there are no new official elements about it, I think it's because they are working on more important features. Labels on #4218 are "enhancements" and "priority/p3".

Of course there is more important features 😃 
I am migrating from [nginx](https://github.com/jwilder/nginx-proxy) to traefik and I can see some features missing (for me), do you know if some of them are planned?
* Transparent (reverse)proxy 
* Custom config to bind local services (on host and in docker containers)
* And custom error pages of course

> I created a workaround explained on my issue if you really need it now 👌

I saw it and will try soon, thanks for sharing!

**Comment by geraldcroes** [comment] 2019-03-20 15:25
Hi and thank you for your request (and patience 👍 )!

As said in the thread, we will close your issue in favor of #4218

**Closed by geraldcroes** 2019-03-20 15:25 UTC
Labels: status/0-needs-triage
