### ISSUE TITLE
Entrypoint redirect or RedirectToScheme middleware targeting entrypoint ?

### ISSUE THREAD

**Issue by NatMarchand** [containous/traefik#5236] opened 2019-08-21 12:49 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently in traefik 1.7.x, it is possible to enforce HTTPS with the current configuration
```
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
```
With 2.0 version, it's a little bit more complicated : it's mandatory to define a router and a service in order to add a RedirectToScheme middleware which takes a port as parameter.

I would like either to define the redirect at the entrypoint level (for HTTP of course) or at least be able to define an entrypoint to redirect to in the middleware (instead of a port value).
I totally understand that the first might be hard to do as I suppose that at entrypoint time, there's no knowledge of the underlying protocol yet.

**Comment by ldez** [comment] 2019-08-21 15:07
Duplicate of #4863

**Closed by ldez** 2019-08-21 15:07 UTC
Labels: status/0-needs-triage
