### ISSUE TITLE
Can it support bandwidth limitation?

### ISSUE THREAD

**Issue by seepine** [containous/traefik#11138] opened 2024-09-29 15:33 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

For example, if the route is configured with `limit-rate: "1024k"`, then the IP speed limit of the route is restricted to a speed of 1MB/s.
If the route is configured with `global-limit-rate: "10240k"`, then the total bandwidth of the route is restricted to a speed of 10MB/s.

**Comment by rtribotte** [comment] 2024-09-30 12:41
Hello @seepine,

Thanks for opening this, but this feature is already tracked with https://github.com/traefik/traefik/issues/4703.

We are closing this one accordingly.

duplicate of #4703

**Closed as completed by rtribotte** 2024-09-30 12:41 UTC
Labels: resolution/duplicate, status/5-frozen-due-to-age
