### ISSUE TITLE
 Compress middleware - allow to skip autoDetect for MIME Content-Type

### ISSUE THREAD

**Issue by PeterFalken** [containous/traefik#7267] opened 2020-09-09 02:43 UTC
Feature request.

Similar to the fix that was put in place for #4761, that allows the autoDetection to be skipped on the ContentType middleware.
Would it be possible to allow the auto detection to be skipped when using the Compress middleware. When the Content-Type is not set for the files to be compressed the middleware classifies them as text/plain sometimes disalbing the page or content to be rendered correctly.

I did put a comment on #7012, but didn't get a reply.

**Comment by ldez** [comment] 2020-09-09 06:27
Duplicate of #6810

**Closed by ldez** 2020-09-09 06:27 UTC
Labels: resolution/duplicate
