### ISSUE TITLE
TLS certificates expiry metrics

### ISSUE THREAD

**Issue by clain23** [containous/traefik#6323] opened 2020-02-16 21:07 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Metrics for every TLS cert used by Traefik.
Main metric - days until expiration, there may be others.

Idea inspired by https://github.com/sapcc/k8s-secrets-certificate-exporter

**Comment by ldez** [comment] 2020-02-16 21:17
duplicate of #6156

**Closed by ldez** 2020-02-16 21:17 UTC
Labels: resolution/duplicate
