### ISSUE TITLE
The acme migration tool does not set its output file permissions correctly by default

### ISSUE THREAD

**Issue by doctorpangloss** [containous/traefik#6860] opened 2020-05-29 05:02 UTC
The migration tool should set the permissions to the migrated `acme.json` to `600`, otherwise you'll spend an hour missing the error message in the logs like I did.

**Comment by notsureifkevin** [comment] 2020-05-29 11:53
related to #6825

**Comment by SantoDE** [comment] 2020-05-29 15:06
Actually, I think it's a duplicate of #6825. We should close that one :-)

**Closed by SantoDE** 2020-05-29 15:06 UTC
Labels: status/0-needs-triage
