### ISSUE TITLE
Traevik v2.1.0 rc3 Dashboard: Lists Only First 10 Routers

### ISSUE THREAD

**Issue by ystan-** [containous/traefik#5961] opened 2019-12-08 05:53 UTC
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
Create 11 IngressRoute CRDs and visit the Dashboard's HTTP Routers Page

### What did you expect to see?
11 of those routers listed, or the ability to page through them

### What did you see instead?
Only the first 10 routers listed. Some are from Traefik itself, like PathPrefix(`/api`).
The badge count on top looks correct, reporting HTTP Routers (14).
The previous/next page buttons on the bottom of the list are disabled.
I see the xhr call for `/api/overview` reporting correctly as well.
```
{
	"http": {
		"routers": {
			"total": 14,
			"warnings": 0,
			"errors": 0
		},
		"services": {
			"total": 14,
			"warnings": 0,
			"errors": 0
		},
		"middlewares": {
			"total": 3,
			"warnings": 0,
			"errors": 0
		}
	},
	"tcp": {
		"routers": {
			"total": 0,
			"warnings": 0,
			"errors": 0
		},
		"services": {
			"total": 0,
			"warnings": 0,
			"errors": 0
		}
	},
	"features": {
		"tracing": "",
		"metrics": "",
		"accessLog": true
	},
	"providers": ["KubernetesCRD"]
}
``` 

### Output of `traefik version`: (_What version of Traefik are you using?_)
v2.1.0 rc3

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Kubernetes Deployment with 1 replica
```
- --api
- --api.dashboard=true
- --api.insecure=true
- --serversTransport.insecureSkipVerify=true
- --accesslog=true
- --entrypoints.web.Address=:8000
- --entryPoints.web-secure.Address=:4443
- --entryPoints.web.forwardedHeaders.insecure
- --entryPoints.web-secure.forwardedHeaders.insecure
- --providers.kubernetescrd
- --certificatesResolvers.default.acme.httpChallenge.entryPoint=web
- --certificatesresolvers.default.acme.email=__my_email_address__
- --certificatesresolvers.default.acme.storage=/somewhere/acme.json
- --ping
- --log=true
```

**Comment by ldez** [comment] 2019-12-08 12:46
duplicate of #5959

**Closed by ldez** 2019-12-08 12:46 UTC
Labels: status/0-needs-triage
