### ISSUE TITLE
ACME got nothing

### ISSUE THREAD

**Issue by rahulwa** [containous/traefik#1687] opened 2017-05-31 11:01 UTC
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
Using traefik with ectd backened for load balancing on non container environment.
Trying to issue ssl cert for domain with `OnHostRule = true` config.
I am using etcd3 cluster.

### What did you expect to see?
I should be getting ssl cert.

### What did you see instead?
But instead i am getting `ACME got nothing test.verifymybiz.com` error.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.0-rc3
Codename:     raclette
Go version:   go1.8.2
Built:        2017-05-24_01:39:53PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```json
{
 "GraceTimeOut": 100000000000,
 "Debug": false,
 "CheckNewVersion": true,
 "AccessLogsFile": "/var/log/traefik/access.log",
 "TraefikLogsFile": "/var/log/traefik/traefik.log",
 "LogLevel": "DEBUG",
 "EntryPoints": {
  "http": {
   "Network": "",
   "Address": ":80",
   "TLS": null,
   "Redirect": null,
   "Auth": null,
   "Compress": false
  },
  "https": {
   "Network": "",
   "Address": ":443",
   "TLS": {
    "MinVersion": "",
    "CipherSuites": null,
    "Certificates": null,
    "ClientCAFiles": null
   },
   "Redirect": null,
   "Auth": null,
   "Compress": false
  }
 },
 "Cluster": null,
 "Constraints": [],
 "ACME": {
  "Email": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "Domains": null,
  "Storage": "traefik/acme/account",
  "StorageFile": "",
  "OnDemand": false,
  "OnHostRule": true,
  "CAServer": "",
  "EntryPoint": "https",
  "DNSProvider": "",
  "DelayDontCheckDNS": 0,
  "ACMELogging": true,
  "TLSConfig": null
 },
 "DefaultEntryPoints": [
  "http",
  "https"
 ],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 180000000000,
 "InsecureSkipVerify": true,
 "Retry": null,
 "HealthCheck": {
  "Interval": 30000000000
 },
 "Docker": null,
 "File": null,
 "Web": {
  "Address": ":8080",
  "CertFile": "",
  "KeyFile": "",
  "ReadOnly": true,
  "Statistics": null,
  "Metrics": null,
  "Path": "",
  "Auth": null
 },
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": {
  "Watch": true,
  "Filename": "",
  "Constraints": [],
  "Endpoint": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "Prefix": "/traefik",
  "TLS": null,
  "Username": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "Password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 },
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ConfigFile": "/opt/traefik.toml"
}
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```shell
time="2017-05-31T10:43:24Z" level=debug msg="Configuration received from provider etcd: {"backends":{"backend2":{"servers":{"server1":{"url":"http://prod.scantool.synup.com","weight":0}},"loadBalancer":{"method":"drr"}}},"frontends":{"frontend1":{"entryPoints":["http","https"],"backend":"backend2","routes":{"test_1":{"rule":"Host:test.internal.synup.com"},"test_2":{"rule":"Host:test.verifymybiz.com"}},"passHostHeader":true,"priority":0,"basicAuth":null}}}"
time="2017-05-31T10:43:24Z" level=info msg="Skipping same configuration for provider etcd"
time="2017-05-31T10:43:26Z" level=debug msg="Challenge GetCertificate test.verifymybiz.com"
time="2017-05-31T10:43:26Z" level=debug msg="ACME got nothing test.verifymybiz.com"
time="2017-05-31T10:43:28Z" level=debug msg="Cannot get key /traefik/alias Key not found in store, setting default /traefik"
time="2017-05-31T10:43:28Z" level=debug msg="Cannot get key /traefik/backends/backend2/circuitbreaker/expression Key not found in store, setting default "
time="2017-05-31T10:43:29Z" level=debug msg="Cannot get key /traefik/backends/backend2/loadbalancer/sticky Key not found in store, setting default false"
time="2017-05-31T10:43:29Z" level=debug msg="Cannot get key /traefik/backends/backend2/maxconn/amount Key not found in store, setting default "
time="2017-05-31T10:43:29Z" level=debug msg="Cannot get key /traefik/backends/backend2/maxconn/extractorfunc Key not found in store, setting default "
time="2017-05-31T10:43:29Z" level=debug msg="Cannot get key /traefik/backends/backend2/servers/server1/weight Key not found in store, setting default 0"
time="2017-05-31T10:43:29Z" level=debug msg="Cannot get key /traefik/frontends/frontend1/entrypoints Key not found in store, setting default empty"
time="2017-05-31T10:43:29Z" level=debug msg="Cannot get key /traefik/frontends/frontend1/passHostHeader Key not found in store, setting default true"
time="2017-05-31T10:43:29Z" level=debug msg="Cannot get key /traefik/frontends/frontend1/priority Key not found in store, setting default 0"
```

**Comment by rahulwa** [comment] 2017-05-31 19:01
It works perfectly fine if i remove etcd backed and use file backend.

**Comment by emilevauge** [comment] 2017-05-31 19:05
@rahulwa Closing this one as it's duplicate of #926.

**Closed by emilevauge** 2017-05-31 19:05 UTC
Labels: area/acme, kind/bug/possible
