### ISSUE TITLE
Access log settings at route level

### ISSUE THREAD

**Issue by sylr** [containous/traefik#6685] opened 2020-04-16 08:17 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be really helpful if access logs settings could be overridden at route level.

One use case would be to discard access logs for non error status codes on routes with high volumes.

Regards.

**Comment by ldez** [comment] 2020-04-17 15:00
duplicate of #6059

**Closed by ldez** 2020-04-17 15:00 UTC
Labels: resolution/duplicate
