### ISSUE TITLE
route traffic directly to the service endpoint with single ingress object

### ISSUE THREAD

**Issue by Shobhit29** [containous/traefik#5104] opened 2019-07-15 20:21 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I am trying to find a solution with traefik in kubernetes to route the request to the correct endpoint based on the service name from a common URL.

For Example:

URL: http://mydomain-internal.com/dcs-api2/abc:9050/v2/search

will send the request to the service endpoint (abc:9050) internally without knowing the client.

Regex: http://mydomain-internal.com/dcs-api2/(.*) URL_TO_CALL: http://$1 (http://abc:9050/v2/search)

I am trying to create the dynamic route based on the URL, so that I do not need to create new ingress objects & Host URL for each internal service.

**Comment by dduportal** [comment] 2019-07-16 15:38
Hi @Shobhit29 , the feature you are requesting is the same thing as #2282 : capability to reuse captured regex variable. The only difference is in your case, it would be reused for determining the backend's URL.

You might want to discuss that subject on our community forum: https://community.containo.us/ , as the reasons why you need a reverse proxy when providing the backend's domain have to be discussed, and the community might help.

I'm closing as a duplicate of #2282 for the feature request part.

**Closed by dduportal** 2019-07-16 15:38 UTC
Labels: status/0-needs-triage
