### ISSUE TITLE
Traefik rewriting HTTP status codes

### ISSUE THREAD

**Issue by adepretis** [containous/traefik#2365] opened 2017-11-06 15:13 UTC
### Do you want to request a *feature* or report a *bug*?

bug (?)

### What did you do?

Access an URL that results in a HTTP error code 403 (not authorized) in the backend - which is perfectly fine and OK! The underlying Angular application recognises the HTTP error code 403 and reacts accordingly (e.g. displaying a login window).

### What did you expect to see?

The login window and HTTP error code 403 for the corresponding request.

Traefik <- nginx <- python application
403 <- 403 <- 403

### What did you see instead?

A failing Angular application because traefik rewrites the HTTP error code 403 to 200 - which fucks up everything else.

Traefik <- nginx <- python application
200 <- 403 <- 403

### Output of `traefik version`:

```
bash-4.3$ traefik version
Version:      v1.4.1
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-24_05:25:28PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
debug = true
logLevel = "INFO"
traefikLogsFile = "/opt/traefik/log/traefik.log"
accessLogsFile = "/opt/traefik/log/access.log"
InsecureSkipVerify = false
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
       entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/opt/traefik/certs/foobar.crt"
      keyFile = "/opt/traefik/certs/foobar.key"

      [[entryPoints.https.tls.certificates]]
      certFile = "/opt/traefik/certs/traefik.crt"
      keyFile = "/opt/traefik/certs/traefik.key"

[web]
address = ":8000"
ReadOnly = false
[web.statistics]
RecentErrors = 10


[rancher]
domain = "rancher.internal"
Watch = true
RefreshSeconds = 15
ExposedByDefault = false
EnableServiceHealthFilter = true

[rancher.metadata]
IntervalPoll = false
Prefix = "/2016-07-29"

[file]
filename = "/opt/traefik/etc/rules.toml"
watch = true
```

**Comment by dtomcej** [comment] 2017-11-06 16:49
Can you please provide us with a snippet of the debug log while you are making these requests?

I am curious as to what gets logged when the backend status code of 403 is returned.

**Comment by dtomcej** [comment] 2017-11-06 16:50
@ldez is this possibly related to #2351 ?

**Comment by o1ek** [comment] 2017-11-06 19:23
We have the same issue. 
With traefik:1.4.0 is returning 202 until results from queries are ready, and then 200. With traefik:1.4.1 or traefik:1.4.2 in immediately returns 200 and empty results. 

Here is my config:
```
version: '3.3'

services:
  traefik:
    image: traefik:1.4.0
    command: -c --docker --docker.swarmmode --docker.domain=some.project.com  --docker.watch --web --acme --web.statistics --acme.storage=/etc/traefik/acme/acme.json --acme.email=some.project.com@gmail.com --acme.entryPoint=https --entryPoints='Name:http Address::80 Compress:on' --entryPoints='Name:https Address::443 TLS Compress:on' --defaultentrypoints=http,https --accessLog --acme.domains="some.project.com"
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/etc/traefik/acme
    networks:
      - appnet
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - 8080:8080
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1

networks:
  appnet:
    external: true

volumes:
  acme:
    driver: local
```

**Comment by adepretis** [comment] 2017-11-06 20:46
@dtomcej is this the information you are looking for (with ``debug=true`` and ``logLevel="DEBUG"``

```
time="2017-11-06T20:43:15Z" level=debug msg="Round trip: http://10.42.253.192:80, code: 403, duration: 3.900531ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:my.foodomain.com"
10.25.25.3 - - [06/Nov/2017:20:43:15 +0000] "GET /api/v1/packages HTTP/2.0" 403 27 "https://my.foodomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.30 Safari/537.36" 8 "Host-my-foodomain-com" "http://10.42.253.192:80" 4ms
```
```my.foodomain.com``` is not the real hostname of course ;-)

**Comment by adepretis** [comment] 2017-11-06 20:58
@dtomcej interesting detail I just discovered: when accessing the site with curl I get a correct 403 response - tried it with and without headers (same as Chrome, see below):

  * accept: application/json, text/plain, */*
  * accept-encoding: gzip, deflate, br

```
*   Trying 10.10.10.10...
* Connected to my.foodomain.com (10.10.10.10) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 596 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.foodomain.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=*.foodomain.com
* 	 start date: Tue, 18 Apr 2017 00:00:00 GMT
* 	 expire date: Sun, 17 Jun 2018 23:59:59 GMT
* 	 issuer: C=US,O=GeoTrust Inc.,CN=RapidSSL SHA256 CA - G2
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /api/v1/login HTTP/1.1
> Host: my.foodomain.com
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Content-Length: 27
< Content-Type: application/json; charset=utf-8
< Date: Mon, 06 Nov 2017 20:48:29 GMT
< Server: nginx
< Vary: Accept-Encoding
<
* Connection #0 to host my.foodomain.com left intact
```
When accessing through Chrome:

![screen shot 2017-11-06 at 21 51 42](https://user-images.githubusercontent.com/587018/32463481-45620cd0-c33d-11e7-853d-0c54cd2040f1.png)

The response in both cases contains: ```{"error": "Not authorized"}```

**Comment by ldez** [comment] 2017-11-07 09:57
Duplicate of #2351

**Closed by ldez** 2017-11-07 09:57 UTC
Labels: contributor/need-more-information, status/0-needs-triage
