### ISSUE TITLE
Support for multiple endpoints via TCP (+TLS) in Docker swarm mode

### ISSUE THREAD

**Issue by bintut** [containous/traefik#1709] opened 2017-06-05 14:52 UTC
Hi all,

I am requesting a feature to support multiple endpoints via TCP (+TLS) when using Docker swarm mode as its backend configuration to eliminate the possibility of a single point of failure when the Traefik tasks are running only on the worker nodes while the availability of the manager nodes are set to drain.

Thank you in advance.

Kind regards,

Marvin

**Comment by ldez** [comment] 2017-06-05 16:29
This is a duplicate of #10 - Feel free to subscribe there for updates.

**Comment by bintut** [comment] 2017-06-06 13:40
Hi @ldez,

This feature request is actually for configuring the `endpoint = "tcp://manager1.example.com:2376"` as per the [Docker backend](https://docs.traefik.io/toml/#docker-backend) configuration when talking to the Docker API in swarm mode via TCP (+ TLS) and not the TCP (+ TLS) load balancing to the backend servers.

The use case is, Traefik tasks (containers) are running on the worker nodes and the manager nodes are set their availability to [drain](https://docs.docker.com/engine/swarm/admin_guide/#run-manager-only-nodes).

`docker node update --availability drain $MANAGER_NODE`

Kind regards,


Marvin

**Comment by bintut** [comment] 2017-06-07 01:14
Hi @ldez,

Thank you for re-opening and considering my feature request.

As I originally mentioned on this feature request, hopefully multiple endpoints can be supported as map separated by commas to eliminate the chance of single point of failure.

Thank you in advance.

Kind regards,


Marvin

**Comment by emilevauge** [comment] 2017-06-14 13:49
@vdemeester any thoughts on this ?

**Comment by vdemeester** [comment] 2017-06-15 14:58
That's an idea 👼

**Comment by bintut** [comment] 2017-07-10 03:01
In Docker swarm mode, the [best practice](https://docs.docker.com/engine/swarm/admin_guide/#run-manager-only-nodes) is to _drain_ the manager nodes and will not run any task/container on it. However, if Traefik is configured to use the Docker swarm mode backend, the only way to run Traefik service on top of the worker nodes of a Docker swarm cluster is to use the TCP+TLS endpoint. But it is currently limited to use a single manager node as an endpoint which can be a SPOF.

**Comment by MrOwen** [comment] 2017-07-17 00:04
I think a possible workaround for this is to use this guy's (or gal's) idea: https://github.com/softonic/docker-traefik. Spin up a socat container as a global service on all manager nodes to expose the Docker socket over a port. Configure Traefik to point to that service in the `endpoint` Docker option. Docker DNS will resolve that to the IPs of the socat containers. If one manager goes down, depending on how DNS resolution works within Traefik, it should connect to the next available socat server to get the Docker runtime info. That pretty much eliminates the need to put in multiple endpoints. Combine this with a K/V store for ACME info and you've got a pretty awesome HA reverse proxy setup.

In a perfect world, you wouldn't have that "middleman" socat container but I don't know of another (as easy) way to get that same DNS resolution technique working.

Can @ldez or someone confirm if Traefik DNS resolution would allow for this HA technique?

**Comment by emilevauge** [comment] 2017-07-17 00:41
@MrOwen it should work indeed. In this case, instead of deploying another socat container, we could eventually do the same thing in traefik.
@vdemeester we need your help on this, WDYT ?

**Comment by bintut** [comment] 2017-07-22 02:38
@MrOwen, IMHO I'd rather run Traefik in all Docker swarm manager nodes and point my endpoint configuration to the Docker Unix socket than running additional (socat) container(s) that will basically use more of my nodes' (limited) resources. Also, running socat container(s) will not solve the issue of freeing up the Docker swarm manager nodes with containers and running them in **drain** mode as per [best practice](https://docs.docker.com/engine/swarm/admin_guide/#run-manager-only-nodes).

**Comment by MrOwen** [comment] 2017-07-25 21:13
@bintut, if you're running Traefik in only your manager nodes and you have a lot of traffic going in/out, you'd be going against the best practices of having dedicated manager nodes. Ideally, your workers also have more resources and are better suited to handle the network traffic (eg, you're running managers on t2.medium and workers on m4.2xlarge). I haven't dug super deep into the tons of socat images but I suspect some use a scratch base meaning socat is literally the only thing in that container. I think the traffic in/out of the socat containers is also minimal because it's essentially only being used for service discovery.

It would be nice if swarm provided programmatic service discovery access to worker nodes aside from DNS but such is life.

**Comment by estenrye** [comment] 2017-08-09 21:18
One way I worked around the need for this feature is by creating a common DNS entry, let's call it managers.swarm.io, and configuring all of the managers in my swarm to communicate over TLS with certificates that include managers.swarm.io in the subject alternative name.  This way, my external load balancer or dns round robin can direct the traffic to an available and responding manager node.

**Comment by bintut** [comment] 2017-08-12 14:25
@MrOwen, I intend not to run any task at all in all our Docker swarm manager nodes as per best practice. I just mentioned in my previous comment that _I'd rather run ... than running additional ..._, IMHO.

**Comment by bintut** [comment] 2018-08-15 13:41
Anyone care to share their workaround to eliminate the possibility of SPOF on using Docker swarm mode backend without running traefik directly on the manager nodes? Thanks in advance!

**Comment by dduportal** [comment] 2018-08-17 09:07
I alm also going to close this issue as duplicate of #766 , where the challenge is the same: 
achieving high availability AND having traefik running on worker node.

As a side note: please read this exchange of comment from Bret Fischer, whom is a Docker Captain, about the "drain" feature of Swarm managers: https://github.com/containous/traefik/issues/766#issuecomment-407952910 . It would save you a lot of troubles :)

**Closed by dduportal** 2018-08-17 09:07 UTC
Labels: area/provider/docker/swarm, kind/enhancement, priority/P3

**Comment by bintut** [comment] 2018-09-26 13:50
Well @dduportal , just because a Docker Captain haven't seen a production swarm cluster with drain mode enabled on the manager nodes does not mean it's not realistic and sane. I am not a Docker Captain but I've seen an international financial institution that has been running a production swarm cluster with drain mode enabled on the manager nodes on a multi-DC private cloud for almost 22 months already with hundreds of services running Spring applications as microservices, Mule and Kong as APIs, etc.

**Comment by dduportal** [comment] 2018-09-26 16:01
Hello @bintut , my apologises if my comment about Bret's blog post sounded bad or pedantic.
I just wanted to give more documentation and sources of content, the goal was absolutely NOT to say this should be a reference, but only to give credits to this content. I absolutely do NOT want to dismiss your work or the things you saw (which, btw, looks awesome!).
