### ISSUE TITLE
Traefik Docker image doesn’t start when letsencrypt is down

### ISSUE THREAD

**Issue by bpierre** [containous/traefik#1632] opened 2017-05-19 12:53 UTC
When launching the latest Docker image, I get the following:

```
Error creating TLS config: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json \"https://acme-v01.api.letsencrypt.org/directory\": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Error preparing server: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json \"https://acme-v01.api.letsencrypt.org/directory\": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by ldez** [comment] 2017-05-19 13:10
Duplicate of #791 and #1631

**Closed by ldez** 2017-05-19 13:10 UTC
