### ISSUE TITLE
No proper instructions for using letsencrypt with kubernetes

### ISSUE THREAD

**Issue by nigel-dewar** [containous/traefik#4349] opened 2019-01-01 00:58 UTC
There is a bug in your docomentation - aka , its completely missing.

here https://docs.traefik.io/user-guide/docker-and-lets-encrypt/

This is for docker using docker compose. You missed the more important product, kubernetes. there is no information for how to setup with kubernetes. You show how to create your own SSL cert, but everyone knows how to do that and noone is going to use that in production are they?

I found your sample for kubernetes here https://github.com/containous/traefik/tree/master/examples/k8s
No info on setting up TLS or letsencrypt here eh? Nothing...

All of your important doco seems to be focused on docker . ie
https://docs.traefik.io/user-guide/kv-config/

This is no good. This is no help to people using kubernetes, by far the more popular orchestrator now.

If you want your product to survive, you will need to put some serious effort into your doco. Im switching to another product, not by choice, but simply because I cant use your product as your doco is completely insufficient. Its been the downfall of many promising products, as you well know. And many inferior products have risen to the top because of thier good doco. So please take this seriously. Thats why Ive raised this as a bug for you. Its critical, more than the code in your product right now.

**Comment by ldez** [comment] 2019-01-01 03:02
- https://docs.traefik.io/user-guide/kubernetes/
- https://docs.traefik.io/user-guide/kubernetes/#add-a-tls-certificate-to-the-ingress
- https://docs.traefik.io/configuration/backends/kubernetes/

**Comment by geraldcroes** [comment] 2019-01-02 15:14
Duplicate of #4279 #2931

**Closed by geraldcroes** 2019-01-02 15:14 UTC
Labels: area/documentation, resolution/duplicate
