### ISSUE TITLE
Feature request: Plain TCP frontend

### ISSUE THREAD

**Issue by dren-dk** [containous/traefik#2866] opened 2018-02-16 08:20 UTC
I'd like to be able to put Træfik in front of phabricator, one of the things that's needed in a frontend is the ability to forward a TCP connection, because git speaks though ssh on TCP port 22.

I like to have the port 22 open for ssh on the same IP as the web ui at port 443.

I see no TCP frontend, is it simply undocumented or is this feature missing?

The front end can bring some intelligence to health checking and failover on TCP, even if it's somewhat limited, but healthchecks I can think of: 
* Ensuring that the three-way-handshake has been completed with the back end.
* Configure a minimum traffic amount in each direction before termination of the connection.
* Timeouts.

It ought to be trivial to reestablish a TCP connection to a another or the same backend if the handshake fails.

It might even be possible to re-try a TCP connection, if the handshake was completed, but only the client transmitted data, so if a client sends a request to a server that fails in stead of responding, then re-sending the request to a new connection could be done.

**Comment by ldez** [comment] 2018-02-16 08:21
Duplicate of #10

**Closed by ldez** 2018-02-16 08:21 UTC
Labels: resolution/duplicate
