### ISSUE TITLE
Compress:on should autodetect if content is already compressed

### ISSUE THREAD

**Issue by Yajo** [containous/traefik#1653] opened 2017-05-23 11:41 UTC
### Do you want to request a *feature* or report a *bug*?

Not sure...

### What did you do?

Serve a site as usual. It turns out the site was already returning gzipped content.

### What did you expect to see?

Site served as usual.

If the response already has a `Content-Encoding: gzip` header, Traefik should be smart enough to skip the compression task for it. Traefik should only take care of compressing responses that come uncompressed.

Another solution would be to specify compression by frontend/backend, not entrypoint.

### What did you see instead?

This thingy:

![captura de pantalla de 2017-05-23 13-22-27](https://cloud.githubusercontent.com/assets/973709/26352196/fade4e0e-3fba-11e7-8acd-bb10418bfdca.png)

Each time I press F5, the characters are different.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.2.3
Codename:     morbier
Go version:   go1.7.5
Built:        2017-04-13_07:21:10PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

arguments:

      - --ACME.ACMELogging
      - --ACME.Email=****
      - --ACME.EntryPoint=https
      - --ACME.OnDemand
      - --ACME.OnHostRule
      - --ACME.Storage=/etc/traefik/acme/acme.json
      - --DefaultEntryPoints=http,https
      - --Docker
      - --Docker.Endpoint=http://dockersocket:2375
      - --Docker.ExposedByDefault=false
      - --Docker.Watch
      - --EntryPoints=Name:http Address::80 Redirect.EntryPoint:https Compress:on
      - --EntryPoints=Name:https Address::443 TLS Compress:on
      - --LogLevel=DEBUG

### Workaround

Remove `Compress:on` from `https` entrypoint.

**Comment by ldez** [comment] 2017-05-23 12:09
Duplicate of #1060 - Feel free to subscribe there for updates.

**Closed by ldez** 2017-05-23 12:09 UTC
Labels: resolution/duplicate
