### ISSUE TITLE
Not listening on port 80

### ISSUE THREAD

**Issue by WTFKr0** [containous/traefik#432] opened 2016-06-02 22:16 UTC
Hi

I use traefik on multiple docker envs without problems, but in one it didn't work
I simplify to your docker-compose example, and this is what happen : 

# cat docker-compose.yml 
version: "2"
services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  whoami1:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"

  whoami2:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"

# docker-compose up -d
Creating network "traefikdemo_default" with the default driver
Creating traefikdemo_traefik_1
Creating traefikdemo_whoami2_1
Creating traefikdemo_whoami1_1

# docker port traefikdemo_traefik_1
80/tcp -> 0.0.0.0:80
8080/tcp -> 0.0.0.0:8080

# curl -H Host:whoami.docker.localhost http://127.0.0.1
curl: (56) Recv failure: Connection reset by peer

Service seems to not listen on port 80
traefik listen well on port 8080 : 
# curl http://127.0.0.1:8080/api
{"docker":{"backends":{"backend-whoami":{"servers":{"server-traefikdemo_whoami1_1":{"url":"http://172.21.0.2:80","weight":1},"server-traefikdemo_whoami2_1":{"url":"http://172.21.0.4:80","weight":1}}}},"frontends":{"frontend-Host-whoami-docker-localhost":{"backend":"backend-whoami","routes":{"route-frontend-Host-whoami-docker-localhost":{"rule":"Host:whoami.docker.localhost"}},"passHostHeader":true}}}}

I test directly on container IP and it seems the conatiner itself is listening only on port 8080, not 80 : 
# exec 3<>/dev/tcp/172.21.0.3/80; echo $?
bash: connect: Connection refused
bash: /dev/tcp/172.21.0.3/80: Connection refused
1
# exec 3<>/dev/tcp/172.21.0.3/8080; echo $?
0

How can I debug why traefik is not listneing on port 80 ?

Env information : 
Docker : Server Version: 1.11.1
docker-compose version 1.7.1, build 0a9ab35
traefik        latest       bf7f4f01be40    2 days ago    19.91 MB

Thanx

**Comment by emilevauge** [comment] 2016-06-03 07:09
Hi @WTFKr0, this has been fixed in https://github.com/containous/traefik/pull/428. I will publish the rc2 soon. Sorry for that regression :/

**Comment by WTFKr0** [comment] 2016-06-03 07:19
OK good to hear that !
Thanx

**Closed** 2016-06-03 11:34 UTC

**Comment by mjgorman** [comment] 2016-06-08 20:33
@emilevauge Just ran into this issue myself. Looks like the official traefik in dockerhub is still busted. Your emilevauge/traefik is working great. Documentation however all uses the official Traefik and causes massive troubleshooting headaches

**Comment by emilevauge** [comment] 2016-06-08 20:35
@mjgorman the dockerhub version will be updated soon ;) https://github.com/docker-library/official-images/pull/1822

**Comment by dakkusingh** [comment] 2017-10-25 00:16
I have the same issue on Mac, using exactly the same docker-compose as above. Any help?

```
MacBookPro:docker $ docker-compose down && docker-compose up -d
Stopping docker_traefik_1 ... done
Stopping docker_whoami1_1 ... done
Removing docker_traefik_1 ... done
Removing docker_whoami1_1 ... done
Removing network docker_default
Creating network "docker_default" with the default driver
Creating docker_whoami1_1 ...
Creating docker_traefik_1 ...
Creating docker_whoami1_1
Creating docker_traefik_1 ... done
```

Port info:
```
80/tcp -> 0.0.0.0:80
8080/tcp -> 0.0.0.0:8080
```

**Comment by timoreimann** [comment] 2017-10-25 04:59
@dakkusingh chances are you are affected by a different problem. Join us on Slack for real time help or create a question on Stackoverflow

If you are really certain that this is a bug (either a new one or a regression), please open a new issue.

**Comment by dakkusingh** [comment] 2017-10-25 08:44
Hi Timo,
Thank you, you are correct, my issue didnt seem to be related to this. Although the symptoms were very similar. This is resolved now.
