### ISSUE TITLE
Redirects to backend

### ISSUE THREAD

**Issue by andrewcfitz** [containous/traefik#1431] opened 2017-04-13 13:19 UTC
### What version of Traefik are you using (`traefik version`)?
1.2.1

### What is your environment & configuration (arguments, toml...)?
Docker

Config (Hostnames have been changed)
```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.http.redirect]
  entryPoint = "https"

[acme]
email = "andrew@test.lan"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging = true
# onDemand = true
OnHostRule = true
#caServer = "https://acme-staging.api.letsencrypt.org/directory"

[[acme.domains]]
   main = "proxy.test.lan"

[file]

[backends]
  [backends.jenkins]
    [backends.jenkins.servers.server1]
    url = "http://10.0.0.43:8080"
    weight = 10
    passHostHeader = true
    [backends.jenkins.LoadBalancer]
      method = "wrr"

[frontends]
  [frontends.jenkins]
  entrypoints = ["http", "https"]
  backend = "jenkins"
    [frontends.jenkins.routes.hostname]
    rule = "Host:jenkins.test.lan"
```

### What did you do?
1. Goto http://jenkins.test.lan/

1. Redirected to https://jenkins.test.lan/

1. Login to Jenkins

### What did you expect to see?
When logged in, I should be on https://jenkins.test.lan/

### What did you see instead?
I got redirected to https://10.0.0.43:8080/

### If applicable, please paste the log output in debug mode (`--debug` switch)

<details>

```
time="2017-04-13T13:09:47Z" level=warning msg="A new release has been found: 1.2.2. Please consider updating."
time="2017-04-13T13:09:48Z" level=info msg="Starting provider *provider.File {\"Watch\":true,\"Filename\":\"/etc/traefik/traefik.toml\",\"Constraints\":null}"
time="2017-04-13T13:09:48Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Statistics\":null,\"Metrics\":null,\"Auth\":null}"
time="2017-04-13T13:09:48Z" level=info msg="Retrieving ACME certificates..."
time="2017-04-13T13:09:48Z" level=info msg="Retrieved ACME certificates"
time="2017-04-13T13:09:48Z" level=debug msg="Testing certificate renew..."
time="2017-04-13T13:09:48Z" level=info msg="Starting server on :443"
time="2017-04-13T13:09:48Z" level=debug msg="Configuration received from provider file: {\"backends\":{\"jenkins\":{\"servers\":{\"server1\":{\"url\":\"http://10.0.0.43:8080\",\"weight\":10}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"jenkins\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"jenkins\",\"routes\":{\"hostname\":{\"rule\":\"Host:jenkins.test.lan\"}},\"priority\":0}}}"
time="2017-04-13T13:09:48Z" level=debug msg="Last file config received more than 2s, OK"
time="2017-04-13T13:09:48Z" level=debug msg="Creating frontend jenkins"
time="2017-04-13T13:09:48Z" level=debug msg="Wiring frontend jenkins to entryPoint http"
time="2017-04-13T13:09:48Z" level=debug msg="Creating route hostname Host:jenkins.test.lan"
time="2017-04-13T13:09:48Z" level=debug msg="Creating entryPoint redirect http -> https : ^(?:https?:\\/\\/)?([\\w\\._-]+)(?::\\d+)?(.*)$ -> https://$1:443$2"
time="2017-04-13T13:09:48Z" level=debug msg="Wiring frontend jenkins to entryPoint https"
time="2017-04-13T13:09:48Z" level=debug msg="Creating route hostname Host:jenkins.test.lan"
time="2017-04-13T13:09:48Z" level=debug msg="Creating backend jenkins"
time="2017-04-13T13:09:48Z" level=debug msg="Creating load-balancer wrr"
time="2017-04-13T13:09:48Z" level=debug msg="Creating server server1 at http://10.0.0.43:8080 with weight 10"
time="2017-04-13T13:09:48Z" level=info msg="Server configuration reloaded on :80"
time="2017-04-13T13:09:48Z" level=info msg="Server configuration reloaded on :443"
time="2017-04-13T13:09:48Z" level=debug msg="LoadCertificateForDomains [jenkins.test.lan]..."
time="2017-04-13T13:10:20Z" level=debug msg="Challenge GetCertificate jenkins.test.lan"
time="2017-04-13T13:10:20Z" level=debug msg="ACME got domain cert jenkins.test.lan"
time="2017-04-13T13:10:20Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 85.892762ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:20Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 110.556522ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:20Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 131.653409ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:20Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 138.957883ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:20Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 144.156769ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:20Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 192.102067ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:20Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 209.770904ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:21Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 130.607902ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:28Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 295.872848ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:39Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 8.108488529s tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:39Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 304, duration: 21.164562ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:39Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 304, duration: 19.426064ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:39Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 304, duration: 22.96959ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:39Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 304, duration: 22.565382ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:39Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 304, duration: 30.603828ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:39Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 304, duration: 34.563684ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:40Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 90.449685ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:40Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 93.224352ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:40Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 63.467754ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:40Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 40.334964ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:40Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 35.921672ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:40Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.362159ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:40Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 22.435373ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:40Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 2.248494ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:40Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 57.079959ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:40Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 43.712572ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:40Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 4.253513ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:40Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 14.982222ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 21.338539ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.470384ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.85602ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.312436ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.011024ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.6738ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.061581ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 991.405µs tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.920377ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 2.002141ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.107371ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.014047ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 995.545µs tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 961.018µs tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.050006ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.042439ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.160105ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.152159ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.087227ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.033259ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.001912ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.226524ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 4.762044ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.047365ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 997.191µs tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.352094ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.487493ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.012389ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.441447ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.394932ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.254107ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 980.194µs tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 959.346µs tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.681624ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.591677ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.285257ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 968.536µs tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 960.672µs tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.753532ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:41Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 1.726254ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:46Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 200, duration: 2.147837ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
time="2017-04-13T13:10:53Z" level=debug msg="Round trip: http://10.0.0.43:8080, code: 302, duration: 5.891625933s tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:jenkins.test.lan"
```

</details>

Here is the response in Chrome
```
content-length:0
content-type:text/plain; charset=utf-8
date:Thu, 13 Apr 2017 13:18:05 GMT
expires:Thu, 01 Jan 1970 00:00:00 GMT
location:https://10.0.0.43:8080/
server:Jetty(9.2.z-SNAPSHOT)
set-cookie:JSESSIONID.4c936f02=eudbpoy7hckgue2d30g3udtk;Path=/;Secure;HttpOnly
status:302
x-content-type-options:nosniff
```

**Comment by emilevauge** [comment] 2017-04-13 15:04
@andrewcfitz Could you give me the output of `curl -v -L -k "http://jenkins.test.lan"` ?

**Comment by andrewcfitz** [comment] 2017-04-13 15:24
```
* Rebuilt URL to: http://jenkins.test.lan/
*   Trying {masked ip}...
* TCP_NODELAY set
* Connected to jenkins.test.lan ({masked ip}) port 80 (#0)
> GET / HTTP/1.1
> Host: jenkins.test.lan
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Location: https://jenkins.test.lan:443/
< Date: Thu, 13 Apr 2017 15:22:04 GMT
< Content-Length: 5
< Content-Type: text/plain; charset=utf-8
<
* Ignoring the response-body
* Curl_http_done: called premature == 0
* Connection #0 to host jenkins.test.lan left intact
* Issue another request to this URL: 'https://jenkins.test.lan:443/'
*   Trying {masked ip}...
* TCP_NODELAY set
* Connected to jenkins.test.lan ({masked ip}) port 443 (#1)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: TRAEFIK DEFAULT CERT
> GET / HTTP/1.1
> Host: jenkins.test.lan
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Content-Length: 793
< Content-Type: text/html;charset=UTF-8
< Date: Thu, 13 Apr 2017 15:22:04 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Server: Jetty(9.2.z-SNAPSHOT)
< Set-Cookie: JSESSIONID.4c936f02=jjrha1hsbiyi12h94ba7pzbe1;Path=/;Secure;HttpOnly
< X-Content-Type-Options: nosniff
< X-Hudson: 1.395
< X-Hudson-Cli-Port: 50000
< X-Jenkins: 2.32.2
< X-Jenkins-Cli-Port: 50000
< X-Jenkins-Cli2-Port: 50000
< X-Jenkins-Session: 5a89cd2e
< X-Permission-Implied-By: hudson.security.Permission.GenericRead
< X-Permission-Implied-By: hudson.model.Hudson.Administer
< X-Required-Permission: hudson.model.Hudson.Read
< X-You-Are-Authenticated-As: anonymous
< X-You-Are-In-Group:
<
<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2F'/><script>window.location.replace('/login?from=%2F');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:

Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer
-->

* Curl_http_done: called premature == 0
* Connection #1 to host jenkins.test.lan left intact
</body></html>
```

**Comment by emilevauge** [comment] 2017-04-13 15:57
@andrewcfitz I don't see any issue with the redirect here (`http` to `https://jenkins.test.lan:443/`). Am I wrong ?

**Comment by andrewcfitz** [comment] 2017-04-13 15:59
The issue isn't with that redirect.  It is when doing a post.  Here is the output from response headers from Chrome:

```
content-length:0
content-type:text/plain; charset=utf-8
date:Thu, 13 Apr 2017 15:58:51 GMT
expires:Thu, 01 Jan 1970 00:00:00 GMT
**location:https://10.0.0.43:8080/**
server:Jetty(9.2.z-SNAPSHOT)
set-cookie:JSESSIONID.4c936f02=19h9u4elx2ghsnxovws42gkdu;Path=/;Secure;HttpOnly
status:302
x-content-type-options:nosniff
```

**Comment by emilevauge** [comment] 2017-04-13 16:05
@andrewcfitz Oh, I think it may be a duplicate of https://github.com/containous/traefik/issues/1323 then.

**Comment by kurlzor** [comment] 2017-04-14 11:50
@andrewcfitz From your last post:
```
server:Jetty(9.2.z-SNAPSHOT)
```
This is a response from Jenkins, not Traefik. Have you set this correctly ?
![image](https://cloud.githubusercontent.com/assets/1843182/25042532/16bdbe7c-2119-11e7-90f1-cddd10f112b7.png)

**Comment by andrewcfitz** [comment] 2017-04-17 12:53
@kurlzor Yes it is configured correctly.  I had a nginx proxy configured for it, and it works perfectly.

**Comment by fabiorauber** [comment] 2017-05-09 15:41
Seeing the same issue with xenorchestra (interlegis/xen-orchestra:5.8.0). When behind traefik, URLs beginning with double slashes fail, returning "JavaScript is required for Xen Orchestra!" instead of the file.

**Comment by ldez** [comment] 2017-06-13 13:12
This is a duplicate of  #1323 - Feel free to subscribe there for updates.

**Comment by andrewcfitz** [comment] 2018-04-09 13:07
This is still an issue, here is the config I tested it with:

'''
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.http.redirect]
  entryPoint = "https"

[acme]
email = "email@test.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging = true
OnHostRule = true
caServer = "https://acme-staging.api.letsencrypt.org/directory"

[acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
   main = "proxy.externaldomain.com"

[file]

[backends]
  [backends.jenkins]
    [backends.jenkins.servers.server1]
    url = "http://dockerci-jenkins.internaldomain.lan/"
    weight = 10
    [backends.jenkins.LoadBalancer]
      method = "wrr"

[frontends]
  [frontends.jenkins]
  entrypoints = ["http", "https"]
  backend = "jenkins"
    [frontends.jenkins.routes.hostname]
    rule = "Host:jenkins.externaldomain.com"
'''

**Comment by jbdoumenjou** [comment] 2018-04-19 07:05
Hello @andrewcfitz, I didn't succeed in reproducing your case.
I used the following configuration

The docker-compose.yml:
```yaml
version: '3'

services:
  reverse-proxy:
    image: traefik:v1.5
    command: --api
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
    extra_hosts:
      - jenkins.internal:10.0.1.3
    networks:
      net:
        ipv4_address: 10.0.1.2
  jenkins: 
    image: jenkins/jenkins:lts
    networks:
      net:
        ipv4_address: 10.0.1.3
networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.1.0/29
``` 

The traefik.toml:
```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]

[backends]
  [backends.jenkins]
    [backends.jenkins.servers.server1]
    url = "http://jenkins.internal:8080/"
    weight = 10
    [backends.jenkins.LoadBalancer]
      method = "wrr"

[frontends]
  [frontends.jenkins]
  entrypoints = ["http"]
  backend = "jenkins"
    [frontends.jenkins.routes.hostname]
    rule = "Host:jenkins.localhost"
```

If I miss some details, please join our [Slack workspace](https://traefik.herokuapp.com/) to discus about your use case.

**Comment by traefiker** [comment] 2018-12-12 00:00
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Closed by traefiker** 2018-12-12 00:00 UTC
Labels: contributor/waiting-for-feedback, kind/bug/possible
