### ISSUE TITLE
Option not to use stack name for Auto generated docker urls

### ISSUE THREAD

**Issue by robertbaker** [containous/traefik#3955] opened 2018-09-30 02:44 UTC
I want to avoid using labels, as I'm aiming got more of a OttB setup. The default naming 
convention is service.stack.domain.tld.

I would like a way with a command line argument to change it globally to service.domain.tld. I'm using docker compose and so far have removed the need for a TOML and docker labels with the exception of changing the hostname of services.

**Comment by ldez** [comment] 2018-11-16 03:44
seems to be a duplicate of #2578

**Closed** 2018-11-16 15:30 UTC
Labels: area/provider/docker, kind/enhancement, resolution/duplicate
