### ISSUE TITLE
Nomad and CLI args - forward auth

### ISSUE THREAD

**Issue by ccakes** [containous/traefik#4306] opened 2018-12-17 17:18 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Use CLI args to configure forward auth on an entrypoint

### What did you expect to see?
Requests routed to the auth service, then the intended service

### What did you see instead?
The HTTP entrypoint didn't work at all

**Logs**
```shell
time="2018-12-17T16:47:34Z" level=info msg="Traefik version v1.7.6 built on 2018-12-14_06:43:37AM"
time="2018-12-17T16:47:34Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2018-12-17T16:47:34Z" level=info msg="Preparing server  &{Address::80 TLS:<nil> Redirect:<nil> Auth:0xc0003a7f80 WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000509560} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-12-17T16:47:34Z" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000509740} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-12-17T16:47:34Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
time="2018-12-17T16:47:34Z" level=info msg="Starting server on :80"
time="2018-12-17T16:47:34Z" level=info msg="Starting server on :8080"
time="2018-12-17T16:47:34Z" level=info msg="Starting provider *consulcatalog.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"consul.service.consul:8500\",\"Domain\":\"aws-eu-west-1.internal\",\"Stale\":false,\"ExposedByDefault\":false,\"Prefix\":\"traefik\",\"FrontEndRule\":\"Host:{{.ServiceName}}.{{.Domain}}\",\"TLS\":null}"
time="2018-12-17T16:47:34Z" level=error msg="Undefined entry point(s) 'http' for frontend frontend-hello-world"
time="2018-12-17T16:47:34Z" level=error msg="no entrypoint defined for frontend frontend-hello-world. Skipping frontend frontend-hello-world..."
time="2018-12-17T16:47:34Z" level=info msg="Server configuration reloaded on :80"
time="2018-12-17T16:47:34Z" level=info msg="Server configuration reloaded on :8080"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
Docker - traefik:alpine (1.7.6)
`traefik version v1.7.6 built on 2018-12-14_06:43:37AM"`

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
I'm using Nomad to run the traefik contain but I don't think that would have much to do with it

**Nomad task config**
```hcl
# Effectively just running:
# docker run --entrypoint "" traefik:alpine traefik --loglevel..... etc
config {
        force_pull = true
        image      = "traefik:alpine"

        entrypoint  = [""]
        command     = "traefik"

        args = [
          "--loglevel=INFO",
          "--accesslog=true",
          "--traefiklog=true",
          "--traefiklog.filepath=/traefik.log",
          "--entrypoints='Name:http Address::80 Auth.Forward.Address:http://auth.service.$${node.datacenter}.consul:1337 Auth.Forward.TrustForwardHeader:true Auth.Forward.TLS.InsecureSkipVerify:true'",
          "--api=true",
          "--ping=true",
          "--consulcatalog.watch=true",
          "--consulcatalog.endpoint=consul.service.consul:8500",
          "--consulcatalog.exposedbydefault=false",
          "--consulcatalog.domain=$${node.datacenter}.${base_domain}",
        ]

        port_map {
          admin = 8080
          http  = 80
        }
      }
```

If I comment the entrypoint argument and add a simple TOML file containing this snippet, it works.

```toml
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.auth.forward]
    address = "http://auth.service.{{ env "node.datacenter" }}.consul:1337"
    trustForwardHeader = true
```

I feel like this is probably just a config issue but the correct config isn't documented anywhere so I'm stuck. Once this ticket is resolved I'm happy to submit a PR with a documentation update

**Comment by ldez** [comment] 2018-12-17 18:16
The issue come from `Auth.Forward.Address:http://auth.service.$${node.datacenter}.consul:1337`, precisely from `$${node.datacenter}`

Try to replace `$$` by `$`

**Comment by ldez** [comment] 2018-12-17 18:34
Could you set `--loglevel=DEBUG` and give the resulting logs (from the start of Traefik).

I don't reproduce:
```bash
docker run -p 8080:8080 -e node.datacenter:test -v /var/run/docker.sock:/var/run/docker.sock \
traefik:1.7-alpine \
--api \
--ping \
--accesslog \
--traefiklog \
--docker --docker.exposedbydefault \
--entrypoints='Name:http Address::80 Auth.Forward.Addrhttp://auth.service.$${node.datacenter}.consul:1337 Auth.Forward.TrustForwardHeader:true Auth.Forward.TLS.InsecureSkipVerify:true' \
--loglevel=DEBUG
```

```bash
docker run -l traefik.frontend.rule=Host:foobar.docker.localhost containous/whoami
```

**Comment by ccakes** [comment] 2018-12-17 19:37
<details>
 <summary>Logs</summary>

```
time="2018-12-17T18:36:09Z" level=info msg="Traefik version v1.7.6 built on 2018-12-14_06:43:37AM"
time="2018-12-17T18:36:09Z" level=debug msg="Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceTimeOut\":0,\"Debug\":false,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false,\"AccessLogsFile\":\"\",\"AccessLog\":{\"format\":\"common\"},\"TraefikLogsFile\":\"\",\"TraefikLog\":{\"file\":\"/traefik.log\",\"format\":\"common\"},\"Tracing\":null,\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"\":{\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":{\"forward\":{\"address\":\"http://forge-auth.service.aws-eu-west-1.consul:1337\",\"trustForwardHeader\":true}},\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"IdleTimeout\":0,\"InsecureSkipVerify\":false,\"RootCAs\":null,\"Retry\":null,\"HealthCheck\":{\"Interval\":30000000000},\"RespondingTimeouts\":null,\"ForwardingTimeouts\":null,\"AllowMinWeightZero\":false,\"KeepTrailingSlash\":false,\"Web\":null,\"Docker\":null,\"File\":null,\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"consul.service.consul:8500\",\"Domain\":\"aws-eu-west-1.internal\",\"Stale\":false,\"ExposedByDefault\":false,\"Prefix\":\"traefik\",\"FrontEndRule\":\"Host:{{.ServiceName}}.{{.Domain}}\",\"TLS\":null},\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null,\"Mesos\":null,\"Eureka\":null,\"ECS\":null,\"Rancher\":null,\"DynamoDB\":null,\"ServiceFabric\":null,\"Rest\":null,\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Debug\":false,\"CurrentConfigurations\":null,\"Statistics\":null},\"Metrics\":null,\"Ping\":{\"EntryPoint\":\"traefik\"},\"HostResolver\":null}"
time="2018-12-17T18:36:09Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2018-12-17T18:36:09Z" level=info msg="Preparing server  &{Address::80 TLS:<nil> Redirect:<nil> Auth:0xc0002d0b10 WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000448720} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-12-17T18:36:09Z" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000448ae0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-12-17T18:36:09Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
time="2018-12-17T18:36:09Z" level=info msg="Starting server on :80"
time="2018-12-17T18:36:09Z" level=info msg="Starting server on :8080"
time="2018-12-17T18:36:09Z" level=info msg="Starting provider *consulcatalog.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"consul.service.consul:8500\",\"Domain\":\"aws-eu-west-1.internal\",\"Stale\":false,\"ExposedByDefault\":false,\"Prefix\":\"traefik\",\"FrontEndRule\":\"Host:{{.ServiceName}}.{{.Domain}}\",\"TLS\":null}"
time="2018-12-17T18:36:09Z" level=debug msg="Health State change detected." ChangedServices="[]" DiscoveredServices="[i-000aa302fd7ceb4a4-_nomad-server-6sukbgobxscxb3vodwgbxwdrukvpa6ao i-08126a970e66f1dd5-_nomad-task-sp5pw7g6ggtzsn7woagvzyo3c2skqfyu i-0ac3fa08faa70274a-_nomad-server-3j7laz7iexvl4op5ae7gqip7hhqbt3wy i-0feaaca93a74fe228-_nomad-server-xideeei2y5yh6ximsp4win6dsajq2s72 i-0ac3fa08faa70274a-_nomad-server-o5qghpkjnrzg2zmdxfk4xs2jyz7uhc4v i-000aa302fd7ceb4a4- i-000aa302fd7ceb4a4-_nomad-server-2m3gylipsc2f4e5ti6n7njkn4bscrjte i-059dd631f7b36c3ff- i-059dd631f7b36c3ff-_nomad-client-ryr6unnwlox62eb6ihs5pjpmbamsvaxb i-0feaaca93a74fe228-vault:172.16.4.179:8200 i-000aa302fd7ceb4a4-_nomad-server-f6wkcvisbeqv6yja4ydfpiak24malk3v i-0ac3fa08faa70274a-_nomad-server-eejtqbgb6rx5ltigei4bnbqlkrfnjee5 i-0feaaca93a74fe228-_nomad-server-ib4fkigltac5kxkqnyzv2sbozj35iqhs i-0feaaca93a74fe228- i-08126a970e66f1dd5- i-000aa302fd7ceb4a4-vault:172.16.5.115:8200 i-0ac3fa08faa70274a-vault:172.16.3.33:8200 i-08126a970e66f1dd5-_nomad-client-3qslbvt3n5dlerzp2g36uzbkdvovlsfc i-0feaaca93a74fe228-_nomad-server-2aenosvqwijfkmursrlekhfv2jddgims i-0ac3fa08faa70274a-]" MissingServices="[]"
time="2018-12-17T18:36:09Z" level=debug msg="List of services changed"
time="2018-12-17T18:36:09Z" level=debug msg="Fetching service" service=consul
time="2018-12-17T18:36:09Z" level=debug msg="Filtering disabled Consul service consul"
time="2018-12-17T18:36:09Z" level=debug msg="Fetching service" service=traefik
time="2018-12-17T18:36:09Z" level=debug msg="Filtering disabled Consul service traefik"
time="2018-12-17T18:36:09Z" level=debug msg="Fetching service" service=nomad
time="2018-12-17T18:36:09Z" level=debug msg="Filtering disabled Consul service nomad"
time="2018-12-17T18:36:09Z" level=debug msg="Fetching service" service=nomad-client
time="2018-12-17T18:36:09Z" level=debug msg="Filtering disabled Consul service nomad-client"
time="2018-12-17T18:36:09Z" level=debug msg="Fetching service" service=vault
time="2018-12-17T18:36:09Z" level=debug msg="Filtering disabled Consul service vault"
time="2018-12-17T18:36:09Z" level=debug msg="List of services changed"
time="2018-12-17T18:36:09Z" level=debug msg="Fetching service" service=nomad-client
time="2018-12-17T18:36:09Z" level=debug msg="Configuration received from provider consul_catalog: {}"
time="2018-12-17T18:36:09Z" level=info msg="Server configuration reloaded on :80"
time="2018-12-17T18:36:09Z" level=info msg="Server configuration reloaded on :8080"
time="2018-12-17T18:36:09Z" level=debug msg="Filtering disabled Consul service nomad-client"
time="2018-12-17T18:36:09Z" level=debug msg="Fetching service" service=vault
time="2018-12-17T18:36:09Z" level=debug msg="Filtering disabled Consul service vault"
time="2018-12-17T18:36:09Z" level=debug msg="Fetching service" service=consul
time="2018-12-17T18:36:09Z" level=debug msg="Filtering disabled Consul service consul"
time="2018-12-17T18:36:09Z" level=debug msg="Fetching service" service=traefik
time="2018-12-17T18:36:09Z" level=debug msg="Filtering disabled Consul service traefik"
time="2018-12-17T18:36:09Z" level=debug msg="Fetching service" service=nomad
time="2018-12-17T18:36:09Z" level=debug msg="Filtering disabled Consul service nomad"
time="2018-12-17T18:36:09Z" level=debug msg="Configuration received from provider consul_catalog: {}"
time="2018-12-17T18:36:09Z" level=info msg="Skipping same configuration for provider consul_catalog"
time="2018-12-17T18:36:36Z" level=debug msg="Health State change detected." ChangedServices="[]" DiscoveredServices="[i-059dd631f7b36c3ff-_nomad-task-xo7yal5bs5iyg2usjmw32gu2plk5csgv]" MissingServices="[]"
time="2018-12-17T18:36:36Z" level=debug msg="List of services changed"
time="2018-12-17T18:36:36Z" level=debug msg="Fetching service" service=nomad-client
time="2018-12-17T18:36:36Z" level=debug msg="Filtering disabled Consul service nomad-client"
time="2018-12-17T18:36:36Z" level=debug msg="Fetching service" service=vault
time="2018-12-17T18:36:36Z" level=debug msg="Filtering disabled Consul service vault"
time="2018-12-17T18:36:36Z" level=debug msg="Fetching service" service=consul
time="2018-12-17T18:36:36Z" level=debug msg="Filtering disabled Consul service consul"
time="2018-12-17T18:36:36Z" level=debug msg="Fetching service" service=traefik
time="2018-12-17T18:36:36Z" level=debug msg="Filtering disabled Consul service traefik"
time="2018-12-17T18:36:36Z" level=debug msg="Filtering disabled Consul service traefik"
time="2018-12-17T18:36:36Z" level=debug msg="Fetching service" service=nomad
time="2018-12-17T18:36:36Z" level=debug msg="Filtering disabled Consul service nomad"
time="2018-12-17T18:36:37Z" level=debug msg="Configuration received from provider consul_catalog: {}"
time="2018-12-17T18:36:37Z" level=info msg="Skipping same configuration for provider consul_catalog"
time="2018-12-17T18:37:21Z" level=debug msg="Fetching service" service=auth
time="2018-12-17T18:37:21Z" level=error msg="Undefined entry point(s) 'http' for frontend frontend-auth"
time="2018-12-17T18:37:21Z" level=debug msg="Backend backend-auth: no load-balancer defined, fallback to 'wrr' method"
time="2018-12-17T18:37:21Z" level=debug msg="Configuration received from provider consul_catalog: {\"backends\":{\"backend-auth\":{\"servers\":{\"auth-0-gubJr3P1TXO-fRhOfNhFELrMFPY\":{\"url\":\"http://172.16.5.207:1337\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-auth\":{\"backend\":\"backend-auth\",\"routes\":{\"route-host-auth\":{\"rule\":\"Host:auth.aws-eu-west-1.internal\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}"
time="2018-12-17T18:37:21Z" level=error msg="no entrypoint defined for frontend frontend-auth. Skipping frontend frontend-auth..."
time="2018-12-17T18:37:21Z" level=info msg="Server configuration reloaded on :8080"
time="2018-12-17T18:37:21Z" level=info msg="Server configuration reloaded on :80"
```

</details>
<br />
I trimmed repeated lines. On line 4 in my log it appears that the entrypoint is being created with no name which explains why `http` isn't found by the created frontends.

This is the argument generated by the Nomad template:
```
--entrypoints='Name:http Address::80 Auth.Forward.Address:http://forge-auth.service.aws-eu-west-1.consul:1337 Auth.Forward.TrustForwardHeader:true Auth.Forward.TLS.InsecureSkipVerify:true'
```

Any idea why the name would be getting trimmed?

**Comment by ldez** [comment] 2018-12-17 20:53
I think it's related to Nomad.

Can you try to change the name of the entrypoint?
```hcl
config {
        force_pull = true
        image      = "traefik:alpine"

        entrypoint  = [""]
        command     = "traefik"

        args = [
          "--loglevel=DEBUG",
          "--accesslog",
          "--traefiklog",
          "--traefiklog.filepath=/traefik.log",
          "--defaultentrypoints=foobar"
          "--entrypoints='Name:foobar Address::80 Auth.Forward.Address:http://auth.service.$${node.datacenter}.consul:1337 Auth.Forward.TrustForwardHeader:true Auth.Forward.TLS.InsecureSkipVerify:true'",
          "--api",
          "--ping",
          "--consulcatalog.watch",
          "--consulcatalog.endpoint=consul.service.consul:8500",
          "--consulcatalog.exposedbydefault=false",
          "--consulcatalog.domain=$${node.datacenter}.${base_domain}",
        ]

        port_map {
          admin = 8080
          http  = 80
        }
      }
```

**Comment by traefiker** [comment] 2018-12-18 15:47
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

Thanks again for your interest in Traefik!

I'm glad to close the issue because I think that the question has been answered (Yes, I'm quite an advanced AI :smile:)

Join our [Slack workspace](https://slack.traefik.io/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Closed by traefiker** 2018-12-18 15:47 UTC
Labels: kind/question

**Comment by soupdiver** [comment] 2019-08-16 20:41
I just had the same issue... solved it by removing the `'` in the `entrypoints='...'` line
