### ISSUE TITLE
Feature Request: Strict-SNI Support

### ISSUE THREAD

**Issue by fritz-fritz** [containous/traefik#2118] opened 2017-09-13 21:58 UTC
Looking to refuse the connection if SNI does not match a configured frontend.

In haproxy this can be configured by appending `strict-sni` to the bind line as follows:

```
frontend WebTraffic
	bind			127.0.0.1:8443 name 127.0.0.1:8443 ssl ciphers AES128+EECDH:AES128+EDH force-tlsv12 no-sslv3 crt /var/etc/haproxy/WebTraffic.pem crt /var/etc/haproxy/WebTraffic strict-sni
```

this would be desirable instead of serving a 404 with an invalid *.local cert as currently configured. The invalid cert just really bugs me.

**Comment by ldez** [comment] 2017-09-13 23:15
Thanks for your interest in Traefik 😃 

Duplicate of #1814

**Comment by fritz-fritz** [comment] 2017-09-14 04:47
I don't believe this is a duplicate. This is not about overriding the default cert it is about dropping the connection before serving it.

**Comment by lphuberdeau** [comment] 2018-04-06 13:07
There is an other related issue about the SNI implementation.

From RFC6066:

     A server that receives a client hello containing the "server_name"
     extension MAY use the information contained in the extension to guide
     its selection of an appropriate certificate to return to the client,
     and/or other aspects of security policy.  In this event, the server
     SHALL include an extension of type "server_name" in the (extended)
     server hello.  The "extension_data" field of this extension SHALL be
     empty.

Currently, Traefik does not include the server_name in the TLS response. Without this required acknowledgement, some clients skip the SNI extension on follow-up connections.

**Closed** 2018-07-06 08:30 UTC
Labels: area/tls, kind/enhancement, priority/P3
