### ISSUE TITLE
ACME Challenge over proxy

### ISSUE THREAD

**Issue by wenerme** [containous/traefik#2715] opened 2018-01-17 07:39 UTC
### Do you want to request a *feature* or report a *bug*?

frature

### What did you do?

Failed to get cert

```
time="2018-01-17T07:22:53Z" level=debug msg="Challenge GetCertificate example.com"
time="2018-01-17T07:22:53Z" level=debug msg="ACME got nothing example.com"
time="2018-01-17T07:23:00Z" level=debug msg="http: TLS handshake error from 100.97.192.4:5025: EOF"
```

The web server can not connect to acme server

```
$ ping 100.97.192.4
PING 100.97.192.4 (100.97.192.4) 56(84) bytes of data.
^C
--- 100.97.192.4 ping statistics ---
7 packets transmitted, 0 received, 100% packet loss, time 5999ms
```

The connection is ok in proxy server

```
$ ping 100.97.192.4
PING 100.97.192.4 (100.97.192.4) 56(84) bytes of data.
64 bytes from 100.97.192.4: icmp_seq=1 ttl=57 time=146 ms
64 bytes from 100.97.192.4: icmp_seq=2 ttl=57 time=146 ms
```

I hope there is a way to use proxy for acme challenge.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.0-rc2
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2017-12-06_03:07:42PM
OS/Arch:      linux/amd64
```

**Comment by Juliens** [comment] 2018-01-18 09:49
duplicate of #1110

**Closed by Juliens** 2018-01-18 09:49 UTC
Labels: area/acme, status/0-needs-triage
