### ISSUE TITLE
Documentation: There exists two user guides for docker swarm cluster which is confusing

### ISSUE THREAD

**Issue by thernstig** [containous/traefik#4057] opened 2018-10-16 20:33 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Read the documents at:
- https://docs.traefik.io/user-guide/swarm-mode/
- https://docs.traefik.io/user-guide/swarm/

Both are very similar and it adds no value to have both as they describe the same thing.

Also, the name in the table of contents to the left should most likely say "Docker Swarm..." and not just "Swarm..." to be more specific.

Also, https://docs.traefik.io/user-guide/swarm/ does not at all specify that `swarmMode = true` needs to be set (as explained here https://docs.traefik.io/configuration/backends/docker/#docker). But the other guide does do it correctly.

**Comment by nmengin** [comment] 2018-10-17 16:28
Hello @thernstig ,

Many thanks for your interest in the project.

As you maybe already know, [Docker Swarm](https://github.com/docker/swarm) is different than [Docker Swarm Mode](https://docs.docker.com/engine/swarm/) that's why it exist two differentes entries in the documentation.

> Also, https://docs.traefik.io/user-guide/swarm/ does not at all specify that `swarmMode = true` needs to be set 

It is because the option `swarmMode` is not necessary in Docker Swarm which is based on the same API as Docker Engine.

If you have questions and need community support, you can join our [Slack workspace](https://slack.traefik.io/) and reach out to us on the [#support channel](https://traefik.slack.com/messages/C0CDT22PJ/).

I guess the issue is solved and I close it.

**Closed by nmengin** 2018-10-17 16:28 UTC
Labels: status/0-needs-triage

**Comment by thernstig** [comment] 2018-10-17 19:52
@nmengin Thank you for Traefik, it's an awesome tool! I'd like to elaborate on this issue. I can now understand the distinction there. However, Docker Swarm is for Docker 1.11 and below, see https://docs.docker.com/swarm/overview/. As such, Docker Swarm Mode has been the default since Docker 1.12. As such maybe the document https://docs.traefik.io/user-guide/swarm/ should be deprecated completely as to not confuse readers? In a sense they are the same, but just for different versions of Docker. I did not find that clear.

The second topic is as to maybe the actual link in the table of contents should still be changed to append the term "Docker" infront of them to make it immediately obvious?
