### ISSUE TITLE
enhance redirectScheme

### ISSUE THREAD

**Issue by MohamedMSaeed** [containous/traefik#6122] opened 2020-01-02 12:24 UTC
### Do you want to request a *feature* or report a *bug*?
Feature

### Case:
I'm using Traefik v2.0.6 with Kubernetes. 

I'm trying to use redirectScheme to redirect all HTTP requests to HTTPS. 

While configuring it, I faced too many redirects issue which was solved by creating 2 IngressRoutes. One for HTTP with applying redirect middleware and the other for https with no middlewares. 

### What did you expect to see?
I expect to use one IngressRout for both. The redirectScheme middleware should detect if the request is http then redirect. if it is https then do nothing. 

Thanks

**Comment by SantoDE** [comment] 2020-01-02 15:45
Hey @MohamedMSaeed,

thanks for your interest in the project.

Can you please provide my with your IngressRoute definitions?

**Comment by ldez** [comment] 2020-01-02 16:32
Duplicate of #4863

**Closed by ldez** 2020-01-02 16:32 UTC
Labels: contributor/need-more-information, status/0-needs-triage
