### ISSUE TITLE
Traefik can not start

### ISSUE THREAD

**Issue by tbouvet** [containous/traefik#902] opened 2016-11-25 10:16 UTC
> docker -v
```
Docker version 1.12.3, build 6b644ec
```
>  docker exec -it swarm-agent-master /swarm -v
```
swarm version 1.2.5 (27968ed)
```
When I'm starting traefik I have errors in the log and traefik does not start.

```
Attaching to traefik-1
traefik-1 | time="2016-11-25T10:05:36Z" level=info msg="Traefik version v1.1.0 built on 2016-11-18_09:20:46AM"
traefik-1 | time="2016-11-25T10:05:36Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml"
traefik-1 | time="2016-11-25T10:05:36Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}"
traefik-1 | time="2016-11-25T10:05:36Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc420304f00 Redirect:<nil> Auth:<nil> Compress:false}"
traefik-1 | time="2016-11-25T10:05:36Z" level=info msg="Starting server on :80"
traefik-1 | time="2016-11-25T10:05:36Z" level=info msg="Starting server on :443"
traefik-1 | time="2016-11-25T10:05:36Z" level=info msg="Starting provider *provider.Docker {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"tcp://xx.xx.xx.xx:3376\",\"Domain\":\"mydomain.com\",\"TLS\":{\"CA\":\"/etc/ssl/ca.pem\",\"Cert\":\"/etc/ssl/cert.pem\",\"Key\":\"/etc/ssl/key.pem\",\"InsecureSkipVerify\":false},\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":false}"
traefik-1 | time="2016-11-25T10:05:36Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null}"
traefik-1 | time="2016-11-25T10:05:36Z" level=warning msg="Error checking new version: Get https://update.traefik.io/repos/containous/traefik/releases: dial tcp: lookup update.traefik.io on 127.0.0.11:53: no such host"
traefik-1 | time="2016-11-25T10:05:36Z" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
traefik-1 | goroutine 50 [running]:
traefik-1 | runtime/debug.Stack(0x4e668f, 0xc42000e6e0, 0xe75a83)
traefik-1 |       /usr/local/go/src/runtime/debug/stack.go:24 +0x79
traefik-1 | runtime/debug.PrintStack()
traefik-1 |       /usr/local/go/src/runtime/debug/stack.go:16 +0x22
traefik-1 | github.com/containous/traefik/safe.defaultRecoverGoroutine(0xd291a0, 0xc42000a030)
traefik-1 |       /go/src/github.com/containous/traefik/safe/routine.go:135 +0x7d
traefik-1 | github.com/containous/traefik/safe.GoWithRecover.func1.1(0xedc6d8)
traefik-1 |       /go/src/github.com/containous/traefik/safe/routine.go:126 +0x57
traefik-1 | panic(0xd291a0, 0xc42000a030)
traefik-1 |       /usr/local/go/src/runtime/panic.go:458 +0x243
traefik-1 | github.com/containous/traefik/provider.parseContainer(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
traefik-1 |       /go/src/github.com/containous/traefik/provider/docker.go:586 +0x2ed
traefik-1 | github.com/containous/traefik/provider.listContainers(0x7f41ab872028, 0xc42000a3e8, 0x7f41ab6878a0, 0xc4204ae480, 0xc4204ae480, 0xc4204067c8, 0x4, 0xc4204067f0, 0x7)
traefik-1 |       /go/src/github.com/containous/traefik/provider/docker.go:545 +0x35a
traefik-1 | github.com/containous/traefik/provider.(*Docker).Provide.func1.1(0xc4204ae300, 0x42a058)
traefik-1 |       /go/src/github.com/containous/traefik/provider/docker.go:141 +0xf1c
traefik-1 | github.com/containous/traefik/vendor/github.com/cenk/backoff.RetryNotify(0xc4203f1000, 0x12e2820, 0xc4203f81b0, 0xedc658, 0xc420495f48, 0x63f18f)
traefik-1 |       /go/src/github.com/containous/traefik/vendor/github.com/cenk/backoff/retry.go:32 +0x3f
traefik-1 | github.com/containous/traefik/provider.(*Docker).Provide.func1()
traefik-1 |       /go/src/github.com/containous/traefik/provider/docker.go:233 +0x132
traefik-1 | github.com/containous/traefik/safe.GoWithRecover.func1(0xedc6d8, 0xc4203f0fe0)
traefik-1 |       /go/src/github.com/containous/traefik/safe/routine.go:129 +0x4d
traefik-1 | created by github.com/containous/traefik/safe.GoWithRecover
traefik-1 |       /go/src/github.com/containous/traefik/safe/routine.go:130 +0x49
```

**Comment by vdemeester** [comment] 2016-11-25 14:20
@tbouvet could you provide your traefik configuration ?

**Comment by tbouvet** [comment] 2016-11-25 14:34
```
################################################################
# Global configuration
################################################################

logLevel = "INFO"

defaultEntryPoints = ["http"]

InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/ssl/certs/mydomain.cert"
      KeyFile = "/etc/ssl/certs/mydomain.key"

################################################################
# Web configuration backend
################################################################

[web]

address = ":8080"

################################################################
# Docker configuration backend
################################################################

[docker]

endpoint = "tcp://xx.xx.xx.xx:3376"

domain = "mydomain.com"

watch = true
swarmmode = false
exposedbydefault = true

[docker.tls]
  ca = "/etc/ssl/ca.pem"
  cert = "/etc/ssl/cert.pem"
  key = "/etc/ssl/key.pem"

```

**Comment by vdemeester** [comment] 2016-11-25 14:36
@tbouvet thanks :angel: Cannot reproduce the error yet. Which kind of image are you running ? do then have *healthchecks* for example ? (or something out of the ordinary)

**Comment by tbouvet** [comment] 2016-11-25 15:06
apache and custom images

**Comment by emilevauge** [comment] 2016-11-26 19:34
@tbouvet which version of traefik?

**Comment by tbouvet** [comment] 2016-11-28 10:24
Traefik version : v1.1.0

**Comment by emilevauge** [comment] 2016-11-28 20:28
@tbouvet I created a Docker image `containous/traefik:swarm` with a fix from #908. We would love if you could test and give us some feedback as we can't reproduce your issue.

**Comment by tbouvet** [comment] 2016-11-29 10:21
@emilevauge I have installed this image. Now I'm waiting some days to see if it's better. Thanks !

**Comment by emilevauge** [comment] 2016-11-29 11:33
@tbouvet then can we consider this issue solved by #908 ?

**Comment by tbouvet** [comment] 2016-11-29 13:07
I will do some tests and I will answer you.

**Comment by emilevauge** [comment] 2016-12-02 15:53
@tbouvet Can we close this one ? #908 has been merged and release in v1.1.1.

**Comment by tbouvet** [comment] 2016-12-05 07:59
@emilevauge ok now, traefik can start. 
But sometimes, traefik is not updating when applications start or stop. So I need to stop/start traeifk and then it's ok.

**Comment by emilevauge** [comment] 2016-12-05 08:39
@tbouvet thanks for your feedback, if you have any other issue, please open a new one on GitHub :)

**Closed by emilevauge** 2016-12-05 08:39 UTC
Labels: bug, priority/P0, provider/docker
