### ISSUE TITLE
Support for entryPoints whitelist

### ISSUE THREAD

**Issue by Shawak** [containous/traefik#5616] opened 2019-10-09 15:20 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Support for entryPoint whitelists in version 2.0

```
      - traefik.entryPoints.http.whitelist.sourceRange=<ip>
      - traefik.entryPoints.http.whitelist.useXForwardedFor=true
```

**Comment by Sarke** [comment] 2019-10-10 01:43
Do you mean this: https://docs.traefik.io/routing/entrypoints/#forwarded-header ?

**Comment by Shawak** [comment] 2019-10-10 06:14
No, that's not an ip whitelist.

**Comment by Sarke** [comment] 2019-10-10 16:33
Ok, then https://docs.traefik.io/middlewares/ipwhitelist/ ?

**Comment by Shawak** [comment] 2019-10-10 18:43
That's what I'm using right now, but if you forget setting it up (correctly) you expose your services to the public.

**Comment by OverloadUT** [comment] 2020-05-02 21:05
A limitation that I am encountering with the whitelist middleware is that it seems to be impossible to have Traefik switch entrypoints _based_ on the whitelist IP. In other words, I want to have a public and private entrypoint, with the private entrypoint only used for internal IPs. Then I can have routers configured to only live on the private entrypoint for all of my internal services.

This is desirable because I'd rather have external requests to internal services get rejected by the entrypoint as a 404 than a 403 forbidden, as the former doesn't expose that a service is living there at all.

It seems like having the whitelist at the entryPoint level would solve this.

Am I going about this the wrong way?

**Comment by ldez** [comment] 2020-05-04 15:53
In v2.2.x, the problem is fixed: you can now use middlewares on entrypoints.

https://docs.traefik.io/v2.2/routing/entrypoints/#middlewares

Closed by 6417

**Closed by ldez** 2020-05-04 15:53 UTC
Labels: area/middleware, kind/enhancement, priority/P3
