### ISSUE TITLE
Dynamic DNS entries

### ISSUE THREAD

**Issue by DblK** [containous/traefik#2180] opened 2017-09-27 15:40 UTC
### Feature request

In internal network, some container are deployed and use `traefik.frontend.rule=Host:*`.
I have to manually update the private DNS server to add those new hosts.

I would like traefik to handle this matter for me automatically.
It should work something similar to `dnsProvider` on the `acme` section.

### Suggested implementation

```toml
[dns]
provider = "pdns"
```
It will need the same environment variables as for `acme` ([dnsprovider](https://docs.traefik.io/configuration/acme/#dnsprovider))
In this case, `PDNS_API_KEY`, `PDNS_API_URL`.

**Comment by ldez** [comment] 2017-09-27 15:45
duplicate of #1191, #1205

**Closed by ldez** 2017-09-27 15:45 UTC
Labels: resolution/duplicate

**Comment by johannges** [comment] 2018-05-28 06:58
#1191 and #1205 are about a DNS inside Traefik. 
This Issue is about Traefik manageing Entries inside an External DNS like DuckDns. For me this is an extremely important feature.

**Comment by milewski** [comment] 2018-08-24 18:03
I'm also in need of this feature... Meanwhile does anyone knows about any tool that severs nicely for this purpose?

**Comment by DblK** [comment] 2018-08-26 14:11
If it should be done automatically, you can use terraform with the various dns provider to interact with the dns provider.

**Comment by SvenDowideit** [comment] 2018-09-12 13:16
I think #1287 covers this better than the others
