### ISSUE TITLE
Auth should be per frontend, not per entrypoint

### ISSUE THREAD

**Issue by Yajo** [containous/traefik#1346] opened 2017-03-27 12:27 UTC
### What version of Traefik are you using (`traefik version`)?
1.2

### What is your environment & configuration (arguments, toml...)?
Docker Swarm.

### What did you do?
I wanted to require a client cert for accessing `/web/*` under some (not all) microservices. All of them are on port 443.

### What did you expect to see?
Some way to do that.

### What did you see instead?
Same auth for all services running behind an entrypoint. Makes not much sense IMHO... 🤔

**Comment by timoreimann** [comment] 2017-04-15 19:42
Duplicate of #751. Closing.

**Closed by timoreimann** 2017-04-15 19:42 UTC
