### ISSUE TITLE
HTTPS with auth basic

### ISSUE THREAD

**Issue by truhlikfredy** [containous/traefik#735] opened 2016-10-15 23:54 UTC
When using auth basic (htdigest) with http it works well, but the moment is used on https then is just keeps in a loop asking for the auth all the time.

**Comment by emilevauge** [comment] 2016-10-17 12:36
@truhlikfredy it works as expected on my laptop.
Can you give me your toml file?

**Comment by truhlikfredy** [comment] 2016-10-17 15:43
Ok I will try to get some minimal config where I can still reproduce it.

**Comment by f3l1x** [comment] 2016-10-24 19:30
```
logLevel = "DEBUG"
debug = true
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80" 
    [entryPoints.http.auth.basic]
      users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/", "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"]

################################################################
# Web configuration backend
################################################################

[web]
 address = ":8080"

[web.auth.basic]
users = ["test:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"]
```

No required auth for WebUI and neither for entrypoint. :( Tested on v1.0.2 and v1.0.3 as well.

**Comment by f3l1x** [comment] 2016-10-24 19:33
`traefik:v1.1.0-rc2` works

**Comment by truhlikfredy** [comment] 2016-10-24 20:24
But that is auth just on http. The setup I mean was to have HTTP redirect to HTTPS and have the auth on HTTPS


```
  [entryPoints.https]
    address = ":443" 
    [entryPoints.https.auth.basic]
      users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/", "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"]

```

**Comment by f3l1x** [comment] 2016-11-15 13:03
Unfortunaly, 1.1.0-rc4 is broken. Basic authentication popup showed up, but then I see only this:
![selection_002](https://cloud.githubusercontent.com/assets/538058/20306756/4ff65756-ab3c-11e6-9821-46feb3d4aa30.png)

**Comment by emilevauge** [comment] 2016-11-15 13:07
@f3l1x sorry, there is a bug in rc4 with webui (already fixed) :'( #796

**Comment by f3l1x** [comment] 2016-11-15 13:13
@emilevauge No problem. Have you any roadmap? Cannot wait until to next release. :rocket:

**Comment by emilevauge** [comment] 2016-11-15 13:15
@f3l1x v1.1 should be out this week or next week if no bug is found ;)

**Comment by viglesiasce** [comment] 2016-11-21 08:30
I was able to reproduce this with the following config. HTTP works fine but HTTPS returns 401:

```
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.auth.basic]
    users = ["test:$apr1$JNHCZzL/$PgzSN/asgdVPM6DoBAYVu1"]
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.auth.basic]
    users = ["test:$apr1$JNHCZzL/$PgzSN/asgdVPM6DoBAYVu1"]
    [entryPoints.https.tls]
[acme]
  email = "example@email.com"
  storage = "/etc/traefik/acme/acme.json"
  entryPoint = "https"
  OnHostRule = true
```

**Comment by ldez** [comment] 2017-06-02 14:41
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Closed by ldez** 2017-06-02 14:41 UTC
Labels: area/authentication, investigation-needed
