### ISSUE TITLE
2 Frontends for the same backend seems to missbehave ( at least on redirects

### ISSUE THREAD

**Issue by EugenMayer** [containous/traefik#3357] opened 2018-05-20 15:43 UTC
Bug

### What did you do?

While this one will never redirect and even use the redirect SSL rule from the `frontends.goedit` backend no matter what is defined in `frontends.goedit_help`

```
[backends]
  [backends.goedit]
    [backends.goedit.servers.server1]
      url = "https://10.1.4.11:443"

[frontends]
  [frontends.goedit_help]
    entrypoints = ["http","https"]
    backend = "goedit"
    passHostHeader=true
    [frontends.goedit_help.redirect]
      regex = "^https://help.goedit.io/(.*)$"
      replacement = "https://goedit.drupal-wiki.com"
      permanent = true
    [frontends.goedit_help.routes.test_1]
      rule = "Host:help.goedit.io"
  [frontends.goedit]
    entrypoints = ["http","https"]
    backend = "goedit"
    passHostHeader=true
    [frontends.goedit.routes.test_1]
      rule = "Host:goedit.io,www.goedit.io,download.goedit.io"
    [frontends.goedit.headers]
      SSLRedirect = true
```

Thats the working example by just introducing a (non needed) second backend.
It is not needed since i only want to have a redirect, the backend should never get used.

```
[backends]
  [backends.goedit]
    [backends.goedit.servers.server1]
      url = "https://10.1.4.11:443"
  [backends.goedit_help]
    [backends.goedit_help.servers.server1]
      url = "https://10.1.4.11:443"


[frontends]
  [frontends.goedit_help]
    entrypoints = ["http","https"]
    backend = "goedit_help"
    passHostHeader=true
    [frontends.goedit_help.redirect]
      regex = "^https://help.goedit.io/(.*)$"
      replacement = "https://goedit.drupal-wiki.com"
      permanent = true
    [frontends.goedit_help.routes.test_1]
      rule = "Host:help.goedit.io"
    [frontends.goedit_help.headers]
      SSLRedirect = true
  [frontends.goedit]
    entrypoints = ["http","https"]
    backend = "goedit"
    passHostHeader=true
    [frontends.goedit.routes.test_1]
      rule = "Host:goedit.io,www.goedit.io,download.goedit.io"
    [frontends.goedit.headers]
      SSLRedirect = true
```

### What did you expect to see?
That the first example works and the defined `[frontends.goedit_help.redirect]` works.
It will though never redirect - there seems to be a odd link/dependency with the backend ( which would not make sense here technically )

This should be there for `curl -vvk -L https://help.goedit.io/asasd` 

```
< HTTP/1.1 302 Found
< Cache-Control: no-cache, must-revalidate, post-check=0, pre-check=0
< Content-Type: text/html; charset=utf-8
< Date: Sun, 20 May 2018 15:35:24 GMT
< Etag: "1526830524"
< Last-Modified: Sun, 20 May 2018 15:35:24 +0000
< Location: https://goedit.drupal-wiki.com/browser_not_supported
< Server: Apache
```

### What did you see instead?

```
$ curl -vvk -L https://help.goedit.io/asasd                                                                                                                         [17:42:01]
*   Trying 144.76.74.30...
* TCP_NODELAY set
* Connected to help.goedit.io (144.76.74.30) port 443 (#0)
* WARNING: disabling hostname validation also disables SNI.
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: TRAEFIK DEFAULT CERT
> GET /asasd HTTP/1.1
> Host: help.goedit.io
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Length: 168
< Content-Type: text/html
< Date: Sun, 20 May 2018 15:41:59 GMT
< Server: nginx/1.6.2
<
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
* Connection #0 to host help.goedit.io left intact
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik version                                                                                                                                         [17:42:27]
Version:      v1.6.0
Codename:     tetedemoine
Go version:   go1.10.1
Built:        2018-04-30_09:28:44PM
OS/Arch:      linux/amd64
```

**Comment by ldez** [comment] 2018-05-20 16:08
Duplicate of ##2323

**Closed by ldez** 2018-05-20 16:08 UTC
Labels: status/0-needs-triage
