### ISSUE TITLE
websocket proxy

### ISSUE THREAD

**Issue by SergeVL** [containous/traefik#3538] opened 2018-06-28 08:09 UTC
There is problem in used gorilla/websocket package for proxying websocket traffic.
I start bug report [Fragment Size is not buffer size](https://github.com/gorilla/websocket/issues/395).
And I thing you should be aware of.

**Comment by traefiker** [comment] 2018-06-28 08:45
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Træfik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by dduportal** [comment] 2018-07-30 16:40
Hi @SergeVL . Thanks for reporting this issue.

I am closing this issue for 2 reasons:

- As specified by the traefiker's Bot, we would need you to use the templates to fill issues. It would help the project to track, fix, collect and analyse issues over time.
- This bug is caused by an upstream dependency. As soon as your fix in gorilla/websocket would have been fixed, we'll update Træfik's to benefit from the dependency's fix.

**Closed by dduportal** 2018-07-30 16:40 UTC
Labels: area/websocket, kind/bug/confirmed, priority/P3

**Comment by SergeVL** [comment] 2018-07-30 16:57
You use  gorilla/websocket constructor without parameters and by default buffers has size just 4K.

At least you can add configuration parameters for this.

**Comment by dduportal** [comment] 2018-07-30 17:16
Hello @SergeVL , as explained on my previous message and by the bot's message, we need your help as you are a potential contributor as well as any other current maintainers.

Could you please help the project by opening an issue using the default's message template? It would help us to prioritize and follow user requests, as it looks like you are giving us a valuable tip.

Thanks in advance
