### ISSUE TITLE
Docker container w. multiple networks, route to wrong IP

### ISSUE THREAD

**Issue by kristoferlundgren** [containous/traefik#1156] opened 2017-02-13 00:15 UTC
### What version of Traefik are you using (`traefik version`)?
1.1.2 (docker "traefik:latest" as of 20170213)

### What is your environment & configuration (arguments, toml...)?
docker 1.13.1
docker-compose-traefik.yml

```yaml
version: "3"

services:

  traefik:
    image: traefik:latest
    command:
      --web --docker --docker.watch --docker.swarmmode --docker.domain=traefik --logLevel=DEBUG --accesslogsfile=/dev/stdout
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx-1:
    image: nginx:latest
    networks:
      - traefik-net
      - db-net
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=PathStrip:/nginx-1"
        - "traefik.docker.network=traefik-net"

  nginx-2:
    image: nginx:latest
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=PathStrip:/nginx-2"
        - "traefik.docker.network=traefik-net"

  db:
    image: alpine:latest
    networks:
      - db-net
    command:
      sleep 120

networks:
  traefik-net:
    driver: overlay
  db-net:
    driver: overlay
```

### What did you do?
Start a docker service with multiple networks (multiple virtual IPs), one for frontend and one backend network for database connectivity.

```
docker swarm init
docker stack deploy -c docker-compose-traefik.yml traefik
```

### What did you expect to see?
Accessing http://localhost/nginx-1 and http://localhost/nginx-2 should consistently get a web page.

### What did you see instead?
http://localhost/nginx-1 access is not routed to designated network set by "traefik.docker.network=traefik-net". Instead, traffic is routed to wrong virtual IP. No access, i.e. "Gateway Timeout".

Traffic is occasionally directed to the right network, docker log of traefik container includes:
```shell
time="2017-02-12T23:55:44Z" level=debug msg="Configuration received from provider docker: {\"backends\":{\"backend-traefik-nginx-1\":{\"servers\":{\"server-traefik_nginx-1\":{\"url\":\"http://10.0.1.2:80\" [...]
time="2017-02-12T23:55:59Z" level=debug msg="Configuration received from provider docker: {\"backends\":{\"backend-traefik-nginx-1\":{\"servers\":{\"server-traefik_nginx-1\":{\"url\":\"http://10.0.0.2:80\" [...]
time="2017-02-12T23:56:14Z" level=debug msg="Configuration received from provider docker: {\"backends\":{\"backend-traefik-nginx-1\":{\"servers\":{\"server-traefik_nginx-1\":{\"url\":\"http://10.0.1.2:80\" [...]
```

Typing "docker service inspect traefik_nginx-1" reveals (amongst other) the two virtual IPs:
```
[...]
            "VirtualIPs": [
                {
                    "NetworkID": "v6ashuultlonotwo4o4lhx390",
                    "Addr": "10.0.1.2/24"
                },
                {
                    "NetworkID": "507sn1hhj5biksrildthrvgeb",
                    "Addr": "10.0.0.2/24"
                }
[...]
```

**Comment by donnex** [comment] 2017-02-16 10:56
I'm having the same issue. This problem makes it impossible to use traefik in both prod and dev.

I'm also using multiple networks with Docker and traefik seems to pick a random IP when routing the backend. For example in this docker-compose setup it picked my hard coded IP instead of the IP the container was assigned when joining the traefik_webgateway network.

```
    networks:
      default:
        ipv4_address: 172.26.0.5
      traefik_webgateway:
```

**Comment by SantoDE** [comment] 2017-02-20 20:11
This is possibly related (and to be fixed by #1171) I guess?

**Comment by kristoferlundgren** [comment] 2017-02-20 23:03
@donnex, this issue relates to docker services. Happy to see you found the traefik.docker.network= option!

@SantoDE, #1171 does indeed look related. Although the original issue it solves (#979) only mentions setting a default network to connect to. Hopefully the fix also includes actively selecting the network per service as well.

**Comment by zweizeichen** [comment] 2017-03-04 18:41
I can confirm this issue. Same with Docker `17.03.0-ce`. Setting `traefik.docker.network`on the service's containers has no effect. Traefik seems to pick a random IP each time I start the services, so sometimes it will pick the correct IP and sometimes not. Interestingly this seems to only affect services connected to multiple networks.

**Comment by CyrilPeponnet** [comment] 2017-03-16 00:37
I'm hitting the same issue but from code I can see

```
			network := networkSettings.Networks[label]
```

If you check your container with inspect the network is prefixed with the stack name. So try with `stack`-`network_name` instead especially if you are using the same stack for both traefik and a container as backend.

In my case I have stack for traefik with:

```
networks:
  backend:
      driver: overlay
```

When deploying the stack with `docker stack deploy -c traefik.yaml proxy` it's named proxy_backend.

On another stack publishing services I have:

```
networks:
  backend:
    driver: overlay
  traefik_backend:
    external:
      name: proxy_backend
  workers:
    external:
      name: workers
```

The service I want to publish have:

```
    networks:
      - traefik_backend
      - backend
      - workers
```

So I added the label `traefik.docker.network=proxy_backend` and it works fine now.

**Comment by zweizeichen** [comment] 2017-03-17 15:34
Just verified @CyrilPeponnet's solution. Docker (-compose) automatically prefixes all your networks with your project's name. By default this is derived from the name of the directory the compose file is located in:

> Note: Your app’s network is given a name based on the “project name”, which is based on the name of the directory it lives in. You can override the project name with either the --project-name flag or the COMPOSE_PROJECT_NAME environment variable.

From: https://docs.docker.com/compose/networking/

For services which are on multiple networks you now need to explicitly specify the network's name _including_ the prefix:

`- "traefik.docker.network=proxy"`

becomes

`- "traefik.docker.network=PROJECT_NAME_proxy"`

Which is confusing, since you're referring the non-prefixed version of the network's name everywhere else in the file, however labels obviously don't get automatically converted when you run your services. So this whole issue is more a usability issue than a bug I guess.
Maybe we could add a friendly warning around [here](https://github.com/containous/traefik/blob/2a61c9049f119b6e57c7d086f2c07f2086d7b2c1/provider/docker.go#L544) when a label specifies a network's name, but the network could not be found. ATM it just 'falls through' to the default case, thus resulting in the seemingly random behaviour. I made a PR including that warning (#1308).

**Comment by ldez** [comment] 2017-06-09 13:05
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Closed by ldez** 2017-06-09 13:05 UTC
Labels: area/provider/docker

**Comment by narramadan** [comment] 2017-11-19 18:46
I am facing the same issue when running `docker stack deploy --compose-file docker-compose.yml someservice`.

Unless I specify label as `- "traefik.docker.network=someservice_proxy"` as proposed by zweizeichen, I am receiving Gateway Timeout error.

Is this the right way to do - appending the project name or name of stack as prefix to `traefik.docker.network` ? As we might change the name of the stack as per user needs and thus they need to modify the docker-compose.yml file.

Is there any other alternative instead of hard-coding it in `docker-compose.yml` file ?

**Comment by zaggash** [comment] 2017-11-21 16:26
I have the exact same issue with only one network  with swam enabled.
17.09.0-ce
traefik 1.4.2

I have to hardcode the label "traefik.docker.network" which is not expected
If the stack name change the whole setup fall appart.

**Comment by yamac-kurtulus** [comment] 2018-07-11 11:17
@zaggash it is a bit late at the moment, however a work around could be to use an environment variable for the stack name
