### ISSUE TITLE
[Bug] X-Forwarded-Host is missing port number

### ISSUE THREAD

**Issue by Starefossen** [containous/traefik#1365] opened 2017-03-30 11:12 UTC
### What version of Traefik are you using (`traefik version`)?

```
Træfik v1.2.1
```

### What is your environment & configuration (arguments, toml...)?

```
Kubernetes 1.5.4
```

[Træfik Configuration](https://gist.github.com/Starefossen/79a1dc7af3ce2a03583dc9b1dec7bca8)

### What did you do?

Set up ingress routing for [`echo-server`](https://console.cloud.google.com/gcr/images/google-containers/global/echoserver?project=google-containers) (similar to `emilevauge/whoami`).

[Echo Server Configuration](https://gist.github.com/Starefossen/09c07ad163d60155ec9b8c993baf62d9)

### What did you expect to see?

`X-Forwareded-Host` header with port number similar to whats [in the documentation](https://github.com/containous/traefik/blob/master/docs/index.md#test-it).

### What did you see instead?

`X-Forwareded-Host` header without port number.

**Comment by Juliens** [comment] 2017-06-12 12:35
When https://github.com/containous/oxy/pull/16 will be merged, you will find X-Forwarded-Port.

But the doc still need to be fixed.

**Comment by ldez** [comment] 2017-08-05 07:49
Duplicate of #1220

**Closed by ldez** 2017-08-05 07:49 UTC
Labels: area/middleware, resolution/duplicate

**Comment by kaendfinger** [comment] 2018-02-18 03:01
This is against the standard I think, the port should be included in X-Forwarded-Host, per MSDN:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host
"Host names and ports of reverse proxies (load balancers, CDNs) may differ from the origin server handling the request, in that case the X-Forwarded-Host header is useful to determine which Host was originally used."
