### ISSUE TITLE
proper route creation with kubernetes provider

### ISSUE THREAD

**Issue by travisghansen** [containous/traefik#6507] opened 2020-03-17 17:17 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Create an `Ingress` with a `tls` block.

### What did you expect to see?

Per `kubectl`

```
NAME       HOSTS                               ADDRESS       PORTS     AGE
httpbin    httpbin.foo.bar.aaaaaaaaaaaa.com    172.28.45.2   80, 443   4d19h
```

So the `Ingress` is considered available on both ports `80` and `443` (as it should I believe).

### What did you see instead?

A single `route` gets created in `traefik` which appears to have `tls` configuration bound to it (based on dashboard ui). This leaves the service generally unavailable on port `80` in the standard sense.  It **is** available, but is required to be accessed via `https` on port `80`.

ie: `curl -v 'https:// httpbin.foo.bar.aaaaaaaaaaaa.com:80` works, `curl -v 'http:// httpbin.foo.bar.aaaaaaaaaaaa.com` sits indefinitely as I recall.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.2.0-rc2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Using the `kubernetes` provider installed via the new helm chart.

I think the general issue leading to this is that operating in `Ingress` mode the scope is perhaps trying to be a bit too much. Not sure. It feels as if operating with the `kubernetes` provider needs to perhaps *imply* a handful of configuration/options and narrow things down a bit on the configuration front.

Ideally (based on my limited knowledge of how 2.x works currently) in the scenario described above 2 `routes` would be created and attached to the correct entrypoints of `web` and `websecure` with the `websecure` route being flagged as `tls` and the `web` route not being flagged as `tls`. None of them bound to the `traefik` entrypoint at all.

Thoughts? Am I simply configuring something wrong?

**Comment by ldez** [comment] 2020-03-17 17:32
duplicate of #6501

**Closed by ldez** 2020-03-17 17:32 UTC
Labels: status/0-needs-triage
