### ISSUE TITLE
deny url or return status in IngressRoute 

### ISSUE THREAD

**Issue by zhengqisong** [containous/traefik#6659] opened 2020-04-10 03:13 UTC
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?
Deny url in IngressRoute
Send status  in IngressRoute

Deny url  like nginx config
```
server {
    listen       80;
    server_name  my.domain.com;
    location ^~ /monitor {
       deny all;
    }
    location ^~ /hystrix {
       deny all;
    }
    location ^~ /druid {
       deny all;
    }
    location /404url {
            return 404;
    }
    location / {            
        proxy_pass http://myserver;
    }
}
```

**Comment by ldez** [comment] 2020-04-10 07:43
Duplicate of #4812

**Closed by ldez** 2020-04-10 07:43 UTC
Labels: resolution/duplicate
