### ISSUE TITLE
server return 502, when HostRegexp contains domain like "{subdomain:[a-z]+}.traefik.com.cn" 

### ISSUE THREAD

**Issue by toby1991** [containous/traefik#1131] opened 2017-02-07 10:04 UTC
### configuration:  

```yml
label:
  - "traefik.backend=nginx"
  - "traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.traefik.com,traefik.com,{subdomain:[a-z]+}.traefik.com.cn,traefik.com.cn"
```

## Problem:  
If I add `{subdomain:[a-z]+}.traefik.com.cn,traefik.com.cn` to `traefik.frontend.rule=HostRegexp:`, the server went down, and return 502 bad gateway.   
But when I remove `,{subdomain:[a-z]+}.traefik.com.cn,traefik.com.cn`, the server goes well.

**It seems like traefik doesn't support domain ".com.cn" ?**

### What did you expect to see?
200

### What did you see instead?
502

**Comment by toby1991** [comment] 2017-02-07 10:07
One more question, 
the server will redirect 
`http://m.traefik.com/#!/blablabla` to `http://m.traefik.com/#/!/blablabla`  
who to fix it by modifying the configuration ?

**Comment by emilevauge** [comment] 2017-03-01 10:48
@toby1991 
Trying to reproduce this:
```
docker run -d -l "traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.traefik.com,traefik.com,{subdomain:[a-z]+}.traefik.com.cn,traefik.com.cn" -l traefik.backend=test emilevauge/whoami

curl -H "Host:test.traefik.com.cn" http://localhost:8001
Hostname: 48c3fd1f25df
IP: 127.0.0.1
IP: ::1
IP: 172.17.0.2
IP: fe80::42:acff:fe11:2
GET / HTTP/1.1
Host: test.traefik.com.cn
User-Agent: curl/7.47.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: test.traefik.com.cn
X-Forwarded-Proto: http
X-Forwarded-Server: spectre

curl -H "Host:traefik.com.cn" http://localhost:8001
Hostname: 48c3fd1f25df
IP: 127.0.0.1
IP: ::1
IP: 172.17.0.2
IP: fe80::42:acff:fe11:2
GET / HTTP/1.1
Host: traefik.com.cn
User-Agent: curl/7.47.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: traefik.com.cn
X-Forwarded-Proto: http
X-Forwarded-Server: spectre
```

It seems to work as intended with `*.com.cn` domains on my local config.

**Comment by mikebranderhorst** [comment] 2017-03-08 13:07
I had this issue and solved it by defining port and protocol. For me somehow the default is 443 https. I don't know (yet) how to change the default though. But you can do this foreach project.
```
    labels:
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.traefik.com,traefik.com,{subdomain:[a-z]+}.traefik.com.cn,traefik.com.cn"
      - "traefik.protocol=http"
      - "traefik.port=80"

```

The debug message from the proxy

```
level=warning msg="Error forwarding to http://ipaddress:443, err: dial tcp ipaddress:443: getsockopt: connection refused"
```

**Comment by ldez** [comment] 2017-06-09 12:35
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Closed by ldez** 2017-06-09 12:35 UTC
Labels: area/rules, kind/question
