### ISSUE TITLE
v2.1.4 docker image

### ISSUE THREAD

**Issue by Lilja** [containous/traefik#6287] opened 2020-02-06 21:10 UTC
I saw in my logs that there was a new release but not a new docker image. Could we please get a new one? 😃

**Comment by ldez** [comment] 2020-02-06 22:40
duplicate of #5992, #5512, #5348 and many other issues like every time we create a new version.

So I will repeat once again:

The official Docker image is built by Docker it-self, it's the process for official images: https://github.com/docker-library/official-images

The official Docker image of Traefik is currently under construction in the Docker build system.

The process takes time, you have to wait a bit (few hours).

- The related PR in the Official Image repository: https://github.com/docker-library/official-images/pull/7427
- The Traefik page in the Jenkins of the Official Images: https://doi-janky.infosiftr.net/job/multiarch/view/images/view/traefik/

**Closed by ldez** 2020-02-06 22:40 UTC
Labels: status/0-needs-triage
