### ISSUE TITLE
Expiry for sticky session cookies

### ISSUE THREAD

**Issue by kishor-git** [containous/traefik#4666] opened 2019-03-26 11:20 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Installed traefik ingress controller using helm. Configured stickness in the ingress & service objects using below annotations.
service:
    "annotations": {
      "traefik.ingress.kubernetes.io/affinity": "true",
      "traefik.ingress.kubernetes.io/load-balancer-method": "drr",
      "traefik.ingress.kubernetes.io/max-conn-amount": "10",
      "traefik.ingress.kubernetes.io/session-cookie-name": "UNIQUE-PEGA-COOKIE-NAME"
    }
Ingress:
"annotations": {
      "kubernetes.io/ingress.class": "traefik"
    }

### What did you expect to see?

Sticky session are working. Though individual requests are not load balanced, different sessions should load balanced across the pods. It should work similar to jsession id. Which means, cookies used by traefik should be aged out after certain period or provide a mechanism to clear the cookies

### What did you see instead?
Traefik cookie is never expired or aged out or deleted hence all the requests are going to the same pod irrespective of various sessions or new browser windows, as long as browser cookies are delete manually for the given site.

### Output of `traefik version`: (_What version of Traefik are you using?_)
Traefik helm chart: traefik-1.52.8
Image: traefik:1.7.4

**Comment by mmatur** [comment] 2019-03-26 15:17
Duplicate of #1939

**Closed by mmatur** 2019-03-26 15:17 UTC
Labels: status/0-needs-triage
