### ISSUE TITLE
gcloud dns acme returns "Permission denied on resource" with valid credentials

### ISSUE THREAD

**Issue by MrFlutters** [containous/traefik#4753] opened 2019-04-09 18:02 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] no

### What did you do?
Attempted to use previously working configuration of traefik and gcloud credentials with docker-compose.
Generating new credentials **does not** fix this.

### What did you expect to see?

Correctly generated DNS certificates for domains using gcloud

### What did you see instead?

gcloud returning permission denied with what looks like invalid formatting as a response around the output

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.10
Codename:     maroilles
Go version:   go1.11.6
Built:        2019-03-29_12:20:34PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform,
My environment variables are
```
GCE_PROJECT="personal-207403"
GCE_SERVICE_ACCOUNT_FILE=/etc/traefik/traefik-data/GCE_ACC_FILE.json
```
I use command line arguments and not a toml file.
```
--api
--docker
--docker.exposedbydefault=false
--logLevel=DEBUG
--entryPoints=Name:http Address::80
--entryPoints=Name:https Address::443 TLS
--defaultentrypoints=http,https
--acme
--acme.acmelogging
--acme.entrypoint=https
--acme.storage=/etc/traefik/acme.json
--acme.dnschallenge
--acme.dnschallenge.provider=gcloud
--acme.dnschallenge.resolvers=8.8.8.8
--acme.domains=*.redacted_domain.com,redacted_domain.com
--acme.email=example@gmail.com
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
time="2019-04-09T17:41:34Z" level=info msg="Traefik version v1.7.10 built on 2019-03-29_12:20:34PM"
time="2019-04-09T17:41:34Z" level=debug msg="Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceTimeOut\":0,\"Debug\":false,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false,\"AccessLogsFile\":\"\",\"AccessLog\":null,\"TraefikLogsFile\":\"\",\"TraefikLog\":null,\"Tracing\":null,\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"https\":{\"Address\":\":443\",\"TLS\":{\"MinVersion\":\"\",\"CipherSuites\":null,\"Certificates\":[],\"ClientCAFiles\":null,\"ClientCA\":{\"Files\":null,\"Optional\":false},\"DefaultCertificate\":null,\"SniStrict\":false},\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}}},\"Cluster\":null,\"Constraints\":[],\"ACME\":{\"Email\":\"Example@gmail.com\",\"Domains\":[{\"Main\":\"*.redacted_domain.com\",\"SANs\":[\"redacted_domain.com\"]}],\"Storage\":\"/etc/traefik/acme.json\",\"StorageFile\":\"\",\"OnDemand\":false,\"OnHostRule\":false,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"EntryPoint\":\"https\",\"KeyType\":\"\",\"DNSChallenge\":{\"Provider\":\"gcloud\",\"DelayBeforeCheck\":0,\"Resolvers\":[\"8.8.8.8\"],\"DisablePropagationCheck\":false},\"HTTPChallenge\":null,\"TLSChallenge\":null,\"DNSProvider\":\"\",\"DelayDontCheckDNS\":0,\"ACMELogging\":true,\"OverrideCertificates\":false,\"TLSConfig\":null},\"DefaultEntryPoints\":[\"http\",\"https\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"IdleTimeout\":0,\"InsecureSkipVerify\":false,\"RootCAs\":null,\"Retry\":null,\"HealthCheck\":{\"Interval\":30000000000},\"RespondingTimeouts\":null,\"ForwardingTimeouts\":null,\"AllowMinWeightZero\":false,\"KeepTrailingSlash\":false,\"Web\":null,\"Docker\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15},\"File\":null,\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null,\"Mesos\":null,\"Eureka\":null,\"ECS\":null,\"Rancher\":null,\"DynamoDB\":null,\"ServiceFabric\":null,\"Rest\":null,\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Debug\":false,\"CurrentConfigurations\":null,\"Statistics\":null},\"Metrics\":null,\"Ping\":null,\"HostResolver\":null}"
time="2019-04-09T17:41:34Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-04-09T17:41:34Z" level=debug msg="Setting Acme Certificate store from Entrypoint: https"
time="2019-04-09T17:41:34Z" level=info msg="Preparing server https &{Address::443 TLS:0xc000230fc0 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc00066e820} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-04-09T17:41:34Z" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc00066eaa0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-04-09T17:41:34Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc00066e760} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-04-09T17:41:34Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
time="2019-04-09T17:41:34Z" level=info msg="Starting server on :443"
time="2019-04-09T17:41:34Z" level=info msg="Starting server on :8080"
time="2019-04-09T17:41:34Z" level=info msg="Starting server on :80"
time="2019-04-09T17:41:34Z" level=info msg="Starting provider *docker.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15}"
time="2019-04-09T17:41:34Z" level=info msg="Starting provider *acme.Provider {\"Email\":\"Example@gmail.com\",\"ACMELogging\":true,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"Storage\":\"/etc/traefik/acme.json\",\"EntryPoint\":\"https\",\"KeyType\":\"\",\"OnHostRule\":false,\"OnDemand\":false,\"DNSChallenge\":{\"Provider\":\"gcloud\",\"DelayBeforeCheck\":0,\"Resolvers\":[\"8.8.8.8\"],\"DisablePropagationCheck\":false},\"HTTPChallenge\":null,\"TLSChallenge\":null,\"Domains\":[{\"Main\":\"*.redacted_domain.com\",\"SANs\":[\"redacted_domain.com\"]}],\"Store\":{}}"
time="2019-04-09T17:41:34Z" level=info msg="Testing certificate renew..."
time="2019-04-09T17:41:34Z" level=debug msg="Configuration received from provider ACME: {}"
time="2019-04-09T17:41:34Z" level=debug msg="Looking for provided certificate(s) to validate [\"*.redacted_domain.com\" \"redacted_domain.com\"]..."
time="2019-04-09T17:41:34Z" level=debug msg="Domains [\"*.redacted_domain.com\" \"redacted_domain.com\"] need ACME certificates generation for domains \"*.redacted_domain.com,redacted_domain.com\"."
time="2019-04-09T17:41:34Z" level=debug msg="Loading ACME certificates [*.redacted_domain.com redacted_domain.com]..."
time="2019-04-09T17:41:34Z" level=info msg="The key type is empty. Use default key type 4096."
time="2019-04-09T17:41:34Z" level=debug msg="Provider connection established with docker 18.09.4 (API 1.39)"
time="2019-04-09T17:41:34Z" level=debug msg="originLabelsmap[com.docker.compose.version:1.24.0 org.label-schema.url:https://traefik.io traefik.enable:True com.docker.compose.config-hash:26b28418921e71b0480fc80ed84db16620a19470d7f2531c097266369f60225f org.label-schema.description:A modern reverse-proxy org.label-schema.vendor:Containous org.label-schema.version:v1.7.10 traefik.frontend.auth.basic.users:flutters:$apr1$O9/S6.gy$.bEMjIFtJx9wnknZlDFBR0,snailchan:$apr1$.T.pxQpP$864SZVYcYXjzis5exNrcv/ org.label-schema.docker.schema-version:1.0 traefik.backend:traefik-dashboard traefik.frontend.rule:Host:traefik.redacted_domain.com,traefik.docker-test-1.local traefik.port:8080 com.docker.compose.container-number:1 com.docker.compose.oneoff:False com.docker.compose.project:traefik com.docker.compose.service:traefik org.label-schema.name:Traefik]"
time="2019-04-09T17:41:34Z" level=debug msg="allLabelsmap[:map[traefik.enable:True traefik.frontend.auth.basic.users:flutters:$apr1$O9/S6.gy$.bEMjIFtJx9wnknZlDFBR0,snailchan:$apr1$.T.pxQpP$864SZVYcYXjzis5exNrcv/ traefik.frontend.rule:Host:traefik.redacted_domain.com,traefik.docker-test-1.local traefik.backend:traefik-dashboard traefik.port:8080]]"
time="2019-04-09T17:41:34Z" level=debug msg="originLabelsmap[com.docker.compose.project:traefik com.docker.compose.service:traefik org.label-schema.name:Traefik traefik.port:8080 com.docker.compose.container-number:1 com.docker.compose.oneoff:False traefik.enable:True com.docker.compose.version:1.24.0 org.label-schema.url:https://traefik.io org.label-schema.vendor:Containous org.label-schema.version:v1.7.10 traefik.frontend.auth.basic.users:flutters:$apr1$O9/S6.gy$.bEMjIFtJx9wnknZlDFBR0,snailchan:$apr1$.T.pxQpP$864SZVYcYXjzis5exNrcv/ com.docker.compose.config-hash:26b28418921e71b0480fc80ed84db16620a19470d7f2531c097266369f60225f org.label-schema.description:A modern reverse-proxy traefik.frontend.rule:Host:traefik.redacted_domain.com,traefik.docker-test-1.local org.label-schema.docker.schema-version:1.0 traefik.backend:traefik-dashboard]"
time="2019-04-09T17:41:34Z" level=debug msg="allLabelsmap[:map[traefik.port:8080 traefik.enable:True traefik.frontend.auth.basic.users:flutters:$apr1$O9/S6.gy$.bEMjIFtJx9wnknZlDFBR0,snailchan:$apr1$.T.pxQpP$864SZVYcYXjzis5exNrcv/ traefik.backend:traefik-dashboard traefik.frontend.rule:Host:traefik.redacted_domain.com,traefik.docker-test-1.local]]"
time="2019-04-09T17:41:35Z" level=debug msg="Backend backend-traefik-dashboard: no load-balancer defined, fallback to 'wrr' method"
time="2019-04-09T17:41:35Z" level=debug msg="Configuration received from provider docker: {\"backends\":{\"backend-traefik-dashboard\":{\"servers\":{\"server-traefik-traefik-1-4f222dca3310205bcce6ca15b4b68224\":{\"url\":\"http://172.18.0.2:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-Host-traefik-redacted-domain-com-traefik-docker-test-1-local-0\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"backend-traefik-dashboard\",\"routes\":{\"route-frontend-Host-traefik-redacted-domain-com-traefik-docker-test-1-local-0\":{\"rule\":\"Host:traefik.redacted_domain.com,traefik.docker-test-1.local\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"auth\":{\"basic\":{\"users\":[\"flutters:$apr1$O9/S6.gy$.bEMjIFtJx9wnknZlDFBR0\",\"snailchan:$apr1$.T.pxQpP$864SZVYcYXjzis5exNrcv/\"]}}}}}"
time="2019-04-09T17:41:35Z" level=info msg="Server configuration reloaded on :80"
time="2019-04-09T17:41:35Z" level=info msg="Server configuration reloaded on :443"
time="2019-04-09T17:41:35Z" level=info msg="Server configuration reloaded on :8080"
time="2019-04-09T17:41:35Z" level=debug msg="Wiring frontend frontend-Host-traefik-redacted-domain-com-traefik-docker-test-1-local-0 to entryPoint http"
time="2019-04-09T17:41:35Z" level=debug msg="Creating backend backend-traefik-dashboard"
time="2019-04-09T17:41:35Z" level=debug msg="Adding TLSClientHeaders middleware for frontend frontend-Host-traefik-redacted-domain-com-traefik-docker-test-1-local-0"
time="2019-04-09T17:41:35Z" level=debug msg="Creating load-balancer wrr"
time="2019-04-09T17:41:35Z" level=debug msg="Creating server server-traefik-traefik-1-4f222dca3310205bcce6ca15b4b68224 at http://172.18.0.2:8080 with weight 1"
time="2019-04-09T17:41:35Z" level=debug msg="Creating route route-frontend-Host-traefik-redacted-domain-com-traefik-docker-test-1-local-0 Host:traefik.redacted_domain.com,traefik.docker-test-1.local"
time="2019-04-09T17:41:35Z" level=debug msg="Wiring frontend frontend-Host-traefik-redacted-domain-com-traefik-docker-test-1-local-0 to entryPoint https"
time="2019-04-09T17:41:35Z" level=debug msg="Creating backend backend-traefik-dashboard"
time="2019-04-09T17:41:35Z" level=debug msg="Adding TLSClientHeaders middleware for frontend frontend-Host-traefik-redacted-domain-com-traefik-docker-test-1-local-0"
time="2019-04-09T17:41:35Z" level=debug msg="Creating load-balancer wrr"
time="2019-04-09T17:41:35Z" level=debug msg="Creating server server-traefik-traefik-1-4f222dca3310205bcce6ca15b4b68224 at http://172.18.0.2:8080 with weight 1"
time="2019-04-09T17:41:35Z" level=debug msg="Creating route route-frontend-Host-traefik-redacted-domain-com-traefik-docker-test-1-local-0 Host:traefik.redacted_domain.com,traefik.docker-test-1.local"
time="2019-04-09T17:41:35Z" level=info msg="Server configuration reloaded on :443"
time="2019-04-09T17:41:35Z" level=info msg="Server configuration reloaded on :8080"
time="2019-04-09T17:41:35Z" level=info msg="Server configuration reloaded on :80"
time="2019-04-09T17:41:39Z" level=debug msg="Building ACME client..."
time="2019-04-09T17:41:39Z" level=debug msg="https://acme-v02.api.letsencrypt.org/directory"
time="2019-04-09T17:41:40Z" level=info msg=Register...
time="2019-04-09T17:41:40Z" level=info msg="legolog: [INFO] acme: Registering account for Example@gmail.com"
time="2019-04-09T17:41:40Z" level=debug msg="Using DNS Challenge provider: gcloud"
time="2019-04-09T17:41:40Z" level=info msg="legolog: [INFO] [*.redacted_domain.com, redacted_domain.com] acme: Obtaining bundled SAN certificate"
time="2019-04-09T17:41:41Z" level=info msg="legolog: [INFO] [*.redacted_domain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/HMp9ah5ZdOYcOi-1UbSgp283JFEo2pLOfTriAfggXt8"
time="2019-04-09T17:41:41Z" level=info msg="legolog: [INFO] [redacted_domain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/YqMwXoalOej68B2A2Q9Gdx3krdyJLmfoUpHthOBWTrw"
time="2019-04-09T17:41:41Z" level=info msg="legolog: [INFO] [*.redacted_domain.com] acme: use dns-01 solver"
time="2019-04-09T17:41:41Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: Could not find solver for: tls-alpn-01"
time="2019-04-09T17:41:41Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: Could not find solver for: http-01"
time="2019-04-09T17:41:41Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: use dns-01 solver"
time="2019-04-09T17:41:41Z" level=info msg="legolog: [INFO] [*.redacted_domain.com] acme: Preparing to solve DNS-01"
time="2019-04-09T17:41:42Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: Preparing to solve DNS-01"
time="2019-04-09T17:41:42Z" level=info msg="legolog: [INFO] [*.redacted_domain.com] acme: Cleaning DNS-01 challenge"
time="2019-04-09T17:41:43Z" level=info msg="legolog: [WARN] [*.redacted_domain.com] acme: error cleaning up: googlecloud: API call failed: googleapi: Error 403: Permission denied on resource project \"personal-207403\"., forbidden "
time="2019-04-09T17:41:43Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: Cleaning DNS-01 challenge"
time="2019-04-09T17:41:44Z" level=info msg="legolog: [WARN] [redacted_domain.com] acme: error cleaning up: googlecloud: API call failed: googleapi: Error 403: Permission denied on resource project \"personal-207403\"., forbidden "
time="2019-04-09T17:41:44Z" level=error msg="Error obtaining certificate retrying in 579.914187ms"
time="2019-04-09T17:41:44Z" level=info msg="legolog: [INFO] [*.redacted_domain.com, redacted_domain.com] acme: Obtaining bundled SAN certificate"
time="2019-04-09T17:41:45Z" level=info msg="legolog: [INFO] [*.redacted_domain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/HMp9ah5ZdOYcOi-1UbSgp283JFEo2pLOfTriAfggXt8"
time="2019-04-09T17:41:45Z" level=info msg="legolog: [INFO] [redacted_domain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/YqMwXoalOej68B2A2Q9Gdx3krdyJLmfoUpHthOBWTrw"
time="2019-04-09T17:41:45Z" level=info msg="legolog: [INFO] [*.redacted_domain.com] acme: use dns-01 solver"
time="2019-04-09T17:41:45Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: Could not find solver for: tls-alpn-01"
time="2019-04-09T17:41:45Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: Could not find solver for: http-01"
time="2019-04-09T17:41:45Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: use dns-01 solver"
time="2019-04-09T17:41:45Z" level=info msg="legolog: [INFO] [*.redacted_domain.com] acme: Preparing to solve DNS-01"
time="2019-04-09T17:41:45Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: Preparing to solve DNS-01"
time="2019-04-09T17:41:45Z" level=info msg="legolog: [INFO] [*.redacted_domain.com] acme: Cleaning DNS-01 challenge"
time="2019-04-09T17:41:46Z" level=info msg="legolog: [WARN] [*.redacted_domain.com] acme: error cleaning up: googlecloud: API call failed: googleapi: Error 403: Permission denied on resource project \"personal-207403\"., forbidden "
time="2019-04-09T17:41:46Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: Cleaning DNS-01 challenge"
time="2019-04-09T17:41:46Z" level=info msg="legolog: [WARN] [redacted_domain.com] acme: error cleaning up: googlecloud: API call failed: googleapi: Error 403: Permission denied on resource project \"personal-207403\"., forbidden "
time="2019-04-09T17:41:46Z" level=error msg="Error obtaining certificate retrying in 976.537731ms"
time="2019-04-09T17:41:47Z" level=info msg="legolog: [INFO] [*.redacted_domain.com, redacted_domain.com] acme: Obtaining bundled SAN certificate"
time="2019-04-09T17:41:47Z" level=info msg="legolog: [INFO] [*.redacted_domain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/HMp9ah5ZdOYcOi-1UbSgp283JFEo2pLOfTriAfggXt8"
time="2019-04-09T17:41:47Z" level=info msg="legolog: [INFO] [redacted_domain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/YqMwXoalOej68B2A2Q9Gdx3krdyJLmfoUpHthOBWTrw"
time="2019-04-09T17:41:47Z" level=info msg="legolog: [INFO] [*.redacted_domain.com] acme: use dns-01 solver"
time="2019-04-09T17:41:47Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: Could not find solver for: tls-alpn-01"
time="2019-04-09T17:41:47Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: Could not find solver for: http-01"
time="2019-04-09T17:41:47Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: use dns-01 solver"
time="2019-04-09T17:41:47Z" level=info msg="legolog: [INFO] [*.redacted_domain.com] acme: Preparing to solve DNS-01"
time="2019-04-09T17:41:47Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: Preparing to solve DNS-01"
time="2019-04-09T17:41:48Z" level=info msg="legolog: [INFO] [*.redacted_domain.com] acme: Cleaning DNS-01 challenge"
time="2019-04-09T17:41:48Z" level=info msg="legolog: [WARN] [*.redacted_domain.com] acme: error cleaning up: googlecloud: API call failed: googleapi: Error 403: Permission denied on resource project \"personal-207403\"., forbidden "
time="2019-04-09T17:41:48Z" level=info msg="legolog: [INFO] [redacted_domain.com] acme: Cleaning DNS-01 challenge"
time="2019-04-09T17:41:48Z" level=info msg="legolog: [WARN] [redacted_domain.com] acme: error cleaning up: googlecloud: API call failed: googleapi: Error 403: Permission denied on resource project \"personal-207403\"., forbidden "
time="2019-04-09T17:41:48Z" level=error msg="Error obtaining certificate: acme: Error -> One or more domains had a problem:\n[*.redacted_domain.com] [*.redacted_domain.com] acme: error presenting token: googlecloud: API call failed: googleapi: Error 403: Permission denied on resource project \"personal-207403\"., forbidden\n[redacted_domain.com] [redacted_domain.com] acme: error presenting token: googlecloud: API call failed: googleapi: Error 403: Permission denied on resource project \"personal-207403\"., forbidden\n"
time="2019-04-09T17:41:48Z" level=error msg="Unable to obtain ACME certificate for domains \"*.redacted_domain.com,redacted_domain.com\" : unable to generate a certificate for the domains [*.redacted_domain.com redacted_domain.com]: acme: Error -> One or more domains had a problem:\n[*.redacted_domain.com] [*.redacted_domain.com] acme: error presenting token: googlecloud: API call failed: googleapi: Error 403: Permission denied on resource project \"personal-207403\"., forbidden\n[redacted_domain.com] [redacted_domain.com] acme: error presenting token: googlecloud: API call failed: googleapi: Error 403: Permission denied on resource project \"personal-207403\"., forbidden\n"
time="2019-04-09T17:41:56Z" level=info msg="I have to go..."
time="2019-04-09T17:41:56Z" level=info msg="Stopping server gracefully"
time="2019-04-09T17:41:56Z" level=debug msg="Waiting 10s seconds before killing connections on entrypoint traefik..."
time="2019-04-09T17:41:56Z" level=debug msg="Waiting 10s seconds before killing connections on entrypoint http..."
time="2019-04-09T17:41:56Z" level=debug msg="Waiting 10s seconds before killing connections on entrypoint https..."
time="2019-04-09T17:41:56Z" level=debug msg="Entrypoint traefik closed"
time="2019-04-09T17:41:56Z" level=debug msg="Entrypoint http closed"
time="2019-04-09T17:41:56Z" level=debug msg="Entrypoint https closed"
time="2019-04-09T17:41:56Z" level=info msg="Server stopped"
time="2019-04-09T17:41:56Z" level=info msg="Shutting down"
```

**Comment by ldez** [comment] 2019-04-09 21:41
Hello @MrFlutters,
Could you try several versions of Traefik to determine if there is a regression with Traefik or gcloud? Thank you.

**Comment by MrFlutters** [comment] 2019-04-09 22:00
@ldez So after testing i can confirm that it works on 1.7.6, 1.7.7
but 1.7.8, 1.7.9 and 1.7.10 it errors like above, so i would assume it was a change with 1.7.8

**Comment by ldez** [comment] 2019-04-09 22:09
I think it's related to https://github.com/go-acme/lego/pull/750

**Comment by MrFlutters** [comment] 2019-04-09 22:18
After testing i believe i can confirm above may be the issue.

Their is weird behavior going on with that change. With GCE_PROJECT set i have the issue specified as above, even if the same value as inside the json, However without specifying GCE_PROJECT it continues and provided valid certificates.

Tested on 1.7.9-alpine and 1.7.10-alpine.

**Comment by geraldcroes** [comment] 2019-04-10 14:44
Thx for the update,

seems like the lego issue is "solved", closing the issue :-)

**Closed by geraldcroes** 2019-04-10 14:44 UTC
Labels: kind/question

**Comment by MrFlutters** [comment] 2019-04-10 14:53
i feel that issue isn't solved as their is still an issue when both `GCE_PROJECT` and `GCE_SERVICE_ACCOUNT_FILE` are set. 

this behavior never existed before, and from what i understand from the pull request above, theirs an issue with how lego is handling `GCE_PROJECT` since that change, as its erroring when provided with the correct details. 

The pull request above also specifies that `GCE_PROJECT` should now always be used if provided, however when its provided at least in my case it returns an error with strange formatting around the `GCE_PROJECT` value.

**Comment by ldez** [comment] 2019-04-10 17:26
As a Traefik maintainer: inside Traefik we cannot change this behavior, because it's in lego.
We cannot downgrade lego, because the version that we use contains bug-fixes.

As a lego maintainer: the error is produced by the gcloud client, I cannot change the error message.
I cannot revert the change because it's now a feature.

As a user, the problem can be solved by removing `GCE_PROJECT` (if the project ID is different from  `GCE_SERVICE_ACCOUNT_FILE`) or set the same project ID in `GCE_PROJECT` and `GCE_SERVICE_ACCOUNT_FILE`.

The previous behavior and the new behavior cannot be reconciled, and in all the case I will create a regression for someone.

So unfortunately, we must consider this as a break change, I'm sorry about that.

**Comment by MrFlutters** [comment] 2019-04-10 17:33
>set the same project ID in GCE_PROJECT and GCE_SERVICE_ACCOUNT_FILE.

This is exactly what i am doing that generates the error.

Both GCE_SERVICE_ACCOUNT_FILE and GCE_PROJECT are **The exact same** including capitalization
following the instructing i quoted, that is the issue im having it gives me the error i reported and tested.

**Comment by MrFlutters** [comment] 2019-04-10 18:34
@ldez So i figured out the issue,
I previously have been using `GCE_PROJECT="personal-207403"` however due to that pull request fixing that GCE_PROJECT is actually used now, and breaks due to my previous formatting.

This is due to the fact that `GCE_PROJECT`' value is not being escaped so its trying to use `\"personal-207403\"` and not an escaped `personal-207403`. 

So I'm not sure if you could class this as an configuration issue or possible something to detect. Because traefik logging does not make this very obvious due to the current logging shows escape characters normally (For example the Global Configuration output).

Normal output for traefik.
```
level=debug msg="Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceTimeOut\":0,`...
```
gcloud's response when failed.
```
Permission denied on resource project \"personal-207403\"., forbidden\n"
```
