### ISSUE TITLE
Use one wildcard certificate on all projects.

### ISSUE THREAD

**Issue by ihack2712** [containous/traefik#5689] opened 2019-10-18 15:45 UTC
### Do you want to request a *feature* or report a *bug*?

Feature/bug

### What did you expect to see?

I'd like to be able to define wildcard domains in static configurations (for fetching SSL certificates from Let's Encrypt), instead of having to define that in dynamic configurations.

The reason for this is because I'd like to have one certificate for all my projects, to reduce the amount of requests sent to Let's Encrypt. Now what Traefik does ([according to documentation](https://docs.traefik.io/routing/routers/#domains)) is that it fetches a new certificate for each time I define a new `domains` property. If I only provide the wildcard domain on one project and don't define it on the rest it will still fetch certificates from Let's Encrypt, but it will fetch a certificate based on the `Host` I assume. So in the end, it doesn't matter how I configure Traefik, it'll always fetch more than one certificate.

So in the end my goal is to be able to use one wildcard certificate on all of my projects, provided by Let's Encrypt of course.

I tried going back to v1.7, but that seems to be outdated, and nothing would work at all. Now because of this version I've gotten API ban on most of my domains on Let's Encrypt.

**Comment by dlq84** [comment] 2019-10-18 17:43
I'm going to assume you're using Kubernetes. I'm trying out Traefik 2 with let's encrypt as we speak. So here's my rant (this is intended as feedback, even though it might sound a bit harsh):

I think the strategy to store the certs in a json file in the pod i flawed, and I think it was a mistake to release v2 before having an alternative that works well with Kubernetes, since its slogan is "The **Cloud Native** Edge Router".

If I restart pod/node or update deployment it means that it will issue a new request for cert, unless I use a persistent disk, but I can only do that if I only have one pod, which means horizontal scaling is  out of the question. So I'm limited to either 1 pod and 5 restarts per week, or 5 pods and 0 restarts per week or anything in between before the rate limit kicks in.

I really hope we'll see more storage options AND cooperation between instances when requesting new certs. Until then one must create Kubernetes secrets and mount those and have a separate cronjob actually requesting the cert with DNS Challange.

**Comment by stephanrenggli** [comment] 2019-10-21 14:56
This looks like Issue https://github.com/containous/traefik/issues/5317.

Reverting to v1.7 worked for me. Make sure to use v1.7 compatible configuration.
Traefik v2.0 is currently unusable with letsencrypt wildcard certs unfortunately.
I don't think letsencrypt will ban you, but you will have reached their API rate limit, so try again a bit later. Let's Encrypt rate limits: https://letsencrypt.org/docs/rate-limits/

**Comment by dduportal** [comment] 2019-10-21 15:25
Hi ! We consider this issue as a duplicate of #5317 as this a potential bug (or misconfiguration) that would lead to issues here, so we are closing to keep activity in the initial issue: feel free to expose your proposal into it.

As a side not, you could define dynamic configuration on Traefik itself, so this configuration would follow Traefik lifecycle as much as your request: WDYT?

**Closed by dduportal** 2019-10-21 15:25 UTC
Labels: status/0-needs-triage
