### ISSUE TITLE
Don't use docker labels for router / load balancer names

### ISSUE THREAD

**Issue by chrisbecke** [containous/traefik#6712] opened 2020-04-21 13:40 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

A user deployed a stack to docker swarm using copy-and-paste traefik labels. They did not notice - or expect - that the router and load-balancer were global and needed to be changed and other services were brought down.

### Proposal

There should be a configuration syntax for docker labels such that router and load balancer names are filled in using the stack and service name. This would ensure that users cannot just paste in `traefik.http.routers.traefik.rule: Host("their-host")` and break critical functionality.

**Comment by ldez** [comment] 2020-04-21 15:11
Duplicate of #5134

**Closed by ldez** 2020-04-21 15:11 UTC
Labels: resolution/duplicate
