### ISSUE TITLE
Consul: Route to unhealthy service

### ISSUE THREAD

**Issue by sparkacus** [containous/traefik#6856] opened 2020-05-27 16:48 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

If the service fails consul health checks, Traefik no longer routes to it - which obviously is a good thing. 

The problem I face is that there are times e.g. during a deployment, where it's possible that all instances will fail the consul health check for a period of time, thus resulting in no route.

If there are no healthy services, I would like the ability to just route to all instances as a failover if they're still registered in Consul.

This is similar to AWS Target Groups i.e. if there are no healthy instances it'll just route to all.

**Comment by SantoDE** [comment] 2020-05-28 14:38
Hello @sparkacus,

thanks for your interest in the project.

I'll close that issue as its a duplicate of #1007

**Closed by SantoDE** 2020-05-28 14:38 UTC
Labels: status/0-needs-triage

**Comment by sparkacus** [comment] 2020-05-28 14:41
@SantoDE no problem - thanks for the link.
