### ISSUE TITLE
Sticky coookie value should be hashed

### ISSUE THREAD

**Issue by sylr** [containous/traefik#4958] opened 2019-06-14 12:56 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I enabled stickiness on my backend and the sticky cookie value contained the endpoint of the server selected

### What did you expect to see?

I expected to see a random value or a hash, not a value divulging an internal ip address.

**Comment by dduportal** [comment] 2019-06-14 13:35
Closing as duplicate of #2299.

Feel free to subscribe to the updates of #2299.

**Closed by dduportal** 2019-06-14 13:35 UTC
Labels: resolution/duplicate
