### ISSUE TITLE
SwarmMode - 1.13 RC2 - DNS RR - Individual IPs not retrieved

### ISSUE THREAD

**Issue by NGalak** [containous/traefik#913] opened 2016-11-29 10:54 UTC
Dear,

When creating a service with **--endpoint-mode dnsrr**, the individual IPs are not retrieved by Traefik.

Purpose:  try to avoid double level of LB: Traefik and Swarm: "You can configure the service to use DNS round-robin directly without using a VIP, by setting the --endpoint-mode dnsrr when you create the service. DNS round-robin is useful in cases where you want to use your own load balancer." (https://docs.docker.com/engine/swarm/networking/). 

Service creation:
docker service create --name guid --replicas 3 --mount type=bind,src=/etc/hostname,dst=/tmp/worker_hostname,readonly --network services --endpoint-mode dnsrr --label traefik.port=9000 swarm-mode-guid:1

Backend URL retrieved by Traefik:
{"server-guid":{"url":"http://:9000","weight":1}}

Internal Swarm Mode DNS:
nslookup guid
Name:      guid
Address 1: 10.0.0.12 guid.3.hwnqvf50rfrsdrp8cwu61aepf.services
Address 2: 10.0.0.10 guid.1.u4ec657n9rxf2u5uhr99un9hp.services
Address 3: 10.0.0.11 guid.2.t695dbbtslm805njqmd40gejd.services

When using a VIP and integrated Swarm LB, everything works OK:
{"server-guid":{"url":"http://10.0.0.10:9000","weight":1}}

Thanks alot for Traefik. 

Best regards

Nian.

**Comment by emilevauge** [comment] 2016-12-02 15:30
Duplicate of #833

**Closed by emilevauge** 2016-12-02 15:30 UTC
