### ISSUE TITLE
Can't get the second page of services, middlewares or routers. 

### ISSUE THREAD

**Issue by MohamedMSaeed** [containous/traefik#5995] opened 2019-12-10 20:57 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm reporting a bug that only appeared in Traefik container v2.0.5 and v2.0.6. 

In the dashboard, whenever I list all services, middlewares or routers I can't get the second list of them. The "next arrow" is always disabled.  The button carries  "disable" attribute although there are more services to list.  

### Output of `traefik version`: (_What version of Traefik are you using?_)

I'm using both traefik:2.0.6 and traefik:2.0.5
```
Version:      2.0.6
Codename:     montdor
Go version:   go1.13.4
Built:        2019-12-02T17:24:31Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```docker-compose.yml
version: "3.4"

services:
  traefik:
    image: traefik:2.0.6
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--log.level=INFO"
      - "--providers.docker.defaultrule=Host(`{{ normalize .Name }}.docker.localhost`)"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami1:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami1.rule=Host(`whoami1.docker.localhost`)"
```
I have 13 more services of woami for the test porpes 

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik_1   | time="2019-12-10T20:53:56Z" level=info msg="Configuration loaded from flags."
traefik_1   | time="2019-12-10T20:53:56Z" level=info msg="Traefik version 2.0.6 built on 2019-12-02T17:24:31Z"
traefik_1   | time="2019-12-10T20:53:56Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}.docker.localhost`)\",\"exposedByDefault\":true,\"swarmModeRefreshSeconds\":15000000000}},\"api\":{\"insecure\":true,\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
traefik_1   | time="2019-12-10T20:53:56Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
traefik_1   | time="2019-12-10T20:53:56Z" level=debug msg="No default certificate, generating one"
traefik_1   | time="2019-12-10T20:53:57Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
traefik_1   | time="2019-12-10T20:53:57Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}.docker.localhost`)\",\"exposedByDefault\":true,\"swarmModeRefreshSeconds\":15000000000}"
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Start TCP Server" entryPointName=http
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Start TCP Server" entryPointName=traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Provider connection established with docker 19.03.5 (API 1.40)" providerName=docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"traefik-traefik\":{\"service\":\"traefik-traefik\",\"rule\":\"Host(`traefik-traefik.docker.localhost`)\"},\"whoami\":{\"middlewares\":[\"whoami\"],\"service\":\"whoami-traefik\",\"rule\":\"PathPrefix(`/whoami`)\"},\"whoami10\":{\"service\":\"whoami10-traefik\",\"rule\":\"Host(`whoami10.docker.localhost`)\"},\"whoami11\":{\"service\":\"whoami11-traefik\",\"rule\":\"Host(`whoami11.docker.localhost`)\"},\"whoami12\":{\"service\":\"whoami12-traefik\",\"rule\":\"Host(`whoami12.docker.localhost`)\"},\"whoami2\":{\"middlewares\":[\"whoami2\"],\"service\":\"whoami2-traefik\",\"rule\":\"PathPrefix(`/whoami/2`)\"},\"whoami3\":{\"service\":\"whoami3-traefik\",\"rule\":\"Host(`whoami3.docker.localhost`)\"},\"whoami4\":{\"service\":\"whoami4-traefik\",\"rule\":\"Host(`whoami4.docker.localhost`)\"},\"whoami5\":{\"service\":\"whoami5-traefik\",\"rule\":\"Host(`whoami5.docker.localhost`)\"},\"whoami6\":{\"service\":\"whoami6-traefik\",\"rule\":\"Host(`whoami6.docker.localhost`)\"},\"whoami7\":{\"service\":\"whoami7-traefik\",\"rule\":\"Host(`whoami7.docker.localhost`)\"},\"whoami8\":{\"service\":\"whoami8-traefik\",\"rule\":\"Host(`whoami8.docker.localhost`)\"},\"whoami9\":{\"service\":\"whoami9-traefik\",\"rule\":\"Host(`whoami9.docker.localhost`)\"}},\"middlewares\":{\"whoami\":{\"stripPrefix\":{\"prefixes\":[\"/whoami\"],\"forceSlash\":true}},\"whoami2\":{\"stripPrefix\":{\"prefixes\":[\"/whoami/2\"],\"forceSlash\":true}}},\"services\":{\"traefik-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.12:80\"}],\"passHostHeader\":true}},\"whoami-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.8:80\"}],\"passHostHeader\":true}},\"whoami10-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.10:80\"}],\"passHostHeader\":true}},\"whoami11-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.6:80\"}],\"passHostHeader\":true}},\"whoami12-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.4:80\"}],\"passHostHeader\":true}},\"whoami2-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.2:80\"}],\"passHostHeader\":true}},\"whoami3-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.5:80\"}],\"passHostHeader\":true}},\"whoami4-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.7:80\"}],\"passHostHeader\":true}},\"whoami5-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.3:80\"}],\"passHostHeader\":true}},\"whoami6-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.11:80\"}],\"passHostHeader\":true}},\"whoami7-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.14:80\"}],\"passHostHeader\":true}},\"whoami8-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.9:80\"}],\"passHostHeader\":true}},\"whoami9-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.26.0.13:80\"}],\"passHostHeader\":true}}}},\"tcp\":{}}" providerName=docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami2@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami11@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami4@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami10@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami9@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=traefik-traefik@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami6@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami8@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami12@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami7@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami3@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http traefik]" routerName=whoami5@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" entryPointName=http routerName=whoami2@docker serviceName=whoami2-traefik middlewareName=pipelining middlewareType=Pipelining
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" entryPointName=http routerName=whoami2@docker serviceName=whoami2-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.2:80" routerName=whoami2@docker serverName=0 serviceName=whoami2-traefik entryPointName=http
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware whoami2-traefik" entryPointName=http routerName=whoami2@docker middlewareName=tracing middlewareType=TracingForwarder
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" routerName=whoami2@docker entryPointName=http middlewareName=whoami2@docker middlewareType=StripPrefix
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Adding tracing to middleware" routerName=whoami2@docker middlewareName=whoami2@docker entryPointName=http
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" routerName=whoami10@docker entryPointName=http serviceName=whoami10-traefik middlewareName=pipelining middlewareType=Pipelining
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" routerName=whoami10@docker entryPointName=http serviceName=whoami10-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.10:80" serviceName=whoami10-traefik routerName=whoami10@docker entryPointName=http serverName=0
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware whoami10-traefik" entryPointName=http routerName=whoami10@docker middlewareName=tracing middlewareType=TracingForwarder
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" serviceName=whoami9-traefik middlewareName=pipelining middlewareType=Pipelining entryPointName=http routerName=whoami9@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" entryPointName=http routerName=whoami9@docker serviceName=whoami9-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.13:80" entryPointName=http routerName=whoami9@docker serviceName=whoami9-traefik serverName=0
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware whoami9-traefik" routerName=whoami9@docker middlewareName=tracing middlewareType=TracingForwarder entryPointName=http
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" routerName=whoami5@docker serviceName=whoami5-traefik middlewareName=pipelining middlewareType=Pipelining entryPointName=http
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" entryPointName=http routerName=whoami5@docker serviceName=whoami5-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.3:80" entryPointName=http routerName=whoami5@docker serviceName=whoami5-traefik serverName=0
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware whoami5-traefik" routerName=whoami5@docker middlewareName=tracing middlewareType=TracingForwarder entryPointName=http
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" middlewareType=Pipelining routerName=whoami6@docker entryPointName=http serviceName=whoami6-traefik middlewareName=pipelining
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" serviceName=whoami6-traefik routerName=whoami6@docker entryPointName=http
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.11:80" serverName=0 routerName=whoami6@docker entryPointName=http serviceName=whoami6-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware whoami6-traefik" routerName=whoami6@docker middlewareName=tracing middlewareType=TracingForwarder entryPointName=http
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" entryPointName=http routerName=whoami8@docker serviceName=whoami8-traefik middlewareName=pipelining middlewareType=Pipelining
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" routerName=whoami8@docker serviceName=whoami8-traefik entryPointName=http
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.9:80" serverName=0 entryPointName=http routerName=whoami8@docker serviceName=whoami8-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware whoami8-traefik" middlewareType=TracingForwarder routerName=whoami8@docker entryPointName=http middlewareName=tracing
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" serviceName=whoami12-traefik middlewareName=pipelining middlewareType=Pipelining entryPointName=http routerName=whoami12@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" entryPointName=http routerName=whoami12@docker serviceName=whoami12-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.4:80" serviceName=whoami12-traefik serverName=0 entryPointName=http routerName=whoami12@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware whoami12-traefik" entryPointName=http routerName=whoami12@docker middlewareType=TracingForwarder middlewareName=tracing
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining serviceName=whoami7-traefik entryPointName=http routerName=whoami7@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" entryPointName=http routerName=whoami7@docker serviceName=whoami7-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.14:80" serviceName=whoami7-traefik entryPointName=http routerName=whoami7@docker serverName=0
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware whoami7-traefik" entryPointName=http routerName=whoami7@docker middlewareName=tracing middlewareType=TracingForwarder
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" routerName=whoami@docker serviceName=whoami-traefik middlewareName=pipelining middlewareType=Pipelining entryPointName=http
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" routerName=whoami@docker serviceName=whoami-traefik entryPointName=http
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.8:80" entryPointName=http routerName=whoami@docker serviceName=whoami-traefik serverName=0
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware whoami-traefik" entryPointName=http routerName=whoami@docker middlewareName=tracing middlewareType=TracingForwarder
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" entryPointName=http routerName=whoami@docker middlewareName=whoami@docker middlewareType=StripPrefix
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Adding tracing to middleware" entryPointName=http routerName=whoami@docker middlewareName=whoami@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" routerName=whoami11@docker entryPointName=http serviceName=whoami11-traefik middlewareName=pipelining middlewareType=Pipelining
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" routerName=whoami11@docker entryPointName=http serviceName=whoami11-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.6:80" entryPointName=http serviceName=whoami11-traefik routerName=whoami11@docker serverName=0
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware whoami11-traefik" entryPointName=http routerName=whoami11@docker middlewareType=TracingForwarder middlewareName=tracing
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining entryPointName=http routerName=whoami4@docker serviceName=whoami4-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" entryPointName=http routerName=whoami4@docker serviceName=whoami4-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.7:80" entryPointName=http serverName=0 routerName=whoami4@docker serviceName=whoami4-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware whoami4-traefik" middlewareType=TracingForwarder routerName=whoami4@docker entryPointName=http middlewareName=tracing
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" middlewareType=Pipelining serviceName=traefik-traefik entryPointName=http routerName=traefik-traefik@docker middlewareName=pipelining
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" serviceName=traefik-traefik entryPointName=http routerName=traefik-traefik@docker
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.12:80" serviceName=traefik-traefik entryPointName=http routerName=traefik-traefik@docker serverName=0
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware traefik-traefik" routerName=traefik-traefik@docker middlewareName=tracing middlewareType=TracingForwarder entryPointName=http
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining routerName=whoami3@docker entryPointName=http serviceName=whoami3-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating load-balancer" routerName=whoami3@docker entryPointName=http serviceName=whoami3-traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating server 0 http://172.26.0.5:80" routerName=whoami3@docker entryPointName=http serviceName=whoami3-traefik serverName=0
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Added outgoing tracing middleware whoami3-traefik" entryPointName=http routerName=whoami3@docker middlewareName=tracing middlewareType=TracingForwarder
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" entryPointName=http middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=traefik
traefik_1   | time="2019-12-10T20:53:57Z" level=debug msg="No default certificate, generating one"

```

**Comment by MohamedMSaeed** [comment] 2019-12-10 21:08
In this screenshot related to v2.0.4, you can find that the next page works fine.
https://drive.google.com/file/d/1GGTVFtgXl9MEVf2Orqza-gb6SyJb6djb/view?usp=sharing


In the following screenshot related to v2.0.6, you can see that both buttons are disabled.
https://drive.google.com/file/d/1LGCqmtRudTMxwJvyGp8-rIHdPWvay2E2/view?usp=sharing

**Comment by kareem-elsayed** [comment] 2019-12-10 21:13
we faced the same issue after upgrading to 2.0.6

**Comment by ldez** [comment] 2019-12-10 22:07
duplicate of #5959

**Closed by ldez** 2019-12-10 22:07 UTC
Labels: status/0-needs-triage
