### ISSUE TITLE
Redirect 302 with respect to PathPrefixStrip

### ISSUE THREAD

**Issue by MrOerni** [containous/traefik#2510] opened 2017-12-01 14:22 UTC
### Do you want to request a *feature* or report a *bug*?
A bug

### What did you do?

When getting redirected on a route with a matched PathPrefix, the Prefix should be included in the redirect.
As you can see below this bothers me when using prometheus. 

### What did you expect to see?
Visiting Path `/prometheus/` [with PathPrefixStrip `/prometheus`]. 
Which is a redirect to `/graph`
Traefik should redirect to `/prometheus/graph`, because of the PathPrefix

### What did you see instead?
It redirects to just `/graph`.
(Curl returns a 302 with `location: /graph`)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.4.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################
defaultEntryPoints = ["http", "https"]

# Entrypoints definition
[entryPoints]
	[entryPoints.http]
	address = ":80"
		[entryPoints.http.redirect]
		entryPoint = "https"
	[entryPoints.https]
	address = ":443"
		[entryPoints.https.tls]

[acme]
email = "xxx@xxx.de"
storage = "acme.json"
entryPoint = "https"
onHostRule = true

[[acme.domains]]
  main = "xxxxx.de"

# Enable web configuration backend
[web]
address = ":8080"
path = "/traefik"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]
domain = "XXXXX.de"
exposedbydefault = true
watch = true
```

**Comment by dtomcej** [comment] 2017-12-01 15:41
Is traefik generating the 302 or is your application generating the redirect?

**Comment by MrOerni** [comment] 2017-12-01 15:59
.. Both? 
I would assume prometheus is generating the 302.

BUT. The same happens with the traefik WebUI. 
Resulting in https://github.com/containous/traefik/issues/1081

**Comment by colinlabs** [comment] 2017-12-07 06:40
same issuer #2537

**Comment by jordijansen** [comment] 2017-12-18 07:46
I'm getting the same behavior. I have the redirect set-up as the orignal bug report.
I have a frontend with PathPrefixStrip /app

When I navigate to http://localhost/app/index.html
It will redirect to https://localhost/index.html

This is blocking me from moving forward with Traefik

**Comment by colinlabs** [comment] 2017-12-29 09:41
+1

**Comment by nmengin** [comment] 2018-01-04 14:26
Seems to be duplicate of #1957

**Closed by nmengin** 2018-01-04 14:26 UTC
Labels: area/rules, resolution/duplicate
