### ISSUE TITLE
Sticky session specify cookie name

### ISSUE THREAD

**Issue by kleinsasserm** [containous/traefik#1574] opened 2017-05-09 13:05 UTC
In some scenarios it is required to specify the cookie name which is used by Traefik for session stickiness. 

For example: We would like to provide a swarm stack with an ingress Traefik loadbalancer which works without any problem but we have to provide a second Traefik that runs on a separate docker host with additional ip addresses to use port 80 and 443 (DNS entries ...). In this setup the sticky cookie setting from the first boundary loadbalancer "overwrites" the sticky cookie from the second loadbalancer because of the same name. The result is that the cookie values are garbled as you can see this in the screenshot.

![09-05-_2017_14-59-06](https://cloud.githubusercontent.com/assets/9364572/25852149/a0fe94fe-34c8-11e7-9ecf-605970274e0c.jpg)

If we use a Nginx loadbalancer as first stage, the stickiness works without any troubles. Therefore an option like stickycookie="_MYFUNNYCOKKIE" would be helpful to configure cascading Traefik setups.

**Comment by ldez** [comment] 2017-05-09 14:10
Seems to be a duplicate of #1207

**Comment by kleinsasserm** [comment] 2017-05-09 14:59
I guess no, because #1207 describes possible types stickiness (cookie, ipaddress). Here I mean, that if maybe type "cookie" is specified, it would be helpful to specify the cookie name. So this is an extension to type cookie.

**Comment by timoreimann** [comment] 2017-05-09 21:15
@ldez I agree with @kleinsasserm that the request is different from #1207. Okay to remove the duplicate status?

**Comment by dtomcej** [comment] 2017-05-12 19:43
@timoreimann I agree that those 2 issues are separate. I also think that the cookie name should be configurable, as:

1. Other proxies (like nginx or haproxy) allow for this, and:
2. Allowing the cookie name to be customized would allow applications to control it as well.

**Comment by richardjq** [comment] 2017-05-24 12:21
Another use case is if you are using Path based frontend rules on the same domain. The cookie for service A will be overwritten by the cookie for service B.

This is a very common use case in our Docker environment.

**Comment by ldez** [comment] 2017-06-13 15:01
Closed by  #1716

**Closed by ldez** 2017-06-13 15:01 UTC
Labels: area/sticky-session, kind/enhancement
