### ISSUE TITLE
v1.2.0-rc2 traefik does not respond to kubernetes ingress create/delete events

### ISSUE THREAD

**Issue by rrichardson** [containous/traefik#1251] opened 2017-03-07 17:58 UTC
### What version of Traefik are you using (`traefik version`)?
v1.2.0-rc2

### What is your environment & configuration (arguments, toml...)?
kubernetes 1.5,2 

      - args:
        - --web
        - --kubernetes
        - --logLevel=DEBUG
        - --web.metrics.prometheus
        - --web.metrics.prometheus.buckets=0.1,0.3,1.2,5

I have traefik exposed through an ELB which has a DNS entry *.mydomain.com pointed at it. 

I have a bunch of ingresses configured at <svcname>.mydomain.com. 

### What did you do?
I  created an new ingress for a service at host mysvc.mydomain.com 

and expected to be able to find the service there, but instead I got 'Bad Gateway' 

### What did you expect to see?
The HTML returned by my service

### What did you see instead?
Bad Gateway

### What did you do? 
I then deleted an ingress for a different service with an ingress at myothersvc.mydomain.com, which I had verified was working. 

### What did you expect to see? 
Bad Gateway or something indicating that there wasn't a provider for this URL

### What did you see instead? 
The HTML returned by the service.

**Comment by rrichardson** [comment] 2017-03-07 18:01
It appears that traefik did receive an event when the service was deleted.  Yet it is still present in the list of endpoints in the traefik dashboard. 

```
time="2017-03-07T17:46:22Z" level=debug msg="Received event from kubernetes &Ingress{ObjectMeta:k8s_io_kubernetes_pkg_api_v1.ObjectMeta{Name:whoami,GenerateName:,Namespace:default,SelfLink:/apis/extensions/v1beta1/namespaces/default/ingresses/whoami,UID:100fcea4-b8b0-11e6-bc4e-066d37d82cc8,ResourceVersion:50522874,Generation:1,CreationTimestamp:2016-12-02 16:55:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-configuration: {\"kind\":\"Ingress\",\"apiVersion\":\"extensions/v1beta1\",\"metadata\":{\"name\":\"whoami\",\"creationTimestamp\":null},\"spec\":{\"rules\":[{\"host\":\"whoami.dev.adquire.com\",\"http\":{\"paths\":[{\"backend\":{\"serviceName\":\"whoami\",\"servicePort\":80}}]}},{\"host\":\"whoami-lb.default.svc.cluster.local\",\"http\":{\"paths\":[{\"backend\":{\"serviceName\":\"whoami\",\"servicePort\":80}}]}}]},\"status\":{\"loadBalancer\":{}}},},OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:IngressSpec{Backend:nil,TLS:[],Rules:[{whoami.dev.adquire.com {HTTPIngressRuleValue{Paths:[{ {whoami {0 80 }}}],}}} {whoami-lb.default.svc.cluster.local {&HTTPIngressRuleValue{Paths:[{ {whoami {0 80 }}}],}}}],},Status:IngressStatus{LoadBalancer:k8s_io_kubernetes_pkg_api_v1.LoadBalancerStatus{Ingress:[],},},}"
```

**Comment by rrichardson** [comment] 2017-03-07 18:07
In most cases I do have multiple ingress pointed at a single service (one for internal LB, and one for external)

**Comment by rrichardson** [comment] 2017-03-07 18:44
I rolled back to 1.1.2 and repeated the above steps and they worked correctly.

**Comment by rrichardson** [comment] 2017-03-10 20:24
I'm curious about the 1.3 milestone. 

As far as I can tell, and I hope I'm wrong.  The current 1.2 release is broken for kubernetes users.  Does the 1.3 milestone mean that you're removing the new k8s golang client (and improved event handling support)  for 1.2, and wait until 1.3 to implement it?  Or are you going to ship 1.2 with broken k8s support?

**Comment by timoreimann** [comment] 2017-03-10 20:41
@rrichardson the milestone is set to 1.2. I accidentally picked 1.3 (fat finger syndrome) but immediately changed it to 1.2. The Github UI does a fairly bad job conveying this.

I don't think we are going to ship 1.2 if the k8s provider (or any other, for that matter) is knowingly broken.

**Comment by rrichardson** [comment] 2017-03-10 20:51
Awesome. Thanks!

**Comment by emilevauge** [comment] 2017-03-11 10:30
Ping @errm @dtomcej, any idea on this one ?

**Comment by timoreimann** [comment] 2017-03-11 12:36
I tried to reproduce it yesterday but failed, possibly because my setup wasn't super equivalent (no ELB, no DNS records).

@rrichardson do you possibly have a `--debug` output that could help us?

**Comment by emilevauge** [comment] 2017-03-14 14:30
@rrichardson I also tried to reproduce it on my laptop and failed :'(
I deployed services + ingresses, then remove a service and the linked frontend disappeared from the dashboard.
Can you confirm the steps and help us reproduce your issue ?

**Comment by rrichardson** [comment] 2017-03-14 17:28
I re-deployed from scratch on my dev cluster.   I was able to re-create the problem.

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

1.  I deleted my whoami ingress. 
2.  I created a new deployment and a new service, and ingress for traefik,  was able to see traefik dashboard through its own ingress.   I still suspect that there was a problem even here, but I'll worry about that later. 
3.  I re-created the whoami ingress from its yaml file. 
4.  Wait a bit, go to the dashboard,  there is no whoami service frontend or back-end in the list. 
5.  This is what I see in my dev cluster. 
```
$ kubectl describe ingress whoami
Name:                   whoami
Namespace:              default
Address:
Default backend:        default-http-backend:80 (<none>)
Rules:
  Host                                  Path    Backends
  ----                                  ----    --------
  whoami.dev.adquire.com
                                                whoami:80 (<none>)
  whoami-lb.default.svc.cluster.local
                                                whoami:80 (<none>)
Annotations:
No events.
```

I also see more 404's than 200's in the traefik dashboard health screen.  I'm going to roll-back to 1.1.2 and verify that the problem is not present there.

**Comment by rrichardson** [comment] 2017-03-14 17:32
I have also grabbed a debug log for traefik. I am happy to email / DM it to somebody.

**Comment by rrichardson** [comment] 2017-03-14 17:40
here is my 1.2 deployment : 

I'm trying to come up with other things which *might* effect it. I'm running traefik in namespace=kube-system


```
apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  labels: 
    k8s-app: traefik-ingress-lb
  name: traefik-ingress-lb 
  namespace: kube-system
spec: 
  replicas: 3
  selector: 
    matchLabels:
      k8s-app: traefik-ingress-lb 
      name: traefik-ingress-lb
      namespace: kube-system 
      version: v1.2.0-rc2
  strategy: 
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 1
    type: RollingUpdate 
  template:
    metadata: 
      creationTimestamp: null
      labels: 
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb 
        namespace: kube-system
        version: v1.2.0-rc2 
    spec: 
      containers:
      - args:
        - --web
        - --kubernetes
        - --logLevel=DEBUG
        - --web.metrics.prometheus
        - --web.metrics.prometheus.buckets=0.1,0.3,1.2,5
        image: containous/traefik:v1.2.0-rc2
        imagePullPolicy: Always
        name: traefik-ingress-controller
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 8080
          name: admin
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 60
```

**Comment by rrichardson** [comment] 2017-03-14 17:43
I rolled back to 1.1.2  and was able to delete the whoami ingress and it was successfully removed from the dashboard.  Then I re-added it and it re-appeared almost immediately.  

So I guess what we need to figure out is what is different about my cluster.  It is basically a standard kops installation of k8s 1.5.2.   I have made one non-standard config change to it, and that is  the runtime config of the API server to allow for batch/v2alpha1 API. 
```
kubeAPIServer:
    runtimeConfig:
        batch/v2alpha1: "true"
```

**Comment by rrichardson** [comment] 2017-03-14 17:51
Ah.. I also notice that --debug is different than --log-level=DEBUG.  I'll do a run with 1.2 in --debug.

**Comment by timoreimann** [comment] 2017-03-14 18:03
@rrichardson feel free to send debug output to my email address. You can find it on [my Github profile](https://github.com/timoreimann).

**Comment by rrichardson** [comment] 2017-03-14 18:12
OK. I found an error in the debug log relating to metrics.   

So I went ahead and ran 1.2  without enabling metrics collection and promethetheus. 
Literally just commented out the lines in my deployment
```
#        - --web.metrics.prometheus 
#        - --web.metrics.prometheus.buckets=0.1,0.3,1.2,5
```

Traefik now works as expected.  

So there is some odd interplay between k8s and metrics that breaks its ingress handler? 

So I guess steps to reproduce are :  run in k8s with -web.metrics.prometheus enabled.

**Comment by rrichardson** [comment] 2017-03-14 18:17
I'm not sure its entirely working correctly I still a very high number of 404's being returned in the health screen.  Not the same ratio as before, however.   I am trying to track down the source of those.

**Comment by emilevauge** [comment] 2017-03-14 20:51
Seems linked to https://github.com/containous/traefik/issues/1261

**Comment by emilevauge** [comment] 2017-03-14 21:27
@rrichardson I just pushed `containous/traefik:c582ea5ff0c72df13962eeca4bff3b337db4e865` that contains the latest fix. It would be awesome if you could confirm that it now works :)

**Comment by rrichardson** [comment] 2017-03-14 22:10
Excellent.  I'll give it a try tomorrow morning EST.

**Comment by cameronattard** [comment] 2017-03-15 06:09
I can confirm that the fix works for me (also experienced this problem today).

**Comment by timoreimann** [comment] 2017-03-15 07:29
@cameronattard thanks for the feedback.

I think we can close this issue if @rrichardson can report back positively as well.

**Comment by rrichardson** [comment] 2017-03-20 16:42
Apologies for the delay.  The latest build works correctly.  Thanks!

**Closed** 2017-03-20 16:42 UTC
Labels: investigation-needed
