### ISSUE TITLE
Traefik not identifying containers created using docker python. 

### ISSUE THREAD

**Issue by ColdHeat** [containous/traefik#2769] opened 2018-01-26 11:59 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Services created for docker swarm using docker python are not picked up by traefik. 

First I used the following script to deploy a service on localhost. 
```
import docker

client = docker.from_env()

service = client.services.create(
    image='emilevauge/whoami',
    name='whoami1',
    labels={
        'traefik.enable': 'true',
        'traefik.port': '80',
        'traefik.backend': 'whoami1',
        'traefik.frontend.rule': "Host:whoami1.lvh.me"
    },
    networks=['test-network']
)
```
This results in a 404. 
```
❯ curl whoami1.lvh.me
404 page not found
```

Now if I use a docker cli command:

```
docker service create \
    --name whoami2 \
    --label traefik.enable=true \
    --label traefik.port=80 \
    --label traefik.backend="whoami2" \
    --label traefik.frontend.rule=HostRegexp:whoami2.lvh.me \
    --network test-network \
    --detach=false \
    emilevauge/whoami

```

```
❯ curl whoami2.lvh.me
Hostname: dbd26295f93b
IP: 127.0.0.1
IP: 10.0.0.19
IP: 10.0.0.20
IP: 172.18.0.5
GET / HTTP/1.1
Host: whoami2.lvh.me
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

The image I am using is traefik:1.5.0.
```
ixtvmpew5fue        traefik             global              1/1                 traefik:1.5.0                                       *:8080->8080/tcp
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Docker Swarm
Docker 17.12.0-ce-mac49 (21995)
Docker Engine: 17.12.0-ce
Docker Python Version: docker (2.7.0)

### If applicable, please paste the log output in debug mode (`--debug` switch)

N/A

**Comment by ldez** [comment] 2018-01-26 12:02
Duplicate of #2582

**Closed** 2018-01-26 12:02 UTC
Labels: resolution/duplicate
