### ISSUE TITLE
h2c gRPC: Proxying trailer headers when server returns not successful response doesn't seems to work correctly

### ISSUE THREAD

**Issue by kruczjak** [containous/traefik#4181] opened 2018-11-09 15:13 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm using gRPC with h2c protocol.
When gRPC server returns correct response -> everything is ok.
When gRPC server returns error -> something with headers passing is wrong in traefik (works correctly using different proxy - nghttpx).

### What did you expect to see?

Traefik should proxy tailer headers correctly when gRPC server returns error.

### What did you see instead?

After enabling gRPC debug log on client, I can clearly see what's going on.
With successful response from server, headers are parsed correctly:
```
(...)
I1109 15:47:48.227941505   31097 parsing.cc:624]             parsing initial_metadata
I1109 15:47:48.228010139   31097 hpack_parser.cc:636]        Decode: ':status: 200', elem_interned=1 [3], k_interned=1, v_interned=1
I1109 15:47:48.228026784   31097 parsing.cc:406]             HTTP:7:HDR:CLI: :status: 32 30 30 '200'
I1109 15:47:48.228036516   31097 hpack_parser.cc:636]        Decode: 'accept-encoding: identity,gzip', elem_interned=1 [3], k_interned=1, v_interned=1
(..... more headers parsing like content-type etc.)
I1109 15:47:48.228194491   31097 parsing.cc:629]             parsing trailing_metadata
I1109 15:47:48.228204788   31097 hpack_parser.cc:636]        Decode: 'grpc-message: OK', elem_interned=1 [1], k_interned=1, v_interned=1
I1109 15:47:48.228211996   31097 parsing.cc:488]             HTTP:7:TRL:CLI: grpc-message: 4f 4b 'OK'
I1109 15:47:48.228222807   31097 hpack_parser.cc:636]        Decode: 'grpc-status: 0', elem_interned=1 [3], k_interned=1, v_interned=1
I1109 15:47:48.228231082   31097 parsing.cc:488]             HTTP:7:TRL:CLI: grpc-status: 30 '0'
(...)
```

With error response:
```
I1109 15:48:27.931384221   31097 parsing.cc:617]             parsing Trailers-Only
I1109 15:48:27.931449261   31097 hpack_parser.cc:636]        Decode: ':status: 200', elem_interned=1 [3], k_interned=1, v_interned=1
I1109 15:48:27.931467406   31097 parsing.cc:488]             HTTP:9:TRL:CLI: :status: 32 30 30 '200'
I1109 15:48:27.931481383   31097 hpack_parser.cc:636]        Decode: 'accept-encoding: identity,gzip', elem_interned=1 [3], k_interned=1, v_interned=1
I1109 15:48:27.931491598   31097 parsing.cc:488]             HTTP:9:TRL:CLI: accept-encoding: 69 64 65 6e 74 69 74 79 2c 67 7a 69 70 'identity,gzip'
I1109 15:48:27.931503401   31097 hpack_parser.cc:636]        Decode: 'content-type: application/grpc', elem_interned=1 [3], k_interned=1, v_interned=1
I1109 15:48:27.931523249   31097 parsing.cc:488]             HTTP:9:TRL:CLI: content-type: 61 70 70 6c 69 63 61 74 69 6f 6e 2f 67 72 70 63 'application/grpc'
```

As you can see, "normal" headers are in place of "tailers". (or just those original tailers are skipped? e.g. grpc-status header)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.4
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-30_10:44:30AM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
#    [entryPoints.http]

[accessLog]
[api]

[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    # Access on backend with h2c
    url = "h2c://localhost:3910"


[frontends]
  [frontends.frontend1]
  entryPoints = ["http"]
  backend = "backend1"

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
DEBU[2018-11-09T16:09:58+01:00] vulcand/oxy/roundrobin/rr: begin ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/grpc_token_service.AdminService/List\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Authorization\":[\"Basic Z3JwYzpzdXBlci1oYXJkLWxveWFsdHktcGFzc3dvcmQ=\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-ruby/1.15.0 grpc-c/6.0.0 (linux; chttp2; glider)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:36110\",\"RequestURI\":\"/grpc_token_service.AdminService/List\",\"TLS\":null}"
DEBU[2018-11-09T16:09:58+01:00] vulcand/oxy/roundrobin/rr: Forwarding this request to URL  ForwardURL="h2c://localhost:3910" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/grpc_token_service.AdminService/List\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Authorization\":[\"Basic Z3JwYzpzdXBlci1oYXJkLWxveWFsdHktcGFzc3dvcmQ=\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-ruby/1.15.0 grpc-c/6.0.0 (linux; chttp2; glider)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:36110\",\"RequestURI\":\"/grpc_token_service.AdminService/List\",\"TLS\":null}"
DEBU[2018-11-09T16:09:58+01:00] vulcand/oxy/forward: begin ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"h2c\",\"Opaque\":\"\",\"User\":null,\"Host\":\"localhost:3910\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Authorization\":[\"Basic Z3JwYzpzdXBlci1oYXJkLWxveWFsdHktcGFzc3dvcmQ=\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-ruby/1.15.0 grpc-c/6.0.0 (linux; chttp2; glider)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:36110\",\"RequestURI\":\"/grpc_token_service.AdminService/List\",\"TLS\":null}"
DEBU[2018-11-09T16:09:58+01:00] vulcand/oxy/forward/http: begin ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"h2c\",\"Opaque\":\"\",\"User\":null,\"Host\":\"localhost:3910\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Authorization\":[\"Basic Z3JwYzpzdXBlci1oYXJkLWxveWFsdHktcGFzc3dvcmQ=\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-ruby/1.15.0 grpc-c/6.0.0 (linux; chttp2; glider)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:36110\",\"RequestURI\":\"/grpc_token_service.AdminService/List\",\"TLS\":null}"
DEBU[2018-11-09T16:09:58+01:00] vulcand/oxy/forward/http: Round trip: h2c://localhost:3910, code: 200, Length: 0, duration: 570.153051ms 
DEBU[2018-11-09T16:09:58+01:00] vulcand/oxy/forward/http: completed ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"h2c\",\"Opaque\":\"\",\"User\":null,\"Host\":\"localhost:3910\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Authorization\":[\"Basic Z3JwYzpzdXBlci1oYXJkLWxveWFsdHktcGFzc3dvcmQ=\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-ruby/1.15.0 grpc-c/6.0.0 (linux; chttp2; glider)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:36110\",\"RequestURI\":\"/grpc_token_service.AdminService/List\",\"TLS\":null}"
DEBU[2018-11-09T16:09:58+01:00] vulcand/oxy/forward: completed ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"h2c\",\"Opaque\":\"\",\"User\":null,\"Host\":\"localhost:3910\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Authorization\":[\"Basic Z3JwYzpzdXBlci1oYXJkLWxveWFsdHktcGFzc3dvcmQ=\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-ruby/1.15.0 grpc-c/6.0.0 (linux; chttp2; glider)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:36110\",\"RequestURI\":\"/grpc_token_service.AdminService/List\",\"TLS\":null}"
DEBU[2018-11-09T16:09:58+01:00] vulcand/oxy/roundrobin/rr: completed ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/grpc_token_service.AdminService/List\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept-Encoding\":[\"identity,gzip\"],\"Authorization\":[\"Basic Z3JwYzpzdXBlci1oYXJkLWxveWFsdHktcGFzc3dvcmQ=\"],\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"identity,deflate,gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-ruby/1.15.0 grpc-c/6.0.0 (linux; chttp2; glider)\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:36110\",\"RequestURI\":\"/grpc_token_service.AdminService/List\",\"TLS\":null}"
::1 - - [09/Nov/2018:15:09:58 +0000] "POST /grpc_token_service.AdminService/List HTTP/2.0" 200 0 "-" "grpc-ruby/1.15.0 grpc-c/6.0.0 (linux; chttp2; glider)" 1 "frontend1" "h2c://localhost:3910" 572ms
```

Also, logs with added env variable `GODEBUG="http2debug=1"` (a bit long)
successful gRPC server response: https://pastebin.com/6etTnc9t
failure gRPC server response: https://pastebin.com/KWqMJKpy (e.g. no grpc-status header returned)

**Comment by kruczjak** [comment] 2018-11-09 16:07
Here is very simple `demo` written in ruby: https://github.com/Boostcom/grpc-bug-traefik-demo

**Comment by juliens** [comment] 2018-11-13 07:51
@kruczjak can you confirm if it works with https?

**Comment by kruczjak** [comment] 2018-11-14 09:50
@juliens Hi, I've checked https and looks like there is same problem there.

**Comment by kruczjak** [comment] 2018-11-15 09:17
I forgot to add what's happening when gRPC server responds with error but without traefik proxy (client logs, client is directly connected to server):

```
I1115 10:09:22.092904686   22956 parsing.cc:655]             parsing initial_metadata
I1115 10:09:22.092921154   22956 hpack_parser.cc:636]        Decode: ':status: 200', elem_interned=1 [3], k_interned=1, v_interned=1
I1115 10:09:22.092928766   22956 parsing.cc:406]             HTTP:3:HDR:CLI: :status: 32 30 30 '200'
I1115 10:09:22.092934805   22956 hpack_parser.cc:636]        Decode: 'content-type: application/grpc', elem_interned=1 [3], k_interned=1, v_interned=1
I1115 10:09:22.092940428   22956 parsing.cc:406]             HTTP:3:HDR:CLI: content-type: 61 70 70 6c 69 63 61 74 69 6f 6e 2f 67 72 70 63 'application/grpc'
I1115 10:09:22.092945676   22956 hpack_parser.cc:636]        Decode: 'grpc-accept-encoding: identity,deflate,gzip', elem_interned=1 [3], k_interned=1, v_interned=1
I1115 10:09:22.092950779   22956 parsing.cc:406]             HTTP:3:HDR:CLI: grpc-accept-encoding: 69 64 65 6e 74 69 74 79 2c 64 65 66 6c 61 74 65 2c 67 7a 69 70 'identity,deflate,gzip'
I1115 10:09:22.092955416   22956 hpack_parser.cc:636]        Decode: 'accept-encoding: identity,gzip', elem_interned=1 [3], k_interned=1, v_interned=1
I1115 10:09:22.092959820   22956 parsing.cc:406]             HTTP:3:HDR:CLI: accept-encoding: 69 64 65 6e 74 69 74 79 2c 67 7a 69 70 'identity,gzip'
I1115 10:09:22.092979009   22956 parsing.cc:660]             parsing trailing_metadata
I1115 10:09:22.092986185   22956 hpack_parser.cc:636]        Decode: 'grpc-status: 7', elem_interned=0 [2], k_interned=1, v_interned=0
I1115 10:09:22.092991066   22956 parsing.cc:502]             HTTP:3:TRL:CLI: grpc-status: 37 '7'
I1115 10:09:22.092996227   22956 hpack_parser.cc:636]        Decode: 'grpc-message: ', elem_interned=0 [2], k_interned=1, v_interned=0
I1115 10:09:22.093000726   22956 parsing.cc:502]             HTTP:3:TRL:CLI: grpc-message: 
```

Comparing to "error response from server client log using traefik" (in first comment): As you can see, there is no `parsing Trailers-Only` message in this log, "normal" headers are parsed normally same way as in successful response and trailers are also correct.

**Comment by kruczjak** [comment] 2018-11-26 11:06
Hi, any news? :)

**Comment by juliens** [comment] 2018-11-27 07:42
Hi, can you try to add this in your configuration:
```toml
[backends]
  [backends.backend1]
    [backends.backend1.responseForwarding]
    flushInterval="1µs"
    [backends.backend1.servers.server1]
    # Access on backend with h2c
    url = "h2c://localhost:9001"

```

**Comment by kruczjak** [comment] 2018-11-27 07:59
Hi @juliens , looks like it worked :D

However it's a bit random, sometimes response is ok, sometimes it's broken but as I understand correctly adding just
```
 [backends.backend1.responseForwarding]
    flushInterval="1µs"
```
is not the solution for production env.

**Comment by juliens** [comment] 2018-11-27 09:20
:+1: 

This is not the solution for production env, it was just in order to confirm the issue, I will make a PR to fix the problem in a better way.

Thx

**Comment by traefiker** [comment] 2018-11-30 15:56
Closed by #4258.

**Closed by traefiker** 2018-11-30 15:56 UTC
Labels: area/server, kind/bug/possible, priority/P1

**Comment by kruczjak** [comment] 2018-12-04 09:16
Thank! Looks like it works perfectly now :D

**Comment by juliens** [comment] 2019-01-22 07:53
@tsangpozheng I can't reproduce this bug with the 1.7.7. Can you create a new issue with a description of your problem. Thx
