### ISSUE TITLE
DASHBOARD  API recommends adding prefix configuration

### ISSUE THREAD

**Issue by ztj1993** [containous/traefik#6872] opened 2020-06-02 07:07 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

When I tested the traefik today, I found that DASHBOARD could not configure the API path, such as the following:
```
version: "3"
services:

  traefik:
    image: traefik:v2.2
    hostname: traefik
    container_name: traefik
    network_mode: bridge
    environment:
      - TRAEFIK_LOG=true
      - TRAEFIK_LOG_LEVEL=DEBUG
      - TRAEFIK_API=true
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_PROVIDERS_DOCKER=true
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.traefik-strip-prefix.stripprefix.prefixes=/traefik
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.rule=PathPrefix(`/traefik`)
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.middlewares=traefik-strip-prefix@docker
    expose:
      - 80/tcp
      - 443/tcp
      - 8080/tcp
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8080/tcp
```
I can access dashboard, but the API path is incorrect.
It is recommended to add the API request path configuration for dashboard.

**Comment by ddtmachado** [comment] 2020-06-02 14:01
@ztj1993 I believe this is already covered under [Operating -> Dashboard](https://docs.traefik.io/operations/dashboard/#dashboard-router-rule) where it states the required use of both `/dashboard` and `/api` when using a `PathPrefix` rule with following examples.

**Comment by ztj1993** [comment] 2020-06-02 15:29
@ddtmachado Assuming that I have only one domain name (the host has only one domain), this domain name needs to use the / API path, and at the same time, I need to configure the traifik dashboard, which is quite embarrassing.

I have many hosts. Each host is configured with a domain name. The / tracefik path is used for tracefik, the / administrator path is used for administrator, and other paths are used for

I recommend adding the API prefix configuration in the front end.

------

The above content comes from the translation software, please understand the problem!

**Comment by SantoDE** [comment] 2020-06-02 15:39
Hello @ztj1993,

thanks for your interest in the projects.

As this issue is a duplicate, I'll close it now.

Duplicate of #5853

**Closed by SantoDE** 2020-06-02 15:39 UTC
Labels: status/0-needs-triage
