### ISSUE TITLE
Do not exit when letsencrypt cannot be reached upon startup

### ISSUE THREAD

**Issue by raarts** [containous/traefik#1641] opened 2017-05-20 14:07 UTC
### Do you want to request a *feature* or report a *bug*?

Feature?

### What did you do?

I restarted traefik, when lesencrypt had an outage.

### What did you expect to see?

Logging an error about it, but continue

### What did you see instead?

traefik quit, and my container got stuck in a loop

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.2.3
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

Sorry, lost the logging, and letsencrypt is up again.

**Comment by ldez** [comment] 2017-05-20 14:28
Duplicate of #791 (and #1631 and #1632 and #1636 and #1637)

**Closed by ldez** 2017-05-20 14:28 UTC
Labels: area/acme, resolution/duplicate
