### ISSUE TITLE
Support override of HTTP 404 when service does not exist or is down

### ISSUE THREAD

**Issue by grobinson-blockchain** [containous/traefik#1077] opened 2017-01-27 15:39 UTC
### What version of Traefik are you using (`traefik version`)?

    Version:      dev
    Codename:     cheddar
    Go version:   go1.7.4
    Built:        I don't remember exactly
    OS/Arch:      darwin/amd64

### Request

Quite often sending HTTP 404 when a service is down (i.e. consul health check fails) is not the correct behavior (for both browsers or clients of APIs) and we'd much rather send HTTP 502 or HTTP 503.

I'm running a fork right now that overrides the NotFoundHandler for the default mux - but it would be nice if this becomes a configurable option, perhaps even with a go template.

```golang
    func badGatewayHandler(w http.ResponseWriter, r *http.Request) {
        w.WriteHeader(http.StatusBadGateway)
        fmt.Fprintf(w, "502 bad gateway")
    }

    func (server *Server) buildDefaultHTTPRouter() *mux.Router {
        router := mux.NewRouter()
        // router.NotFoundHandler = http.HandlerFunc(notFoundHandler)
        router.NotFoundHandler = http.HandlerFunc(badGatewayHandler)
        router.StrictSlash(true)
        router.SkipClean(true)
        return router
    }
```

**Comment by dtomcej** [comment] 2017-02-10 16:05
When a service does not exist, the correct response is 404. If you dynamically generate and configure services, it can be tempting to want to return a 50x.

Unfortunately, as far as the proxy is concerned, it is designed to be stateless, relying on providers for configuration. If your provider does not respond, or has missing services, traefik has no way to tell if that was legitimately deleted, or is missing, and therefore has to treat it as the former.

If you are having issues with your provider not passing health checks etc, you may want to look at providing a frontend/backend through a different provider (such as the toml), that can provide the persistence you are looking for.

**Comment by ljagiello** [comment] 2017-02-10 18:25
@dtomcej there is a difference between page not found and lack of service. RFC2616 (https://www.ietf.org/rfc/rfc2616.txt) describe when HTTP 502 should be used:
```
10.5.3 502 Bad Gateway

   The server, while acting as a gateway or proxy, received an invalid
   response from the upstream server it accessed in attempting to
   fulfill the request.
```
Lack of service of entire service down is not the same as page not found.

**Comment by dtomcej** [comment] 2017-02-10 18:31
@ljagiello Yes, I agree, but traefik is stateless. Unless you have provided state information, traefik cannot tell that your service is down/missing/broken or never existed.

If you statically define the service, then yes, it will return a 50x. If your dynamic config removes your service due to it being missing, then No, it should be a 404, as the service no longer exists.

**Comment by grobinson-blockchain** [comment] 2017-02-12 10:32
The trouble is that when Traefik returns 404 it breaks _a lot_ of stuff, one such example being error_page in NGINX.

Let's suppose we used consul-template to render the upstream directive in NGINX.

When the service is up, the upstream looks like this:

```
upstream app {
   server 10.134.xxx.xxx;
   server 10.134.xxx.xxx;
}
```

and when all services are down we have this:

```
upstream app {
}
```

NGINX does not return 404 in this case, which is the behavior we need from Traefik. 

> If you are having issues with your provider not passing health checks etc, you may want to look at providing a frontend/backend through a different provider (such as the toml), that can provide the persistence you are looking for.

Is there an example of this?

**Comment by dtomcej** [comment] 2017-02-13 18:10
No, in the case you described, nginx is NOT stateless. It is aware that `app` SHOULD exist, even without there being any servers in its pool.

As stated earlier, if you manually create a Frontend/Backend as per https://docs.traefik.io/toml/#file-backend.

If you populated a backend with no servers (or fictitious servers that didn't exist), then you should have the same behaviour.

You can also use multiple providers at the same time (you can have consul handle some things, and the file provider handle others).

**Comment by dtomcej** [comment] 2017-02-13 18:17
So just to confirm:

Your consul returns a service with no endpoints, and traefik ignores the service, leading to you getting a 404?

Or does consul not return a service due to there being no endpoints?

**Comment by discordianfish** [comment] 2017-02-20 10:37
It also breaks caching because 404 is a valid response which most CDN/reverse proxy cache. So I agree with @grobinson-blockchain that this needs some solution.

But I guess how to solve this depends on the configuration backend it uses. I'm using it on Kubernetes and it should be possible to return 502 if a ingress is configured but the backend isn't available.

The current behavior is IMO a major blocker for most prod use cases.

**Comment by errm** [comment] 2017-02-22 00:13
Agreed if we have configuration for frontends but there are no matching backends something like 502 is most appropriate...

This should be possible with the kubernetes backend, I will take a look at an implementation... unless anyone else wants to?

**Comment by errm** [comment] 2017-02-22 10:47
I have done some testing on kubernetes currently things seem to behave as they should.

If the ingress and referenced service exist, but no pods exist (or they are not ready) Traefik will return a 502 Bad Gateway...

If the ingress and service does not exist, then Traefik returns a 404.

I don't know if there is a simple way to replicate this behaviour on other providers, perhaps we could create frontends for services that have failing backends, but skip adding any servers to the backend...

**Comment by discordianfish** [comment] 2017-02-22 15:52
@errm Hrm interesting.. I'm pretty sure that I saw my application crashing and traefik returning 404. Will try to reproduce and update issue.

**Comment by jezell** [comment] 2017-03-06 19:40
We've also been seeing traefik return 404s while scaling kubernetes nodes. Seems like sometimes during scale kubernetes API service is sometimes temporarily unavailable in GKE after scaling (kubectl command line also returns errors during same time period). If traefik encounters an error getting node info from kubernetes backend does it not maintain the last known good configuration until it can reach it again?

**Comment by timoreimann** [comment] 2017-03-06 20:44
@jezell as mentioned earlier by @dtomcej, Traefik is stateless: It subscribes to the Kubernetes Watch API and uses each event just as a trigger to fetch all Ingress resources along with the associated Services and Endpoints in order to build up the frontends, backends, and servers. Not having to maintain a state machine makes it fairly robust but does not allow for the kind of things you've mentioned, like maintaining the last good state.

That wouldn't be a "correct" solution to the problem anyway though, in the sense that it does not give guarantees and induces delays due to retries. The way to achieve interruption-free scaling in Kubernetes is to require readiness checks and graceful termination. The former guarantees that new Pods don't receive traffic too early and the latter that Pods aren't taken out of load-balancing too soon.

**Comment by jezell** [comment] 2017-03-06 21:15
That's not true. Traefik maintains a cached state of the last good configuration. All I'm saying is it should continue to use the last good configuration when it encounters an API error during sync process. Right now it just logs the error and throws it away, and then acts like the sync succeeded and swaps out the last known config with a corrupt config. If it were simply to return errors here:

https://github.com/containous/traefik/blob/master/provider/kubernetes.go#L194

Instead of a continue statement, then it wouldn't override the config here:

https://github.com/containous/traefik/blob/master/provider/kubernetes.go#L88

And take down the entire router because of a temporary API error. The current behavior can't possibly be desired by anyone, certainly it's enough to make us stop using traefik if it's expected for it to just competely fall over because it fails to make an api call every once and a while.

**Comment by Regner** [comment] 2017-03-06 21:26
Seems like the err and exists should be split into two different if blocks.

https://github.com/containous/traefik/blob/master/provider/kubernetes.go#L191

If `err != nil` traefik should probably keep the current state and if `!exists` it should probably do what it does now, remove the current service.

**Comment by timoreimann** [comment] 2017-03-06 21:43
@jezell apologies, I misunderstood on what level you were arguing (payload requests vs. configuration/control requests).

Your point seems reasonable, though seemingly not strictly related to the issue at hand. Maybe you should create a separate issue (assuming none has been filed yet)?

**Comment by jezell** [comment] 2017-03-06 21:53
@timoreimann yeah it is probably a different issue. I'll create one. Sorry for the confusion.

**Comment by bsphere** [comment] 2017-03-09 22:26
just verified it as well, if consul returns a service with no endpoints Traefik returns 404 which is wrong..
(using the consulcatalog backend)

**Comment by discordianfish** [comment] 2017-03-22 10:17
Even if there is no service for a given name, I'd rather have it respond with 502 than 404.

In general a 404 is not an error, while a backend that should be there but isn't clearly is an error. With static configuration that's easy: Once configured, it knows what should be there. That doesn't work with traefik. So instead I'd like to have a option to always return 502 (think proxy vs webserver mode) if the request doesn't match a service.

Now that I think about this more (so far using traefik only for pet projects), this would be a hard requirement for me to introduce traefik to production.

**Comment by grobinson-blockchain** [comment] 2017-04-13 12:43
The other issue is that 404 is a client error code, not a server error. However, if a service doesn't exist, because it is down, this is not a client error.

**Comment by counterliero** [comment] 2017-04-28 16:05
I absolutely agree with @discordianfish and @grobinson-blockchain. This not a client error but a server error. Why shouldn't it be possible to return 502 if there is no route to a backend? This would be an indicator for a missing backend and could be use to differentiate 404 and 503 errors.
Additionally, this will break caching in Varnish and other caches/reverse proxies. IMHO, this is a major blocker for production usage.

**Comment by rohte** [comment] 2017-05-15 12:57
I agree with @discordianfish, @grobinson-blockchain and @splieth that the behaviour of traefik is not what I would expect from a proxy.
There is also the thing in the Marathon provider (https://github.com/containous/traefik/blob/master/provider/marathon/marathon.go) that it filters all suspended or unhealthy tasks.
I would expect the app to be known when all tasks of a specific app are unhealthy. So a 50x error if the app is there, but not available at the moment and a 404 if the app is not defined. The first one is an error on the server side and the second one an error on the client side.
And even if traefik is stateless, marathon provides this information, the proxy is just not acting accordingly.
The suggestion by @grobinson-blockchain to configure the NotFoundHandler wouldn't fix this.

**Comment by timoreimann** [comment] 2017-05-15 16:41
To me it looks like we have two different, desirable behavior changes here:

1. Return a configurable error code (e.g., something from the `50[234]` range) if either a target frontend or its backends are missing.
1. Return a configurable error code if the backends to a known frontend are missing, and a 404 if the frontend is unknown.

Would that be a correct observation?

Personally, I am also worried about negative caching effects that may occur in a dynamic, microservices-driven environment where frontends can easily (but inadvertently) disappear for short periods of time. Hence, approach 1. (which the current in-flight PR implements) seems to be the safer one from this perspective. I'm open for discussion and possible re-adjustment, though.

**Comment by rohte** [comment] 2017-05-17 14:45
At least I am speaking about the second one @timoreimann . I personally don't really care about the specific error code returned, as long as it is in the 50x range.

What I have so far observed is that (in a Mesos/Marathon environment) it happens every now and then that all instances of an application are unhealthy. But so far I have never seen an application being temporarily undefined.
So to me an undefined application really means that it should not be there (hence 404). An unhealthy one on the other side means that it should be there, but is temporarily unavailable (hence 50x). This might be different for other providers.
It is sort of neat, that unhealthy instances are not even known by traefik, but it induces a lot of confusion during operation.
One reason I want a 404 and a 50x is that where I am, there is some logic that happens on a 404 that tries to find a relevant page for the user before actually returning a 404-error-page. This would break if only one of those codes is returned on both occasions.
Another reason is that this is AFAIK how any other reverse proxy behaves and it just fits more into the correct definition of client and server errors.

**Comment by timoreimann** [comment] 2017-05-31 17:29
After re-reading and reviewing this issue again, it seems like there are a few, related concerns being discussed on the general question on what error codes should be returned under which conditions, and how existing providers are behaving right now in this regard. It's become somewhat tricky though to follow the debate and see what we need/want to achieve exactly. The essence of it all seems to be that we should prevent 404s from being returned where a frontend (often denoted as "service" within this issue) is expected to exist.

Therefore, we (the maintainers) have concluded that it's best to spin off more specific issues to track effort towards making the existing providers adjust accordingly. As far as I understood, however, providers like Consul cannot be covered, and we may need to evaluate alternatives.

I'll close this issue for now. Thanks everybody involved for giving feedback and providing use cases so far. I'd be happy to see you contribute to the follow-up issues 1688 and 1689 in order to help coming to an adequate solution for the problem at hand.

**Closed by timoreimann** 2017-05-31 17:29 UTC
Labels: kind/enhancement

**Comment by zebpalmer** [comment] 2018-04-11 19:12
As this comes up pretty easily for searches about not wanting the default 404 for missing/down services, I thought I'd drop a note here. We do dynamic traefik configuration in docker swarm and the tree of issues/PRs that relate to this issue were, as of current and as far as we can tell, not solving our issue. We needed traefik to respond with a 50x instead of 404 when a service was unavailable in a swarm regardless if it was not registered with traefik.  Returning 404 when a service isn't present on a swarm feels wrong -- in our case it caused the client side not to retry against other healthy swarms. 

This is hacky... but we ended up deploying a web service that returns http 503 on any request. We then registered this service with a catchall rule and a lower priority.   In our testing, this works pretty well.   

```
traefik.frontend.rule=HostRegexp:{catchall:.*}
traefik.frontend.priority=1
```

**Comment by ravilr** [comment] 2018-05-02 18:51
@timoreimann what do you suggest to use for readinessProbe for traefik deployment in Kubernetes? 
while rolling out an upgrade, we notice that a new traefik pod returns 404's for few seconds right after the startup, because the initial sync of ingresses, services from K8s api hasn't happened yet.  
I think all the providers should implement a `isReady()` interface, so that traefik can use it declare itself ready for serving during startup?

**Comment by port22** [comment] 2019-06-07 12:05
I second the configurable HTTP status code for non-reachable backends, on a per-frontend-configurable basis and/or at least a globally default.
Problem with the general 404 is that it confuses bots and also users.

**Comment by strarsis** [comment] 2019-11-11 22:12
@josefglatz: I just have an issue with a manually added router and "Bad Gateway" (HTTP 502) with Traefik v2.x, so yes I guess.

**Comment by OmegaVVeapon** [comment] 2020-01-20 21:56
For what it's worth, I was dealing with this issue today as well.

The only semi-reasonable solution I found was to use the **file** provider for the non-reachable backend like so:

```
http:
  services:
    my-backend:
      loadBalancer:
        servers:
          - url: "http://172.69.69.69:12240/my-backend"
  routers:
    my-backend:
      # By default, routers listen to every entry points
      rule: "PathPrefix(`/my-backend`)"
      entryPoints:
        - "http"
      service: "my-backend"
```
Since the IP in that URL is the one from the `my-backend` Docker container, I forced the container's IP to be static as described in the docker-compose file reference [here](https://docs.docker.com/compose/compose-file/#ipv4_address-ipv6_address). Otherwise, you can't use this approach since your container's IP will obviously change.

I'm not a big fan of use a **file** provider for a Docker container backend but @dtomcej is right, unless you tell Traefik _somewhere_ it's impossible for it to know whether `/my-backend` is a non-existent path or a path that _should_ exist but routes to a backend that is currently down. So them's the breaks?

**Comment by pySilver** [comment] 2021-01-04 02:15
Is there any good way to have 502 or 503 in traefik 2.x? There is so much reasons to show 502 instead of 404. Search bots like googlebot or msnbot (or any other) does not like 404 in case service is down. Its bad for SEO and it's bad for business.
