### ISSUE TITLE
Use Kubernetes Secrets as K/V to store ACME certificates

### ISSUE THREAD

**Issue by Sturgelose** [containous/traefik#2236] opened 2017-10-10 07:12 UTC
### What did you do?

As a user I'd like to easily setup a HA cluster in Kubernetes.

### What did you expect to see?

As a user, I'd like to store Traefik HTTPS certificates generated with Let's Encrypt into a Secret resource in Kubernetes.
At the moment this can be achieved using the K/V store tutorial, but requires to setup an Etcd or Consul cluster, when Kubernetes is based already in a K/V Etcd cluster. Also, setting up an K/V cluster increases deployment complexity and the resource consumption in the cluster.

Secrets allow to be updated inside of containers in real time, which eventually would allow to reload the certificates in all the Traefik Ingresses instances or anywhere else needed. A similar implementation can be found in kube-lego https://github.com/jetstack/kube-lego, where they create a Service Account and use it to store a Secret in Kubernetes' API. However, it doesn't allow to, for example, setup the ACME callback via Cloudflare or other providers.

In order to implement this feature there would be 3 things to be done:

1. Add logic to write to secrets from Traefik to Kubernetes API
2. Be able to elect leader using Traefik secrets as K/V ??
3. Update RBAC manifest to allow Traefik to use a Service Account to update its own specific secrets.

### What did you see instead?

It is needed to setup a K/V cluster, which is a waste of resources if you only need it for Traefik.
Also, shared volumes between nodes are difficult to setup in Kubernetes.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.8
Codename:     raclette
Go version:   go1.8.3
Built:        2017-09-07_08:46:19PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes 1.7.8 in AWS set up wit Kops.
Traefik set up manually (no Helm).

**Comment by ldez** [comment] 2017-10-10 11:54
Duplicate of #378

**Closed by ldez** 2017-10-10 11:54 UTC
Labels: area/acme, status/0-needs-triage
