### ISSUE TITLE
Traefik forwardAuth should have an option to forward the path as well like nginx 

### ISSUE THREAD

**Issue by Vad1mo** [containous/traefik#6840] opened 2020-05-24 19:10 UTC
With nginx it is possible to create forward auth-url with a dynamic request_uri

`nginx.ingress.kubernetes.io/auth-url: https://forwardauth.corp.example.com/verify?uri=$scheme://$host$request_uri
`
I would be good if traefik forwardAuth Middleware provided a similar option:

```yaml
http:
  middlewares:
    test-auth:
      forwardAuth:
        address: "https://example.com/auth"
        appnedRequestUri: true
```

Even better or more flexible solution would be if traefik suppored suppored the header values with gotemplate in the address.

**Comment by SantoDE** [comment] 2020-05-25 15:27
Duplicate of #6839

**Closed** 2020-05-26 15:04 UTC
Labels: resolution/duplicate
