### ISSUE TITLE
Traefik Dashboard doesn't respects X-Forwarder-Prefix

### ISSUE THREAD

**Issue by dm3ch** [containous/traefik#5852] opened 2019-11-16 21:49 UTC
### Do you want to request a *feature* or report a *bug*? 

Bug

### What did you do?
Set up traefik and configured it to serve dashboard on some domain on certain path with prefix stripping.

Here's my traefik docker labels:
```
"traefik.http.routers.traefik.rule=Host(`sample.domain`) && PathPrefix(`/traefik`)"
"traefik.http.routers.traefik.entrypoints=http"
"traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
"traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
"traefik.http.routers.traefik.middlewares=redirect-https@docker"
"traefik.http.routers.traefik-secure.rule=Host(`sample.domain`) && PathPrefix(`/traefik`)"
"traefik.http.routers.traefik-secure.entrypoints=https"
"traefik.http.routers.traefik-secure.service=api@internal"
"traefik.http.middlewares.traefik-auth.basicauth.users={{ basic_auth }}"
"traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/traefik"
"traefik.http.routers.traefik-secure.middlewares=traefik-auth,traefik-strip"
"traefik.http.routers.traefik-secure.tls=true"
"traefik.http.routers.traefik-secure.tls.certresolver=main"
```

### What did you expect to see?
Traefik dashboard works well with given prefix path.

### What did you see instead?
Traefik frontend tries to access sample.domain/api/overview and other api endpoints.
It would be very useful if dashboard would forming this URLS respecting  X-Forwarded-Prefix heade

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.5
Codename:     montdor
Go version:   go1.13.4
Built:        2019-11-14T18:11:01Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by ldez** [comment] 2019-11-17 00:09
duplicate of #5374

**Closed** 2019-11-17 00:09 UTC
Labels: resolution/duplicate
