### ISSUE TITLE
passTLSCert middleware not modifying headers on kubernetes

### ISSUE THREAD

**Issue by rochaporto** [containous/traefik#4493] opened 2019-02-13 12:03 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Followed issue #4048 but still couldn't see the headers being modified and forwarded.

On a test setup with kubernetes + ingress, i tried:

1. curl with a custom CA
2. backend is a golang server that dumps the HTTP request (https://gitlab.cern.ch/rbritoda/go-headers)

### What did you expect to see?

X-Forwarded-Ssl-Client-Cert and X-Forwarded-Tls-Client-Cert-info showing up in my go test implementation with the client cert information.

### What did you see instead?

No such headers appeared.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
kubectl -n kube-system exec ingress-traefik traefik version
traefik version
Version:      v1.7.8
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-01-29_04:33:36PM
OS/Arch:      linux/amd64

kubectl -n kube-system exec ingress-traefik ps auxw
PID   USER     TIME  COMMAND
    1 root      0:08 traefik traefik --api --traefikLog=true --kubernetes --kubernetes.enablepasstlscert=true --logLevel=DEBUG --entrypoints=Name:http Address::80 --entrypoints=Name:https Address::443 TLS
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Certificate creation:
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=passtlstest001.cern.ch"
kubectl  create secret tls go-headers-secret --key=tls.key --cert=tls.crt
```

Sample kubernetes deployment + ingress:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-headers-deployment
spec:
  selector:
    matchLabels:
      app: go-headers
  replicas: 1
  template:
    metadata:
      labels:
        app: go-headers
    spec:
      containers:
      - name: go-headers
        image: go-headers
        ports:
        - containerPort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-headers
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: https
    traefik.ingress.kubernetes.io/pass-client-tls-cert: |
      pem: true
      infos:
        notafter: true
        notbefore: true
        sans: true
        subject:
          country: true
          province: true
          locality: true
          organization: true
          commonname: true
          serialnumber: true
          domaincomponent: true
        issuer:
          country: true
          province: true
          locality: true
          organization: true
          commonname: true
          serialnumber: true
          domaincomponent: true
spec:
  rules:
  - host: passtlstest001.cern.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: go-headers
          servicePort: 8000
  tls:
   - secretName: go-headers-secret
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

Traefik logs (there's an example.com entry i'm not sure where it comes from):
```
time="2019-02-12T22:31:42Z" level=debug msg="Wiring frontend passtlstest001.cern.ch/ to entryPoint https"
time="2019-02-12T22:31:42Z" level=debug msg="Creating backend passtlstest001.cern.ch/"
time="2019-02-12T22:31:42Z" level=debug msg="Adding TLSClientHeaders middleware for frontend passtlstest001.cern.ch/"
time="2019-02-12T22:31:43Z" level=debug msg="Creating load-balancer wrr"
time="2019-02-12T22:31:43Z" level=debug msg="Creating route passtlstest001.cern.ch Host:passtlstest001.cern.ch"
time="2019-02-12T22:31:43Z" level=debug msg="Creating route / PathPrefix:/"
time="2019-02-12T22:31:43Z" level=debug msg="Wiring frontend traefik.example.com to entryPoint http"
time="2019-02-12T22:31:43Z" level=debug msg="Creating backend traefik.example.com"
time="2019-02-12T22:31:43Z" level=debug msg="Adding TLSClientHeaders middleware for frontend traefik.example.com"
time="2019-02-12T22:31:43Z" level=error msg="failed to create the forwarder for frontend traefik.example.com: failed to create RoundTripper for frontend traefik.example.com: failed to create TLSClientConfig: no TLS provided. Skipping frontend traefik.example.com..."
time="2019-02-12T22:31:43Z" level=debug msg="Add certificate for domains passtlstest001.cern.ch"
```

Sample request:
```
echo | openssl s_client -showcerts -servername passtlstest001.cern.ch -connect passtlstest001.cern.ch:443 2>/dev/null  > ca.crt

curl --cacert ca.crt  https://passtlstest001.cern.ch
GET / HTTP/1.1 
Header field "X-Forwarded-For", Value ["<redacted>"]
Header field "X-Forwarded-Host", Value ["passtlstest001.cern.ch"]
Header field "X-Forwarded-Port", Value ["443"]
Header field "X-Real-Ip", Value ["<redacted>"]
Header field "User-Agent", Value ["curl/7.29.0"]
Header field "Accept", Value ["*/*"]
Header field "X-Forwarded-Proto", Value ["https"]
Header field "X-Forwarded-Server", Value ["<redacted>"]
Header field "Accept-Encoding", Value ["gzip"]
Host = "passtlstest001.cern.ch"
RemoteAddr= "10.100.50.1:42458"

Finding value of "Accept" ["*/*"]
```

Traefik logs:
```
time="2019-02-12T22:34:54Z" level=warning msg="Try to extract certificate on a request without TLS"
time="2019-02-12T22:34:54Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"passtlstest001.cern.ch\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<redacted>:54616\",\"RequestURI\":\"/\",\"TLS\":null}"
```

The [relevant code](https://github.com/containous/traefik/blob/master/middlewares/passtlsclientcert/pass_tls_client_cert.go#L217) seems to indicate the TLS field in the request is being passed empty.

**Comment by mazhead** [comment] 2019-02-13 17:10
This exact thing actually happens on swarm also. Seems to be a problem overall not limited to kubernetes.

**Comment by rochaporto** [comment] 2019-02-20 11:49
Any feedback or progress on this?

**Comment by jbdoumenjou** [comment] 2019-02-20 13:55
Hi @rochaporto, sorry for the delay.
I will try to reproduce your case in the coming days.
First quick comment, you don't need the `--kubernetes.enablepasstlscert=true` which is the deprected option. The `traefik.ingress.kubernetes.io/pass-client-tls-cert` annotation is sufficient.

**Comment by rochaporto** [comment] 2019-02-20 23:04
Ok thanks, let me know if you need any more info.

**Comment by vkuznet** [comment] 2019-02-26 20:46
is there are any progress on this. Different groups at CERN are awaiting for this fix.

**Comment by jbdoumenjou** [comment] 2019-03-05 10:54
Hi, 

to use this option, you need a "valid" tls connexion with the entrypoint, so you have to configure your entrypoint with a client CA that matches your domain.
I used the following arguments in my traefik deployment:
```yaml
args:
  - --debug
  - --kubernetes
  - --logLevel=DEBUG
  - --defaultentrypoints=http,https
  - --entrypoints=Name:http Address::80
  - --entrypoints=Name:https Address::443 TLS CA:/app/certs/ca/myca
```
I used a [containous/whoami](https://github.com/containous/whoami) as backend, and the following ingress configuration:

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
  namespace: kube-system
  labels:
    app: whoami
  annotations:
    kubernetes.io/ingress.class: 'traefik'
    traefik.ingress.kubernetes.io/pass-client-tls-cert: |-
      pem: true
      infos:
        notafter: true
        notbefore: true
        sans: true
        subject:
          country: true
          province: true
          locality: true
          organization: true
          commonname: true
          serialnumber: true
spec:
  rules:
    - host: server
      http:
        paths:
          - backend:
              serviceName: whoami
              servicePort: 80
```
I exposed my traefik-ingress service (8443->443), then:

```
$ curl -k -H "Host:server" https://localhost:8443 --cert client.pem --key client.key
Hostname: whoami-6ff8c9f956-8q59z
IP: 127.0.0.1
IP: ::1
IP: 10.42.0.8
IP: fe80::b0d8:4eff:fef9:eb28
GET / HTTP/1.1
Host: server
User-Agent: curl/7.64.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: server
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik-ingress-controller-6cd99f68f5-f66dk
X-Forwarded-Tls-Client-Cert: MIIDKzCCAhM [...] xbyA%3D%3D
X-Forwarded-Tls-Client-Cert-Infos: Subject%3D%22C%3D [...] %2CSAN%3D
X-Real-Ip: 127.0.0.1
```

Let me know if it solves your issue.

**Comment by rochaporto** [comment] 2019-03-05 11:45
Thanks @jbdoumenjou .

I'll try that, but that means adding one CA explicitly to the ingress traefik controller. I was trying instead to pass the TLS cert in the ingress resource, as in:
```
spec:
  rules:
  - host: passtlstest001.cern.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: go-headers
          servicePort: 8000
  tls:
   - secretName: go-headers-secret
```

I can see the controller then serves the correct cert in the entrypoint, so shouldn't this work in the same way?

**Comment by rochaporto** [comment] 2019-03-05 13:53
I confirm this works when explicitly passing the CA in the ingress controller config.

But that would mean that for each cluster we can only rely on one CA? Is this by design? And then all secrets passed in the ingress resources should come from that CA is this it?

**Comment by vkuznet** [comment] 2019-03-05 14:08
@jbdoumenjou, let me understand your point. You wrote "you have to configure your entrypoint with a client CA that matches your domain", but I think you meant to configure entrypoint with **server** CA that matches the domain. In other words, first we get domain name, then create CA for it and use it to configure the k8s cluster. Then our clients (which have their own certs) will be able to talk to k8s cluster and their certs will be passed in traefk HTTP headers to backends. Am I right?

**Comment by jbdoumenjou** [comment] 2019-03-05 14:37
@rochaporto, you can also specify a list of CA to match all your cases. And yes, it is by design to validate that you have a secured connection to pass your certificates / keys. 

@vkuznet, I talked about the CA for the incoming requests to traefik. As I said, we assume that you pass the certificates / keys with a secured connection. I hope this is clearer.

I encourage you to open a new issue if you want an enhancement on the TLS client cert feature.
You can also join the #support channel on our slack https://slack.traefik.io/ if you have more questions.

If I answer your question, I will close this issue.

**Comment by rochaporto** [comment] 2019-03-05 14:59
From my side this is clear, you can close it.

**Comment by geraldcroes** [comment] 2019-03-05 15:38
Thank you for your feedback! 
Closing the issue 👍

**Closed by geraldcroes** 2019-03-05 15:38 UTC
Labels: area/middleware, contributor/waiting-for-feedback, kind/question, priority/P2
