### ISSUE TITLE
Error msg in logs "Failed to retrieve auth configuration for ingress / failed to load auth credentials " but ingress rule configured as expected

### ISSUE THREAD

**Issue by looztra** [containous/traefik#4523] opened 2019-02-25 10:18 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- **Given** I use traefik (v1.7.9) as an Ingress Controller in a Kubernetes instance
- **When** I create a __Kubernetes Ingress Rule__ that refers to a secret holding the basic auth infos (both the ingress rule and the secret are in the same namespace called `ingress-controllers`) with : 

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-secret: traefik-ui-auth
    ingress.kubernetes.io/auth-type: basic
    kubernetes.io/ingress.class: traefik
  name: traefik-web-ui
  namespace: ingress-controllers
spec:
  rules:
  - host: traefik-ui.192.168.99.100.xip.io
    http:
      paths:
      - backend:
          serviceName: traefik-web-ui
          servicePort: admin
```

and the secret descriptor is : 

```yaml
apiVersion: v1
data:
  auth: ZW1pbGU6JGFwcjEkV3B2LnRlL0MkZE5FMHQ1NjBkbFBTNUlqNTI5TmNRLgo=
kind: Secret
metadata:
  name: traefik-ui-auth
  namespace: ingress-controllers
type: Opaque
```

### What did you expect to see?

- The ingress rule is applied and protected by basic auth
- Nothing shows up in logs

### What did you see instead?

- The ingress rule is applied and protected by basic auth
- An error message is printed in logs :

```bash
time="2019-02-25T09:29:52Z" level=error msg="Failed to retrieve auth configuration for ingress ingress-controllers/traefik-web-ui: failed to load auth credentials: secret \"ingress-controllers\"/\"traefik-ui-auth\" not found"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Full set of descriptors (minus the secret) to test in minikube (for instance)
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-controllers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: ingress-controllers
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: awesome:traefik-ingress-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: awesome:traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awesome:traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: ingress-controllers
---
apiVersion: v1
data:
  traefik.toml: |
    insecureSkipVerify = true
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [acme]
    email = "techops@awesome.com"
    storageFile = "/acme/acme.json"
    entryPoint = "https"
    onDemand = true
    onHostRule = true
    [acme.httpChallenge]
      entryPoint = "http"
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: ingress-controllers
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-endpoint
  namespace: ingress-controllers
spec:
  loadBalancerIP: ""
  ports:
  - name: main-http
    port: 80
    targetPort: main-http
  - name: main-https
    port: 443
    targetPort: main-https
  selector:
    app: traefik-ingress-lb
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: ingress-controllers
spec:
  ports:
  - name: admin
    port: 8080
    targetPort: admin
  selector:
    app: traefik-ingress-lb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: traefik-ingress-lb
  name: traefik-ingress-controller
  namespace: ingress-controllers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-ingress-lb
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
    spec:
      containers:
      - args:
        - --configfile=/config/traefik.toml
        - --web
        - --kubernetes
        image: traefik:v1.7.9
        imagePullPolicy: Always
        name: traefik
        ports:
        - containerPort: 80
          name: main-http
        - containerPort: 443
          name: main-https
        - containerPort: 8080
          name: admin
        resources:
          limits:
            cpu: 200m
            memory: 64Mi
        volumeMounts:
        - mountPath: /acme
          name: traefik-acme
        - mountPath: /config
          name: traefik-config
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: traefik-acme
        persistentVolumeClaim:
          claimName: traefik-acme
      - configMap:
          name: traefik-conf
        name: traefik-config
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-secret: traefik-ui-auth
    ingress.kubernetes.io/auth-type: basic
    kubernetes.io/ingress.class: traefik
  name: traefik-web-ui
  namespace: ingress-controllers
spec:
  rules:
  - host: traefik-ui.192.168.99.100.xip.io
    http:
      paths:
      - backend:
          serviceName: traefik-web-ui
          servicePort: admin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-acme
  namespace: ingress-controllers
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard

```

**Comment by vrobert78** [comment] 2019-02-26 08:34
Hi, 

we have the same problem. Tested with traefik:v1.7 and traefik:v1.6.

The auth config is well applied despite the error message.

Regards,

**Comment by dtomcej** [comment] 2019-02-26 17:31
Hello @looztra, can you provide the debug logs from the traefik startup?

I am curious to see if this issue is a duplicate of (https://github.com/containous/traefik/issues/3667), where the error messages are due to the asynchronous loading of the kubernetes objects.

In that case, the ingresses are loaded before the secrets, and generate an error in the log. Once the objects are all loaded, the ingress works as intended.

Please let us know!

**Comment by looztra** [comment] 2019-02-26 20:51
looks like it is related according to what I understand of the logs

```
+ traefik-ingress-controller-76fff49668-w22ks › traefik
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:47:59Z" level=info msg="Using TOML configuration file /config/traefik.toml"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:47:59Z" level=warning msg="web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:47:59Z" level=warning msg="ACME.StorageFile is deprecated, use ACME.Storage instead"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:47:59Z" level=warning msg="ACME.OnDemand is deprecated"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:47:59Z" level=info msg="Traefik version v1.7.9 built on 2019-02-11_11:36:32AM"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:47:59Z" level=debug msg="Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceTimeOut\":0,\"Debug\":false,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false,\"AccessLogsFile\":\"\",\"AccessLog\":null,\"TraefikLogsFile\":\"\",\"TraefikLog\":null,\"Tracing\":null,\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"TLS\":null,\"Redirect\":{\"entryPoint\":\"https\"},\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"https\":{\"Address\":\":443\",\"TLS\":{\"MinVersion\":\"\",\"CipherSuites\":null,\"Certificates\":null,\"ClientCAFiles\":null,\"ClientCA\":{\"Files\":null,\"Optional\":false},\"DefaultCertificate\":null,\"SniStrict\":false},\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}}},\"Cluster\":null,\"Constraints\":[],\"ACME\":{\"Email\":\"techops@awesome.com\",\"Domains\":null,\"Storage\":\"/acme/acme.json\",\"StorageFile\":\"/acme/acme.json\",\"OnDemand\":true,\"OnHostRule\":true,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"EntryPoint\":\"https\",\"KeyType\":\"\",\"DNSChallenge\":null,\"HTTPChallenge\":{\"EntryPoint\":\"http\"},\"TLSChallenge\":null,\"DNSProvider\":\"\",\"DelayDontCheckDNS\":0,\"ACMELogging\":false,\"OverrideCertificates\":false,\"TLSConfig\":null},\"DefaultEntryPoints\":[\"http\",\"https\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"IdleTimeout\":0,\"InsecureSkipVerify\":true,\"RootCAs\":null,\"Retry\":null,\"HealthCheck\":{\"Interval\":30000000000},\"RespondingTimeouts\":null,\"ForwardingTimeouts\":null,\"AllowMinWeightZero\":false,\"KeepTrailingSlash\":false,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Statistics\":null,\"Metrics\":null,\"Path\":\"/\",\"Auth\":null,\"Debug\":false},\"Docker\":null,\"File\":null,\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\",\"IngressEndpoint\":null},\"Mesos\":null,\"Eureka\":null,\"ECS\":null,\"Rancher\":null,\"DynamoDB\":null,\"ServiceFabric\":null,\"Rest\":null,\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Debug\":false,\"CurrentConfigurations\":null,\"Statistics\":null},\"Metrics\":null,\"Ping\":{\"EntryPoint\":\"traefik\"},\"HostResolver\":null}"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:47:59Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:47:59Z" level=debug msg="Setting Acme Certificate store from Entrypoint: https"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:02Z" level=info msg="Preparing server https &{Address::443 TLS:0xc0002a7170 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc00058d8c0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc00058d8e0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=info msg="Starting server on :443"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=debug msg="Creating entry point redirect http -> https"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:0xc000242140 Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc00058d8a0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=info msg="Starting server on :8080"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=info msg="Starting server on :80"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=info msg="Starting provider *kubernetes.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\",\"IngressEndpoint\":null}"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=info msg="Starting provider *acme.Provider {\"Email\":\"techops@awesome.com\",\"ACMELogging\":false,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"Storage\":\"/acme/acme.json\",\"EntryPoint\":\"https\",\"KeyType\":\"\",\"OnHostRule\":true,\"OnDemand\":true,\"DNSChallenge\":null,\"HTTPChallenge\":{\"EntryPoint\":\"http\"},\"TLSChallenge\":null,\"Domains\":null,\"Store\":{}}"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=info msg="Testing certificate renew..."
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=debug msg="Using Ingress label selector: \"\""
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=info msg="ingress label selector is: \"\""
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=info msg="Creating in-cluster Provider client"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:03Z" level=debug msg="Configuration received from provider ACME: {}"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:04Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:04Z" level=error msg="Failed to retrieve auth configuration for ingress ingress-controllers/traefik-web-ui: failed to load auth credentials: secret \"ingress-controllers\"/\"traefik-ui-auth\" not found"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:04Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"traefik-ui.192.168.99.100.xip.io\":{\"loadBalancer\":{\"method\":\"wrr\"}}}}"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:04Z" level=debug msg="Received Kubernetes event kind *v1.Secret"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:04Z" level=debug msg="Received Kubernetes event kind *v1.Secret"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:04Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:04Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"traefik-ui.192.168.99.100.xip.io\":{\"servers\":{\"traefik-ingress-controller-76fff49668-w22ks\":{\"url\":\"http://172.17.0.6:8080\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"traefik-ui.192.168.99.100.xip.io\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"traefik-ui.192.168.99.100.xip.io\",\"routes\":{\"traefik-ui.192.168.99.100.xip.io\":{\"rule\":\"Host:traefik-ui.192.168.99.100.xip.io\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null,\"auth\":{\"basic\":{\"users\":[\"emile:$apr1$Wpv.te/C$dNE0t560dlPS5Ij529NcQ.\"]},\"headerField\":\"X-WebAuth-User\"}}}}"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:04Z" level=debug msg="Received Kubernetes event kind *v1.Secret"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:04Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:04Z" level=debug msg="Received Kubernetes event kind *v1.Secret"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:04Z" level=debug msg="Skipping Kubernetes event kind *v1.Secret"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:05Z" level=info msg="Server configuration reloaded on :443"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:05Z" level=info msg="Server configuration reloaded on :8080"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:05Z" level=info msg="Server configuration reloaded on :80"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:05Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:05Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:06Z" level=debug msg="Received Kubernetes event kind *v1.Endpoints"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:06Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:06Z" level=info msg="Server configuration reloaded on :80"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:06Z" level=info msg="Server configuration reloaded on :443"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:06Z" level=info msg="Server configuration reloaded on :8080"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Wiring frontend traefik-ui.192.168.99.100.xip.io to entryPoint http"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Creating backend traefik-ui.192.168.99.100.xip.io"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Adding TLSClientHeaders middleware for frontend traefik-ui.192.168.99.100.xip.io"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Creating load-balancer wrr"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Creating server traefik-ingress-controller-76fff49668-w22ks at http://172.17.0.6:8080 with weight 1"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Creating route traefik-ui.192.168.99.100.xip.io Host:traefik-ui.192.168.99.100.xip.io"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Wiring frontend traefik-ui.192.168.99.100.xip.io to entryPoint https"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Creating backend traefik-ui.192.168.99.100.xip.io"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Adding TLSClientHeaders middleware for frontend traefik-ui.192.168.99.100.xip.io"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Creating load-balancer wrr"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Creating server traefik-ingress-controller-76fff49668-w22ks at http://172.17.0.6:8080 with weight 1"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Creating route traefik-ui.192.168.99.100.xip.io Host:traefik-ui.192.168.99.100.xip.io"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=info msg="Server configuration reloaded on :80"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=info msg="Server configuration reloaded on :443"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=info msg="Server configuration reloaded on :8080"
traefik-ingress-controller-76fff49668-w22ks traefik time="2019-02-26T20:48:07Z" level=debug msg="Try to challenge certificate for domain [traefik-ui.192.168.99.100.xip.io] founded in Host rule"

```

**Comment by dtomcej** [comment] 2019-02-27 16:33
Confirmed Duplicate of #3667

**Closed** 2019-03-01 15:16 UTC
Labels: area/provider/k8s, priority/P2, resolution/duplicate
