### ISSUE TITLE
Dashboard show backend health

### ISSUE THREAD

**Issue by LukeMauldin** [containous/traefik#2892] opened 2018-02-19 21:29 UTC
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?

Visual demonstration of the each backends health in the dashboard page (similar to haproxy stats page indicators).

### What did you see instead?
No visual indication if the backend is healthy

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.5.2

**Comment by ldez** [comment] 2018-02-20 00:11
Duplicate of #1783

**Closed by ldez** 2018-02-20 00:11 UTC
Labels: area/webui, resolution/duplicate
