### ISSUE TITLE
Backend HTTP response headers ignored

### ISSUE THREAD

**Issue by rbadsi** [containous/traefik#518] opened 2016-07-12 13:07 UTC
I am running traefik v1.0.0-rc3. It looks like traefik is either ignoring or changing the HTTP headers. This is the response I get when I send the request directly to the backend:

```console
$ curl -v -H 'Host: tiny_noether.docker.localhost' http://192.168.100.1:8066/image.svg
* Hostname was NOT found in DNS cache
*   Trying 192.168.100.1...
* Connected to 192.168.100.1 (192.168.100.1) port 8066 (#0)
> GET /image.svg HTTP/1.1
> User-Agent: curl/7.37.0
> Accept: */*
> Host: tiny_noether.docker.localhost
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: SimpleHTTP/0.6 Python/3.4.1
< Date: Tue, 12 Jul 2016 14:59:11 GMT
< Content-type: image/svg+xml
< Content-Length: 840
< Last-Modified: Fri, 01 Apr 2016 14:23:50 GMT
```

When I send the same request through the traefik, the Content-Type header changes to text/plain and the Last-Modified header disappears:

```console
$ curl -v -H 'Host: tiny_noether.docker.localhost' http://192.168.100.1/image.svg
* Hostname was NOT found in DNS cache
*   Trying 192.168.100.1...
* Connected to 192.168.100.1 (192.168.100.1) port 80 (#0)
> GET /image.svg HTTP/1.1
> User-Agent: curl/7.37.0
> Accept: */*
> Host: tiny_noether.docker.localhost
> 
< HTTP/1.1 200 OK
< Date: Tue, 12 Jul 2016 14:41:09 GMT
< Content-Length: 840
< Content-Type: text/plain; charset=utf-8
```

The response body is OK.

Thanks!

**Comment by emilevauge** [comment] 2016-07-12 13:20
Please try v1.0.0, this should be fixed now.

**Comment by ajutzeler** [comment] 2016-12-30 22:48
I am having the same kind of issue somehow with v1.1.2.

In my case, it's the 'Connection' header that Traefik makes disappear. The original value of this header set by my backend is 'keep alive'.

I am using a docker backend with the provided default config and 'MaxIdleConnsPerHost' set to 200.

**Comment by ajutzeler** [comment] 2016-12-31 17:43
It only happens when I use HTTPS entrypoint

**Comment by Klim3r0** [comment] 2017-03-09 14:40
Same issue but different use-case.

Backend response with headers only (no content and content-type header not set).
Traefik response with a 'text/plain' content-type header.

**Comment by timoreimann** [comment] 2017-03-28 22:30
I'm having difficulties confirming this issue: My tests with Traefik 1.1.2 and 1.2.1 are looking good.

Can anyone provide a reproducible case?

**Comment by marco-jantke** [comment] 2017-04-27 15:51
I am currently looking into this issue and can confirm so far that at least the `Connection` header is dropped from traefik. I will test it more the next days and try to find a reproducible case also for other headers like `Content-Type`. Those are working so far for me. The traefik version I am using is the current master, so the issue seems to be still up to date.

I tested this by setting up a nginx serving static files with the following Dokerfile:
```
FROM nginx
COPY static /usr/share/nginx/html
```
I start the docker image with `docker run -p 8081:80 sample-nginx`.

My traefik configuration:
```
➜  518 cat traefik.toml 
# traefik.toml
logLevel = "DEBUG"
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":8080"

[web]
address = ":10000"

[file]

[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Host:localhost"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://localhost:8081"
```

When I do a curl against the nginx docker container directly I get the following:
```
➜  retry curl -v -s http://localhost:8081/profile_facebook.jpg 1> /dev/null
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8081 (#0)
> GET /profile_facebook.jpg HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.11.13
< Date: Thu, 27 Apr 2017 15:48:31 GMT
< Content-Type: image/jpeg
< Content-Length: 281273
< Last-Modified: Wed, 26 Apr 2017 08:23:31 GMT
< Connection: keep-alive
< ETag: "59005903-44ab9"
< Accept-Ranges: bytes
< 
{ [16384 bytes data]
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

When I do this curl against traefik I get the following:
```
➜  retry curl -v -s http://localhost:8080/profile_facebook.jpg 1> /dev/null
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /profile_facebook.jpg HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 281273
< Content-Type: image/jpeg
< Date: Thu, 27 Apr 2017 15:49:01 GMT
< Etag: "59005903-44ab9"
< Last-Modified: Wed, 26 Apr 2017 08:23:31 GMT
< Server: nginx/1.11.13
< 
{ [16163 bytes data]
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

As you can see all the headers are carried over, except the `Connection` header. So I will debug this issue more. It would be quite helpful for me to get sample configurations of your installations, where the `Content-Type` header is lost.

**Comment by marco-jantke** [comment] 2017-04-28 13:59
I researched this issue now quite in-depth and for me it looks correct what traefik does. First of all, I tried to reproduce a loss of any `end-to-end` header like `Content-Type`. I could not reproduce this, even though I tried with https as well as I was activating different middlewares. Of course I am not able to check all different middleware permutations, so in case this issue is still relevant for you, please provide a sample traefik configuration with which we can reproduce it. 

With regards to the connection header, this is something seemingly surprising, but Traefik does actually match the specification. First of all, as a reverse proxy, its important to blindly pass these headers between the client and the backend, as the `Connection` header is a so called hop-to-hop header and should not be passed through. You can find some background information here:

- https://www.mnot.net/blog/2011/07/11/what_proxies_must_do
- https://tools.ietf.org/html/draft-ietf-httpbis-p1-messaging-14#section-7.1.3.1
- https://tools.ietf.org/html/draft-ietf-httpbis-p1-messaging-14#section-9.1

In a short summary, the RFCs state that a reverse proxy MUST NOT pass on hop-to-hop headers to its backends. Whether it responds with them is not specified in the RFC, which brings me to the actual point that the connection header is dropped. I analysed the behaviour in my last post and as you can see in the last line of the curl request `* Connection #0 to host localhost left intact` the connection stays open. This is because `curl` speaks HTTP 1.1 by default and in this version connections are considered to persistent by default! Therefore the goal we wanted to have, a persistent connection, is achieved. Wonderfully when telling curl it should speak HTTP 1.0, traefik responds with an appropriate header. See the following: 

```
➜  retry curl -v -s --http1.0 -H "Connection: keep-alive" http://localhost:8080/profile_facebook.jpg 1> /dev/null 
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /profile_facebook.jpg HTTP/1.0
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: */*
> Connection: keep-alive
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Accept-Ranges: bytes
< Content-Length: 281273
< Content-Type: image/jpeg
< Date: Fri, 28 Apr 2017 13:44:55 GMT
< Etag: "59005903-44ab9"
< Last-Modified: Wed, 26 Apr 2017 08:23:31 GMT
< Server: nginx/1.11.13
< Vary: Accept-Encoding
* HTTP/1.0 connection set to keep alive!
< Connection: keep-alive
< 
{ [16116 bytes data]
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

Said this, I can not see an actual issue here with Traefik. @rbadsi please let me know when you agree with my understanding and whether we can close the issue, except of course someone can provide a reproducible example where end-to-end headers are dropped.

One note I would like to for the maintainers. Together with @timoreimann I figured out that we have a patched fork of the `vulcand/oxy` library and in there we have a fix to remove the hop-to-hop headers that are coming from the response of the backend. This is correct behaviour and should not be lost when updating the library. This is even something we could thing about pushing upstream. WDYT?

**Comment by marco-jantke** [comment] 2017-05-05 11:24
@rbadsi Ping.

**Comment by hcguersoy** [comment] 2018-01-24 11:08
I just wanted to come back to the comment / issue by @yjacobs (https://github.com/containous/traefik/issues/518#issuecomment-285369215): 
we observe the same behavior  that a header (_content-type_) is added to the response.

As @marco-jantke described, _hop-to-hop_ headers can be added, changed etc. 
But this is not the case for _end-to-end_ headers, like _content-type_. 
See https://tools.ietf.org/html/draft-ietf-httpbis-p1-messaging-14#section-7.1.3.2

**Comment by dtomcej** [comment] 2018-05-15 19:19
Since this initial ticket and a bunch of intermediate comments have been filed, we have updated our version of oxy to take into account a bunch of header-based updates.

Due to there being almost 6 major Traefik releases since this ticket was opened, I will close it, and we can reference this ticket if needed.

**Closed by dtomcej** 2018-05-15 19:19 UTC
Labels: kind/bug/possible, priority/P2
