### ISSUE TITLE
Support for blue/green deployment

### ISSUE THREAD

**Issue by bintut** [containous/traefik#1708] opened 2017-06-05 14:36 UTC
Hi all,

I am requesting a feature to support blue/green deployment when using Docker swarm mode as its backend configuration.

The idea is to support a label for source IP address(es), IP address range or subnet (or geolocation perhaps) and forward the users' traffic to a backend server intended for the green deployment. Let's say serviceA is running version 1.0.0 in the blue environment (active) at overlay network A then another serviceA is also running but this time it is on version 1.0.1 in the green environment attached to both overlay networks A and B but for selected users only whose IP addresses matches to the label.

Thank you in advance.

Kind regards,

Marvin

**Comment by ldez** [comment] 2017-06-05 16:26
Seems to be a duplicate of #914

**Comment by timoreimann** [comment] 2017-06-09 22:01
Closing. @bintut, feel free to amend #914 if you think it's missing some of your proposal details.

**Closed by timoreimann** 2017-06-09 22:01 UTC
Labels: area/provider/docker
