### ISSUE TITLE
Support for Unix Sockets as backend URLs

### ISSUE THREAD

**Issue by gabrielgrant** [containous/traefik#1396] opened 2017-04-06 21:54 UTC
Traefik doesn't currently seem to support using unix sockets in the `url` field of a backend server. This would be useful for a project I'm currently working on, or any case of a local server accepting connections over a socket

**Comment by dtomcej** [comment] 2017-04-13 18:06
Unfortunately sockets run at L4, whereas traefik currently only supports L7.

There has been discussion about L4 implementation, but no solid plans.

**Comment by ldez** [comment] 2017-06-13 12:36
This is a duplicate of #10 - Feel free to subscribe there for updates.

**Closed by ldez** 2017-06-13 12:36 UTC
Labels: kind/enhancement, resolution/duplicate

**Comment by gabrielgrant** [comment] 2019-03-01 22:41
I may be misunderstanding, but it's not clear to me that this is really something that requires full L4 support -- in the same way that treafik can send data from a given frontend to a particular backend port, could it not also send that data to a given unix socket as it's backend?
