### ISSUE TITLE
Dashboard behind PathPrefix in 2.0 fails to load static assets

### ISSUE THREAD

**Issue by KiNgMaR** [containous/traefik#5374] opened 2019-09-13 09:19 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

The new dashboard in 2.0 does not seem to handle being put behind a `PathPrefix`. More specifically, the frontend continues to look for assets in `/dashboard` instead of `/traefik/dashboard`. Configuration:

```toml
[http.routers]
    [http.routers.api]
        entryPoints = ["http"]
        rule = "HostRegexp(`systems.{tld:[a-z0-9.-]+}`) && PathPrefix(`/traefik`)"
        service = "api@internal"
        middlewares = ["adminAuth", "traefikAcp", "securityHeaders"]

[http.middlewares]
    [http.middlewares.traefikAcp.stripPrefix]
        prefixes = ["/traefik"]
```

Generated HTML:

```html
<script type="text/javascript" src="/dashboard/js/app.b1a5516b.js"></script>
<script type="text/javascript" src="/dashboard/js/vendor.bf460595.js"></script>
```

### What did you expect to see?

The new dashboard, i.e. assets being loaded from relative paths.

### What did you see instead?

A white page, because assets are loaded with an absolute path.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
{"Version":"2.0.0-rc3","Codename":"montdor"}
```

**Comment by kzay** [comment] 2019-09-16 18:56
Confirmed. I have the same problem.

`
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-admin
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/traefik-ui`)
      kind: Rule
      priority: 0
      services:
        - name: traefik-admin
          port: 8080
      middlewares:
        - name: traefik-admin-stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-admin-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /traefik-ui
`

**Comment by trajano** [comment] 2019-09-20 12:49
https://github.com/containous/traefik/blob/56e0580aa5ef5fc40a1969ec78014fef693c8a09/webui/quasar.conf.js#L140 may need to add a `publicPath: ''`

**Comment by aacebedo** [comment] 2019-09-27 09:54
I am seeing this issue too. Correct me if I am wrong but I do not see anything about it the 2.0.1 version .

**Comment by er1z** [comment] 2019-10-03 22:44
Any news on issue?

**Comment by dduportal** [comment] 2019-10-04 09:52
Hello dear users, as a reminder, this issue has been labelled to materialize the current status. FYI The explanation for the label can be found on the Traefik documentation: https://docs.traefik.io/v2.0/contributing/maintainers/#labels. 

The current labelling means that this issue is currently being worked on and **should** be on the next release unless something more deep happen (bug confirmed + priorit P1). There is someone assigned on it, which confirm this status. 

We understand this issue might bit you on your different setup, and this is why has been priorized as P1. But now you have to wait and see: the issue will be updated when something will be done :) 

Thanks a lot for your understanding!

**Comment by zopar** [comment] 2019-10-09 15:51
I confirm the problem on 2.0.1, is it possible to fix it for the 2.0.2?
It is funny that traefik that is intended to help on this type of configuration is the first that not works :)

**Comment by Ben-Atherton** [comment] 2019-10-23 11:27
As this hasn't been fixed in 2.0.2 would it be possible to fix this in 2.0.3?

**Comment by er1z** [comment] 2019-10-29 18:39
@Ben-Atherton — I've checked the latest changelog and no mention there. :(

**Comment by alexvaut** [comment] 2019-11-09 16:40
+1 Same on 2.0.4

**Comment by ldez** [comment] 2019-11-09 16:51
As long as the issue is not closed it is that the problem still exists.

The problem will be fixed soon, thank you to wait a little.

**Comment by alexvaut** [comment] 2019-11-09 17:00
Thanks Idez for the update ! By the way, very good job on traefik, it's a great piece of work !

**Closed** 2019-11-14 15:40 UTC
Labels: area/api, area/webui, kind/bug/confirmed, priority/P1

**Comment by trajano** [comment] 2019-11-18 18:00
This issue is closed, can someone add a link to the documentation on how to configure this?  I can't find it.

**Comment by AndrewSav** [comment] 2019-11-18 18:55
@trajano I could be wrong but I think this is slated for 2.1 and is not yet in for 2.0.5

**Comment by andrewsav-datacom** [comment] 2019-11-19 00:43
Volume 2: https://github.com/containous/traefik/issues/5853
