### ISSUE TITLE
Traefik middleware transform headers

### ISSUE THREAD

**Issue by llacroix** [containous/traefik#5997] opened 2019-12-10 23:04 UTC
**Feature**

Add a middleware that can be used to alter/transform headers. 

Use case:

When using something like forwardAuth, it seems that traefik allows the forwardAuth to trustForwarded headers. I couldn't test the way I understand is that if HTTP_X_FORWARDED_HOST is defined, then it will pass it to the authentication server. As long as the authentication server is available without passing through a proxy server this will possibly work. But if you want to access an authentication server through a load balancer like traefik. The headers will be overriden and inside your Authentication server you'll see only the HTTP_X_FORWARDED_HOST which is the actual domain of the auth server. The information about the origin of the forwarded authentication seems to be gone from there. 

Renaming headers would allow to rename the header to something like HTTP_REFERER which would point to the server that originated the forward auth request, Header for paths could be renamed too so we know where to make the redirect to. Modifications could be done in batch to rename all the defined X-Forwarded-.* to X-Auth-Forwarded-.*

`traefik.http.middlewares.<middleware>.headers.transform = op1, op2, op3`

1. Transforming operations:

- Rename: Rename(header, new_header) 
- HeaderRewriteRule(regex, replace): Rewrite header name using a regex with a match/capture
- ValueRewriteRule(header, regex, replace): Same as HeaderRewriteRule but for values
- Join(header, sep, value/header) : Possibility to join multiple headers inside one. This can be useful when you're hoping through multiple proxy servers. For example HTTP_X_FORWARDED_FOR can be use to track a list of all the proxies 

Here https://en.wikipedia.org/wiki/X-Forwarded-For

From my experience, it doesn't seem like Traefik comply with this. But with a way to transform an header. When I look at the result of whoami.example.com, I can see that traefik doesn't append the ip of each proxy being passed. With a middleware like that it could be as simple as

```
Join(X-Forwarded-For, ',' REMOTE_ADDR)
X-Forwarded-For: 127.0.0.1
REMOTE_ADDR: 192.168.1.1
=
X-Forwarded-For: 127.0.0.1,192.168.1.1
```

At the same time, this would solve this issue #3919

Those are suggestion to come up with a solution for forwardAuth and if done correctly, it could be used internally to define generic rules like the X-Forwarded-For that could be implemented directly with such rule by default.

**Comment by llacroix** [comment] 2019-12-10 23:11
As for X-Forwarded-For, it would allow things like tracing path of request in a multi proxy setup. Right now, it doesn't seem like the endpoint has any knowledge of the complete path it takes. Having something in the line of what I'm proposing would enable couple of useful usecases and not just fixing forwardAuth implementations.

That said, if someone comes with better syntax for transformation considering that we may want to create multiple rules but having to create 1 middleware for each rule may seem a bit overkill. Being able to set something like that using labels could be done by adding multiple rules sequentially while being part of the headers middleware.

Something in the line of 

`traefik.http.middlewares.<middleware>.headers.transform = op1, op2, op3`

Where modifications made by op1 impact on op2 and op3.

**Comment by ldez** [comment] 2019-12-11 09:00
> From my experience, it doesn't seem like Traefik comply with this. But with a way to transform an header. When I look at the result of whoami.example.com, I can see that traefik doesn't append the ip of each proxy being passed.

By default, Traefik v2 don't trust external X-Forwarded-* headers, but you trust them: 
https://docs.traefik.io/v2.1/routing/entrypoints/#forwarded-header

**Comment by llacroix** [comment] 2019-12-11 11:11
@ldez Thank you, with that setting I can finally get my headers down to the auth server. That's one problem solved and I guess it would be a good enough solution for many people. But... I see a few issues.
1. This is a list of static IPs, what are my guarantee that my ips won't change on my services and I'll be trusting IPs that shouldn't be trusted and IPs that should be trusted won't be trusted anymore.
2. While having the forwarded headers down to the auth server is definitely some progress, my application server requires the forwarded-host to correctly find which db is associated to the request. It's a design that allow one server to serve multiple domains. So you can share the same code with different database selected by a rule computed from forwarded headers. In this case, the auth server would require both headers from the client to the auth server but I only receive 1 or the other set.

In the meantime, I can fix the database name but being able to get both sets would be a better solution. Considering that it would always work regardless of the trustedIPs list.

Thanks again, I'll be able to finish this.

**Comment by ldez** [comment] 2019-12-11 16:34
We will close this issue, because the main topic of the issue is a question around ` X-Forwarded-*` headers.

But the part of this issue about a middleware to interact with header, is a good subject for a proposal.

So we propose to open another issue to keep the issue clean.

Thank you.

**Closed by ldez** 2019-12-11 16:34 UTC
Labels: kind/question

**Comment by llacroix** [comment] 2019-12-11 21:23
@ldez ok I'll create a new issue for the proposal alone
