### ISSUE TITLE
Incorrect backend in marathon provider

### ISSUE THREAD

**Issue by tcolgate** [containous/traefik#1362] opened 2017-03-29 13:31 UTC
### What version of Traefik are you using (`traefik version`)?
git hash 240b2be1a85eeb39623cef04b70ce9445947a09b

### What is your environment & configuration (arguments, toml...)?
marathon

### What did you do?

run the marathon back end with the default template.

### What did you expect to see?

Traefik should use the backend server names/ips for each configured backend.

### What did you see instead?

Traefik creates backend using the internal container IP
Replacing the default backed url template with
```    url = "{{getProtocol . $apps}}://{{.Host}}:{{getPort . $apps}}"``
fixes this.

It's not immediately obvious to me as to how the existing template can work, unless marathon is running inside a docker-compose with the hosted applications. It cannot work if (as is normal), marathon is running outside of the same container network as the running tasks.

**Comment by timoreimann** [comment] 2017-03-29 16:47
Thanks for your report.

I believe this is a duplicate of #1243.

A fix to automatically detect if host or task IP addresses should be used is already in review: #1345. Feel free to subscribe to the PR if you'd like to be informed about it being merged.

I'm going to close the issue. Let me know if you think the problem you were raising is different and that we should reopen.

**Closed by timoreimann** 2017-03-29 16:47 UTC
