### ISSUE TITLE
Dedicated EntryPoint for Ping does not work with Traefik 2 using CLI conf

### ISSUE THREAD

**Issue by tlvenn** [containous/traefik#5797] opened 2019-11-08 07:11 UTC
Using Traefik 2.0.4 with cli config:

```
--log.level=info
--entrypoints.web.address=:80
--entrypoints.websecure.address=:443
--entryPoints.traefik.address=:8080
--api.dashboard=true
--api.insecure=true
--ping=true
--ping.entryPoint="web"
--metrics=true
--metrics.prometheus=true
--metrics.prometheus.entryPoint="traefik"
--providers.kubernetesingress
--providers.kubernetescrd
```

http://server_ip:80/ping returns a 404
if i remove the `--ping.entryPoint="web"`, then http://server_ip:8080/ping works as expected

**Comment by tlvenn** [comment] 2019-11-08 07:12
I just noticed #5326 which might explain what is going on but then the documentation need to be updated.

**Comment by ldez** [comment] 2019-11-08 08:40
Hello,

I don't reproduce.
 
```yml
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0.4
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--ping=true"
      - "--ping.entryPoint=web"
```

```console
$ curl localhost/ping
OK
```

The behavior in #5326 has been fixed in v2.0.0

**Closed by ldez** 2019-11-08 08:40 UTC
Labels: status/0-needs-triage

**Comment by tlvenn** [comment] 2019-11-08 15:44
Bonjour @ldez ,

There is one key difference with your config, you did not use quotes around the entryPoint name which indeed works (Tested on my side with k8s).

The issue is in the documentation:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/3340262/68489253-7a62d680-0292-11ea-90f8-70fd7691f889.png">

**Comment by tlvenn** [comment] 2019-11-08 15:47
Maybe there is no issue with the doc itself and it all depends on how those arguments are being fed to traefik at runtime.

**Comment by dduportal** [comment] 2019-11-08 15:57
Hi @tlvenn , there are reasons why we ask for an issue template, you're right in one of the reasons: you provided partial informations (we did not know that you were using Kubernetes for example so we assume you're using Docker for instance).

Providing the right debug information can help you as we can analyze faster and in a more efficient way.

Please, don't hesitate to use the community forum for such subject next time, and switch to an issue if it happens other users can also reproduce the problem, meaning this is a bug, and not a configuration problem, as we want to focus the github issue tracker to feature request and bugs.  

Thanks a lot for your understanding!

**Comment by tlvenn** [comment] 2019-11-08 18:42
Hi @dduportal , I did provide my entire CLI config which includes both k8s providers... ;)

Going back to the doc, does it make sense that the CLI flavor use double quotes ? Is there a context where they are actually needed and expected by traefik ?

It seems to me that only the file versions (Toml / Yaml) need double quotes for string arguments.

**Comment by ldez** [comment] 2019-11-08 19:02
If you are using the binary (not the Docker image) you can use the double quotes.

But yes the double quotes are optional.

**Comment by dduportal** [comment] 2019-11-12 08:54
> Hi @dduportal , I did provide my entire CLI config which includes both k8s providers... ;)

Hi @tlvenn , please follow the issue template next time. If every issuers write on their "own style", we, maintainers, will never be able to follow up and analyse correctly. Really, we do this for easing our life when it come to help user, trust us, we do not do this for the pleasure of annoying people :)

By the way, a software run on a given context. Providing partial information (e.g. "only the CLI flags") is not enough: the template compels you to provide DEBUG logs, which could have helped on this topic earlier for instance.
The "double quote" behavior is a also a common challenge when dealing with YAML or Helm in Kubernetes environments: it might helps when it comes to such elements.
This is why we ask you to provide more informations next time please.
