### ISSUE TITLE
[question] Can I change error codes pages?

### ISSUE THREAD

**Issue by wido-gg** [containous/traefik#800] opened 2016-11-03 20:16 UTC
The title pretty much sums: can I change error codes pages?

When I go to a host that doesn't exists, I get a "404 page not found" text. I would like to assign a custom 404 page. Is that possible? I'm guessing that should be copied in a new traefik image, or in the web src angular code, somewhere

Cheers

PS: sorry, I don't know how to add labels to the issues

**Comment by Starefossen** [comment] 2016-11-10 11:35
This is currently not possible. Possible duplicate of #652.

**Comment by errm** [comment] 2016-11-12 04:45
yes this is a dupe of #652

**Closed by errm** 2016-11-12 04:45 UTC
Labels: question

**Comment by gcmalloc** [comment] 2017-05-31 19:06
I felt on this feature request, this is now implemented in traefik with https://github.com/containous/traefik/pull/1576.

**Comment by timoreimann** [comment] 2017-05-31 19:42
@gcmalloc it is *not* implemented: #1576 got declined in favor of #1634.
