### ISSUE TITLE
Traefik not generating TLS certificate (Error 401)

### ISSUE THREAD

**Issue by Shlokp** [containous/traefik#6782] opened 2020-05-09 16:55 UTC
Bug

### What did you do?
After having to reset traefik, it can no longer generate certificates

### What did you expect to see?
Certificate for my domain on cloudflare to be issued

### What did you see instead?
Log
`level=error msg="Unable to obtain ACME certificate for domains \"*.redacted\" : unable to generate a certificate for the domains [*.redacted]: acme: Error -> One or more domains had a problem:\n[*.redacted] [*.redacted] acme: error presenting token: cloudflare: failed to create TXT record: error from makeRequest: HTTP status 401: invalid credentials\n"`

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.7.2 in docker on arm32 raspberry pi 4 4gb

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
docker-compose
```
version: "3.6"
services:

  traefik:
    hostname: traefik
    image: traefik:v1.7.2
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"  
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/pi/docker/traefik:/etc/traefik
      - /home/pi/docker/shared:/shared
```

toml

```
#debug = true

logLevel = "ERROR" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
InsecureSkipVerify = true 
defaultEntryPoints = ["https", "http"]

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations 
[api]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[file]
  watch = true
  filename = "/etc/traefik/rules.toml"

# Let's encrypt configuration
[acme]
email = "redacted" #any email id will work
storage="/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging=true 
onDemand = false #create certificate when container is created
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 5
[[acme.domains]]
   main = "redacted"
[[acme.domains]]
   main = "*.redacted"
   
# Connection to docker host system (docker.sock)
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "redacted"
watch = true
# This will hide all docker containers that don't have explicitly  
# set label to "enable"
exposedbydefault = false
```

I have checked the cloudflare credentails multiple times, reset the cloudflare global api and retried, used a different cloudflare accout, changed domain and tried on a different raspberry pi.

**Comment by cantelope** [comment] 2020-05-11 15:09
Are you using a FreeNOM domain -- .cf, .ga, .gq, .ml, or .tk TLD (top-level domain)?

**Comment by mmatur** [comment] 2020-05-11 15:10
Hi @Shlokp,

Following the [documentation](https://docs.traefik.io/v1.7/configuration/acme/#provider) it seems that your are not using the correct environment variables.

![image](https://user-images.githubusercontent.com/1776972/81577822-433cc180-93aa-11ea-8dfb-def9faba3681.png)

I will close this issue.

**Closed by mmatur** 2020-05-11 15:10 UTC
Labels: status/0-needs-triage

**Comment by Shlokp** [comment] 2020-05-11 15:11
> Are you using a FreeNOM domain -- .cf, .ga, .gq, .ml, or .tk TLD (top-level domain)?

Yes I am.

> Hi @Shlokp,
> 
> Following the [documentation](https://docs.traefik.io/v1.7/configuration/acme/#provider) it seems that your are not using the correct environment variables.
> 
> ![image](https://user-images.githubusercontent.com/1776972/81577822-433cc180-93aa-11ea-8dfb-def9faba3681.png)
> 
> I will close this issue.

Hi, I have tried using those environment variables too. Both the ones ive written and the ones you mentioned give the error

**Comment by cantelope** [comment] 2020-05-11 15:13
> > Are you using a FreeNOM domain -- .cf, .ga, .gq, .ml, or .tk TLD (top-level domain)?
> 
> Yes I am.

JSON response from Cloudflare:
{
  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
}

**Comment by Shlokp** [comment] 2020-05-11 15:14
> > > Are you using a FreeNOM domain -- .cf, .ga, .gq, .ml, or .tk TLD (top-level domain)?
> > 
> > 
> > Yes I am.
> 
> JSON response from Cloudflare:
> {
> "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
> }

Is this is recent change? It used to work fine when I set it up. Regardless, thank you for clearing that up. Been scratching my head on this one for a long long time.

**Comment by cantelope** [comment] 2020-05-11 15:16
Yes, apparently so.  I hit this problem yesterday too, and just managed to figure out the cause.

**Comment by Shlokp** [comment] 2020-05-11 15:19
How would you go about using traefik with these domains?

**Comment by cantelope** [comment] 2020-05-11 15:27
I have not figured that out yet.

**Comment by MohammedX** [comment] 2020-05-12 03:03
try generating Edge Certificates from Cloudflare and instill them in Traefik
for more [https://docs.traefik.io/https/tls/](url)

**Comment by Shlokp** [comment] 2020-05-12 12:45
Thanks for that. I have got it working by having edge certificates on in cloudflare, generating a origin certificate and then adding that to the traefik.toml file. Security wise, is it the same having an origin certificate + edge certficate compared to the acme genereted certificate being presented directly to the browser
