### ISSUE TITLE
Use weighted service with 0 weight as fallback

### ISSUE THREAD

**Issue by sylr** [containous/traefik#6127] opened 2020-01-03 13:12 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Could the `0` weight be used for fallback and fallback only, i.e., be used if and only if backends with higher weights are not available.

e.g.:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: go-lev-tls
  namespace: default
spec:
  entryPoints:
  - https
  routes:
  - kind: Rule
    match: Host(`go-lev.company.com`)
    services:
    - name: go-lev
      passHostHeader: true
      port: 80
      weight: 10
    // fallback to maintenance service if go-lev service has no endpoints
    - name: maintenance
      namespace: maintenance
      passHostHeader: true
      port: 80
      weight: 0
  tls:
    secretName: company-com-tls
```

Regards.

**Comment by SantoDE** [comment] 2020-01-03 15:29
Hello @sylr,

thanks for your interest. 

What you're asking for, could be seen as a "workaround". A very long time ago, something like that has already been asked and we labeled it as an enhancement. Therefore, I'm closing that issue.

Duplicate of #1007

**Closed** 2020-01-03 15:36 UTC
Labels: resolution/duplicate
