### ISSUE TITLE
Simplify creation of HTTP+HTTPS router

### ISSUE THREAD

**Issue by Yajo** [containous/traefik#7235] opened 2020-09-02 11:30 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Almost all my deployed services listen on both HTTP and HTTPS. Most routes just use the HTTP version to apply a 301 redirection to the HTTPS version.

[The docs](https://docs.traefik.io/routing/routers/#general) clearly say:

![imagen](https://user-images.githubusercontent.com/973709/91975362-348e6780-ed17-11ea-8110-85ae6cf50502.png)

This is very disappointing, because a router might have a bunch of middlewares and other configurations, and having to repeat every single thing just because I want the 301 redirection is tedious.

I think it would be best to be able to configure a router like this:

```yaml
## Dynamic configuration
http:
  middlewares:
    forceSecure:
      forceSTSHeader: true
      sslRedirect: true

  routers:
    my-http-and-https-router:
      rule: "Host(`foo-domain`) && Path(`/foo-path/`)"
      service: service-id
      middlewares: [forceSecure]
      tls:
        # Listen on both TLS and non-TLS modes. The forceSecure middleware will upgrade all non-TLS requests anyway.
        required: false
```

This way:

1. If you want an HTTP-only router, you don't define a `tls` section.
1. If you want an HTTPS-only router, you define the `tls` section (`true` would be the default value for `tls.required`).
1. If you want an HTTP+S router, you define `tls.required=false` and, optionally, leverage a middleware to force it.

**Comment by rtribotte** [comment] 2020-09-02 12:18
Hello @Yajo,

Thanks for your interest in Traefik !

Since v2.2 you can attach the TLS configuration to your entrypoints (see the [documentation](https://docs.traefik.io/v2.2/routing/entrypoints/#tls), i think what you want to achieve is already doable.
As stated in the documentation the entrypoint TLS configuration will apply to all routers attached to it, unless a more specific one is defined on the router.

Accordingly, i will close this issue as a duplicate.

Duplicate of #4863

**Closed by rtribotte** 2020-09-02 12:18 UTC
Labels: status/0-needs-triage

**Comment by Yajo** [comment] 2020-09-09 11:07
Well, not exactly.

What I want is the ability to serve one site on both HTTP and HTTPS, not to establish a redirection from the HTTP site to its HTTPS version.

**Comment by rtribotte** [comment] 2020-09-10 07:52
Hello @Yajo,

I think you can achieve this with the configuration on entry points.
If no entry point is specified on it, an HTTP router will accept requests from all defined entry points.
So if you define two entry points, one with TLS and one without, you will be able to serve one site on both HTTP and HTTPS.

Please feel free to open a thread on [the community forum](https://community.containo.us/c/traefik/traefik-v2/) if you need more inputs or to discuss about your configuration.

Thanks again for your interest in Traefik !
