### ISSUE TITLE
Traefik does not start when acme-v01.api.letsencrypt.org is not reachable

### ISSUE THREAD

**Issue by MaZderMind** [containous/traefik#1637] opened 2017-05-19 20:23 UTC
Traefik-Version v1.1.2

In our Test-Installation we see, with the current Breakdown of LetsEncrypt ([[1]](https://letsencrypt.status.io/pages/incident/55957a99e800baa4470002da/591e962c4f9ef22239001819), [[2]](https://news.ycombinator.com/item?id=14374933)), our Traefik-Instance to fail staring up with the following Log-Output, followed by a restart triggered by the surrounding Kubernetes-Cluster.

```

2017-05-19T20:00:39.656228017Z time="2017-05-19T20:00:39Z" level=info msg="Traefik version v1.1.2 built on 2016-12-15_10:21:15AM" 
2017-05-19T20:00:39.656900655Z time="2017-05-19T20:00:39Z" level=info msg="Using TOML configuration file /config/traefik.toml" 
2017-05-19T20:00:39.746869323Z time="2017-05-19T20:00:39Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc420395170 Auth:<nil> Compress:false}" 
2017-05-19T20:00:39.746943871Z time="2017-05-19T20:00:39Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc4202e2de0 Redirect:<nil> Auth:<nil> Compress:false}" 
2017-05-19T20:00:39.746953159Z time="2017-05-19T20:00:39Z" level=info msg="Starting server on :80" 
2017-05-19T20:00:42.547673057Z time="2017-05-19T20:00:42Z" level=info msg="Loading ACME Account..." 
2017-05-19T20:00:42.948217997Z time="2017-05-19T20:00:42Z" level=info msg="Loaded ACME config from store /acme/acme.json" 
2017-05-19T20:00:43.748647058Z time="2017-05-19T20:00:43Z" level=warning msg="A new release has been found: 1.2.3. Please consider updating." 
2017-05-19T20:00:53.0455302Z time="2017-05-19T20:00:53Z" level=error msg="Error creating TLS config get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get \"https://acme-v01.api.letsencrypt.org/directory\": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
2017-05-19T20:00:53.045763747Z time="2017-05-19T20:00:53Z" level=fatal msg="Error preparing server: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get \"https://acme-v01.api.letsencrypt.org/directory\": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
```

I think this might be a bug, because even with unreachable LE Servers Traefik should start up and serve domains based on the stored certificates or even using old certs, if a renewal is not possible.

I currently have no access to the Config but I will add it as soon as I can access it.

**Comment by ldez** [comment] 2017-05-19 20:25
Duplicate of #791 (and #1631 and #1632 and #1636)

**Closed by ldez** 2017-05-19 20:25 UTC
Labels: area/acme, resolution/duplicate

**Comment by MaZderMind** [comment] 2017-05-19 20:28
@ldez Sorry for not searching better. Thank you for pointing this out.
