### ISSUE TITLE
Panic error on bare metal Kubernetes (installed with Kubeadm)

### ISSUE THREAD

**Issue by thaume** [containous/traefik#897] opened 2016-11-24 12:00 UTC
Hello there,

I installed Kubernetes on a bare metal Ubuntu 16.04LTS server with the Kubeadm package.

I then installed Traefik with Let's Encrypt SSL certificates (which work really, really well thanks) and I opened a couple of Ingress controllers mapped to Traefik (a frontend and the Traefik dashboard).

The traffic is well handled by Traefik but right now I have the following error on the traefik-controller pod :

```
2016-11-24T11:53:55.697013716Z time="2016-11-24T11:53:55Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://10.96.0.1:443/apis/extensions/v1beta1/ingresses\" : unexpected EOF, retrying in 320.440991ms" 
2016-11-24T11:53:55.700128854Z panic: send on closed channel
2016-11-24T11:53:55.700152563Z 
2016-11-24T11:53:55.700168323Z goroutine 159 [running]:
2016-11-24T11:53:55.700205637Z panic(0xd292c0, 0xc42014ed40)
2016-11-24T11:53:55.700224184Z  /usr/local/go/src/runtime/panic.go:500 +0x1a1
2016-11-24T11:53:55.700240615Z github.com/containous/traefik/provider/k8s.(*clientImpl).watch.func1.1(0xc4205586c0, 0xc4204783c0, 0xc420215b30, 0x26, 0xc420478300)
2016-11-24T11:53:55.700256034Z  /go/src/github.com/containous/traefik/provider/k8s/client.go:280 +0x33f
2016-11-24T11:53:55.700271313Z created by github.com/containous/traefik/provider/k8s.(*clientImpl).watch.func1
2016-11-24T11:53:55.700286371Z  /go/src/github.com/containous/traefik/provider/k8s/client.go:286 +0xbf
```

The traefik-controller seems to restart all the time (172 restarts in 23 hours). Do you have any idea where that could be coming from ?

I can provide more information upon request :)

Thanks !

**Comment by emilevauge** [comment] 2016-11-24 12:39
Duplicate of https://github.com/containous/traefik/issues/877

**Closed by emilevauge** 2016-11-24 12:39 UTC
