### ISSUE TITLE
Traefik not working with more than 3 ports exposed 

### ISSUE THREAD

**Issue by khanhvnkaopiz** [containous/traefik#2336] opened 2017-10-27 08:47 UTC
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

I'm trying to get email service working with traefik. 
I need to expose 25, 100, 143.. etc.
But traefik only works with <= 3 ports. If I add more than 3, it it stopped working.
 This is my sample config:

```networks:
      - traefik-net
    environment:
      - HTTPS=OFF
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      replicas: 1
      labels:
        - "traefik.backend=mail"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:mail.mydomain.com"
        - "traefik.docker.network=traefik-net"
        - "traefik.mail.port=80"
        - "traefik.mail25.port=25"
        - "traefik.mail110.port=110"
        - "traefik.mail143.port=143"
        - "traefik.mail465.port=465"
        - "traefik.mail587.port=587"
        - "traefik.mail993.port=993"
        - "traefik.mail995.port=995"
```

### What did you expect to see?

Email service works and the whole ports exposed

### What did you see instead?

Traefik dashboard shows all the exposed ports, but my service get "Internal server error"

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.4.1

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```logLevel = "INFO"
defaultEntryPoints = ["http", "https"]
[web]
address = ":8080"
[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
compress = true
[entryPoints.https.tls]
[docker]
watch = true
swarmmode = true
[acme]
email = "myemail"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging = true
onDemand = false
OnHostRule = true
[[acme.domains]]
  main = "mydomain"
```

Everything works fine 'till I added more than 3 ports.

I've tried with other services always get the same results.
Thank in advance and sorry for my bad English.

**Comment by mmatur** [comment] 2017-10-27 09:09
Every time someone does not respect the issue's template, a little bunny dies.

<details>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>
<br>

Please edit your issue description to respect the [issue template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md) as much as possible.

**Comment by nmengin** [comment] 2017-10-30 14:32
Duplicate of SO (https://stackoverflow.com/questions/46969350/traefik-not-working-with-more-than-3-ports-exposed).
The answer is on SO.

**Closed by nmengin** 2017-10-30 14:32 UTC
Labels: status/0-needs-triage

**Comment by khanhvnkaopiz** [comment] 2017-10-31 02:51
Thanks for your time.
