### ISSUE TITLE
Please add the support for running GO code on incoming requests 

### ISSUE THREAD

**Issue by alexbpx** [containous/traefik#4510] opened 2019-02-21 09:33 UTC
Hi,

HAProxy has the possibility to run lua code in order to process incoming requests ( filtering, manipulation, etc). Apache has the ability to run third party libraries. 
It would be great to use your product with the support for third party libraries that can manipulate and process incoming http requests.

Is this something in your roadmap?
If not, it would be a great addition.

Thanks,
Alex

**Comment by ldez** [comment] 2019-02-21 09:40
Duplicate of #1336

**Closed** 2019-02-22 15:14 UTC
Labels: resolution/duplicate
