### ISSUE TITLE
[2.0] anoymous usage option broken?

### ISSUE THREAD

**Issue by andig** [containous/traefik#4786] opened 2019-04-17 06:40 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Run current docker image and disable anoymous usage:

    ❯ docker pull traefik:v2.0
    v2.0: Pulling from library/traefik
    Digest: sha256:a8ced49825b3eb4ffee7d7c2a534a80d3d663acf6e5d5be647ec98f90e941f09
    Status: Image is up to date for traefik:v2.0

    ❯ docker run traefik:v2.0 --help | grep -i global.send
        --global.sendanonymoususage                                 send periodically anonymous usage statistics                                    (default "false")

    ❯ docker run traefik:v2.0 --global.sendanonymoususage=false

### What did you expect to see?

Usage disabled. 

### What did you see instead?

    time="2019-04-17T06:37:54Z" level=error msg="\nYou haven't specify the sendAnonymousUsage option, it will be enable by default.\n"

Apart from the switch not being applied (either lower or camel case), the message should read "**dis**abled" as this is the default for this flag.

This is possible:

    ❯ docker run traefik:v2.0 --global.sendanonymoususage false
    ^C 

This is not:

    ❯ docker run traefik:v2.0 --global.sendanonymoususage=false
    time="2019-04-17T06:49:36Z" level=error msg="\nYou haven't specify the sendAnonymousUsage option, it will be enable by default.\n"

### Output of `traefik version`: (_What version of Traefik are you using?_)

    ❯ docker run traefik:v2.0 version
    Version:      2.0.0-alpha3
    Codename:     faisselle
    Go version:   go1.12.1
    Built:        2019-03-29T17:53:25Z
    OS/Arch:      linux/amd64

**Comment by ldez** [comment] 2019-04-17 07:12
Duplicate of #4740

**Closed** 2019-04-17 07:26 UTC
Labels: status/0-needs-triage
