### ISSUE TITLE
Traefik doesn’t configure backend settings

### ISSUE THREAD

**Issue by traffsh0w** [containous/traefik#2539] opened 2017-12-07 13:49 UTC
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Checking new traefik version: 1.4.5

### What did you expect to see?

Backends configured for appropriate frontends

### What did you see instead?

I see backends without any settings.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.5
Codename:     roquefort
Go version:   go1.9.2
Built:        2017-12-06_10:16:48AM
OS/Arch:      linux/amd64
```

### Operating system

```
CentOS Linux release 7.4.1708 (Core)
```

### Kernel and kernel package version

```
4.13.10-1.el7.elrepo.x86_64

kernel-ml-4.13.10-1.el7.elrepo.x86_64
```

### Docker version and docker info

```
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:05 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:05:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Containers: 20
 Running: 18
 Paused: 0
 Stopped: 2
Images: 12
Server Version: 17.10.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.13.10-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.794GiB
Name: ent101.ent1.tonicfordev.com
ID: XLQG:R3FF:34GN:H4BE:FZ2G:OEEM:QO6C:VCEJ:Y7RJ:YGXB:KORN:FRHU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
graceTimeOut = "10s"
checkNewVersion = false
logLevel = "DEBUG"
ProvidersThrottleDuration = "2s"
IdleTimeout = "180s"
MaxIdleConnsPerHost = 200
InsecureSkipVerify = true
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/ssl/certs/tonicfordev.com.crt"
      KeyFile = "/etc/ssl/certs/tonicfordev.com.key"
[web]
  address = ":8080"
[docker]
  domain = "docker.local"
  watch = true
  exposedbydefault = false
  endpoint = "unix:///var/run/docker.sock"
```

Traefik creates backend but doesn’t configure any backend settings for appropriate frontends.
In version 1.4.2 everything is fine.

<img width="1011" alt="1_4_2" src="https://user-images.githubusercontent.com/20369697/33718445-127a8630-db66-11e7-9fc0-901b1996788e.png">
<img width="994" alt="1_4_5" src="https://user-images.githubusercontent.com/20369697/33718446-12933d1a-db66-11e7-9f39-d24e8a273a25.png">

**Comment by ldez** [comment] 2017-12-07 14:21
@traffsh0w could you provide any logs ?

And could try with 1.5.0-rc2 ?

**Comment by traffsh0w** [comment] 2017-12-07 14:54
Versions 1.4.4 and 1.5.0-rc2 are also affected.

traefik logs

`time="2017-12-07T14:50:37Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml"
time="2017-12-07T14:50:37Z" level=info msg="Traefik version v1.4.5 built on 2017-12-06_10:16:48AM"
time="2017-12-07T14:50:37Z" level=debug msg="Global configuration loaded {"GraceTimeOut":10000000000,"Debug":false,"CheckNewVersion":false,"AccessLogsFile":"","AccessLog":null,"TraefikLogsFile":"","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":false,"ProxyProtocol":null,"ForwardedHeaders":{"Insecure":true,"TrustedIPs":null}},"https":{"Network":"","Address":":443","TLS":{"MinVersion":"","CipherSuites":null,"Certificates":[{"CertFile":"/etc/ssl/certs/tonicfordev.com.crt","KeyFile":"/etc/ssl/certs/tonicfordev.com.key"}],"ClientCAFiles":null},"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":false,"ProxyProtocol":null,"ForwardedHeaders":{"Insecure":true,"TrustedIPs":null}}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":[],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":180000000000,"InsecureSkipVerify":true,"RootCAs":null,"Retry":null,"HealthCheck":{"Interval":30000000000},"RespondingTimeouts":null,"ForwardingTimeouts":null,"Docker":{"Watch":true,"Filename":"","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"unix:///var/run/docker.sock","Domain":"docker.local","TLS":null,"ExposedByDefault":false,"UseBindPortIP":false,"SwarmMode":false},"File":null,"Web":{"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"/","Auth":null,"Debug":false,"CurrentConfigurations":null,"Stats":null,"StatsRecorder":null},"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null}"
time="2017-12-07T14:50:37Z" level=warning msg="top-level idle timeout configuration has been deprecated -- please use responding timeouts"
time="2017-12-07T14:50:37Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4202af620} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2017-12-07T14:50:37Z" level=warning msg="top-level idle timeout configuration has been deprecated -- please use responding timeouts"
time="2017-12-07T14:50:37Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc420539d40 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4202af660} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2017-12-07T14:50:37Z" level=info msg="Starting provider *docker.Provider {"Watch":true,"Filename":"","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"unix:///var/run/docker.sock","Domain":"docker.local","TLS":null,"ExposedByDefault":false,"UseBindPortIP":false,"SwarmMode":false}"
time="2017-12-07T14:50:37Z" level=info msg="Starting provider *web.Provider {"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"/","Auth":null,"Debug":false,"CurrentConfigurations":{},"Stats":{"Uptime":"2017-12-07T14:50:37.049512141Z","Pid":1,"ResponseCounts":{},"TotalResponseCounts":{},"TotalResponseTime":"0001-01-01T00:00:00Z"},"StatsRecorder":null}"
time="2017-12-07T14:50:37Z" level=info msg="Starting server on :80"
time="2017-12-07T14:50:37Z" level=info msg="Starting server on :443"
time="2017-12-07T14:50:37Z" level=debug msg="Provider connection established with docker 17.10.0-ce (API 1.33)"
time="2017-12-07T14:50:37Z" level=debug msg="Filtering disabled container /traefik"
time="2017-12-07T14:50:37Z" level=debug msg="Filtering disabled container /redis"
time="2017-12-07T14:50:37Z" level=debug msg="Filtering disabled container /elasticsearch"
time="2017-12-07T14:50:37Z" level=debug msg="Filtering disabled container /mailcatcher"
time="2017-12-07T14:50:37Z" level=debug msg="Filtering disabled container /activemq"
time="2017-12-07T14:50:37Z" level=debug msg="Filtering disabled container /rabbitmq"
time="2017-12-07T14:50:37Z" level=debug msg="Filtering container without port and no traefik.port label /consul : strconv.Atoi: parsing "": invalid syntax"
time="2017-12-07T14:50:37Z" level=debug msg="Validation of load balancer method for backend backend-ent1 failed: invalid load-balancing method ''. Using default method wrr."
time="2017-12-07T14:50:37Z" level=debug msg="Configuration received from provider docker: {"backends":{"backend-ent1":{"loadBalancer":{"method":"wrr"}},"backend-ent1-ent1-nginx":{"loadBalancer":{"method":"wrr"}}},"frontends":{"frontend-ent1.ent1_nginx-ent1-ent1-nginx-http":{"entryPoints":["http"],"backend":"backend-ent1.ent1_nginx-ent1-ent1-nginx-http","routes":{"service-http":{"rule":"Host:my.ent1.tonicfordev.com, my.ent1.tonicforhealth.com"}},"passHostHeader":true,"priority":0,"basicAuth":[],"headers":{}},"frontend-ent1.ent1_nginx-ent1-ent1-nginx-https":{"entryPoints":["https"],"backend":"backend-ent1.ent1_nginx-ent1-ent1-nginx-https","routes":{"service-https":{"rule":"Host:my.ent1.tonicfordev.com, my.ent1.tonicforhealth.com"}},"passHostHeader":true,"priority":0,"basicAuth":[],"headers":{}}}}"
time="2017-12-07T14:50:37Z" level=debug msg="Last docker config received more than 2s, OK"
time="2017-12-07T14:50:37Z" level=debug msg="Creating frontend frontend-ent1.ent1_nginx-ent1-ent1-nginx-http"
time="2017-12-07T14:50:37Z" level=debug msg="Wiring frontend frontend-ent1.ent1_nginx-ent1-ent1-nginx-http to entryPoint http"
time="2017-12-07T14:50:37Z" level=debug msg="Creating route service-http Host:my.ent1.tonicfordev.com, my.ent1.tonicforhealth.com"
time="2017-12-07T14:50:37Z" level=debug msg="Creating backend backend-ent1.ent1_nginx-ent1-ent1-nginx-http"
time="2017-12-07T14:50:37Z" level=error msg="Undefined backend 'backend-ent1.ent1_nginx-ent1-ent1-nginx-http' for frontend frontend-ent1.ent1_nginx-ent1-ent1-nginx-http"
time="2017-12-07T14:50:37Z" level=error msg="Skipping frontend frontend-ent1.ent1_nginx-ent1-ent1-nginx-http..."
time="2017-12-07T14:50:37Z" level=debug msg="Creating frontend frontend-ent1.ent1_nginx-ent1-ent1-nginx-https"
time="2017-12-07T14:50:37Z" level=debug msg="Wiring frontend frontend-ent1.ent1_nginx-ent1-ent1-nginx-https to entryPoint https"
time="2017-12-07T14:50:37Z" level=debug msg="Creating route service-https Host:my.ent1.tonicfordev.com, my.ent1.tonicforhealth.com"
time="2017-12-07T14:50:37Z" level=debug msg="Creating backend backend-ent1.ent1_nginx-ent1-ent1-nginx-https"
time="2017-12-07T14:50:37Z" level=error msg="Undefined backend 'backend-ent1.ent1_nginx-ent1-ent1-nginx-https' for frontend frontend-ent1.ent1_nginx-ent1-ent1-nginx-https"
time="2017-12-07T14:50:37Z" level=error msg="Skipping frontend frontend-ent1.ent1_nginx-ent1-ent1-nginx-https..."
time="2017-12-07T14:50:37Z" level=info msg="Server configuration reloaded on :443"
time="2017-12-07T14:50:37Z" level=info msg="Server configuration reloaded on :80"`

**Comment by mmatur** [comment] 2017-12-07 15:23
Could you give us labels used on containers or services please ?

**Comment by traffsh0w** [comment] 2017-12-07 15:50
`docker inspect ent1.ent1_nginx | grep Labels -A 13
            "Labels": {
                "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
                "traefik.backend": "ent1.ent1_nginx",
                "traefik.backend.loadbalancer.method": "wrr",
                "traefik.enable": "true",
                "traefik.frontend.entryPoints": "http,https",
                "traefik.frontend.rule": "Host:my.ent1.tonicfordev.com, my.ent1.tonicforhealth.com",
                "traefik.http.frontend.entryPoints": "http",
                "traefik.http.port": "80",
                "traefik.http.protocol": "http",
                "traefik.https.frontend.entryPoints": "https",
                "traefik.https.port": "443",
                "traefik.https.protocol": "https"
            },`


Ansible deploy:

**defaults\main.yml**

`TRAEFIK_LABELS:
  "traefik.enable":                       "true"
  "traefik.backend":                      "ent1.ent1_nginx"
  "traefik.frontend.rule":                "Host:my.ent1.tonicfordev.com, my.ent1.tonicforhealth.com"
  "traefik.frontend.entryPoints":         "http,https"
  "traefik.backend.loadbalancer.method":  "wrr"
  "traefik.http.frontend.entryPoints":    "http"
  "traefik.https.frontend.entryPoints":   "https"
  "traefik.http.protocol":                "http"
  "traefik.https.protocol":               "https"
  "traefik.http.port":                    "80"
  "traefik.https.port":                   "443"
`


**tasks\main.yml**

`- name: Launch Nginx container
  become: yes
  docker_container:
    name: "ent1.ent1_nginx"
    image: "nginx:alpine"
    pull: true
    restart_policy: always
    volumes:
      - "/etc/ssl/certs/nginx/:/etc/ssl/certs/nginx/:ro"
      - "/srv/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/srv/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/srv/nginx/logs/:/var/log/nginx/:rw"
    published_ports:
      - "80:80"
      - "443:443"
    labels: "{{ TRAEFIK_LABELS }}"`

**Comment by ldez** [comment] 2017-12-07 15:57
@traffsh0w Could you try without the dot in the backend name?

```
traefik.backend":  "ent1-ent1_nginx"
```

**Comment by traffsh0w** [comment] 2017-12-07 16:20
Nothing changed with version 1.4.5
Should I test this with 1.5.0-rc2?

**Comment by nmengin** [comment] 2017-12-07 16:26
@traffsh0w

> Should I test this with 1.5.0-rc2?

Yes, doo ti if it's possible : I just tested your configuration with the master branch and it seems to work.

**Comment by traffsh0w** [comment] 2017-12-07 16:28
It doesn't helped, unfortunately.

https://pastebin.com/xAhndTCX

https://pastebin.com/n1Ky72kP

**Comment by traffsh0w** [comment] 2017-12-07 16:46
Traefik version 1.4.5

@ldez why traefik telling that backend is undefined for created frontend and then skips it?

https://pastebin.com/CKV83Jdk

**Comment by ldez** [comment] 2017-12-08 00:53
I tried this:


```shell
wget https://github.com/containous/traefik/releases/download/v1.4.5/traefik_linux-amd64
chmod +x traefik_linux-amd64
mv traefik_linux-amd64 traefik
```

- `traefik.toml` with exactly you configuration (copy/paste from the issue)

- `docker-compose.yml`
```yml
version: '2'
services:
 odooo:
   image: emilevauge/whoami
   expose:
     - "443"
   labels:
     "traefik.enable": "true"
     "traefik.frontend.rule": "Host:my.ent1.tonicfordev.com, my.ent1.tonicforhealth.com"
     "traefik.frontend.entryPoints": "http,https"

     "traefik.backend": "ent1.ent1_nginx"
     "traefik.backend.loadbalancer.method": "wrr"

     "traefik.http.frontend.entryPoints": "http"
     "traefik.http.protocol": "http"
     "traefik.http.port": "80"

     "traefik.https.frontend.entryPoints": "https"
     "traefik.https.protocol": "https"
     "traefik.https.port": "443"
```

```shell
docker-compose up -d
./traefik
```

This works, I cannot reproduce your problem.

Could you do the same test?

**Comment by BlakeMesdag** [comment] 2018-01-08 15:40
@ldez try it using a container name with a period in it, the backend label works with periods for me but the container name messes things up when it has periods.

**Comment by BlakeMesdag** [comment] 2018-01-08 16:50
@ldez looks like it's fixed in v.1.5.0-rc4 and on master.

The issue was in the `getServiceBackend` method where it wasn't normalizing the generated service name.

**Comment by marco-jantke** [comment] 2018-01-27 16:08
@traffsh0w can you test whether you still have the problem with the v1.5 release?

**Comment by traffsh0w** [comment] 2018-01-31 17:46
I've checked 1.5.1 and its okay.

Thanks, people!

**Closed** 2018-01-31 18:07 UTC
Labels: area/provider/docker, kind/bug/possible
