### ISSUE TITLE
Ability to hot-reload certs listed in config files

### ISSUE THREAD

**Issue by Sarke** [containous/traefik#7202] opened 2020-08-19 22:15 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The issue we're having is that we have a separate process for renewing our LE certs, and those then get rsync'ed to the various nodes.  Traefik doesn't notice these changes and continue to use the old, already loaded certs.  Currently only a restart seems to work to load the new certs.

I would like to see, either:

**a)** Use `SIGUSR1` to also reload the config files and certs.  It is currently used to [rotate logfiles already](https://github.com/containous/traefik/pull/1761).  `SIGUSR2` could also be used, but since this would be a soft reload I think one signal to do both is fine.

_or_

**b)** Extend the [config file watch](https://docs.traefik.io/providers/file/#watch) to also watch for changes in associated cert files.  Note that `touch certs.toml` doesn't work.  Also note that LE certs are usually symlinked from the `live` folder.

**Comment by ldez** [comment] 2020-08-19 22:40
Duplicate of #5495

**Closed** 2020-09-02 07:17 UTC
Labels: resolution/duplicate
