### ISSUE TITLE
Docker provider weight dynamic changes

### ISSUE THREAD

**Issue by ralmn** [containous/traefik#4160] opened 2018-11-05 09:52 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

We would like to implement a basic semi-automatic blue/green deployment on a docker swarm mode provider. We are trying to use the traefik weight. However the api currently doesn't allow to change the weight of an existing backend on the fly. We were thinking of something like `/api/providers/docker/backends/{backend}/weight/{weight}` 

Ideally, we would like to specify all other backend and frontend configuration throught labels as usual and just use the api for dynamic weight changes. We don't need the api to overwrite any label. 

Does anybody have the same kinds of needs ? Is there any reason why this is not currently possible ? 

Thank you for considering implementing this.

**Comment by dtomcej** [comment] 2018-11-05 16:07
Hello @ralmn,

Unfortunately configuration like that is not possible through the current labels feature, and configuration via the api is a duplicate of #3695.

If you have any further questions or concerns, please reach out to us on slack: traefik.slack.com

Thanks!

**Closed by dtomcej** 2018-11-05 16:07 UTC
Labels: kind/question, resolution/duplicate
