### ISSUE TITLE
Latest 2.0 version doesn' read config args correctly for ACME

### ISSUE THREAD

**Issue by kurt70** [containous/traefik#5497] opened 2019-09-26 03:49 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

After getting the latest version of Traefik, my existing configuration, that worked earlier, failed on SSL regeneration.
The error message was that challenge method was not spesified.
I am running Traefik on a bare metal K8s installation (ARM)

### What did you expect to see?

My website with a new working SSL certificate.

### Output of `traefik version`: (_What version of Traefik are you using?_)
Traefik:v2.0 -  (arm/v6) - Doesn't work.
Traefik:v2.0.0-beta1 -  (arm/v6) - works.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Excerpt of deployment template:

containers:
      - name: traefik
        image: traefik:v2.0
        imagePullPolicy: Always
        args:
          - --log.Level=debug
          - --api
          - --api.dashboard
          - --accesslog
          - --entrypoints.web.Address=:80          
          - --entrypoints.websecure.Address=:443
          - --entrypoints.mqtt.Address=:1883
          - --entrypoints.influxdb.Address=:8086
          - --providers.kubernetescrd
          - --certificatesResolvers.default.acme.httpChallenge=true
          - --certificatesResolvers.default.acme.httpChallenge.entryPoint=web          
          - --certificatesresolvers.default.acme.email=my.email@domain.com
          - --certificatesresolvers.default.acme.storage=acme.json          

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by ldez** [comment] 2019-09-26 07:24
duplicate of #5360

**Closed by ldez** 2019-09-26 07:24 UTC
Labels: status/0-needs-triage
