### ISSUE TITLE
Traefik does not retry looking for consul cluster at startup

### ISSUE THREAD

**Issue by davidgenn** [containous/traefik#2211] opened 2017-10-04 06:58 UTC
### What did you do?
Start new consul/nomad cluster and start traefik.

### What did you expect to see?
Traefik waits for consul cluster to start and then polls the catalogue.

### What did you see instead?
Traefik errors and does not retry connecting to consul.

If I kill traefik and start it again, it connects to consul successfully.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.0-rc4
Codename:     roquefort
Go version:   go1.9
Built:        2017-10-02_02:19:32PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```json
{
 "GraceTimeOut": 10000000000,
 "Debug": true,
 "CheckNewVersion": true,
 "AccessLogsFile": "/var/log/traefik/access.log",
 "AccessLog": null,
 "TraefikLogsFile": "/var/log/traefik/traefik.log",
 "LogLevel": "DEBUG",
 "EntryPoints": {},
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 0,
 "InsecureSkipVerify": false,
 "RootCAs": null,
 "Retry": null,
 "HealthCheck": {
  "Interval": 30000000000
 },
 "RespondingTimeouts": null,
 "ForwardingTimeouts": null,
 "Docker": null,
 "File": null,
 "Web": null,
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": {
  "Watch": false,
  "Filename": "",
  "Constraints": [],
  "Trace": false,
  "DebugLogGeneratedTemplate": false,
  "Endpoint": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "Domain": "service.consul",
  "ExposedByDefault": true,
  "Prefix": "traefik",
  "FrontEndRule": "Host:{{ServiceName}}.{{Domain}},PathPrefixStrip:/{{ServiceName}}"
 },
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ConfigFile": "/etc/traefik/traefik.toml"
}
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
time="2017-10-04T06:02:44Z" level=info msg="Traefik version v1.4.0-rc4 built on 2017-10-02_02:19:32PM" 
time="2017-10-04T06:02:44Z" level=debug msg="Global configuration loaded {"GraceTimeOut":10000000000,"Debug":true,"CheckNewVersion":true,"AccessLogsFile":"/var/log/traefik/access.log","AccessLog":null,"TraefikLogsFile":"/var/log/traefik/traefik.log","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":false,"ProxyProtocol":false}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":["http"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":0,"InsecureSkipVerify":false,"RootCAs":null,"Retry":null,"HealthCheck":{"Interval":30000000000},"RespondingTimeouts":null,"ForwardingTimeouts":null,"Docker":null,"File":null,"Web":{"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"","Auth":null,"Debug":false,"CurrentConfigurations":null,"Stats":null,"StatsRecorder":null},"Marathon":null,"Consul":null,"ConsulCatalog":{"Watch":false,"Filename":"","Constraints":[],"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"127.0.0.1:8500","Domain":"service.consul","ExposedByDefault":true,"Prefix":"traefik","FrontEndRule":"Host:{{ServiceName}}.{{Domain}},PathPrefixStrip:/{{ServiceName}}"},"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null}" 
time="2017-10-04T06:02:44Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:false} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
time="2017-10-04T06:02:44Z" level=info msg="Starting provider *web.Provider {"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"","Auth":null,"Debug":true,"CurrentConfigurations":{},"Stats":{"Uptime":"2017-10-04T06:02:44.192885209Z","Pid":1442,"ResponseCounts":{},"TotalResponseCounts":{},"TotalResponseTime":"0001-01-01T00:00:00Z"},"StatsRecorder":null}" 
time="2017-10-04T06:02:44Z" level=info msg="Starting provider *consul.CatalogProvider {"Watch":false,"Filename":"","Constraints":[],"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"127.0.0.1:8500","Domain":"service.consul","ExposedByDefault":true,"Prefix":"traefik","FrontEndRule":"Host:{{ServiceName}}.{{Domain}},PathPrefixStrip:/{{ServiceName}}"}" 
time="2017-10-04T06:02:44Z" level=info msg="Starting server on :80" 
time="2017-10-04T06:02:44Z" level=error msg="Failed to retrieve health checks" error="Unexpected response code: 500 (No known Consul servers)" 
time="2017-10-04T06:02:44Z" level=error msg="Failed to list services: Unexpected response code: 500 (No known Consul servers)" 
```

**Comment by SaikiranDaripelli** [comment] 2017-10-13 11:57
Will it be part of 1.4.0? i am also facing same issue.

**Comment by dtomcej** [comment] 2017-10-13 14:50
duplicate of #2147

**Closed** 2017-10-13 14:50 UTC
Labels: area/provider/consulcatalog, kind/bug/possible
