### ISSUE TITLE
Configurable session timeout for UDP messages

### ISSUE THREAD

**Issue by bocajim** [containous/traefik#7231] opened 2020-08-31 13:21 UTC
This is a FEATURE request...

The current 3 second hard coded value does not work for IoT use cases where sessions can have many hours between communications.  

In public networks, the timing window is typically 30 seconds for firewalls to keep the NAT mapping for a UDP packet alive, but in private networks (common in cellular deployments, especially in North America), networks can be built without NAT enabling very long delays (up to 24 hours) where devices are still reachable.

My request is to allow for the configuration of the timeout, such that the sessions will be kept alive for longer periods of time.  As part of this, you may need to include some metrics to track # of active sessions (may already be present) to monitor the number of sessions that may be active.

**Comment by SantoDE** [comment] 2020-08-31 15:09
Duplicate of #6859 - closing :)

**Closed by SantoDE** 2020-08-31 15:09 UTC
Labels: status/0-needs-triage
