### ISSUE TITLE
Traefik 2 - entryPoints for Kubernetes Ingress Controller

### ISSUE THREAD

**Issue by tlvenn** [containous/traefik#5790] opened 2019-11-06 13:13 UTC
Hi,

At the moment, k8s ingresses are exposed through all the entrypoints, it would be great if we could configure over which entrypoints they should be exposed as an additional provider configuration.

**Comment by ldez** [comment] 2019-11-06 16:06
Duplicate of #5624

**Closed by ldez** 2019-11-06 16:06 UTC
Labels: resolution/duplicate

**Comment by tlvenn** [comment] 2019-11-06 22:42
My bad, did not see the other issue, thanks for the consolidation @ldez !
