### ISSUE TITLE
Traefik cluster + Consul KV + ACME - CERTS NOT RENEWED “Error calling Leadership listener: Existing key does not match lock use”

### ISSUE THREAD

**Issue by divyaraghavann** [containous/traefik#6961] opened 2020-06-24 19:59 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Nothing. I was hoping to see certs renewed for our internal domains automatically 30 days before expiry. 

### What did you expect to see?
I'm running a traefik stack on docker with consul as a backend store. My cluster is made of three nodes on different instances. and has traefik configured to renew certificates with ACME every 3 months automatically 30 days before expiry. 

### What did you see instead?
However, the certs are not getting renewed. I restarted the traefik docker containers and I assume something is messed up. I restarted the docker containers on 3 nodes manually and I see this. 
```
time="2020-06-22T18:03:23Z" level=info msg="Node e1064c63-57b5-415c-9bde-5138c0ce8947 elected leader ♚"
time="2020-06-22T18:03:23Z" level=info msg="Starting ACME renew job..."
time="2020-06-22T18:03:23Z" level=error msg="Error calling Leadership listener: Existing key does not match lock use"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
(v1.7.12)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
"traefik",
            "storeconfig",
            "\n--api",
            "\n--logLevel=INFO",
            "\n--insecureskipverify=true",
            "\n--consulcatalog.prefix=traefik",
            "\n--consulcatalog.endpoint=<consul-ip>:8500",
            "\n--consulcatalog.exposedbydefault=false",
            "\n--defaultentrypoints=http,https",
            "\n--consul",
            "\n--consul.endpoint=<consul-ip>:8500",
            "\n--consul.prefix=traefik",
            "\n--metrics",
            "\n--metrics.datadog.address=<consul-ip>:8125",
            "\n--consulcatalog.prefix=traefik",
            "\n--consulcatalog.exposedbydefault=false",
            "\n--defaultentrypoints=http,https",
            "\n--entrypoints=Name:http Address::80 Redirect.EntryPoint:https",
            "\n--entrypoints=Name:https Address::443 TLS",
            "\n--acme",
            "\n--acme.acmelogging",
            "\n--acme.storage=traefik/acme/account",
            "\n--acme.dnschallenge=true",
            "\n--acme.entrypoint=https",
            "\n--acme.domains=*.staging.blah.blah.net",
            "\n--acme.email=<email>",
            "\n--acme.ondemand=false",
            "\n--acme.httpchallenge=false",
            "\n--acme.onhostrule=true",
            "\n--acme.dnsprovider=route53"
        ],
```

---- Follow up---
Deleted the traefik/acme/account/lock on consul and I get this

```
time="2020-06-24T20:30:16Z" level=info msg="Starting ACME renew job..."
time="2020-06-24T20:30:16Z" level=info msg="Skipping same configuration for provider consul"
time="2020-06-24T20:30:16Z" level=info msg="Skipping same configuration for provider consul"
time="2020-06-24T20:30:16Z" level=error msg="Datastore sync error: object lock value: expected 510b9329-21c7-46f6-9b35-902feec4732a, got 036cb958-57fd-46ce-b49a-9061faf1f613, retrying in 407.093697ms"
time="2020-06-24T20:30:16Z" level=info msg="Skipping same configuration for provider consul"
```

**Comment by SantoDE** [comment] 2020-07-01 10:00
Hello @divyaraghavann,

thanks for your interest in the project. 

This issue seems to be a duplicate of #5077 and thus, I'll close that one.

**Closed by SantoDE** 2020-07-01 10:00 UTC
Labels: area/cluster
