### ISSUE TITLE
Traefik cannot handle HTTP & HTTPS in one route

### ISSUE THREAD

**Issue by SeaLife** [containous/traefik#5506] opened 2019-09-26 15:08 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

In Traefik 2.0 i need a hell of docker labels on my containers to achieve what was simple in v1.7.

In my case im thinking of the routers and how they handle SSL and HTTP (no SSL) now.

What i expected to happen when i configured my service like this:

```
  [...]
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.rule=Host(`traefik.r3ktm8.de`)"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.routers.traefik.entrypoints=https,http"
      - "traefik.http.routers.traefik.middlewares=ssl"
      - "traefik.http.routers.traefik.tls.certresolver=le"

      - "traefik.http.middlewares.ssl.redirectscheme.scheme=https"
```

is traefik listening to my route on :80 and :443 and accepting a TLS connection on 443 and a normal HTTP connection on :80.

Since the TLS option was moved to a "certificateResolver" traefik does not know what entrypoint is a TLS entrypoint...

But now i need atleast 3 more labels to achieve the redirect scheme to get active on HTTP connection:

```
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.rule=Host(`traefik.r3ktm8.de`)"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.middlewares=ssl"
      - "traefik.http.routers.traefik.tls.certresolver=le"

      - "traefik.http.routers.traefik_http.middlewares=ssl"
      - "traefik.http.routers.traefik_http.entrypoints=http"
      - "traefik.http.routers.traefik_http.rule=Host(`traefik.r3ktm8.de`)"

      - "traefik.http.middlewares.ssl.redirectscheme.scheme=https"
```

I need 9 Labels to get a simple routing with SSL redirection.. (+1 label for the middleware, but this can be re-used, so - no issue there)

In 1.7 i only had to add those lables:

```
#!/bin/bash
docker run [...] \
        -l "traefik.admin.frontend.rule=Host:traefik.r3ktm8.de" \
        -l "traefik.admin.port=8080" \
        -l "traefik.admin.frontend.redirect.entryPoint=https" \
       [...]
```

Only 3 labels to achieve the same.

Just to mention it - you could also make all routes redirecting to SSL by default so you could minify it to 2 labels (if the application does NOT expose a port) otherwise you only need 1 label.

### Proposal

For this case it would be good to simply allow the router to accept a non-tls connection and redirect it. (or maybe even configurable to use this as a default behaviour)

But there may also be a reason to allow HTTP and HTTPS in one route (without redirection) which is also possible in v1.7.

//EDIT:
Found a issue with nearly the same problem (except for having HTTP and HTTPS routes to a service without redirecting) 
https://github.com/containous/traefik/issues/4863#issue-442458019

Regards
SeaLife

**Comment by ldez** [comment] 2019-09-26 16:03
Duplicate of #4863

**Closed by ldez** 2019-09-26 16:03 UTC
Labels: status/0-needs-triage

**Comment by kari** [comment] 2019-10-22 17:47
The documentation at https://docs.traefik.io/routing/providers/docker/ has an example that is really misleading if http and https cannot be handled in one route:

> traefik.http.routers.<router_name>.entrypoints
> See entry points for more information.
> - "traefik.http.routers.myrouter.entrypoints=web,websecure"

**Comment by dduportal** [comment] 2019-10-22 19:00
Hi @kari , would you be willing to contribute to the documentation page to elaborate/edit the example, so it would look like what you would have expected?

**Comment by kari** [comment] 2019-10-22 19:10
Sorry, but as a user, I do not know how this software is supposed to work. I was hoping the documentation would tell me that. Elsewhere the documentation presents `web` as a HTTP and `websecure` as HTTPS entrypoints, so as a casual reader this example would imply that it is possible to declare these two on one router. 

Apparently it is not possible to put these on one router. Is this a bug? Is this intended behavior? I do not know. If this is not possible, in my opinion, that example in documentation should not list both and HTTP and HTTPS entrypoints, only either one. Although, I guess, the point of the example is to show how multiple entrypoints can be listed (with a comma) and this is useful information, but I do not know what would be a more relevant and actually working example to show there.

**Comment by woto** [comment] 2019-11-03 03:03
Stucked with same problem (((

Works both http and https
```
- "traefik.http.routers.ruweb.entrypoints=web"
- "traefik.http.routers.ruweb.rule=Host(`example.com`)"

- "traefik.http.routers.ruwebsecure.entrypoints=websecure"
- "traefik.http.routers.ruwebsecure.tls.certresolver=myhttpchallenge"
- "traefik.http.routers.ruwebsecure.rule=Host(`example.com`)"
```

Works only https. http respond with 404
```
- "traefik.http.routers.web.entrypoints=web,websecure"
- "traefik.http.routers.web.rule=Host(`example.com`)"
- "traefik.http.routers.web.tls.certresolver=myhttpchallenge"
```

**Comment by chrisbecke** [comment] 2019-11-12 14:08
Wait. Am I to take it from this discussion that "web, websecure" and even more specifically the "Listens to every entrypoint" example do not, in fact allow one router to handle http and https?

Thats a good two hours of my afternoon I could have spent doing something else.
