### ISSUE TITLE
Allow force reload of provider without restarting traefik

### ISSUE THREAD

**Issue by trondhindenes** [containous/traefik#3426] opened 2018-06-01 16:38 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
It would be awesome to have a documented way of having traefik do a forced update of its providers, thru SIGHUP or similar. We're using Consul Catalog backend, and can't find a reliable way of forcing Traefik to reload, except killing/restarting the traefik service, which is obviously not something we want to do.

**Comment by ldez** [comment] 2018-06-01 16:52
Duplicate of #1188

**Closed by ldez** 2018-06-01 16:52 UTC
Labels: status/0-needs-triage
