### ISSUE TITLE
Expose traefik service health check status as metrics (prometheus, datadog, etc)

### ISSUE THREAD

**Issue by hansehe** [containous/traefik#7168] opened 2020-08-13 09:55 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The metrics exposed by traefik are missing typical service health check status.
In general, one of the most common metrics use-cases are service statuses. 
It would be very helpfull if service statuses are exposed as metrics, to create valuable service status dashboards.

**Comment by ldez** [comment] 2020-08-13 11:50
Duplicate of #3783

**Closed by ldez** 2020-08-13 11:50 UTC
Labels: resolution/duplicate
