### ISSUE TITLE
Ability for Docker backend to use the DNS entry instead of IP

### ISSUE THREAD

**Issue by nealf** [containous/traefik#644] opened 2016-08-24 17:35 UTC
Edit: Wanted to say thanks for a great project!

Since Docker provides a built-in DNS solution with their networks and linked containers, it would be valuable if Traefik could use that instead of the internal IP address. The biggest issue I've come across with using IPs is that you can't do https on the backend without going through a number of headaches: Traefik won't trust the cert on the backend unless it has the appropriate IP SAN (though I haven't even gotten that to work yet), even with InsecureSkipVerify = true. So you have to create a static IP for that container in the Docker network, and then of course this is difficult to scale because certs on each of the containers have to have corresponding IP SANs to match. 

So instead of: 
- Client -> Traefik -> https://172.20.0.2:443

it would do:
- Client -> Traefik -> https://containername

This would also allow Docker to handle the load-balancing algorithm, as Traefik would just be referencing the service name, and it would determine which container to route traffic to based on its configuration.

**Comment by emilevauge** [comment] 2016-08-27 09:40
Have you seen this https://github.com/containous/traefik/pull/602 ?

**Comment by alvarolizama** [comment] 2016-08-28 17:39
In theory if traefik is part of the same network you can do that.

**Comment by nealf** [comment] 2016-08-29 12:50
@alvarolizama Interesting, how are you able to configure it to do that?

@emilevauge I think that compatibility with Swarm mode gets us most of the way there, and if @alvarolizama's way of making it work continues to work with the changes in that pull request then that would do it!

**Comment by nealf** [comment] 2016-08-29 13:13
I did just find #489 which is a similar issue that I had missed when searching previously, and these issues could probably be merged

**Comment by jm66** [comment] 2017-01-26 19:00
@nealf did you find a workaround for this?

**Comment by nealf** [comment] 2017-01-31 18:56
Unfortunately, I never did @jm66

**Comment by chulkilee** [comment] 2017-01-31 21:44
Note

* default docker network does not provide docker embedded dns
* traefik using docker backend does not mean it is running inside docker, so may not be able to use docker embedded dns

**Comment by ldez** [comment] 2017-06-02 13:23
This is a duplicate of #489 - Feel free to subscribe there for updates.

**Closed by ldez** 2017-06-02 13:23 UTC
Labels: area/provider/docker, kind/enhancement, resolution/duplicate
