### ISSUE TITLE
error middleware can create and influence the middleware that is created later

### ISSUE THREAD

**Issue by OojaxoO** [containous/traefik#6726] opened 2020-04-24 09:40 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I create a middleware ok (but the format is a failure), subsequent middleware creation fails, and after a particular restart, all middleware will fail.

### What did you expect to see?
1. error middleware can not create and return error.
2. When there is an incorrect middleware, the page is displayed and does not affect subsequent creation of middleware

### What did you see instead?
When a middleware creation succeeds (but the format is a failure), subsequent middleware creation fails, and after a particular restart, all middleware will fail.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik: 2.0.5 and 2.2.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
provider: k8s-1.13.4
platform: Ubuntu 18.04.1 
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
E0424 08:47:55.804226       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190718183610-8e956561bbf5/tools/cache/reflector.go:98: Failed to list *v1alpha1.Middleware: v1alpha1.MiddlewareList.Items: []v1alpha1.Middleware: v1alpha1.Middleware.Spec: v1alpha1.MiddlewareSpec.Headers: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|headers":[{"key":"ac|..., bigger context ...|":"test.test-nginx.80.headers","spec":{"headers":[{"key":"accessControlMaxAge","value":"100"}]}},{"a|...
```

**Comment by ldez** [comment] 2020-04-24 09:46
duplicate of #6109

**Closed by ldez** 2020-04-24 09:46 UTC
Labels: status/0-needs-triage
