### ISSUE TITLE
When Kubernetes API Fails, Traefik starts returning 404s

### ISSUE THREAD

**Issue by jezell** [containous/traefik#1240] opened 2017-03-06 21:59 UTC
### What version of Traefik are you using (`traefik version`)?

1.1.3

### What is your environment & configuration (arguments, toml...)?

Kubernetes ingress controllers

### What did you do?

When kube api returns error during sync, traefik starts returning 404s.

### What did you expect to see?

Traefik continues to run with last known configuration.

### What did you see instead?

Traefik wipes config and starts returning 404s until API calls start succeeding.

Traefik maintains a cached state of the last good configuration. It should continue to use the last good configuration when it encounters an API error during sync process. Right now it just logs the error and throws it away, and then behaves as if the sync succeeded and swaps out the last known config with a corrupt config.

I believe if it were to return errors here (and other places where it is currently throwing away the errors):

https://github.com/containous/traefik/blob/master/provider/kubernetes.go#L194

Then it wouldn't override the config here, and the last good state would be maintained instead of being cleared out:

https://github.com/containous/traefik/blob/master/provider/kubernetes.go#L88

**Comment by timoreimann** [comment] 2017-03-06 22:05
@jezell thanks for filing a separate issue. 👍 

Continued from #1077.

/cc @Regner.

**Comment by timoreimann** [comment] 2017-03-09 22:35
@Regner do you possibly work on this one? Just for the book-keeping. :-)

**Comment by Regner** [comment] 2017-03-09 22:41
Yea, the fix is easy but updating the tests to cover it is the more difficult part. I am busy during the week here but would love to take a shot at fixing it this coming weekend if there isn't a rush on it.

**Comment by timoreimann** [comment] 2017-03-09 22:43
@Regner no rush from my end, take your time.

I suppose you saw my response on Slack to your testing question. Feel free to reach out again if I can assist somehow. 😃

**Comment by Regner** [comment] 2017-03-09 22:44
Will do! Thanks. :)

**Comment by timoreimann** [comment] 2017-03-19 20:30
Should be fixed by #1295 (which went into the 1.2 branch).

**Closed by timoreimann** 2017-03-19 20:30 UTC
Labels: provider/k8s

**Comment by jonaz** [comment] 2017-03-22 09:25
This looks like a duplicate of #912 ?
