### ISSUE TITLE
Traefik crashes when using Consul catalog

### ISSUE THREAD

**Issue by drywheat** [containous/traefik#699] opened 2016-09-24 17:03 UTC
I'm running Traefik inside of a container (**v1.0.2**) configured to use the Consul catalog for backend discovery. It will run well for about 2 days on average and then crash with the following error: `Cannot connect to consul server Consul service list nil`. This happens consistently.

My Consul cluster has remained stable during this entire testing effort so I believe this is a bug inside of Traefik.  Here is some console output:

![image](https://cloud.githubusercontent.com/assets/65274/18753308/e0a11ff2-80b2-11e6-937e-e12360e2b83b.png)

**Comment by emilevauge** [comment] 2016-09-26 06:19
I assume it's due to a lot of reconnections to consul. This should be fixed in master. Could you try with `containous/traefik:experimental` Docker image?

**Comment by drywheat** [comment] 2016-09-26 14:58
I can use that image and it should be pretty straightforward to verify that this fixes the problem.  I do, however, have one question. Should I be using the `traefik` or `containous/traefik` container in general? Is the former being actively maintained (it doesn't have the **v1.0.3** or **experimental** tagged images)?

**Comment by emilevauge** [comment] 2016-09-28 22:00
@drywheat `traefik` is the official Docker image, and each new version need a pull request at Docker. `containous/traefik` is managed by traefik team instead. We use the latest for experimental builds.

**Comment by drywheat** [comment] 2016-09-29 16:48
Thank you for clearing that up.

So, regarding the newer `experimental` traefik image, it no longer errors out in a way that causes the container to exit.  Instead, its health check stopped responding and it stopped routing requests after a couple of days (same time period as before).

Here's a screenshot of the new logs:

![image](https://cloud.githubusercontent.com/assets/65274/18963461/12b836e8-8643-11e6-8f3d-f6a1b8c2027c.png)

**Comment by emilevauge** [comment] 2016-10-05 09:59
@drywheat sadly I can't reproduce your issue :'( Could give me more details on this? How much errors do you get between traefik start and the issue? Could you launch traefik in DEBUG mode for few hours and send the logs?

**Comment by drywheat** [comment] 2016-10-18 01:02
I'm sorry I waited so long to respond.  I believe this bug went away after I updated to **v1.1.0-rc1**.  I'm happy to close the issue now and I want to say thanks for your help.

**Closed** 2016-10-26 14:53 UTC
Labels: investigation-needed
