### ISSUE TITLE
Feature Request: Dynamically reload provided (non-ACME) certificates for entrypoints

### ISSUE THREAD

**Issue by Takios** [containous/traefik#1662] opened 2017-05-24 14:06 UTC
### What version of Traefik are you using?
```
Version:      v1.2.3
Codename:     morbier
Go version:   go1.7.5
Built:        2017-04-13_07:33:22PM
OS/Arch:      linux/386
```

### What is your environment & configuration (arguments, toml...)?
```json
{
 "GraceTimeOut": 10,
 "Debug": true,
 "CheckNewVersion": false,
 "AccessLogsFile": "/var/log/traefik/access.log",
 "TraefikLogsFile": "/var/log/traefik/traefik.log",
 "LogLevel": "DEBUG",
 "EntryPoints": {
  "http": {
   "Network": "",
   "Address": ":80",
   "TLS": null,
   "Redirect": null,
   "Auth": null,
   "Compress": false
  },
  "https": {
   "Network": "",
   "Address": ":443",
   "TLS": {
    "MinVersion": "",
    "CipherSuites": null,
    "Certificates": [
     {
      "CertFile": "/etc/traefik/certs/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.crt",
      "KeyFile": "/etc/traefik/certs/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.key"
     }
    ],
    "ClientCAFiles": null
   },
   "Redirect": null,
   "Auth": null,
   "Compress": false
  }
 },
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "InsecureSkipVerify": false,
 "Retry": {
  "Attempts": 3
 },
 "Docker": null,
 "File": {
  "Watch": true,
  "Filename": "/etc/traefik/rules.toml",
  "Constraints": null
 },
 "Web": null,
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "ConfigFile": "/etc/traefik/traefik.toml"
}
```

### What did you do?
Add a certificate to the https entrypoint (would also apply to removing a certificate)

### What did you expect to see?
Traefik using the new certificate without restarting the whole service. A manual "reload" function would be fine as well.

### What did you see instead?
Traefik does not use the new certificate until a full restart of traefik, disrupting the service for a short time.

**Comment by ldez** [comment] 2017-05-24 15:20
This is a duplicate of #1623 - Feel free to subscribe there for updates.

**Closed by ldez** 2017-05-24 15:20 UTC
Labels: resolution/duplicate
