### ISSUE TITLE
Path exclusion for routers

### ISSUE THREAD

**Issue by DrPyser** [containous/traefik#6196] opened 2020-01-18 18:29 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

One feature missing from traefik routing, is the ability to specify that a router should not match some paths, for example paths with prefix `/api` should not be routed to a UI, but all other paths should. It doesn't seem like this can be expressed currently, as `PathPrefix` does not support negative lookahead in regexes. 

Without changing the regex implementation for `PathPrefix`, I guess a way to support this feature is to add a `PathPrefixExclude` match operator, and use a rule like ``PathPrefix(`/`) && PathPrefixExclude(`/api`)``.

Thanks for this great project!

**Comment by ldez** [comment] 2020-01-18 18:33
Duplicate of #4812

**Closed by ldez** 2020-01-18 18:33 UTC
Labels: resolution/duplicate

**Comment by DrPyser** [comment] 2020-01-18 20:31
@ldez Sorry, I interpreted that issue as talking about access restriction based on other request properties. 
> [...] enforce global path restrictions which would applied to all frontends

My needs are only concerning the routing rule for a given router. In my example, a `/api/servicethatmightexist` would not be matched by a router using ``PathPrefixExclude(`/api`)`` in its rule, but could be matched by another router. No response is returned by the first router.
