### ISSUE TITLE
Forwarding to ExternalNames ignores port

### ISSUE THREAD

**Issue by joshuacox** [containous/traefik#3071] opened 2018-03-23 15:25 UTC
I have sought support on this issue, on [stackoverflow](https://stackoverflow.com/questions/49431284/forward-to-externalname-with-traefik-in-kubernetes-as-the-documenation-suggests/49434310?noredirect=1#comment85878366_49434310) and the [slack channel](https://traefik.slack.com/archives/C0CDT22PJ/p1521762460000087)

However, this appears to be a bug. 

### What did you do?

Added traefik to a cluster:
```console
kubectl apply -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-ds.yaml
```

And set an ingress for an externalname with an alternate port:
```yml
---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-exp
  namespace: kube-system
spec:
  type: ExternalName
  ports:
  - name: app-port
    port: 4080
  externalName: 10.33.33.87
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-exp
  namespace: kube-system
  annotations:
    traefik.frontend.passHostHeader: "false"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: gitlab.example.com
    http:
      paths:
      - backend:
          serviceName: gitlab-exp
          servicePort: app-port
```

### What did you expect to see?

Traefik serving the externalname from 4080 on it's port 80

### What did you see instead?

Traefik serving 10.33.33.87's port 80 and not port 4080

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.5.4
from the latest docker image:
```
traefik                                                  latest              fde722950ccf        7 days ago          49.7MB
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

default for kubernetes, the kubectl commands above have been run on many freshly built clusters on many different machines and data centers.  Including https://labs.play-with-k8s.com/ upon which this can be replicated easily.

**Comment by joshuacox** [comment] 2018-03-23 16:11
to replicate on https://labs.play-with-k8s.com/ start up your first instance and:

```
curl https://gist.githubusercontent.com/joshuacox/ed8173a43659f01ede983fcbaa0dafe2/raw/8faf3eca30cff2cbc319b67e8fc420f5eea084b7/kubestart.sh | bash
```

create a second instance and:

```
curl https://gist.githubusercontent.com/joshuacox/bddac4a9e0595a8ff08b2735a05ff724/raw/a9a9fc86576d8538079a833248ae532d55c6db29/traefik-test.sh|bash
```

to create two nginx containers one on 80 (bad), and one on 4080 (good)

```
[node1 /]$ curl -s https://gist.githubusercontent.com/joshuacox/8c7a6ce9a44ba5b51ee89de656f98cfa/raw/b0caa39196a2369a74ae6e32bb1a41288446f8f3/addingress.sh > addingress.sh
[node1 /]$ chmod +x addingress.sh
[node1 /]$ ./addingress.sh 172.30.0.3
[node1 /]$ curl gitlab.example.com
bad
[node1 /]$ curl 172.30.0.3
bad
[node1 /]$ curl 172.30.0.3:4080
good
```

**Comment by timoreimann** [comment] 2018-03-23 20:28
Thanks for reporting!

This seems to be a duplicate of #1816.

I'll close the issue -- if you think it addresses a separate problem, please let us know.

**Closed by timoreimann** 2018-03-23 20:28 UTC
Labels: area/provider/k8s, status/0-needs-triage
