### ISSUE TITLE
forwarded_header lost X-Forwarded-For

### ISSUE THREAD

**Issue by zhengqisong** [containous/traefik#6573] opened 2020-03-25 04:15 UTC
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
pkg/middlewares/forwardedheaders/forwarded_header.go not deal X-Forwarded-For

insecure is true, can not x-forward in xHeaders
```
if !x.insecure && !x.isTrustedIP(r.RemoteAddr) {
		for _, h := range xHeaders {
			r.Header.Del(h)
		}
	}

	x.rewrite(r)
```

version: 2.1.6
providers: kubernetes-crd
flow: client(10.1.1.2) -> elb(10.2.2.2) -> nginx(10.3.3.3) -> traefik(10.4.4.3) -> app

traefik host tcpdump:
X-Forwarded-For: 10.1.1.2,10.2.2.2,10.3.3.3

app host tcpdump
X-Forwarded-For: 10.3.3.3
X-Forwarded-Host: your.domain.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: hostname
X-Real-Ip: 10.3.3.3
X-Ruxit-Forwarded-For: 10.1.1.2, 10.1.1.2

**Comment by zhengqisong** [comment] 2020-03-25 12:03
I use traefik.toml or traefik.yaml，can not load entryPoints.web.forwardedHeaders.insecure, but use cmd entryPoints.web.forwardedHeaders.insecure can load.

start log
```
{"level":"debug","msg":"Static configuration loaded {\"global\":{\"checkNewVersion\":true,\"sendAnonymousUsage\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"test\":{\"address\":\":8001\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"traefik\":{\"address\":\":8083\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"web\":{\"address\":\":8000\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}},\"websecure\":{\"address\":\":4443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"kubernetesIngress\":{\"token\":\"/root/ingress_controller/token\",\"certAuthFilePath\":\"/root/ingress_controller/ca.pem\"},\"kubernetesCRD\":{\"token\":\"/root/ingress_controller/token\",\"certAuthFilePath\":\"/root/ingress_controller/ca.pem\"}},\"api\":{\"insecure\":true,\"dashboard\":true},\"metrics\":{\"prometheus\":{\"buckets\":[0.1,0.3,1.2,5],\"addEntryPointsLabels\":true,\"addServicesLabels\":true,\"entryPoint\":\"traefik\"}},\"log\":{\"level\":\"DEBUG\",\"filePath\":\"/data/log/traefiklog/log.log\",\"format\":\"json\"},\"accessLog\":{\"filePath\":\"/data/log/traefiklog/access.log\",\"format\":\"json\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"drop\"}},\"bufferingSize\":100}}","time":"2020-03-25T10:38:39+08:00"}
```
traefik.toml
```
[entrypoints]
  [entrypoints.web]
    Address = ":8000"
    [entryPoints.web.forwardedHeaders]
      insecure = true

```

**Comment by ldez** [comment] 2020-03-25 12:40
TOML and YAML are case sensitive: `entrypoints` != `entryPoints`

duplicate of #6563

**Closed by ldez** 2020-03-25 12:40 UTC
Labels: status/0-needs-triage
