### ISSUE TITLE
Multiple forward slashes in path gets forwarded with http protocol

### ISSUE THREAD

**Issue by soedar** [containous/traefik#1966] opened 2017-08-17 07:58 UTC
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?

Traefik seems to forward paths with multiple forward slashes (/) with http protocol prefix.

This is particularly troublesome for Go backends with `DefaultServeMux`, which will return a 301 of the request path.

**Curl**
```bash
curl -v localhost//google.com
```

**Sample Go backend server**
```golang
package main

import (
	"fmt"
	"log"
	"net/http"
	"net/http/httputil"
)

func main() {
	mux := http.NewServeMux()
	log.Fatal(http.ListenAndServe(":3000", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requestDump, _ := httputil.DumpRequest(r, true)
		log.Println(string(requestDump))
		mux.ServeHTTP(w, r)
	})))
}
```

**Start traefik** (See below for traefik.toml)
```bash
sudo ./traefik_linux-amd64 --configfile=./traefik.toml --web --loglevel=DEBUG
```

### What did you expect to see?
Go's output
```
$ go run server.go
2017/08/17 15:44:48 GET //google.com HTTP/1.1
Accept: */*
Accept-Encoding: gzip
User-Agent: curl/7.47.0
X-Forwarded-For: ::1
X-Forwarded-Host: localhost:3000
X-Forwarded-Proto: http
X-Forwarded-Server: server
```

curl output
```
$ curl -v localhost//google.com
*   Trying ::1...
* Connected to localhost (::1) port 80 (#0)
> GET //google.com HTTP/1.1
> Host: localhost
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Thu, 17 Aug 2017 07:44:48 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 46
< Location: /google.com
< 
<a href="/google.com">Moved Permanently</a>.
```

### What did you see instead?
Go's output
```
$ go run server.go
2017/08/17 15:42:08 GET http://google.com HTTP/1.1
Accept: */*
Accept-Encoding: gzip
User-Agent: curl/7.47.0
X-Forwarded-For: ::1
X-Forwarded-Host: localhost:3000
X-Forwarded-Proto: http
X-Forwarded-Server: server
```

curl output
```
$ curl -v localhost//google.com
*   Trying ::1...
* Connected to localhost (::1) port 80 (#0)
> GET //google.com HTTP/1.1
> Host: localhost
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=utf-8
< Date: Thu, 17 Aug 2017 07:46:31 GMT
< Content-Length: 53
< Location: http://google.com/
< 
<a href="http://google.com/">Moved Permanently</a>.
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.5
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-01_03:55:31PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]

[frontends]
  [frontends.website]
  backend = "website"
  entrypoints = ["http"]

[backends]
  [backends.website]
    [backends.website.servers.website]
    url = "http://localhost:3000"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
DEBU[2017-08-17T15:48:34+08:00] Round trip: http://localhost:3000, code: 301, duration: 1.229961ms
```

**Comment by ldez** [comment] 2017-08-17 09:12
Duplicate of #1323

**Closed** 2017-08-17 09:14 UTC
