### ISSUE TITLE
Should route by entrypoint if two ingresses have same Host+Path

### ISSUE THREAD

**Issue by irgb** [containous/traefik#4445] opened 2019-01-31 02:19 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I have two Ingresses, and I want to route traffic from my.domain.com:9090 to service1, and route traffic from my.domain.com:80 to service2.

```yml
# ingress1 with backend service1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: 9090 # listen to only 9090
  labels:
    app.kubernetes.io/name: ingress1
  name: ingress1
spec:
  rules:
  - host: my.domain.com
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: 80
        path: /
```

```yml
# ingress2 with backend service2
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: 8080 # listen to only 8080
  labels:
    app.kubernetes.io/name: ingress2
  name: ingress2
spec:
  rules:
  - host: my.domain.com
    http:
      paths:
      - backend:
          serviceName: service2
          servicePort: 80
        path: /
```

### What did you expect to see?
After I install ingress1 and ingress2, I expect that traefik (V1.6.5) should contain two rules:

```
Route Rule: 
  PathPrefix:/
  Host: my.domain.com
Entry Points: 8080
```
and 
```
Route Rule: 
  PathPrefix:/
  Host: my.domain.com
Entry Points: 9090
```

### What did you see instead?
But traefik is confused with these two rules, and route traffic from 8080 and 9090 to service1 and service2 randomly!

I expect traefik do not merge two ingresses have different entrypoints.

After some digging, I found that when traefik load Ingress from kubernetes , it use `baseName := r.Host + pa.Path` as key. I think It should be `key = Host + entryPoint + path` 

https://github.com/containous/traefik/blob/bdc0e3bfcf5f6ce9c6dade2dda47737f7c97ef8f/provider/kubernetes/kubernetes.go#L190

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
V1.6.5
```

**Comment by ldez** [comment] 2019-01-31 02:43
Do you still have the same problem with the latest version (v1.7.8)? [releases](https://github.com/containous/traefik/releases)

**Comment by ldez** [comment] 2019-02-01 00:49
Duplicate of #4416

**Comment by irgb** [comment] 2019-02-01 02:08
> Do you still have the same problem with the latest version (v1.7.8)? [releases](https://github.com/containous/traefik/releases)

I didn't test on v1.7.8. But the calculation method of baseName doesn't change between  V1.6.5 and v1.7.8. So I think the problem still exists in  v1.7.8. 

https://github.com/containous/traefik/blob/418dca1113acd336d2acecb64f4ca3d2ba468110/provider/kubernetes/kubernetes.go#L242

**Comment by geraldcroes** [comment] 2019-02-01 15:25
Hi!

Could you send us the logs and your configuration file? 

Thank you!

**Comment by irgb** [comment] 2019-02-12 11:33
Sorry, I can't reconstruct the environment to reproduce the phenomenon.
But, this bug is obvious as long as `baseName := r.Host + pa.Path` exists.

**Comment by traefiker** [comment] 2019-03-28 13:22
Closed by #4679.

**Closed by traefiker** 2019-03-28 13:22 UTC
Labels: area/provider/k8s/ingress, kind/bug/confirmed
