### ISSUE TITLE
Prometheus metrics router removed in v1.7.4

### ISSUE THREAD

**Issue by joshadambell** [containous/traefik#4235] opened 2018-11-26 21:48 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Configured traefik to pull prometheus metrics.

### What did you expect to see?
The endpoint :8080/metrics available

### What did you see instead?
The endpoint :8080/metrics doesn't exist

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.7.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Kubernetes on AWS

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)
v1.7.4
```
time="2018-11-26T21:46:22Z" level=debug msg="Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceTimeOut\":0,\"Debug\":false,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false,\"AccessLogsFile\":\"\",\"AccessLog\":null,\"TraefikLogsFile\":\"\",\"TraefikLog\":null,\"Tracing\":null,\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"IdleTimeout\":0,\"InsecureSkipVerify\":false,\"RootCAs\":null,\"Retry\":null,\"HealthCheck\":{\"Interval\":30000000000},\"RespondingTimeouts\":null,\"ForwardingTimeouts\":null,\"AllowMinWeightZero\":false,\"KeepTrailingSlash\":false,\"Web\":null,\"Docker\":null,\"File\":null,\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\",\"IngressEndpoint\":null},\"Mesos\":null,\"Eureka\":null,\"ECS\":null,\"Rancher\":null,\"DynamoDB\":null,\"ServiceFabric\":null,\"Rest\":null,\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Debug\":false,\"CurrentConfigurations\":null,\"Statistics\":null},\"Metrics\":{\"Prometheus\":{\"Buckets\":[0.1,0.3,1.2,5],\"EntryPoint\":\"traefik\"},\"Datadog\":null,\"StatsD\":null,\"InfluxDB\":null},\"Ping\":null,\"HostResolver\":null}"
```

v1.7.3
```
time="2018-11-26T21:39:52Z" level=debug msg="Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceTimeOut\":0,\"Debug\":false,\"CheckNewVersion\":true,\"SendAnonymousUsage\":false,\"AccessLogsFile\":\"\",\"AccessLog\":null,\"TraefikLogsFile\":\"\",\"TraefikLog\":null,\"Tracing\":null,\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}},\"traefik\":{\"Address\":\":8080\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"WhitelistSourceRange\":null,\"WhiteList\":null,\"Compress\":false,\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":true,\"TrustedIPs\":null}}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"IdleTimeout\":0,\"InsecureSkipVerify\":false,\"RootCAs\":null,\"Retry\":null,\"HealthCheck\":{\"Interval\":30000000000},\"RespondingTimeouts\":null,\"ForwardingTimeouts\":null,\"AllowMinWeightZero\":false,\"Web\":null,\"Docker\":null,\"File\":null,\"Marathon\":null,\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\",\"IngressEndpoint\":null},\"Mesos\":null,\"Eureka\":null,\"ECS\":null,\"Rancher\":null,\"DynamoDB\":null,\"ServiceFabric\":null,\"Rest\":null,\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Debug\":false,\"CurrentConfigurations\":null,\"Statistics\":null},\"Metrics\":{\"Prometheus\":{\"Buckets\":[0.1,0.3,1.2,5],\"EntryPoint\":\"traefik\"},\"Datadog\":null,\"StatsD\":null,\"InfluxDB\":null},\"Ping\":null,\"HostResolver\":null}"
```

Line commented out: 
https://github.com/containous/traefik/blob/a09dfa3ce10f222ab6e10ac11386d330698ff6f8/old/configuration/router/internal_router.go#L49

**Comment by ldez** [comment] 2018-11-27 08:20
The code of versions 1.7.x is on the branch `v1.7`.
The code in the branch `master` is not related to `v1.7` but to the next release (not bugfix on v1.7)

**Comment by mmatur** [comment] 2018-11-27 16:25
Hi @joshadambell,

Thanks for your interest in the project.

After some investigations I can confirm that there is no bug.


## Tests
With traefik v1.7.3
```console
$ docker run --rm -p 127.0.0.1:8080:8080 traefik:v1.7.3 --metrics.prometheus
```
Curl /metrics
```console
$ curl -s http://127.0.0.1:8080/metrics
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.00010449
go_gc_duration_seconds{quantile="0.25"} 0.000129462
go_gc_duration_seconds{quantile="0.5"} 0.000193783
go_gc_duration_seconds{quantile="0.75"} 0.000272303
go_gc_duration_seconds{quantile="1"} 0.000288296
go_gc_duration_seconds_sum 0.001408918
go_gc_duration_seconds_count 7
...
```

With traefik v1.7.4
```console
$ docker run --rm -p 127.0.0.1:8080:8080 traefik:v1.7.4 --metrics.prometheus
```

Curl /metrics
```console
$ curl -s http://127.0.0.1:8080/metrics 
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.000115892
go_gc_duration_seconds{quantile="0.25"} 0.000122344
go_gc_duration_seconds{quantile="0.5"} 0.000154267
go_gc_duration_seconds{quantile="0.75"} 0.000278334
go_gc_duration_seconds{quantile="1"} 0.000312442
go_gc_duration_seconds_sum 0.001474739
go_gc_duration_seconds_count 8
...
```

So I will close this issue because I think that the question is answered.

**Closed by mmatur** 2018-11-27 16:25 UTC
Labels: status/0-needs-triage
