### ISSUE TITLE
Prioritize Path-less Host before Path-less HostRegexp 

### ISSUE THREAD

**Issue by Getty** [containous/traefik#4084] opened 2018-10-19 15:07 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

On setting up a new traefik server I was suddenly hit by a problem through the priority logic. I had one docker which was supposed to be a catchall for all the unknown domains, so he had the frontend rule:

```
traefik.frontend.rule=HostRegexp:{catchall:.*}
```

While there was another host with a precise rule like this:

```
traefik.frontend.rule=Host:xxx.de
```

Now the problem is that traefik by default prefers the HostRegexp rule because it is longer as the Host rule, while the exact matching Host for sure is a better match then the HostRegexp broadsword. I didn't noticed the problem before, because:

```
traefik.frontend.rule=Host:very.very.very.very.long.with.sugar.on.top.domain.de
```

Would still work out, because it is longer as the HostRegexp. Which makes that in my eyes a problem, because you will not obvious see why this domain works while the other doesn't work, if you as traefik user not yet learned about prioritizing or aren't thinking about this one.

Primary my feature request or wish, would be that every frontend rule for a Host (but without a Path*) is always processed before a frontend rule for a HostRegexp. This would for sure not remove any working case, because everyone who felt into this problem has a non working Host frontend rule which he should already have noticed yet. There is no positive case that would make this current behavior acceptable (again: only if there is no Path, if there is a Path, then all bets are off again and the current behavior is fine).

I discussed this briefly with @dtomcej on the Slack, he told me I should mention him on here, cause he has an idea how implement a solution here.

Thanks in advance for consideration.

**Comment by port22** [comment] 2018-10-22 13:49
same problem here I think:

```
      - "traefik.frontend.rule=HostRegexp:{subdomain:.+}.example.com"
```
seems to have precedence over
```
      - "traefik.frontend.rule=Host:exact.example.com"
```

Is there any workaround/hack for the mean time?
Or is this even intended?

**Comment by Getty** [comment] 2018-10-22 14:11
Yes, you can set:

```
traefik.frontend.priority=10
```

on the Host: ones, and for the HostRegexp: you set:

```
traefik.frontend.priority=1
```

That will do the trick for now.

**Comment by jbdoumenjou** [comment] 2018-10-23 14:53
Hello @Getty , it seems to be a duplicate of #1663, so I'll close this issue.

**Closed by jbdoumenjou** 2018-10-23 14:53 UTC
Labels: status/0-needs-triage
