### ISSUE TITLE
x509: cannot validate certificate for 192.168.16.7 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by FernandoMiguel** [containous/traefik#3906] opened 2018-09-19 10:34 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?
to load upstream to load via HTTPS

### What did you see instead?
`500 Internal Server Error' caused by: x509: cannot validate certificate for 192.168.16.7 because it doesn't contain any IP SANs`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker run --rm  traefik:v1.7-alpine version
Version:      v1.7.0-rc5
Codename:     maroilles
Go version:   go1.11
Built:        2018-09-18_01:50:00PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################

debug = false
# defaultEntryPoints = ["http", "https"]

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/ssl/private/fullchain.pem"
      keyFile = "/etc/ssl/private/cert.key"


# Enable Docker configuration backend
[docker]

# domain = "docker.localhost"
domain = "docker.dev.XXXXX.com"
network = "traefik-web"

# exposedByDefault = true
exposedByDefault = false

# InsecureSkipVerify = true
```

```YAML
version: "3.6"

services:
  tls-volume:
    image: myrepo/acme-tls
    container_name: tls-volume
    # networks:
    #   - VOID
    volumes:
      - tls:/acme-tls/tls:ro
    command: ["sleep", "1"]
    user: nobody

  traefik:
    image: traefik:v1.7-alpine #The official Traefik docker image
    container_name: traefik
    command: --api --docker #Enables the web UI and tells Træfik to listen to docker
    ports:
      - "8080:8080" #The Web UI (enabled by --api)
      - "172.16.29.29:80:80"     #The HTTP port
      - "172.16.29.29:443:443"
      # - "80:80"     #The HTTP port
      # - "443:443"
    networks:
      - traefik-web
    volumes:
      - $PWD/traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - tls:/etc/ssl/private:ro
    depends_on:
      - tls-volume

  frontend-storage:
    image: myrepo/storage
    container_name: frontend-storage
    volumes:
      - frontend:/var/www
    user: nobody

  frontend-nginx:
    image: myrepo/nginx
    container_name: frontend-nginx
    labels:
      - "traefik.backend=frontend-nginx"
      - "traefik.frontend.rule=Host:docker.dev.XXXX.com"
      - "traefik.docker.network=traefik-web"
      - "traefik.port=443"
      - "traefik.protocol=https"
    expose:
      - "443"
    networks:
      - traefik-web
      - frontend
    volumes:
      - tls:/etc/ssl/private:ro
      - frontend:/var/www
    depends_on:
      - traefik
      - frontend-storage
      - frontend-php
      - tls-volume

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="https://192.168.16.7:443"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="'500 Internal Server Error' caused by: x509: cannot validate certificate for 192.168.16.7 because it doesn't contain any IP SANs"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/forward/http: Round trip: https://192.168.16.7:443, code: 500, Length: 21, duration: 162.4747ms tls:version: 303, tls:resume:false, tls:csuite:c02b, tls:server:docker.dev.XXXX.com"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:30Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}" ForwardURL="https://192.168.16.7:443"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="'500 Internal Server Error' caused by: x509: cannot validate certificate for 192.168.16.7 because it doesn't contain any IP SANs"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/forward/http: Round trip: https://192.168.16.7:443, code: 500, Length: 21, duration: 2.2809ms tls:version: 303, tls:resume:false, tls:csuite:c02b, tls:server:docker.dev.XXXX.com"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"192.168.16.7:443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
traefik                         | time="2018-09-19T10:23:31Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en;q=0.9\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://docker.dev.XXXX.com/\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"docker.dev.XXXX.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.16.1:40902\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
```

**Comment by nmengin** [comment] 2018-09-19 15:33
Hello @FernandoMiguel ,

Many thanks for your interest in the project.

Your problem seems to come from the communication between Træfik and your backend `frontend-nginx`. 
The error appears because you have specified the option `traefik.protocol=https` which force a TLS communication between Træfik and your backend but the certificates provided by the backend do not seems to be valid for its IP.

Indeed, Træfik have used the backend IP in the HTTP request, that's why this IP has to be set as a ipSAN into your certificate.

For the moment, it does not exist a perfect solution, we are aware of the problem and have worked on a global solution (for all the providers).

As a workaround, you can:

- Communicate in HTTP between Træfik and your backends (of course ;) )
- Set the IP address into your service (available in docker but not in docker-swarm)
- Generate automatically a certificate into your backend by adding its IP address as a IP SAN
- Define a Docker network with a set of IP adress, and them to you certificate and link use this network into your backend.

I guess, it is not a bug but a question and I close the issue.

But feel free to reopenit if necessary or join our [Slack workspace](https://slack.traefik.io/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Closed by nmengin** 2018-09-19 15:33 UTC
Labels: status/0-needs-triage

**Comment by FernandoMiguel** [comment] 2018-09-22 21:48
@nmengin thanks for the reply.
Indeed I'm aware of the reason why the communication between Traefik and my httpd fails.
It is indeed due to Traefik reaching up to the upstream via IP, instead of setting the proper SNI, like any other Load Balancer.

We would like to be able to establish secure communication with our nginx dockers without having to do complex processes to generate TLS certs (currently using Let's Encrypt to generate a SAN cert shared in our nginx dockers).
As you are aware, LE does not issue certs for IPs, only FQDN.

Besides the 4 workarounds you provided, is there anything else I can do to make this work?
Is it possible to request a Feature on Traefik so this behaviour is improved in a future release?

Thanks in advance.

**Comment by rafaelmagu** [comment] 2018-09-23 22:49
I have also hit this issue and am at a loss as to why SNI isn't being used. Is this not a supported feature of Traefik?

**Comment by nmengin** [comment] 2018-10-01 07:09
Hello @FernandoMiguel , @rafaelmagu 

As I said previously, we are aware of the need but we want to solve it globally for all the providers (K8s, Docker...). It's not easy because they do not use the same kind of mechanism to solve IP addresses from domain names.

In addition, the feature needs to manage the `HTTP Transport` in a very different way and the modifications we have to do are hard too.

Be sure we know the need and we'll try to solve in the future but, for the moment, only the workarounds I described have worked.

**Comment by ldez** [comment] 2018-10-01 08:52
@FernandoMiguel as @nmengin say "we'll try to solve in the future". For now, we have some constraints on this topic but it's in our plan to find a solution about that.

**Comment by SachinB2** [comment] 2018-10-16 21:16
@nmandery, I am seeing same issue when backend container needs client certificate based authorization,  to be precise, we have a https backend docker container without any IP specific certificates and we are able to access through traefik without any issues, but another backend container (apache/nifi with https setup) which requires client certificate based authorization fails with error mentioned above. Any suggestions here is would be of great help.

**Comment by FernandoMiguel** [comment] 2018-10-16 21:37
@sachinb2 you have a working TLS httpd backend with traefik?
I would love to hear more, as I never managed that, sadly

**Comment by SachinB2** [comment] 2018-10-16 21:49
@FernandoMiguel , Not httpd,  https backend container.

**Comment by FernandoMiguel** [comment] 2018-10-16 22:40
By httpd I mean a http daemon server
Could be nginx, apache or something, receiving http/s requests and spawning child processes

**Comment by sysofwan** [comment] 2018-11-29 16:39
+1 also having the same issue. @nmengin is there a discussion thread on how you are going to solve this?

**Comment by dimm0** [comment] 2019-02-05 06:41
I'm considering switching to another ingress controller, even though I love traefik in general, since this is not being resolved.
How hard would it be to include an option to query backend by service name instead of endpoint IPs?

**Comment by vishalvisd** [comment] 2019-02-07 14:20
traefik is overhyped as of now. It sounds a good concept but its a waste of time and energy to have its practical use as of now.

**Comment by davidxianggao** [comment] 2019-07-23 00:10
insureSkipVerify=true

**Comment by dimm0** [comment] 2019-07-23 00:17
> insureSkipVerify=true

insecureSkipVerify means INSECURE
the point of having x509 is having it SECURE

**Comment by dduportal** [comment] 2019-07-23 15:42
Hi @FernandoMiguel , @davidxianggao @dimm0, could you try this use case with the latest Traefik `v2.0.0-beta1` please? As the new version 2.0 of Traefik [allows TLS pass through when using TCP](https://docs.traefik.io/v2.0/routing/routers/#tls_1), it would totally solve the use case for you here.

I invite you to switch this discussion and your feedbacks in our [brand new community forum](https://community.containo.us/) which has a section dedicated for Traefik v2. The goals would be:

- To avoid discussing on a closed issue.
- To confirm that this use case is solved with `v2.0`
- To share the knowledge with the community.

Thanks all!
