### ISSUE TITLE
ACME Let's Encrypt with Frontend Basic Auth

### ISSUE THREAD

**Issue by ParanoidRat** [containous/traefik#3226] opened 2018-04-24 01:13 UTC
### Do you want to request a *feature* or report a *bug*?
*bug*

### What did you do?
Deployed single-container traefik service on Docker Swarm with the Consul K/V store configuration for Let's Encrypt (see config dump below). Then, deployed a number of app services with different `traefik.frontend.rule=Host:X.Y.Z` labels.

### What did you expect to see?
 Traefik successfully obtaining Let's Encrypt certs over ACME for all services with `traefik.enable=true` lable.

### What did you see instead?
Traefik obtained certs up until the container that had `traefik.frontend.auth.basic` label defined. For that specific container and all containers after that traefik ACME client failed reporting "Access Denied".

Further troubleshooting confirmed that if the service with Basic Auth is not in the stack deployment, traefik obtains certs normally for the rest of the hostnames in the stack.

Unfortunately, either the troubleshooting efforts or traefik's ACME client retries hit the Let's Encrypt API limit. So, now I get the following when try to re-deploy that specific "troubled" service / hostname without any Basic Auth configured.

```
time="2018-04-23T21:13:43Z" level=error msg="Error getting ACME certificates [X.Y.Z] : cannot obtain certificates map[X.Y.Z:acme: Error 429 - urn:acme:error:rateLimited - Error creating new authz :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/]" 
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
traefik/accesslogsfile:
traefik/acme/:
traefik/acme/account/lock:[REDACTED]
traefik/acme/account/object: [REDACTED]
traefik/acme/acmelogging:true
traefik/acme/caserver:
traefik/acme/delaydontcheckdns:0
traefik/acme/dnsprovider:
traefik/acme/email:[REDACTED]
traefik/acme/entrypoint:https
traefik/acme/httpchallenge/:
traefik/acme/httpchallenge/entrypoint:http
traefik/acme/ondemand:false
traefik/acme/onhostrule:true
traefik/acme/storage:traefik/acme/account
traefik/checknewversion:true
traefik/consul/:
traefik/consul/debugloggeneratedtemplate:false
traefik/consul/endpoint:consul:8500
traefik/consul/filename:
traefik/consul/password:
traefik/consul/prefix:traefik
traefik/consul/trace:false
traefik/consul/username:
traefik/consul/watch:true
traefik/debug:false
traefik/defaultentrypoints/0:http
traefik/defaultentrypoints/1:https
traefik/docker/:
traefik/docker/debugloggeneratedtemplate:false
traefik/docker/domain:
traefik/docker/endpoint:unix:///var/run/docker.sock
traefik/docker/exposedbydefault:false
traefik/docker/filename:
traefik/docker/swarmmode:true
traefik/docker/trace:false
traefik/docker/usebindportip:false
traefik/docker/watch:true
traefik/entrypoints/http/:
traefik/entrypoints/http/address::80
traefik/entrypoints/http/compress:false
traefik/entrypoints/http/network:
traefik/entrypoints/http/redirect/:
traefik/entrypoints/http/redirect/entrypoint:https
traefik/entrypoints/http/redirect/regex:
traefik/entrypoints/http/redirect/replacement:
traefik/entrypoints/https/:
traefik/entrypoints/https/address::443
traefik/entrypoints/https/compress:false
traefik/entrypoints/https/network:
traefik/entrypoints/https/tls/:
traefik/entrypoints/https/tls/clientca/optional:false
traefik/entrypoints/https/tls/minversion:
traefik/gracetimeout:0
traefik/healthcheck/:
traefik/healthcheck/interval:30000000000
traefik/idletimeout:0
traefik/insecureskipverify:false
traefik/leader:[REDACTED]
traefik/lifecycle/gracetimeout:10000000000
traefik/lifecycle/requestacceptgracetimeout:0
traefik/loglevel:ERROR
traefik/maxidleconnsperhost:200
traefik/providersthrottleduration:2000000000
traefik/sendanonymoususage:false
traefik/traefiklogsfile:
```

**Comment by nmengin** [comment] 2018-04-24 12:05
Hello @ParanoidRat .

Many thanks for your interest in the project.

I am sorry but I cannot reproduce your problem.

Can you provide more information (your `docker stack` options for example) and DEBUG logs please?
Did you use the `storeconfig` command to migrate data from a TOML file to your consul as described in this [user guide](https://docs.traefik.io/user-guide/cluster-docker-consul/)?

**Comment by ParanoidRat** [comment] 2018-04-27 19:41
@nmengin I did testing with the config above and could not reproduce the problem myself.
I only have the following error in the logs which I guess is a normal artefact of Traefik running in a clustered deployment
```
level=error msg="Datastore sync error: Object lock value: expected 32b0fb3a-6de0-4b4a-9418-0e0ffc06a150, got f3c2d41b-afc9-4949-82bb-a9d0dcb2b3ff, retrying in 338.978139ms" 
```
The ACME "Access denied" error might be caused by inconsistency of docker load-balancing capability. Now I recall that earlier in the Traefik deployment cycle, I started with a single-instance Traefik service and had intermittent "host unreachable" errors while testing without ACME on plain HTTP. Then I transitioned to the stack I outlined above and deployed all apps one by one excluding the one that got ACME "access denied" error.

**Comment by nmengin** [comment] 2018-05-14 09:29
Hello @ParanoidRat ,

Indeed the log you described may be generated when the cluster mode in started.

I guess your issue is solved and I close it.

If you need more help, please join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Closed by nmengin** 2018-05-14 09:29 UTC
Labels: contributor/waiting-for-feedback, kind/question
