### ISSUE TITLE
File Watch Doesn't Work

### ISSUE THREAD

**Issue by guiguan** [containous/traefik#595] opened 2016-08-04 12:06 UTC
I am using Traefik on my osx docker installation with following config:

```toml
#...
[file]
filename = "/etc/traefik/rules.toml"
watch = true

#...
```

After I changed and saved `rules.toml`, the configuration however did not hot-reload, and I had to restart the Traefik docker container.

**Comment by emilevauge** [comment] 2016-08-04 13:21
@guiguan I can't reproduce this. I just tested on MacOS and it works like a charm.

**Comment by guiguan** [comment] 2016-08-05 10:45
@emilevauge Hi, thanks for your quick response. Are you using the new docker for mac with xhyve virtualisation?

**Comment by emilevauge** [comment] 2016-08-05 12:24
Oops, I read to quickly sorry... I tested using `traefik_darwin-amd64` binary, not in Docker for Mac. I suppose https://github.com/fsnotify/fsnotify doesn't work with xhyve then...

**Comment by nothing-fr** [comment] 2016-09-01 19:51
Same here, docker with shared file rules.toml on my mac... file watch not working :/

**Comment by ascora** [comment] 2016-09-18 22:54
same for me

**Comment by Juliens** [comment] 2017-05-30 10:06
The watch in https://github.com/fsnotify/fsnotify doesn't work when we mount a file in a container (but it works with a dir)

Moreover, be careful when you're mounting a file
https://forums.docker.com/t/modify-a-file-which-mount-as-a-data-volume-but-it-didnt-change-in-container/2813

**Comment by nmengin** [comment] 2017-10-25 07:47
I added a link to #2233 because the watcher has been modified in the way to listen to the parent directory of a file instead of the file itself.

This can help to watch all of files changes even if the file is copied/deleted/created by the editor.
Moreover, it has to work with all the OS.

Do not hesitate to give a feedback when the PR will be merged :wink:

**Closed** 2017-11-09 11:16 UTC
Labels: kind/bug/confirmed

**Comment by navinSing** [comment] 2018-03-28 13:34
is there a way to watch file on mounted directory or its sub directories ?

**Comment by traefiker** [comment] 2018-03-28 14:01
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Træfik, but this issue is now closed :lock:

If needed, don't hesitate to open a new issue (and follow the [bug](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/bugs.md) or [feature](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/features.md) templates).

You can also join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by xiaods** [comment] 2018-07-01 06:02
this bug occurs in v1.6.4 version traefik, ubuntu 16.04 docker images.

anyone can reproduce this bug.

**Comment by Marusyk** [comment] 2018-07-09 23:46
I'm using Windows 10 with docker 18.04.0-ce and v1.6.4 version traefik. The same issue

**Comment by revolunet** [comment] 2018-07-27 18:30
Hi, looks like the same happens on :
 - UBUNTU 17.10
 - Docker version 17.12.1-ce
 - traefik v1.6.4 (in docker)

i have in rules.toml :
```
[file]
watch = true
...
```

in traefik.toml :
```
[file]
  filename = "rules.toml"
  watch = true
...
```

**Comment by ianldgs** [comment] 2018-11-07 17:40
Same problem here.

* Ubuntu Server 18.04
* Docker version 18.06.1-ce
* Traefik v1.7.4 (in docker)

A workarround to persist the changes is to restart the container:
`docker container restart traefik`

But it will make any current request fail.

**Comment by kajmagnus** [comment] 2019-01-09 05:53
Tips: One needs to place the file directly in the directory being watched. Then works fine for me.  Having it in a sub directory of the watched directory,  didn't work.  Because of this?:  https://github.com/fsnotify/fsnotify#faq

> When I watch a directory, are all subdirectories watched as well?
> No, you must add watches for any directory you want to watch (a recursive watcher is on the roadmap #18).

@ianldgs , @revolunet,, @xiaods  @Marusyk

**Comment by xiaods** [comment] 2019-01-09 06:45
@kajmagnus got it.
