### ISSUE TITLE
HTTP to HTTPS redirect not working as expected with docker

### ISSUE THREAD

**Issue by andig** [containous/traefik#3573] opened 2018-07-08 20:52 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm running traefik 1.6.3 in docker on a NAS; using ports 8080 and 8443 as 80 and 443 were already taken. My router is redirecting 80 -> nas:8080 and 443 -> nas:8443. This is already working fine for HTTPS access.

The goal is to implement HTTP to HTTPS redirect. Since the traefik HTTPS port in docker is 8443 I've added a secondary entrypoint using 443 to "redirect" to in order for the port numbers- when accessed externally- to match.

```toml
    defaultEntryPoints = ["https"]
    [entryPoints]
      [entryPoints.traefik]
      address = ":8000"
      [entryPoints.http]
      address = ":8080"
        [entryPoints.http.redirect]
        entryPoint = "httpsExternal"
      [entryPoints.https]
      address = ":8443"
        [entryPoints.https.tls]
      [entryPoints.httpsExternal]
      address = ":443"
        [entryPoints.httpsExternal.tls]
```
I then 

    curl http://volkszaehler.io

### What did you expect to see?

Redirect to https://volkszaehler.io at port 443

### What did you see instead?

    ❯ curl -v http://volkszaehler.io
    * Rebuilt URL to: http://volkszaehler.io/
    *   Trying 77.23.37.87...
    * TCP_NODELAY set
    * Connected to volkszaehler.io (77.23.37.87) port 80 (#0)
    > GET / HTTP/1.1
    > Host: volkszaehler.io
    > User-Agent: curl/7.54.0
    > Accept: */*
    >
    < HTTP/1.1 302 Found
    < Location: https://volkszaehler.io:8443/
    < Date: Sun, 08 Jul 2018 20:38:14 GMT
    < Content-Length: 5
    < Content-Type: text/plain; charset=utf-8
    <

This is still using the wrong port 8443.

### Output of `traefik version`: (_What version of Traefik are you using?_)

    v1.6.3

**Comment by SantoDE** [comment] 2018-07-09 06:16
Hey @andig ,

did you try with `curl -L? You need to tell curl to follow redirects.

Locally, I'm getting redirected correctly then. I cant see something, but I guess thats on purpose ;-)

```
curl -L http://volkszaehler.io
curl: (7) Failed to connect to volkszaehler.io port 8443: Connection refused
```

**Comment by andig** [comment] 2018-07-09 07:16
> You need to tell curl to follow redirects.

Thats not the issue. The problem is the redirection traefik ends which is `Location: https://volkszaehler.io:8443/`. That port is open on docker but not externally on the Router.

So the problem is that I need the redirect to go to another port than the one traefik is listening on.

**Comment by dduportal** [comment] 2018-07-09 15:37
Hi @andig , thanks for taking time to explain your use case.

If Træfik would have to know the public port, then it would goes against the principles of PAT (Port Adresse Translation).

However, your use case is quite clear and should be solved, but this is not really the role of Træfik.

You have 2 solutions:

- First solution would be to deal with this redirect with the network's asset which has the knowledge of the port translation, contrary to Træfik: I nominate your router as the candidate for this. This is the kind of pattern you could find on a Load-Balancer like lvs/ipvs, haproxy or Cloud Load Balancers. I would bet that you cannot change your router's system to provide redirection, which would make this solution unacceptable, but I wanted to bring it for awareness.

- Second solution is to consider this is a dedicated HTTP routing feature of your setup, which compensate the lack of routing capability. So you would need an HTTP server's placeholder which responsibility would be to tell your HTTP client where to redirect. An nginx webserver could be set as backend for the HTTP trafic from Træfik, which would redirect all request to your public's HTTPS URL with a configuration like this one: 
```
server {
    listen 80 default; # Or listen 8080;
    server_name volkszaehler.io;
    return 301 https://volkszaehler.io$request_uri;
}
```

Let us know if it is ok for your use case ?

**Comment by dduportal** [comment] 2018-07-09 16:13
Hey @andig , A little bird just told me a third solution which could help you, only using Træfik: using the "Secure Headers".

The documentation can be found here: https://docs.traefik.io/basics/#security-headers .

The idea is to set the header `SSLRedirect = true` which will always redirect to 443, whatever port is configured for the https's entrypoint, as I understand.

I am not really at ease with this one, so let's try it, but don't hesitate to let us know the result here!

Hope it helps :)

**Comment by SantoDE** [comment] 2018-07-09 16:38
Hey @andig, sorry I missunderstood your case in the first place then :-)

@dduportal got a valid point. I hope it will help you out

**Comment by andig** [comment] 2018-07-09 18:47
Hi guys, hi @dduportal. Let me starting my saying a big thank you. Working with traefik and the level of support by the community (and the open-mindedness when faced with questions like these) is outstanding.

> First solution would be to deal with this redirect with the network's asset .... I would bet that you cannot change your router's system to provide redirection,

Understood and no :(

> Second solution is to consider this is a dedicated HTTP routing feature of your setup

Right. That would work! 

> If Træfik would have to know the public port, then it would goes against the principles of PAT (Port Adresse Translation).

Ok. I still feel like I might be able to trick Traefik into doing what I want without additional software without the scenario being directly supported.

> The idea is to set the header SSLRedirect = true which will always redirect to 443, whatever port is configured for the https's entrypoint, as I understand.

Workaround 1 does the trick- I can confirm this approach to be working! Due to https://github.com/containous/traefik/issues/2109 I have a dummy frontend on the http entrypoint that I'm using for this purpose.

What I still do not understand is why my original approach (call it Workaround 2) doesn't work:

      [entryPoints.http]
      address = ":8080"
        [entryPoints.http.redirect]
        entryPoint = "httpsExternal"
      [entryPoints.httpsExternal]
      address = ":443"
        [entryPoints.httpsExternal.tls]

I thought this would be good enough to make traefik use the `httpExternal` entrypoint with the associated port for its redirect but it doesn't?

**Comment by SantoDE** [comment] 2018-07-10 06:11
Hmm. Thats a good question. Do you have set the needed information about the CertFile and Keyfile below  [entryPoints.httpsExternal.tls]? Otherwise, the entryPoint will not be setuped correctly as you declared it as TLS but did not set the required values. Maybe you can post your whole entryPoint configuration and just strip out the pathes to the files?

**Comment by andig** [comment] 2018-07-10 06:50
The entire `entrypoints` section is in the initial issue description. No `certfile` as ACME is configured (and working):

	[acme]
	email = "cpuidle..."
	storage = "/etc/traefik/acme.json"
	entryPoint = "https"
	onHostRule = true
	acmeLogging = true

That makes me wonder if this is cause for  the entrypoint rule not working? Does the redirect look at the ACME `entryPoint` instead of the configured one?

Anyway I have a perfectly working setup now- please feel free to close without further investigation. Otherwise I'd be happy to follow the discussion.

**Comment by joanayma** [comment] 2018-07-10 10:08
Have you tried with:
`traefik.frontend.headers.SSLProxyHeaders: "X-Forwarded-Proto:https`?
https://docs.traefik.io/configuration/backends/docker/#security-headers

**Comment by dduportal** [comment] 2018-07-10 11:54
Hello @andig !

Using the configuration snippet you provided on your initial comment, with the same Træfik version, I was not able to reproduce your issue, the behaviour is what you expected: https://gist.github.com/dduportal/55fcb9e9d19c8f6694efa044714a04f8 (done a macOS 10.13.5 with Docker4Mac Edge 18.05).

I am going to close this issue since you acknowledged you problem was solved, but feel free to check that your initial configuration was correctly applied, and put all useful informations on a gist to let us know what is your configuration (toml, Træefik's command options, docker or docker-compose containers and options, etc.) if you are able to reproduce it.

**Comment by traefiker** [comment] 2018-07-10 11:57
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

Thanks again for your interest in Træfik!

I'm glad to close the issue because I think that the question has been answered (Yes, I'm quite an advanced AI :smile:)

Join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Closed by traefiker** 2018-07-10 11:57 UTC
Labels: kind/question

**Comment by seth100** [comment] 2019-02-16 13:45
Hi,
I have the same issue, @andig how did you solve it?

**Comment by andig** [comment] 2019-03-21 09:44
@seth100 I've solved this as suggested by @dduportal:

> The idea is to set the header SSLRedirect = true which will always redirect to 443, whatever port is configured for the https's entrypoint, as I understand.

This lets traefik redirect to `domain:443` which is accessible from outside and is independent from the port configured on the entrypoint.
