### ISSUE TITLE
traefik stops processing Ingresses if RBAC permissions for Secrets are not granted

### ISSUE THREAD

**Issue by jeroenjacobs1205** [containous/traefik#1826] opened 2017-07-04 14:17 UTC
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Install the latest version of the official traeffik docker container in kubernetes

### What did you expect to see?

traeffik processing k8s ingress rules. Our current k8s yaml files used to work until last week to deploy traeffik as k8s ingress controller

### What did you see instead?

this message:

`github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Secret: the server does not allow access to the requested resource (get secrets)
`
Wy would traefik suddenly require access to the secrets resource? This is nowhere mentioned in the official rbac rules either: https://github.com/containous/traefik/blob/master/examples/k8s/traefik-rbac.yaml

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.2
Codename:     raclette
Go version:   go1.8.3
Built:        2017-06-29_04:52:35PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

We run it inside k8s 1.6.6

No toml file used. 

This is the k8s yaml file:

<details>

```yml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        args:
        - --web
        - --kubernetes
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: traefik-ingress-controller
  name: traefik-ingress-controller
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    name: http
  selector:
    k8s-app: traefik-ingress-lb

```
</details>

**Comment by jeroenjacobs1205** [comment] 2017-07-04 14:32
I have another k8s cluster, that is setup identically (also kubernetes 1.6.6), and there we don't have that issue. However, it's a different version:

```
Version:      v1.3.1
Codename:     raclette
Go version:   go1.8.3
Built:        2017-06-16_11:21:48AM
OS/Arch:      linux/amd64
```

seems our issue started with v1.3.2. Will do some more tests to verify this.

**Comment by jeroenjacobs1205** [comment] 2017-07-04 14:43
confirmed.

Downgrading to v1.3.1 solves the issue on our affected cluster.

**Comment by jeroenjacobs1205** [comment] 2017-07-04 14:59
I'm looking at the pull request here, which was merged in 1.3.2: https://github.com/containous/traefik/pull/1798

I think the following remark might have something to do with it:

> Wait for secret controller to finish synchronizing.

**Comment by timoreimann** [comment] 2017-07-04 20:41
@jeroenjacobs1205 thanks for the bug report.

I'm surprised to hear that you supposedly cannot observe permission access failure log messages on 1.3.1: Traefik 1.3.0 added a feature to support basic auth on Kubernetes (#1488) which started to watch for Secrets objects unconditionally (i.e., regardless of whether basic auth was used or not). To verify, I just started a copy of that Traefik version with Secrets-restricted RBAC permissions locally and saw the very same error in my logs. Are you running the Alpine or non-Alpine Traefik container?

I have filed #1784 a few days ago to make Traefik reach out for Secrets objects only when it really needs to. Until then, the possible workarounds are to relax the RBAC permissions or ignore the error -- while being noisy, it's also harmless.

A PR for the documentation update lives in #1707, though I expect it to be superseded as soon as #1784 lands.

**Comment by jeroenjacobs1205** [comment] 2017-07-05 06:12
It's not harmless at all. That something I forgot to mention: Traefik 1.3.2 returned 404 on every request. Once I gave access to secrets OR downgraded to 1.3.1, Traefik was working as expected.

It seems Traefik 1.3.2 doesn't process Ingress rules as long as it doesn't have access to secrets.

**Comment by timoreimann** [comment] 2017-07-05 07:05
The behavior you're describing should be the one observed on 1.3.1 and fixed on 1.3.2: The earlier version returned an error while the latter just logs it.

I'll double-check. Maybe I got one bug out and another one in. :-)

Just in case we need the information: could you tell me if you use the regular Docker image or the Alpine one?

**Comment by jeroenjacobs1205** [comment] 2017-07-05 07:32
Since I'm pulling the "traefik:latest" tag (which is installed traefik 1.3.2) and now "traefik:v1.3.1" for the working version, I assume those are the regular ones, and not the alpine ones.

**Comment by timoreimann** [comment] 2017-07-05 07:40
Just to be certain: are you positive that `latest` matches 1.3.2 in your case? Having `latest` cached to a previous version while not forcing re-pulls can lead to unintended versions sometimes.

**Comment by timoreimann** [comment] 2017-07-05 07:45
@jeroenjacobs1205 another question: do you actually try to use basic auth in any of your Ingresses?

**Comment by jeroenjacobs1205** [comment] 2017-07-05 07:47
Nope, no basic authentication at all.

**Comment by jeroenjacobs1205** [comment] 2017-07-05 07:49
And I'm sure the version that has this behaviour is version 1.3.2. This issue occured when I deployed a new cluster yesterday, on a fresh server. No docker image caching involved at that point.

**Comment by timoreimann** [comment] 2017-07-05 15:23
I can confirm the behavior now. Let me see if I can find the root cause quickly.

**Comment by timoreimann** [comment] 2017-07-05 20:29
@jeroenjacobs1205 I have filed a PR to fix the problem and also pushed a custom image `timoreimann/traefik:rbacsecrets` including the fix. If you have time and the possibility, I'd love to hear your feedback on whether that one works for you.

Thanks!

**Comment by jeroenjacobs1205** [comment] 2017-07-05 23:05
I have a few days off, so I can test this next Monday at the earliest.

**Comment by timoreimann** [comment] 2017-07-05 23:23
@jeroenjacobs1205 no worries appreciated!

**Comment by ldez** [comment] 2017-07-06 15:32
Closed by #1828

**Closed by ldez** 2017-07-06 15:32 UTC
Labels: area/provider/k8s, kind/bug/confirmed, priority/P0

**Comment by raja-gola** [comment] 2017-11-06 05:21
Still seeing this in 1.4.2 version
`time="2017-11-06T05:16:47Z" level=info msg="Traefik version v1.4.2 built on 2017-11-02_01:47:46PM"
time="2017-11-06T05:16:47Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc420055620} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2017-11-06T05:16:47Z" level=info msg="Starting provider *web.Provider {"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"/","Auth":null,"Debug":false,"CurrentConfigurations":{},"Stats":{"Uptime":"2017-11-06T05:16:47.017278876Z","Pid":1,"ResponseCounts":{},"TotalResponseCounts":{},"TotalResponseTime":"0001-01-01T00:00:00Z"},"StatsRecorder":null}"
time="2017-11-06T05:16:47Z" level=info msg="Starting server on :80"
time="2017-11-06T05:16:47Z" level=info msg="Starting provider *kubernetes.Provider {"Watch":true,"Filename":"","Constraints":[],"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"","Token":"","CertAuthFilePath":"","DisablePassHostHeaders":false,"Namespaces":null,"LabelSelector":""}"
time="2017-11-06T05:16:47Z" level=info msg="Creating in-cluster Provider client
"
E1106 05:16:47.057350       1 reflector.go:199] github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Secret: the server does not allow access to the requested resource (get secrets)
time="2017-11-06T05:16:47Z" level=info msg="Server configuration reloaded on :80"
E1106 05:16:48.060892       1 reflector.go:199] github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Secret: the server does not allow access to the requested resource (get secrets)
E1106 05:16:49.064083       1 reflector.go:199] github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Secret: the server does not allow access to the requested resource (get secrets)
E1106 05:16:50.067017       1 reflector.go:199] github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Secret: the server does not allow access to the requested resource (get secrets)
`

**Comment by timoreimann** [comment] 2017-11-06 06:16
@raja-gola is Traefik actually stopping servicing Ingresses for you or "just" spamming the logs? I'd bet it's the latter, in which case you'd actually be affected by #1784.
