### ISSUE TITLE
Dashboard status doesn't reflect reality

### ISSUE THREAD

**Issue by perosb** [containous/traefik#6599] opened 2020-03-29 07:09 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

Looking at the dashboard the `Errors` doesn't reflect the state of the Service.
![image](https://user-images.githubusercontent.com/982752/77843348-8cd7a100-719c-11ea-8dfc-3b88051a21dc.png)

Dashboard says all is okay, but one Service doesn't have any servers working.
![image](https://user-images.githubusercontent.com/982752/77843357-abd63300-719c-11ea-862e-556d73b1e207.png)

This should mean the Service is having an error?
If it would have 1 failing out of 1+ servers, it would mean a Warning?

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
v2.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
running in docker.
docker swarm
consul

**Comment by ldez** [comment] 2020-03-30 15:10
Duplicate of #6117

**Closed by ldez** 2020-03-30 15:10 UTC
Labels: status/0-needs-triage
