### ISSUE TITLE
Traefik didn't register mesos Tasks (universal containerizer) / mesos backend

### ISSUE THREAD

**Issue by lusche** [containous/traefik#1393] opened 2017-04-06 07:54 UTC
### What is your environment & configuration (arguments, toml...)?
We run an marathon/mesos Cluster and try to use Traefik as LB solution. Unfortunately both the mesos and the marathon backend didn't work as aspected. Maybe i use it wrong. 

The Environment:
- CentOS Linux release 7.3.1611 (Core)
- docker-engine.x86_64 1.11.2-1.el7.centos
- mesos 1.1.0
- marathon-1.4.1
- Traefik version v1.2.1 built on 2017-03-27_03:19:40PM
- CNI Calico (version v1.1.0, build 882dd008)

traefik.toml
```toml
debug = true

################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"

[mesos]
endpoint = "zk://mesos3.domain.xyz:2181,mesos4.domain.xyz:2181,mesos5.domain.xyz:2181/mesos"
domain = "mesos.localhost"
ExposedByDefault = true
# IPSources = "docker"
IPSources = "mesos"

[marathon]
endpoint = "http://mesos3.domain.xyz:8080,mesos4.domain.xyz:8080,mesos5.domain.xyz:8080"
domain = "marathon.localhost"
marathonLBCompatibility = true
exposedByDefault = true
groupsAsSubDomains = true
```

### What did you do?
We run two tasks / Services to test this setup. One as docker container and a second one as Universal containerizer.

docker:
``` json
{
    "container": {
        "type": "DOCKER",
        "docker": {
            "forcePullImage": true,
            "image": "hub.binky.domain.xyz/trashcan/fixed:0.1",
            "privileged": false,
            "network": "USER",
            "portMappings": [
              {
                "containerPort": 80,
                "protocol": "tcp",
                "name": null,
                "labels": null
              }
            ]
        }
    },
    "cpus": 0.1,
    "id": "/traefik/docker-1",
    "instances": 1,
    "minimumHealthCapacity": 1,
    "acceptedResourceRoles": ["*"],
    "mem": 128,
    "labels": {
      "HAPROXY_0_VHOST": "docker-1.traefik.binky.domain.xyz",
      "HAPROXY_GROUP": "internal"
    },    
    "ipAddress": {
        "networkName": "my-calico-net",
        "labels": {
          "app": "test",
          "group": "development"
        }
    }
}
```

universal containerizer:
```json
{
    "container": {
        "type": "MESOS",
        "docker": {
            "forcePullImage": true,
            "image": "hub.binky.domain.xyz/trashcan/fixed:0.1",
            "privileged": false
        }
    },
    "cpus": 0.1,
    "id": "/traefik/mesos-1",
    "instances": 1,
    "minimumHealthCapacity": 1,
    "acceptedResourceRoles": ["*"],
    "mem": 128,
    "labels": {
      "HAPROXY_0_VHOST": "mesos-1.traefik.binky.domain.xyz",
      "HAPROXY_GROUP": "internal"
    },    
    "ipAddress": {
        "networkName": "calico-net-1",
        "labels": {
          "app": "test",
          "group": "development"
        }
    }
}
```

### What did you expect to see?
both containers registered in Traefik

### What did you see instead?
As result Traefik shows an empty marathon tab and the mesos tap contains at least the docker Task. if i change the ```IPSources = "mesos"``` to ```IPSources = "docker"``` i geth the ip of the docker task, but the universal containerizer is still not present.

### If applicable, please paste the log output in debug mode (`--debug` switch)

debug:
```
time="2017-04-05T10:07:33Z" level=info msg="Traefik version v1.2.1 built on 2017-03-27_03:19:40PM"
time="2017-04-05T10:07:33Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml"
time="2017-04-05T10:07:33Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":true,\"CheckNewVersion\":true,\"AccessLogsFile\":\"\",\"TraefikLogsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"Compress\":false}},\"Cluster\":null,\"Constraints\":[],\"ACME\":null,\"DefaultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost\":200,\"InsecureSkipVerify\":false,\"Retry\":null,\"Docker\":null,\"File\":null,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Statistics\":null,\"Metrics\":null,\"Auth\":null},\"Marathon\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"http://mesos3.domain.xyz:8080,mesos4.domain.xyz:8080,mesos5.domain.xyz:8080\",\"Domain\":\"marathon.localhost\",\"ExposedByDefault\":true,\"GroupsAsSubDomains\":true,\"DCOSToken\":\"\",\"MarathonLBCompatibility\":true,\"TLS\":null,\"DialerTimeout\":60,\"KeepAlive\":10,\"Basic\":null},\"Consul\":null,\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null,\"Mesos\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"zk://mesos3.domain.xyz:2181,mesos4.domain.xyz:2181,mesos5.domain.xyz:2181/mesos\",\"Domain\":\"mesos.localhost\",\"ExposedByDefault\":true,\"GroupsAsSubDomains\":false,\"ZkDetectionTimeout\":30,\"RefreshSeconds\":30,\"IPSources\":\"mesos\",\"StateTimeoutSecond\":30,\"Masters\":null},\"Eureka\":null,\"ECS\":null,\"Rancher\":null}"
time="2017-04-05T10:07:33Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}"
time="2017-04-05T10:07:33Z" level=info msg="Starting provider *provider.Marathon {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"http://mesos3.domain.xyz:8080,mesos4.domain.xyz:8080,mesos5.domain.xyz:8080\",\"Domain\":\"marathon.localhost\",\"ExposedByDefault\":true,\"GroupsAsSubDomains\":true,\"DCOSToken\":\"\",\"MarathonLBCompatibility\":true,\"TLS\":null,\"DialerTimeout\":60,\"KeepAlive\":10,\"Basic\":null}"
time="2017-04-05T10:07:33Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Statistics\":null,\"Metrics\":null,\"Auth\":null}"
time="2017-04-05T10:07:33Z" level=info msg="Starting provider *provider.Mesos {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Endpoint\":\"zk://mesos3.domain.xyz:2181,mesos4.domain.xyz:2181,mesos5.domain.xyz:2181/mesos\",\"Domain\":\"mesos.localhost\",\"ExposedByDefault\":true,\"GroupsAsSubDomains\":false,\"ZkDetectionTimeout\":30,\"RefreshSeconds\":30,\"IPSources\":\"mesos\",\"StateTimeoutSecond\":30,\"Masters\":null}"
time="2017-04-05T10:07:33Z" level=info msg="Starting server on :80"
time="2017-04-05T10:07:33Z" level=warning msg="clientTLS is nil"
time="2017-04-05T10:07:33Z" level=debug msg=mesos
time="2017-04-05T10:07:33Z" level=debug msg="Starting master detector for ZK %!(EXTRA string=zk://mesos3.domain.xyz:2181,mesos4.domain.xyz:2181,mesos5.domain.xyz:2181/mesos)"
2017/04/05 10:07:33 structs.go:21: Connected to 10.107.19.21:2181
2017/04/05 10:07:33 structs.go:21: Authenticated: id=97688275774341178, timeout=40000
time="2017-04-05T10:07:33Z" level=debug msg="new masters detected: [10.107.19.21:5050]"
time="2017-04-05T10:07:33Z" level=debug msg="Filtering marathon task without port %s/traefik/docker-1"
time="2017-04-05T10:07:33Z" level=debug msg="Filtering marathon task without port %s/traefik/mesos-1"
time="2017-04-05T10:07:33Z" level=debug msg="Configuration received from provider marathon: {}"
time="2017-04-05T10:07:33Z" level=debug msg="Last marathon config received more than 2s, OK"
time="2017-04-05T10:07:33Z" level=info msg="Server configuration reloaded on :80"
time="2017-04-05T10:07:33Z" level=debug msg="Filtering mesos task without port mesos-1.traefik"
time="2017-04-05T10:07:33Z" level=debug msg="new masters detected: [10.107.19.21:5050 10.107.19.23:5050 10.107.19.22:5050]"
time="2017-04-05T10:07:33Z" level=debug msg="Load balancer method '<nil>' for backend backend-docker-1-traefik: Invalid method, using default. Using default wrr."
time="2017-04-05T10:07:33Z" level=debug msg="Configuration received from provider mesos: {\"backends\":{\"backend-docker-1-traefik\":{\"servers\":{\"server-traefik-docker-1-bf60da40-19e5-11e7-8fb4-02427ff3bac1\":{\"url\":\"http://:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-traefik-docker-1-bf60da40-19e5-11e7-8fb4-02427ff3bac1\":{\"entryPoints\":[\"http\"],\"backend\":\"backend-docker-1-traefik\",\"routes\":{\"route-hosttraefik-docker-1-bf60da40-19e5-11e7-8fb4-02427ff3bac1\":{\"rule\":\"Host:docker-1.traefik.mesos.localhost\"}},\"priority\":0}}}"
time="2017-04-05T10:07:33Z" level=debug msg="Last mesos config received less than 2s, waiting..."
time="2017-04-05T10:07:33Z" level=debug msg="Filtering mesos task without port mesos-1.traefik"
time="2017-04-05T10:07:33Z" level=debug msg="Load balancer method '<nil>' for backend backend-docker-1-traefik: Invalid method, using default. Using default wrr."
time="2017-04-05T10:07:33Z" level=debug msg="Configuration received from provider mesos: {\"backends\":{\"backend-docker-1-traefik\":{\"servers\":{\"server-traefik-docker-1-bf60da40-19e5-11e7-8fb4-02427ff3bac1\":{\"url\":\"http://:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-traefik-docker-1-bf60da40-19e5-11e7-8fb4-02427ff3bac1\":{\"entryPoints\":[\"http\"],\"backend\":\"backend-docker-1-traefik\",\"routes\":{\"route-hosttraefik-docker-1-bf60da40-19e5-11e7-8fb4-02427ff3bac1\":{\"rule\":\"Host:docker-1.traefik.mesos.localhost\"}},\"priority\":0}}}"
time="2017-04-05T10:07:33Z" level=debug msg="Last mesos config received less than 2s, waiting..."
time="2017-04-05T10:07:35Z" level=debug msg="Waited for mesos config, OK"
time="2017-04-05T10:07:35Z" level=debug msg="Creating frontend frontend-traefik-docker-1-bf60da40-19e5-11e7-8fb4-02427ff3bac1"
time="2017-04-05T10:07:35Z" level=debug msg="Wiring frontend frontend-traefik-docker-1-bf60da40-19e5-11e7-8fb4-02427ff3bac1 to entryPoint http"
time="2017-04-05T10:07:35Z" level=debug msg="Creating route route-hosttraefik-docker-1-bf60da40-19e5-11e7-8fb4-02427ff3bac1 Host:docker-1.traefik.mesos.localhost"
time="2017-04-05T10:07:35Z" level=debug msg="Creating backend backend-docker-1-traefik"
time="2017-04-05T10:07:35Z" level=debug msg="Creating load-balancer wrr"
time="2017-04-05T10:07:35Z" level=debug msg="Creating server server-traefik-docker-1-bf60da40-19e5-11e7-8fb4-02427ff3bac1 at http://:80 with weight 0"
time="2017-04-05T10:07:35Z" level=info msg="Server configuration reloaded on :80"
```

**Comment by lusche** [comment] 2017-04-06 07:55
![bildschirmfoto 2017-04-05 um 12 58 36](https://cloud.githubusercontent.com/assets/25299298/24743594/1e2763e0-1aaf-11e7-8030-61e7589223a7.png)

**Comment by timoreimann** [comment] 2017-04-13 06:07
The logs tell us the task is being filtered because Traefik thinks there's no port available.

Looking at the code, we expect the port to be provided through `DiscoveryInfo.Ports.DiscoveryPorts`. @lusche, I have zero experience running apps directly on Mesos without Marathon. Is this assumption legitimate? Do we need to extend the provider somehow, like by porting the port label override to Mesos somehow?

**Comment by lusche** [comment] 2017-04-13 06:22
@timoreimann I run the Task with marathon but use the mesos backend to geht the information back to Traefik. I had problems with the marathon backend: https://github.com/containous/traefik/issues/1390 I try to  solve it by using the mesos backend. 

The mesos /tasks endpoint has the following information for the task:

```json
{
            "container": {
                "mesos": {
                    "image": {
                        "cached": false,
                        "docker": {
                            "name": "hub.binky.domain.xyz/trashcan/fixed:0.1"
                        },
                        "type": "DOCKER"
                    }
                },
                "network_infos": [
                    {
                        "ip_addresses": [
                            {}
                        ],
                        "labels": {
                            "labels": [
                                {
                                    "key": "app",
                                    "value": "test"
                                },
                                {
                                    "key": "group",
                                    "value": "development"
                                }
                            ]
                        },
                        "name": "calico-net-1"
                    }
                ],
                "type": "MESOS"
            },
            "discovery": {
                "name": "mesos-2.traefik",
                "ports": {},
                "visibility": "FRAMEWORK"
            },
            "executor_id": "",
            "framework_id": "adfda254-8d0c-4e37-8a72-886806f10717-0000",
            "id": "traefik_mesos-2.062ffe10-1b58-11e7-8fb4-02427ff3bac1",
            "labels": [
                {
                    "key": "HAPROXY_0_VHOST",
                    "value": "mesos-2.traefik.binky.domain.xyz"
                },
                {
                    "key": "HAPROXY_GROUP",
                    "value": "internal"
                },
                {
                    "key": "traefik.port",
                    "value": "80"
                }
            ],
            "name": "mesos-2.traefik",
            "resources": {
                "cpus": 0.1,
                "disk": 0.0,
                "gpus": 0.0,
                "mem": 128.0
            },
            "slave_id": "adfda254-8d0c-4e37-8a72-886806f10717-S21",
            "state": "TASK_RUNNING",
            "statuses": [
                {
                    "container_status": {
                        "network_infos": [
                            {
                                "ip_addresses": [
                                    {
                                        "ip_address": "192.168.1.20",
                                        "protocol": "IPv4"
                                    }
                                ],
                                "labels": [
                                    {
                                        "key": "app",
                                        "value": "test"
                                    },
                                    {
                                        "key": "group",
                                        "value": "development"
                                    }
                                ],
                                "name": "calico-net-1"
                            }
                        ]
                    },
                    "state": "TASK_RUNNING",
                    "timestamp": 1491545055.0468
                }
            ]
        },
```

For me it look like an weakness from marathon that there is no way to define a port while use an CNI / Network plugin. 

For me it would be a great solution if I can pass a port as Label that is used regardless to what is discovered.

**Comment by timoreimann** [comment] 2017-04-13 06:55
Support in the Marathon provider to specify an arbitrary port is already there. I'm waiting for my fix to a regression to be merged -- once that has happened, you can give Marathon another try.

To get the priorities clear: Is Mesos just the backup plan for you? If Marathon treated you well, would you still want Mesos?

**Comment by timoreimann** [comment] 2017-05-18 16:57
@lusche is this still relevant to you, now that we have extended the Marathon provider?

**Comment by lusche** [comment] 2017-05-19 08:50
@timoreimann no, the marathon provider works fine for me. Feel free to close this one.

**Closed** 2017-05-19 12:16 UTC
Labels: area/provider/mesos
